; ==================================================================
; Bank $66. Gex's animation frames 1 to 41 of PLAYER_GFX_SET_MARSUPIAL_MADNESS1.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $452c, then 560 tiles of graphics from $4530 to $682f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/sprite_data/bank7F.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_66_4000_PlayerFrame_001:
    player_frame_header   8, $1f, $22, data_66_4530_PlayerTiles + $0000
    player_piece  -12,  -10, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,  -10, PLAYER_PIECE_PAL1
    player_piece  -13,  -10, PLAYER_PIECE_PAL1
    player_piece  -29,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,    6, PLAYER_PIECE_PAL1

data_66_4025_PlayerFrame_002:
    player_frame_header   9, $1f, $22, data_66_4530_PlayerTiles + $0100
    player_piece  -12,  -10, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece   -3,    6, PLAYER_PIECE_PAL0
    player_piece  -29,  -10, PLAYER_PIECE_PAL1
    player_piece  -16,  -10, PLAYER_PIECE_PAL1
    player_piece  -29,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,    6, PLAYER_PIECE_PAL1

data_66_404e_PlayerFrame_003:
    player_frame_header   9, $1f, $22, data_66_4530_PlayerTiles + $0220
    player_piece  -12,  -10, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece   -7,    6, PLAYER_PIECE_PAL0
    player_piece  -29,  -10, PLAYER_PIECE_PAL1
    player_piece  -16,  -10, PLAYER_PIECE_PAL1
    player_piece  -29,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,    6, PLAYER_PIECE_PAL1

data_66_4077_PlayerFrame_004:
    player_frame_header   9, $1f, $22, data_66_4530_PlayerTiles + $0340
    player_piece  -13,  -10, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece  -13,    6, PLAYER_PIECE_PAL0
    player_piece  -29,  -10, PLAYER_PIECE_PAL1
    player_piece  -16,  -10, PLAYER_PIECE_PAL1
    player_piece  -29,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,    6, PLAYER_PIECE_PAL1

data_66_40a0_PlayerFrame_005:
    player_frame_header   8, $1f, $22, data_66_4530_PlayerTiles + $0460
    player_piece  -25,   -5, PLAYER_PIECE_PAL0
    player_piece   -9,  -11, PLAYER_PIECE_PAL0
    player_piece  -17,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    3, PLAYER_PIECE_PAL1
    player_piece  -13,   -7, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_66_40c5_PlayerFrame_006:
    player_frame_header   9, $1f, $22, data_66_4530_PlayerTiles + $0560
    player_piece  -25,   -5, PLAYER_PIECE_PAL0
    player_piece  -22,    3, PLAYER_PIECE_PAL0
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece   -9,   -4, PLAYER_PIECE_PAL0
    player_piece   -7,    8, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    3, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -24,    3, PLAYER_PIECE_PAL1

data_66_40ee_PlayerFrame_007:
    player_frame_header   6, $1f, $22, data_66_4530_PlayerTiles + $0680
    player_piece  -13,  -18, PLAYER_PIECE_PAL0
    player_piece  -28,  -10, PLAYER_PIECE_PAL0
    player_piece  -28,   -2, PLAYER_PIECE_PAL0
    player_piece  -15,    6, PLAYER_PIECE_PAL0
    player_piece  -31,  -10, PLAYER_PIECE_PAL1
    player_piece  -31,   -2, PLAYER_PIECE_PAL1

data_66_410b_PlayerFrame_008:
    player_frame_header   6, $1f, $22, data_66_4530_PlayerTiles + $0740
    player_piece  -21,  -18, PLAYER_PIECE_PAL0
    player_piece  -34,  -10, PLAYER_PIECE_PAL0
    player_piece  -34,   -2, PLAYER_PIECE_PAL0
    player_piece  -22,    6, PLAYER_PIECE_PAL0
    player_piece  -38,  -10, PLAYER_PIECE_PAL1
    player_piece  -38,   -2, PLAYER_PIECE_PAL1

data_66_4128_PlayerFrame_009:
    player_frame_header   4, $1f, $22, data_66_4530_PlayerTiles + $0800
    player_piece  -42,  -15, PLAYER_PIECE_PAL0
    player_piece  -40,   -7, PLAYER_PIECE_PAL0
    player_piece  -40,    1, PLAYER_PIECE_PAL0
    player_piece  -42,    8, PLAYER_PIECE_PAL0

data_66_413d_PlayerFrame_010:
    player_frame_header   3, $20, $22, data_66_4530_PlayerTiles + $0880
    player_piece  -39,  -10, PLAYER_PIECE_PAL0
    player_piece  -39,   -2, PLAYER_PIECE_PAL0
    player_piece  -42,    6, PLAYER_PIECE_PAL0

data_66_414e_PlayerFrame_011:
    player_frame_header   2, $20, $22, data_66_4530_PlayerTiles + $08e0
    player_piece  -39,  -10, PLAYER_PIECE_PAL0
    player_piece  -39,   -2, PLAYER_PIECE_PAL0

data_66_415b_PlayerFrame_012:
    player_frame_header   8, $1f, $22, data_66_4530_PlayerTiles + $0920
    player_piece  -12,  -10, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,  -10, PLAYER_PIECE_PAL1
    player_piece  -13,  -10, PLAYER_PIECE_PAL1
    player_piece  -29,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,    6, PLAYER_PIECE_PAL1

data_66_4180_PlayerFrame_013:
    player_frame_header   7, $1d, $22, data_66_4530_PlayerTiles + $0a20
    player_piece  -21,   -5, PLAYER_PIECE_PAL0
    player_piece  -21,    3, PLAYER_PIECE_PAL0
    player_piece  -38,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -9, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1
    player_piece  -16,    7, PLAYER_PIECE_PAL1
    player_piece  -32,   -3, PLAYER_PIECE_PAL1

data_66_41a1_PlayerFrame_014:
    player_frame_header   6, $1a, $22, data_66_4530_PlayerTiles + $0b00
    player_piece  -21,  -10, PLAYER_PIECE_PAL0
    player_piece  -21,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,  -10, PLAYER_PIECE_PAL1
    player_piece  -24,   -2, PLAYER_PIECE_PAL1
    player_piece   -8,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,    6, PLAYER_PIECE_PAL1

data_66_41be_PlayerFrame_015:
    player_frame_header   7, $16, $22, data_66_4530_PlayerTiles + $0bc0
    player_piece  -20,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,    3, PLAYER_PIECE_PAL0
    player_piece  -20,   -7, PLAYER_PIECE_PAL1
    player_piece  -20,    1, PLAYER_PIECE_PAL1
    player_piece   -4,   -9, PLAYER_PIECE_PAL1
    player_piece   -4,   -1, PLAYER_PIECE_PAL1
    player_piece   -4,    7, PLAYER_PIECE_PAL1

data_66_41df_PlayerFrame_016:
    player_frame_header   7, $13, $22, data_66_4530_PlayerTiles + $0ca0
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,    4, PLAYER_PIECE_PAL0
    player_piece  -17,   -8, PLAYER_PIECE_PAL1
    player_piece  -17,    0, PLAYER_PIECE_PAL1
    player_piece   -1,   -9, PLAYER_PIECE_PAL1
    player_piece   -1,   -1, PLAYER_PIECE_PAL1
    player_piece   -2,    7, PLAYER_PIECE_PAL1

data_66_4200_PlayerFrame_017:
    player_frame_header   3, $0f, $22, data_66_4530_PlayerTiles + $0d80
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -16,    2, PLAYER_PIECE_PAL1

data_66_4211_PlayerFrame_018:
    player_frame_header   2, $09, $22, data_66_4530_PlayerTiles + $0de0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL1

data_66_421e_PlayerFrame_019:
    player_frame_header   9, $1c, $22, data_66_4530_PlayerTiles + $0e20
    player_piece  -36,  -18, PLAYER_PIECE_PAL0
    player_piece  -26,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece  -32,  -18, PLAYER_PIECE_PAL1
    player_piece  -25,  -10, PLAYER_PIECE_PAL1
    player_piece   -9,  -10, PLAYER_PIECE_PAL1
    player_piece  -22,   -2, PLAYER_PIECE_PAL1
    player_piece   -6,   -2, PLAYER_PIECE_PAL1
    player_piece  -14,    6, PLAYER_PIECE_PAL1

data_66_4247_PlayerFrame_020:
    player_frame_header   7, $1e, $22, data_66_4530_PlayerTiles + $0f40
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece  -28,    5, PLAYER_PIECE_PAL0
    player_piece  -18,  -15, PLAYER_PIECE_PAL1
    player_piece  -28,   -7, PLAYER_PIECE_PAL1
    player_piece  -12,   -7, PLAYER_PIECE_PAL1
    player_piece  -23,    1, PLAYER_PIECE_PAL1
    player_piece   -7,    1, PLAYER_PIECE_PAL1

data_66_4268_PlayerFrame_021:
    player_frame_header   7, $1d, $22, data_66_4530_PlayerTiles + $1020
    player_piece  -24,  -10, PLAYER_PIECE_PAL0
    player_piece  -23,   -2, PLAYER_PIECE_PAL0
    player_piece  -20,  -18, PLAYER_PIECE_PAL1
    player_piece  -27,  -10, PLAYER_PIECE_PAL1
    player_piece  -11,  -10, PLAYER_PIECE_PAL1
    player_piece  -26,   -2, PLAYER_PIECE_PAL1
    player_piece   -9,   -2, PLAYER_PIECE_PAL1

data_66_4289_PlayerFrame_022:
    player_frame_header   7, $1c, $22, data_66_4530_PlayerTiles + $1100
    player_piece  -22,   -2, PLAYER_PIECE_PAL0
    player_piece  -13,    6, PLAYER_PIECE_PAL0
    player_piece  -18,  -15, PLAYER_PIECE_PAL1
    player_piece  -26,   -7, PLAYER_PIECE_PAL1
    player_piece  -31,    1, PLAYER_PIECE_PAL1
    player_piece  -10,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1

data_66_42aa_PlayerFrame_023:
    player_frame_header   8, $1f, $22, data_66_4530_PlayerTiles + $11e0
    player_piece  -23,    1, PLAYER_PIECE_PAL0
    player_piece  -25,    8, PLAYER_PIECE_PAL0
    player_piece  -39,    1, PLAYER_PIECE_PAL0
    player_piece  -18,  -12, PLAYER_PIECE_PAL1
    player_piece  -16,   -4, PLAYER_PIECE_PAL1
    player_piece  -16,    4, PLAYER_PIECE_PAL1
    player_piece  -32,   -3, PLAYER_PIECE_PAL1
    player_piece  -33,    5, PLAYER_PIECE_PAL1

data_66_42cf_PlayerFrame_024:
    player_frame_header   7, $20, $22, data_66_4530_PlayerTiles + $12e0
    player_piece  -26,   -2, PLAYER_PIECE_PAL0
    player_piece  -25,    1, PLAYER_PIECE_PAL0
    player_piece  -30,  -12, PLAYER_PIECE_PAL1
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,  -12, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -24,    4, PLAYER_PIECE_PAL1

data_66_42f0_PlayerFrame_025:
    player_frame_header   7, $21, $22, data_66_4530_PlayerTiles + $13c0
    player_piece  -27,  -10, PLAYER_PIECE_PAL0
    player_piece  -26,   -2, PLAYER_PIECE_PAL0
    player_piece  -22,  -18, PLAYER_PIECE_PAL1
    player_piece  -31,  -10, PLAYER_PIECE_PAL1
    player_piece  -15,  -10, PLAYER_PIECE_PAL1
    player_piece  -27,   -2, PLAYER_PIECE_PAL1
    player_piece  -11,   -2, PLAYER_PIECE_PAL1

data_66_4311_PlayerFrame_026:
    player_frame_header   7, $1c, $22, data_66_4530_PlayerTiles + $14a0
    player_piece  -22,    1, PLAYER_PIECE_PAL0
    player_piece  -26,    8, PLAYER_PIECE_PAL0
    player_piece  -17,  -11, PLAYER_PIECE_PAL1
    player_piece  -17,   -3, PLAYER_PIECE_PAL1
    player_piece  -18,    5, PLAYER_PIECE_PAL1
    player_piece  -33,   -5, PLAYER_PIECE_PAL1
    player_piece  -33,    3, PLAYER_PIECE_PAL1

data_66_4332_PlayerFrame_027:
    player_frame_header   7, $1c, $22, data_66_4530_PlayerTiles + $1580
    player_piece  -22,    1, PLAYER_PIECE_PAL0
    player_piece  -26,    8, PLAYER_PIECE_PAL0
    player_piece  -17,  -10, PLAYER_PIECE_PAL1
    player_piece  -17,   -2, PLAYER_PIECE_PAL1
    player_piece  -20,    6, PLAYER_PIECE_PAL1
    player_piece  -33,   -7, PLAYER_PIECE_PAL1
    player_piece  -33,    1, PLAYER_PIECE_PAL1

data_66_4353_PlayerFrame_028:
    player_frame_header   7, $25, $22, data_66_4530_PlayerTiles + $1660
    player_piece  -31,   -2, PLAYER_PIECE_PAL0
    player_piece  -31,    6, PLAYER_PIECE_PAL0
    player_piece  -35,   -6, PLAYER_PIECE_PAL1
    player_piece  -19,   -8, PLAYER_PIECE_PAL1
    player_piece  -30,    0, PLAYER_PIECE_PAL1
    player_piece  -14,   -3, PLAYER_PIECE_PAL1
    player_piece  -18,    5, PLAYER_PIECE_PAL1

data_66_4374_PlayerFrame_029:
    player_frame_header   6, $21, $22, data_66_4530_PlayerTiles + $1740
    player_piece  -27,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    6, PLAYER_PIECE_PAL0
    player_piece  -31,   -6, PLAYER_PIECE_PAL1
    player_piece  -26,    2, PLAYER_PIECE_PAL1
    player_piece  -15,   -8, PLAYER_PIECE_PAL1
    player_piece  -16,    0, PLAYER_PIECE_PAL1

data_66_4391_PlayerFrame_030:
    player_frame_header   7, $1e, $22, data_66_4530_PlayerTiles + $1800
    player_piece  -24,   -2, PLAYER_PIECE_PAL0
    player_piece  -24,    6, PLAYER_PIECE_PAL0
    player_piece  -28,  -10, PLAYER_PIECE_PAL1
    player_piece  -12,  -10, PLAYER_PIECE_PAL1
    player_piece  -27,   -2, PLAYER_PIECE_PAL1
    player_piece  -11,   -2, PLAYER_PIECE_PAL1
    player_piece  -17,    6, PLAYER_PIECE_PAL1

data_66_43b2_PlayerFrame_031:
    player_frame_header   7, $1d, $22, data_66_4530_PlayerTiles + $18e0
    player_piece  -23,   -2, PLAYER_PIECE_PAL0
    player_piece  -23,    6, PLAYER_PIECE_PAL0
    player_piece  -27,  -10, PLAYER_PIECE_PAL1
    player_piece  -11,  -10, PLAYER_PIECE_PAL1
    player_piece  -26,   -2, PLAYER_PIECE_PAL1
    player_piece  -10,   -2, PLAYER_PIECE_PAL1
    player_piece  -17,    6, PLAYER_PIECE_PAL1

data_66_43d3_PlayerFrame_032:
    player_frame_header   8, $1f, $24, data_66_4530_PlayerTiles + $19c0
    player_piece  -25,   -4, PLAYER_PIECE_PAL0
    player_piece  -12,    4, PLAYER_PIECE_PAL0
    player_piece   -9,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    3, PLAYER_PIECE_PAL1
    player_piece  -13,   -8, PLAYER_PIECE_PAL1
    player_piece  -16,    0, PLAYER_PIECE_PAL1
    player_piece  -16,    8, PLAYER_PIECE_PAL1

data_66_43f8_PlayerFrame_033:
    player_frame_header   8, $1f, $24, data_66_4530_PlayerTiles + $1ac0
    player_piece  -21,   -6, PLAYER_PIECE_PAL0
    player_piece  -22,    2, PLAYER_PIECE_PAL0
    player_piece  -39,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -16,    2, PLAYER_PIECE_PAL1
    player_piece  -21,    9, PLAYER_PIECE_PAL1
    player_piece  -32,   -4, PLAYER_PIECE_PAL1
    player_piece  -32,    4, PLAYER_PIECE_PAL1

data_66_441d_PlayerFrame_034:
    player_frame_header   7, $1f, $24, data_66_4530_PlayerTiles + $1bc0
    player_piece  -24,   -7, PLAYER_PIECE_PAL0
    player_piece   -9,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,    3, PLAYER_PIECE_PAL1
    player_piece  -21,   11, PLAYER_PIECE_PAL1

data_66_443e_PlayerFrame_035:
    player_frame_header   6, $1f, $24, data_66_4530_PlayerTiles + $1ca0
    player_piece  -24,   -6, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    3, PLAYER_PIECE_PAL1
    player_piece  -20,    9, PLAYER_PIECE_PAL1
    player_piece  -13,   -6, PLAYER_PIECE_PAL1
    player_piece  -13,    2, PLAYER_PIECE_PAL1

data_66_445b_PlayerFrame_036:
    player_frame_header   6, $1f, $24, data_66_4530_PlayerTiles + $1d60
    player_piece  -25,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,   -4, PLAYER_PIECE_PAL1
    player_piece  -29,    4, PLAYER_PIECE_PAL1
    player_piece  -13,   -8, PLAYER_PIECE_PAL1
    player_piece  -13,    0, PLAYER_PIECE_PAL1
    player_piece   -7,    8, PLAYER_PIECE_PAL1

data_66_4478_PlayerFrame_037:
    player_frame_header   6, $1f, $24, data_66_4530_PlayerTiles + $1e20
    player_piece  -24,    5, PLAYER_PIECE_PAL0
    player_piece  -18,  -11, PLAYER_PIECE_PAL1
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -13,   -3, PLAYER_PIECE_PAL1
    player_piece  -26,    5, PLAYER_PIECE_PAL1
    player_piece  -10,    5, PLAYER_PIECE_PAL1

data_66_4495_PlayerFrame_038:
    player_frame_header   8, $1f, $24, data_66_4530_PlayerTiles + $1ee0
    player_piece  -22,    0, PLAYER_PIECE_PAL0
    player_piece  -24,    2, PLAYER_PIECE_PAL0
    player_piece  -22,  -18, PLAYER_PIECE_PAL1
    player_piece  -16,  -10, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,    6, PLAYER_PIECE_PAL1
    player_piece  -32,   -2, PLAYER_PIECE_PAL1
    player_piece  -34,    6, PLAYER_PIECE_PAL1

data_66_44ba_PlayerFrame_039:
    player_frame_header   8, $1f, $24, data_66_4530_PlayerTiles + $1fe0
    player_piece  -25,   -1, PLAYER_PIECE_PAL0
    player_piece  -12,    7, PLAYER_PIECE_PAL0
    player_piece   -9,   -1, PLAYER_PIECE_PAL0
    player_piece  -17,  -12, PLAYER_PIECE_PAL1
    player_piece  -29,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    4, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,    3, PLAYER_PIECE_PAL1

data_66_44df_PlayerFrame_040:
    player_frame_header   9, $1b, $22, data_66_4530_PlayerTiles + $20e0
    player_piece  -21,   -2, PLAYER_PIECE_PAL0
    player_piece   -5,   -2, PLAYER_PIECE_PAL0
    player_piece  -20,    6, PLAYER_PIECE_PAL0
    player_piece   -4,  -18, PLAYER_PIECE_PAL1
    player_piece  -25,  -10, PLAYER_PIECE_PAL1
    player_piece   -9,  -10, PLAYER_PIECE_PAL1
    player_piece  -25,   -2, PLAYER_PIECE_PAL1
    player_piece   -9,   -2, PLAYER_PIECE_PAL1
    player_piece  -18,    6, PLAYER_PIECE_PAL1

data_66_4508_PlayerFrame_041:
    player_frame_header   8, $19, $22, data_66_4530_PlayerTiles + $2200
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece  -21,    6, PLAYER_PIECE_PAL0
    player_piece   -3,  -18, PLAYER_PIECE_PAL1
    player_piece  -16,  -10, PLAYER_PIECE_PAL1
    player_piece  -23,   -2, PLAYER_PIECE_PAL1
    player_piece   -7,   -2, PLAYER_PIECE_PAL1
    player_piece  -23,    6, PLAYER_PIECE_PAL1
    player_piece   -7,    6, PLAYER_PIECE_PAL1

    ds   $4530 - @, 0                    ; the bank pads to a 16-byte boundary here
data_66_4530_PlayerTiles:
; INCBINd by main.asm - see the header above
