; ==================================================================
; Bank $75. Gex's animation frames 184 to 198 of PLAYER_GFX_SET_TUT_TV.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $41b2, then 180 tiles of graphics from $41c0 to $4cff, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/sprite_data/bank7F.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_75_4000_PlayerFrame_184:
    player_frame_header   6, $27, $16, data_75_41c0_PlayerTiles + $0000
    player_piece  -37,   -5, PLAYER_PIECE_PAL0
    player_piece  -37,    3, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -21,    3, PLAYER_PIECE_PAL0
    player_piece  -18,   -2, PLAYER_PIECE_PAL0
    player_piece  -48,    0, PLAYER_PIECE_PAL1

data_75_401d_PlayerFrame_185:
    player_frame_header   6, $26, $16, data_75_41c0_PlayerTiles + $00c0
    player_piece  -36,   -6, PLAYER_PIECE_PAL0
    player_piece  -36,    2, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece  -20,    3, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -47,   -1, PLAYER_PIECE_PAL1

data_75_403a_PlayerFrame_186:
    player_frame_header   6, $22, $1c, data_75_41c0_PlayerTiles + $0180
    player_piece  -12,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -43,    5, PLAYER_PIECE_PAL1

data_75_4057_PlayerFrame_187:
    player_frame_header   6, $20, $1f, data_75_41c0_PlayerTiles + $0240
    player_piece  -21,  -11, PLAYER_PIECE_PAL0
    player_piece  -26,   -3, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -31,    5, PLAYER_PIECE_PAL0
    player_piece  -30,   12, PLAYER_PIECE_PAL0
    player_piece  -40,   12, PLAYER_PIECE_PAL1

data_75_4074_PlayerFrame_188:
    player_frame_header   6, $1f, $21, data_75_41c0_PlayerTiles + $0300
    player_piece  -30,  -11, PLAYER_PIECE_PAL0
    player_piece  -31,   -3, PLAYER_PIECE_PAL0
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece  -28,   13, PLAYER_PIECE_PAL0
    player_piece  -12,   13, PLAYER_PIECE_PAL0
    player_piece  -39,   13, PLAYER_PIECE_PAL1

data_75_4091_PlayerFrame_189:
    player_frame_header   6, $20, $20, data_75_41c0_PlayerTiles + $03c0
    player_piece  -33,  -11, PLAYER_PIECE_PAL0
    player_piece  -35,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -13,    5, PLAYER_PIECE_PAL0
    player_piece  -26,   13, PLAYER_PIECE_PAL0
    player_piece  -34,   13, PLAYER_PIECE_PAL1

data_75_40ae_PlayerFrame_190:
    player_frame_header   6, $20, $1d, data_75_41c0_PlayerTiles + $0480
    player_piece  -35,  -11, PLAYER_PIECE_PAL0
    player_piece  -34,   -3, PLAYER_PIECE_PAL0
    player_piece  -25,    5, PLAYER_PIECE_PAL0
    player_piece   -9,    5, PLAYER_PIECE_PAL0
    player_piece  -19,   10, PLAYER_PIECE_PAL0
    player_piece  -17,    5, PLAYER_PIECE_PAL1

data_75_40cb_PlayerFrame_191:
    player_frame_header   6, $22, $1e, data_75_41c0_PlayerTiles + $0540
    player_piece  -27,  -11, PLAYER_PIECE_PAL0
    player_piece  -32,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0
    player_piece  -43,    3, PLAYER_PIECE_PAL1

data_75_40e8_PlayerFrame_192:
    player_frame_header   5, $22, $1e, data_75_41c0_PlayerTiles + $0600
    player_piece  -31,  -10, PLAYER_PIECE_PAL0
    player_piece  -32,   -2, PLAYER_PIECE_PAL0
    player_piece  -34,    5, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -43,   -2, PLAYER_PIECE_PAL1

data_75_4101_PlayerFrame_193:
    player_frame_header   6, $22, $1f, data_75_41c0_PlayerTiles + $06a0
    player_piece  -32,  -10, PLAYER_PIECE_PAL0
    player_piece  -32,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    6, PLAYER_PIECE_PAL0
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -15,    4, PLAYER_PIECE_PAL0
    player_piece  -43,   -4, PLAYER_PIECE_PAL1

data_75_411e_PlayerFrame_194:
    player_frame_header   6, $22, $20, data_75_41c0_PlayerTiles + $0760
    player_piece  -35,  -13, PLAYER_PIECE_PAL0
    player_piece  -32,   -5, PLAYER_PIECE_PAL0
    player_piece  -18,    7, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,    3, PLAYER_PIECE_PAL0
    player_piece  -43,   -8, PLAYER_PIECE_PAL1

data_75_413b_PlayerFrame_195:
    player_frame_header   7, $22, $1f, data_75_41c0_PlayerTiles + $0820
    player_piece  -34,  -12, PLAYER_PIECE_PAL0
    player_piece  -32,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,    4, PLAYER_PIECE_PAL0
    player_piece  -18,    6, PLAYER_PIECE_PAL0
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece   -8,    4, PLAYER_PIECE_PAL0
    player_piece  -44,   -5, PLAYER_PIECE_PAL1

data_75_415c_PlayerFrame_196:
    player_frame_header   5, $22, $1f, data_75_41c0_PlayerTiles + $0900
    player_piece  -31,   -9, PLAYER_PIECE_PAL0
    player_piece  -15,   -9, PLAYER_PIECE_PAL0
    player_piece  -32,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -27,    6, PLAYER_PIECE_PAL0

data_75_4175_PlayerFrame_197:
    player_frame_header   7, $22, $21, data_75_41c0_PlayerTiles + $09a0
    player_piece  -18,  -17, PLAYER_PIECE_PAL0
    player_piece  -24,   -9, PLAYER_PIECE_PAL0
    player_piece   -8,   -9, PLAYER_PIECE_PAL0
    player_piece  -32,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -34,    7, PLAYER_PIECE_PAL0
    player_piece  -44,    7, PLAYER_PIECE_PAL1

data_75_4196_PlayerFrame_198:
    player_frame_header   6, $22, $22, data_75_41c0_PlayerTiles + $0a80
    player_piece  -18,  -11, PLAYER_PIECE_PAL0
    player_piece  -32,    1, PLAYER_PIECE_PAL0
    player_piece  -39,    9, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -27,    5, PLAYER_PIECE_PAL0
    player_piece  -43,    8, PLAYER_PIECE_PAL1

    ds   $41c0 - @, 0                    ; the bank pads to a 16-byte boundary here
data_75_41c0_PlayerTiles:
; INCBINd by main.asm - see the header above
