; ==================================================================
; Bank $63. Gex's animation frames 68 to 144 of PLAYER_GFX_SET_ANIME_CHANNEL.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $4868, then 884 tiles of graphics from $4870 to $7faf, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/sprite_data/bank7F.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_63_4000_PlayerFrame_068:
    player_frame_header   6, $1e, $28, data_63_4870_PlayerTiles + $0000
    player_piece  -36,   -4, PLAYER_PIECE_PAL0
    player_piece  -37,    4, PLAYER_PIECE_PAL0
    player_piece  -25,   -9, PLAYER_PIECE_PAL1
    player_piece  -25,   -1, PLAYER_PIECE_PAL1
    player_piece  -16,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1

data_63_401d_PlayerFrame_069:
    player_frame_header   6, $1e, $28, data_63_4870_PlayerTiles + $00c0
    player_piece  -36,   -3, PLAYER_PIECE_PAL0
    player_piece  -37,    5, PLAYER_PIECE_PAL0
    player_piece  -21,   -9, PLAYER_PIECE_PAL1
    player_piece  -26,   -1, PLAYER_PIECE_PAL1
    player_piece  -10,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1

data_63_403a_PlayerFrame_070:
    player_frame_header   6, $1e, $28, data_63_4870_PlayerTiles + $0180
    player_piece  -36,   -2, PLAYER_PIECE_PAL0
    player_piece  -37,    6, PLAYER_PIECE_PAL0
    player_piece  -21,   -8, PLAYER_PIECE_PAL1
    player_piece  -26,    0, PLAYER_PIECE_PAL1
    player_piece   -5,   -8, PLAYER_PIECE_PAL1
    player_piece  -16,    0, PLAYER_PIECE_PAL1

data_63_4057_PlayerFrame_071:
    player_frame_header   6, $1e, $28, data_63_4870_PlayerTiles + $0240
    player_piece  -36,   -2, PLAYER_PIECE_PAL0
    player_piece  -37,    6, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL1
    player_piece  -26,    1, PLAYER_PIECE_PAL1
    player_piece   -9,   -8, PLAYER_PIECE_PAL1
    player_piece  -16,    0, PLAYER_PIECE_PAL1

data_63_4074_PlayerFrame_072:
    player_frame_header   6, $15, $26, data_63_4870_PlayerTiles + $0300
    player_piece  -13,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -20,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,    5, PLAYER_PIECE_PAL0
    player_piece  -20,   11, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL1

data_63_4091_PlayerFrame_073:
    player_frame_header   6, $14, $27, data_63_4870_PlayerTiles + $03c0
    player_piece  -14,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece  -19,    5, PLAYER_PIECE_PAL0
    player_piece  -20,   12, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL1

data_63_40ae_PlayerFrame_074:
    player_frame_header   5, $14, $27, data_63_4870_PlayerTiles + $0480
    player_piece  -13,  -14, PLAYER_PIECE_PAL0
    player_piece  -23,   -6, PLAYER_PIECE_PAL0
    player_piece  -18,    2, PLAYER_PIECE_PAL0
    player_piece  -20,   10, PLAYER_PIECE_PAL0
    player_piece  -30,   10, PLAYER_PIECE_PAL1

data_63_40c7_PlayerFrame_075:
    player_frame_header   6, $14, $27, data_63_4870_PlayerTiles + $0520
    player_piece  -13,  -19, PLAYER_PIECE_PAL0
    player_piece  -22,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -19,    5, PLAYER_PIECE_PAL0
    player_piece  -22,   12, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL1

data_63_40e4_PlayerFrame_076:
    player_frame_header   5, $14, $25, data_63_4870_PlayerTiles + $05e0
    player_piece  -13,  -16, PLAYER_PIECE_PAL0
    player_piece  -23,   -8, PLAYER_PIECE_PAL0
    player_piece  -20,    0, PLAYER_PIECE_PAL0
    player_piece  -20,    8, PLAYER_PIECE_PAL0
    player_piece  -30,    8, PLAYER_PIECE_PAL1

data_63_40fd_PlayerFrame_077:
    player_frame_header   6, $14, $26, data_63_4870_PlayerTiles + $0680
    player_piece  -14,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    5, PLAYER_PIECE_PAL0
    player_piece  -26,   11, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL1

data_63_411a_PlayerFrame_078:
    player_frame_header   6, $15, $26, data_63_4870_PlayerTiles + $0740
    player_piece  -15,  -16, PLAYER_PIECE_PAL0
    player_piece  -23,   -8, PLAYER_PIECE_PAL0
    player_piece  -18,    0, PLAYER_PIECE_PAL0
    player_piece  -20,    8, PLAYER_PIECE_PAL0
    player_piece  -29,   11, PLAYER_PIECE_PAL0
    player_piece  -31,   10, PLAYER_PIECE_PAL1

data_63_4137_PlayerFrame_079:
    player_frame_header   5, $1e, $26, data_63_4870_PlayerTiles + $0800
    player_piece  -16,  -14, PLAYER_PIECE_PAL0
    player_piece  -21,   -6, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -34,    6, PLAYER_PIECE_PAL0
    player_piece  -39,    2, PLAYER_PIECE_PAL1

data_63_4150_PlayerFrame_080:
    player_frame_header   5, $1e, $26, data_63_4870_PlayerTiles + $08a0
    player_piece  -16,  -14, PLAYER_PIECE_PAL0
    player_piece  -22,   -6, PLAYER_PIECE_PAL0
    player_piece  -29,    1, PLAYER_PIECE_PAL0
    player_piece  -32,    9, PLAYER_PIECE_PAL0
    player_piece  -39,    2, PLAYER_PIECE_PAL1

data_63_4169_PlayerFrame_081:
    player_frame_header   6, $1e, $26, data_63_4870_PlayerTiles + $0940
    player_piece   -4,  -19, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece  -28,    5, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL1

data_63_4186_PlayerFrame_082:
    player_frame_header   6, $1f, $26, data_63_4870_PlayerTiles + $0a00
    player_piece  -17,  -13, PLAYER_PIECE_PAL0
    player_piece  -18,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece  -28,    4, PLAYER_PIECE_PAL0
    player_piece  -39,    8, PLAYER_PIECE_PAL0
    player_piece  -40,    3, PLAYER_PIECE_PAL1

data_63_41a3_PlayerFrame_083:
    player_frame_header   5, $1f, $26, data_63_4870_PlayerTiles + $0ac0
    player_piece  -17,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -28,    2, PLAYER_PIECE_PAL0
    player_piece  -36,    8, PLAYER_PIECE_PAL0
    player_piece  -41,    5, PLAYER_PIECE_PAL1

data_63_41bc_PlayerFrame_084:
    player_frame_header   5, $1f, $26, data_63_4870_PlayerTiles + $0b60
    player_piece  -15,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL0
    player_piece  -32,   11, PLAYER_PIECE_PAL0

data_63_41d5_PlayerFrame_085:
    player_frame_header   5, $1f, $26, data_63_4870_PlayerTiles + $0c00
    player_piece  -18,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -36,   11, PLAYER_PIECE_PAL0

data_63_41ee_PlayerFrame_086:
    player_frame_header   6, $1e, $26, data_63_4870_PlayerTiles + $0ca0
    player_piece  -33,  -14, PLAYER_PIECE_PAL0
    player_piece  -25,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -20,   10, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -25,    9, PLAYER_PIECE_PAL1

data_63_420b_PlayerFrame_087:
    player_frame_header   6, $1d, $26, data_63_4870_PlayerTiles + $0d60
    player_piece  -36,  -19, PLAYER_PIECE_PAL0
    player_piece  -28,  -11, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece   -6,   -3, PLAYER_PIECE_PAL0
    player_piece  -17,    5, PLAYER_PIECE_PAL0
    player_piece  -11,    5, PLAYER_PIECE_PAL1

data_63_4228_PlayerFrame_088:
    player_frame_header   6, $1b, $26, data_63_4870_PlayerTiles + $0e20
    player_piece  -36,  -19, PLAYER_PIECE_PAL0
    player_piece  -27,  -11, PLAYER_PIECE_PAL0
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece   -3,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0
    player_piece  -11,    5, PLAYER_PIECE_PAL1

data_63_4245_PlayerFrame_089:
    player_frame_header   6, $1e, $26, data_63_4870_PlayerTiles + $0ee0
    player_piece  -35,  -19, PLAYER_PIECE_PAL0
    player_piece  -29,  -11, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0
    player_piece  -11,   11, PLAYER_PIECE_PAL0
    player_piece  -25,    5, PLAYER_PIECE_PAL1

data_63_4262_PlayerFrame_090:
    player_frame_header   5, $1d, $26, data_63_4870_PlayerTiles + $0fa0
    player_piece  -35,  -12, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -17,   10, PLAYER_PIECE_PAL0
    player_piece  -26,   12, PLAYER_PIECE_PAL1

data_63_427b_PlayerFrame_091:
    player_frame_header   4, $1c, $26, data_63_4870_PlayerTiles + $1040
    player_piece  -32,  -13, PLAYER_PIECE_PAL0
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -19,   10, PLAYER_PIECE_PAL0

data_63_4290_PlayerFrame_092:
    player_frame_header   4, $1d, $26, data_63_4870_PlayerTiles + $10c0
    player_piece  -32,  -14, PLAYER_PIECE_PAL0
    player_piece  -24,   -6, PLAYER_PIECE_PAL0
    player_piece  -14,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    5, PLAYER_PIECE_PAL0

data_63_42a5_PlayerFrame_093:
    player_frame_header   6, $1d, $23, data_63_4870_PlayerTiles + $1140
    player_piece  -35,    1, PLAYER_PIECE_PAL0
    player_piece  -36,    9, PLAYER_PIECE_PAL0
    player_piece  -19,  -11, PLAYER_PIECE_PAL1
    player_piece  -20,   -3, PLAYER_PIECE_PAL1
    player_piece  -21,    5, PLAYER_PIECE_PAL1
    player_piece  -36,   -2, PLAYER_PIECE_PAL1

data_63_42c2_PlayerFrame_094:
    player_frame_header   7, $1d, $23, data_63_4870_PlayerTiles + $1200
    player_piece  -35,    2, PLAYER_PIECE_PAL0
    player_piece  -36,    9, PLAYER_PIECE_PAL0
    player_piece  -20,  -11, PLAYER_PIECE_PAL1
    player_piece  -25,   -3, PLAYER_PIECE_PAL1
    player_piece  -32,    5, PLAYER_PIECE_PAL1
    player_piece  -19,   -3, PLAYER_PIECE_PAL1
    player_piece   -7,    5, PLAYER_PIECE_PAL1

data_63_42e3_PlayerFrame_095:
    player_frame_header   7, $1e, $23, data_63_4870_PlayerTiles + $12e0
    player_piece  -36,   -2, PLAYER_PIECE_PAL0
    player_piece  -36,    6, PLAYER_PIECE_PAL0
    player_piece  -12,  -18, PLAYER_PIECE_PAL1
    player_piece  -20,  -10, PLAYER_PIECE_PAL1
    player_piece  -26,   -2, PLAYER_PIECE_PAL1
    player_piece  -18,   -2, PLAYER_PIECE_PAL1
    player_piece  -33,    6, PLAYER_PIECE_PAL1

data_63_4304_PlayerFrame_096:
    player_frame_header   6, $1e, $22, data_63_4870_PlayerTiles + $13c0
    player_piece  -36,   -2, PLAYER_PIECE_PAL0
    player_piece  -36,    6, PLAYER_PIECE_PAL0
    player_piece  -11,  -18, PLAYER_PIECE_PAL1
    player_piece  -15,  -10, PLAYER_PIECE_PAL1
    player_piece  -26,   -2, PLAYER_PIECE_PAL1
    player_piece  -10,   -2, PLAYER_PIECE_PAL1

data_63_4321_PlayerFrame_097:
    player_frame_header   5, $1e, $22, data_63_4870_PlayerTiles + $1480
    player_piece  -36,   -1, PLAYER_PIECE_PAL0
    player_piece  -37,    7, PLAYER_PIECE_PAL0
    player_piece  -17,  -11, PLAYER_PIECE_PAL1
    player_piece  -17,   -3, PLAYER_PIECE_PAL1
    player_piece  -31,   -2, PLAYER_PIECE_PAL1

data_63_433a_PlayerFrame_098:
    player_frame_header   7, $1f, $22, data_63_4870_PlayerTiles + $1520
    player_piece  -37,    0, PLAYER_PIECE_PAL0
    player_piece  -37,    8, PLAYER_PIECE_PAL0
    player_piece  -23,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    4, PLAYER_PIECE_PAL1
    player_piece  -16,  -11, PLAYER_PIECE_PAL1
    player_piece  -17,   -3, PLAYER_PIECE_PAL1
    player_piece  -11,    5, PLAYER_PIECE_PAL1

data_63_435b_PlayerFrame_099:
    player_frame_header   7, $1e, $22, data_63_4870_PlayerTiles + $1600
    player_piece  -36,    0, PLAYER_PIECE_PAL0
    player_piece  -36,    8, PLAYER_PIECE_PAL0
    player_piece  -19,  -11, PLAYER_PIECE_PAL1
    player_piece  -26,   -3, PLAYER_PIECE_PAL1
    player_piece  -25,    5, PLAYER_PIECE_PAL1
    player_piece  -18,   -5, PLAYER_PIECE_PAL1
    player_piece  -10,    3, PLAYER_PIECE_PAL1

data_63_437c_PlayerFrame_100:
    player_frame_header   7, $1d, $22, data_63_4870_PlayerTiles + $16e0
    player_piece  -35,    1, PLAYER_PIECE_PAL0
    player_piece  -36,    8, PLAYER_PIECE_PAL0
    player_piece  -20,  -11, PLAYER_PIECE_PAL1
    player_piece  -22,   -3, PLAYER_PIECE_PAL1
    player_piece  -31,    5, PLAYER_PIECE_PAL1
    player_piece  -19,   -7, PLAYER_PIECE_PAL1
    player_piece   -8,    2, PLAYER_PIECE_PAL1

data_63_439d_PlayerFrame_101:
    player_frame_header   7, $1d, $22, data_63_4870_PlayerTiles + $17c0
    player_piece  -35,    2, PLAYER_PIECE_PAL0
    player_piece  -35,    8, PLAYER_PIECE_PAL0
    player_piece  -14,  -11, PLAYER_PIECE_PAL1
    player_piece  -23,   -3, PLAYER_PIECE_PAL1
    player_piece  -32,    5, PLAYER_PIECE_PAL1
    player_piece  -19,   -3, PLAYER_PIECE_PAL1
    player_piece   -8,    5, PLAYER_PIECE_PAL1

data_63_43be_PlayerFrame_102:
    player_frame_header   6, $1f, $22, data_63_4870_PlayerTiles + $18a0
    player_piece  -37,    4, PLAYER_PIECE_PAL0
    player_piece  -38,   12, PLAYER_PIECE_PAL0
    player_piece  -21,   -9, PLAYER_PIECE_PAL1
    player_piece  -19,   -1, PLAYER_PIECE_PAL1
    player_piece  -22,    0, PLAYER_PIECE_PAL1
    player_piece  -38,    3, PLAYER_PIECE_PAL1

data_63_43db_PlayerFrame_103:
    player_frame_header   5, $1f, $22, data_63_4870_PlayerTiles + $1960
    player_piece  -37,    2, PLAYER_PIECE_PAL0
    player_piece  -38,    8, PLAYER_PIECE_PAL0
    player_piece  -21,   -9, PLAYER_PIECE_PAL1
    player_piece  -19,   -1, PLAYER_PIECE_PAL1
    player_piece  -35,    0, PLAYER_PIECE_PAL1

data_63_43f4_PlayerFrame_104:
    player_frame_header   5, $1e, $22, data_63_4870_PlayerTiles + $1a00
    player_piece  -36,    1, PLAYER_PIECE_PAL0
    player_piece  -37,    9, PLAYER_PIECE_PAL0
    player_piece  -18,   -9, PLAYER_PIECE_PAL1
    player_piece  -18,   -1, PLAYER_PIECE_PAL1
    player_piece  -32,    0, PLAYER_PIECE_PAL1

data_63_440d_PlayerFrame_105:
    player_frame_header   6, $1f, $22, data_63_4870_PlayerTiles + $1aa0
    player_piece  -37,   -2, PLAYER_PIECE_PAL0
    player_piece  -37,    6, PLAYER_PIECE_PAL0
    player_piece  -12,  -10, PLAYER_PIECE_PAL1
    player_piece  -27,   -2, PLAYER_PIECE_PAL1
    player_piece  -11,   -2, PLAYER_PIECE_PAL1
    player_piece  -20,    6, PLAYER_PIECE_PAL1

data_63_442a_PlayerFrame_106:
    player_frame_header   6, $1f, $22, data_63_4870_PlayerTiles + $1b60
    player_piece  -37,    1, PLAYER_PIECE_PAL0
    player_piece  -38,    9, PLAYER_PIECE_PAL0
    player_piece  -20,   -9, PLAYER_PIECE_PAL1
    player_piece  -27,   -1, PLAYER_PIECE_PAL1
    player_piece  -11,   -3, PLAYER_PIECE_PAL1
    player_piece  -21,    5, PLAYER_PIECE_PAL1

data_63_4447_PlayerFrame_107:
    player_frame_header   6, $17, $1c, data_63_4870_PlayerTiles + $1c20
    player_piece  -29,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL0
    player_piece  -12,  -12, PLAYER_PIECE_PAL1
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece   -3,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,    0, PLAYER_PIECE_PAL1

data_63_4464_PlayerFrame_108:
    player_frame_header   5, $17, $1b, data_63_4870_PlayerTiles + $1ce0
    player_piece  -29,   -5, PLAYER_PIECE_PAL0
    player_piece  -29,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1
    player_piece  -33,   -3, PLAYER_PIECE_PAL1

data_63_447d_PlayerFrame_109:
    player_frame_header   6, $17, $24, data_63_4870_PlayerTiles + $1d80
    player_piece  -29,   -4, PLAYER_PIECE_PAL0
    player_piece  -30,    4, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece   -3,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,    4, PLAYER_PIECE_PAL1
    player_piece  -11,    8, PLAYER_PIECE_PAL1

data_63_449a_PlayerFrame_110:
    player_frame_header   6, $17, $28, data_63_4870_PlayerTiles + $1e40
    player_piece  -29,  -12, PLAYER_PIECE_PAL0
    player_piece  -29,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece   -3,   -4, PLAYER_PIECE_PAL1
    player_piece  -13,    4, PLAYER_PIECE_PAL1
    player_piece  -11,   12, PLAYER_PIECE_PAL1

data_63_44b7_PlayerFrame_111:
    player_frame_header   6, $17, $22, data_63_4870_PlayerTiles + $1f00
    player_piece  -29,  -12, PLAYER_PIECE_PAL0
    player_piece  -29,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece   -3,   -4, PLAYER_PIECE_PAL1
    player_piece  -13,    4, PLAYER_PIECE_PAL1
    player_piece  -10,    6, PLAYER_PIECE_PAL1

data_63_44d4_PlayerFrame_112:
    player_frame_header   4, $17, $1c, data_63_4870_PlayerTiles + $1fc0
    player_piece  -30,   -4, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,    0, PLAYER_PIECE_PAL1

data_63_44e9_PlayerFrame_113:
    player_frame_header   6, $17, $1c, data_63_4870_PlayerTiles + $2040
    player_piece  -29,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL0
    player_piece  -11,  -12, PLAYER_PIECE_PAL1
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece   -3,   -4, PLAYER_PIECE_PAL1
    player_piece  -12,    0, PLAYER_PIECE_PAL1

data_63_4506_PlayerFrame_114:
    player_frame_header   6, $17, $1e, data_63_4870_PlayerTiles + $2100
    player_piece  -29,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -11,  -20, PLAYER_PIECE_PAL1
    player_piece  -12,  -12, PLAYER_PIECE_PAL1
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece   -3,   -4, PLAYER_PIECE_PAL1

data_63_4523_PlayerFrame_115:
    player_frame_header   7, $20, $1d, data_63_4870_PlayerTiles + $21c0
    player_piece  -38,   -4, PLAYER_PIECE_PAL0
    player_piece  -40,    4, PLAYER_PIECE_PAL0
    player_piece  -21,   -9, PLAYER_PIECE_PAL1
    player_piece  -24,   -1, PLAYER_PIECE_PAL1
    player_piece  -29,    5, PLAYER_PIECE_PAL1
    player_piece   -8,   -2, PLAYER_PIECE_PAL1
    player_piece  -13,    5, PLAYER_PIECE_PAL1

data_63_4544_PlayerFrame_116:
    player_frame_header   7, $20, $1f, data_63_4870_PlayerTiles + $22a0
    player_piece  -39,   -4, PLAYER_PIECE_PAL0
    player_piece  -40,    4, PLAYER_PIECE_PAL0
    player_piece  -23,   -7, PLAYER_PIECE_PAL1
    player_piece  -24,    1, PLAYER_PIECE_PAL1
    player_piece  -24,    7, PLAYER_PIECE_PAL1
    player_piece   -8,   -4, PLAYER_PIECE_PAL1
    player_piece   -8,    5, PLAYER_PIECE_PAL1

data_63_4565_PlayerFrame_117:
    player_frame_header   7, $1f, $1d, data_63_4870_PlayerTiles + $2380
    player_piece  -38,   -4, PLAYER_PIECE_PAL0
    player_piece  -38,    4, PLAYER_PIECE_PAL0
    player_piece  -28,  -10, PLAYER_PIECE_PAL1
    player_piece  -23,   -2, PLAYER_PIECE_PAL1
    player_piece  -19,    5, PLAYER_PIECE_PAL1
    player_piece  -12,   -7, PLAYER_PIECE_PAL1
    player_piece  -17,    1, PLAYER_PIECE_PAL1

data_63_4586_PlayerFrame_118:
    player_frame_header   7, $21, $1a, data_63_4870_PlayerTiles + $2460
    player_piece  -38,   -4, PLAYER_PIECE_PAL0
    player_piece  -38,    2, PLAYER_PIECE_PAL0
    player_piece  -31,  -11, PLAYER_PIECE_PAL1
    player_piece  -24,   -3, PLAYER_PIECE_PAL1
    player_piece  -20,    2, PLAYER_PIECE_PAL1
    player_piece  -15,   -9, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1

data_63_45a7_PlayerFrame_119:
    player_frame_header   7, $1f, $1d, data_63_4870_PlayerTiles + $2540
    player_piece  -38,   -4, PLAYER_PIECE_PAL0
    player_piece  -38,    4, PLAYER_PIECE_PAL0
    player_piece  -25,  -10, PLAYER_PIECE_PAL1
    player_piece  -22,   -2, PLAYER_PIECE_PAL1
    player_piece  -27,    5, PLAYER_PIECE_PAL1
    player_piece   -9,   -7, PLAYER_PIECE_PAL1
    player_piece  -17,    1, PLAYER_PIECE_PAL1

data_63_45c8_PlayerFrame_120:
    player_frame_header   7, $20, $1e, data_63_4870_PlayerTiles + $2620
    player_piece  -38,   -4, PLAYER_PIECE_PAL0
    player_piece  -40,    4, PLAYER_PIECE_PAL0
    player_piece  -21,  -11, PLAYER_PIECE_PAL1
    player_piece  -24,   -3, PLAYER_PIECE_PAL1
    player_piece  -30,    5, PLAYER_PIECE_PAL1
    player_piece   -8,   -6, PLAYER_PIECE_PAL1
    player_piece  -14,    2, PLAYER_PIECE_PAL1

data_63_45e9_PlayerFrame_121:
    player_frame_header   7, $1f, $1f, data_63_4870_PlayerTiles + $2700
    player_piece  -37,   -4, PLAYER_PIECE_PAL0
    player_piece  -38,    4, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL1
    player_piece  -22,    1, PLAYER_PIECE_PAL1
    player_piece  -34,    7, PLAYER_PIECE_PAL1
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece   -6,    3, PLAYER_PIECE_PAL1

data_63_460a_PlayerFrame_122:
    player_frame_header   7, $1e, $1c, data_63_4870_PlayerTiles + $27e0
    player_piece  -37,   -4, PLAYER_PIECE_PAL0
    player_piece  -37,    4, PLAYER_PIECE_PAL0
    player_piece  -27,   -9, PLAYER_PIECE_PAL1
    player_piece  -21,   -1, PLAYER_PIECE_PAL1
    player_piece  -19,    4, PLAYER_PIECE_PAL1
    player_piece  -11,   -6, PLAYER_PIECE_PAL1
    player_piece   -5,    2, PLAYER_PIECE_PAL1

data_63_462b_PlayerFrame_123:
    player_frame_header   7, $20, $1b, data_63_4870_PlayerTiles + $28c0
    player_piece  -39,   -4, PLAYER_PIECE_PAL0
    player_piece  -39,    3, PLAYER_PIECE_PAL0
    player_piece  -30,  -10, PLAYER_PIECE_PAL1
    player_piece  -24,   -2, PLAYER_PIECE_PAL1
    player_piece  -20,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -6, PLAYER_PIECE_PAL1
    player_piece  -17,    2, PLAYER_PIECE_PAL1

data_63_464c_PlayerFrame_124:
    player_frame_header   8, $20, $1c, data_63_4870_PlayerTiles + $29a0
    player_piece  -38,   -4, PLAYER_PIECE_PAL0
    player_piece  -39,    4, PLAYER_PIECE_PAL0
    player_piece  -25,  -10, PLAYER_PIECE_PAL1
    player_piece  -23,   -6, PLAYER_PIECE_PAL1
    player_piece  -23,    2, PLAYER_PIECE_PAL1
    player_piece   -7,   -4, PLAYER_PIECE_PAL1
    player_piece  -39,    5, PLAYER_PIECE_PAL1
    player_piece  -22,    5, PLAYER_PIECE_PAL1

data_63_4671_PlayerFrame_125:
    player_frame_header   4, $21, $19, data_63_4870_PlayerTiles + $2aa0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_63_4686_PlayerFrame_126:
    player_frame_header   4, $20, $18, data_63_4870_PlayerTiles + $2b20
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_63_469b_PlayerFrame_127:
    player_frame_header   4, $20, $18, data_63_4870_PlayerTiles + $2ba0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_63_46b0_PlayerFrame_128:
    player_frame_header   4, $20, $18, data_63_4870_PlayerTiles + $2c20
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_63_46c5_PlayerFrame_129:
    player_frame_header   4, $21, $18, data_63_4870_PlayerTiles + $2ca0
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_63_46da_PlayerFrame_130:
    player_frame_header   4, $20, $18, data_63_4870_PlayerTiles + $2d20
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_63_46ef_PlayerFrame_131:
    player_frame_header   4, $20, $18, data_63_4870_PlayerTiles + $2da0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_63_4704_PlayerFrame_132:
    player_frame_header   6, $1e, $1a, data_63_4870_PlayerTiles + $2e20
    player_piece  -35,   -8, PLAYER_PIECE_PAL0
    player_piece  -37,    0, PLAYER_PIECE_PAL0
    player_piece  -22,   -8, PLAYER_PIECE_PAL1
    player_piece  -21,    0, PLAYER_PIECE_PAL1
    player_piece   -6,   -8, PLAYER_PIECE_PAL1
    player_piece  -17,    0, PLAYER_PIECE_PAL1

data_63_4721_PlayerFrame_133:
    player_frame_header   6, $1d, $19, data_63_4870_PlayerTiles + $2ee0
    player_piece  -33,  -10, PLAYER_PIECE_PAL0
    player_piece  -37,   -2, PLAYER_PIECE_PAL0
    player_piece  -22,  -10, PLAYER_PIECE_PAL1
    player_piece   -6,  -10, PLAYER_PIECE_PAL1
    player_piece  -21,   -2, PLAYER_PIECE_PAL1
    player_piece  -17,   -2, PLAYER_PIECE_PAL1

data_63_473e_PlayerFrame_134:
    player_frame_header   6, $1d, $19, data_63_4870_PlayerTiles + $2fa0
    player_piece  -33,  -10, PLAYER_PIECE_PAL0
    player_piece  -36,   -2, PLAYER_PIECE_PAL0
    player_piece  -22,  -10, PLAYER_PIECE_PAL1
    player_piece   -6,  -10, PLAYER_PIECE_PAL1
    player_piece  -20,   -2, PLAYER_PIECE_PAL1
    player_piece  -17,   -2, PLAYER_PIECE_PAL1

data_63_475b_PlayerFrame_135:
    player_frame_header   6, $18, $1e, data_63_4870_PlayerTiles + $3060
    player_piece  -28,  -10, PLAYER_PIECE_PAL0
    player_piece  -29,   -2, PLAYER_PIECE_PAL0
    player_piece  -17,  -10, PLAYER_PIECE_PAL1
    player_piece   -1,  -10, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1
    player_piece   -4,    4, PLAYER_PIECE_PAL1

data_63_4778_PlayerFrame_136:
    player_frame_header   5, $14, $1e, data_63_4870_PlayerTiles + $3120
    player_piece  -24,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    4, PLAYER_PIECE_PAL0
    player_piece  -10,  -11, PLAYER_PIECE_PAL1
    player_piece  -16,   -3, PLAYER_PIECE_PAL1
    player_piece   -5,    4, PLAYER_PIECE_PAL1

data_63_4791_PlayerFrame_137:
    player_frame_header   5, $13, $1e, data_63_4870_PlayerTiles + $31c0
    player_piece  -23,   -2, PLAYER_PIECE_PAL0
    player_piece  -26,    4, PLAYER_PIECE_PAL0
    player_piece  -10,  -11, PLAYER_PIECE_PAL1
    player_piece  -16,   -3, PLAYER_PIECE_PAL1
    player_piece   -5,    4, PLAYER_PIECE_PAL1

data_63_47aa_PlayerFrame_138:
    player_frame_header   6, $17, $1f, data_63_4870_PlayerTiles + $3260
    player_piece  -29,    0, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -18,  -10, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -17,    5, PLAYER_PIECE_PAL1
    player_piece  -33,    4, PLAYER_PIECE_PAL1

data_63_47c7_PlayerFrame_139:
    player_frame_header   6, $17, $1d, data_63_4870_PlayerTiles + $3320
    player_piece  -29,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,    3, PLAYER_PIECE_PAL0
    player_piece  -18,  -10, PLAYER_PIECE_PAL1
    player_piece  -19,   -2, PLAYER_PIECE_PAL1
    player_piece   -3,   -2, PLAYER_PIECE_PAL1
    player_piece  -13,    3, PLAYER_PIECE_PAL1

data_63_47e4_PlayerFrame_140:
    player_frame_header   5, $17, $21, data_63_4870_PlayerTiles + $33e0
    player_piece  -28,    3, PLAYER_PIECE_PAL0
    player_piece  -28,    7, PLAYER_PIECE_PAL0
    player_piece  -20,  -14, PLAYER_PIECE_PAL1
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -16,    2, PLAYER_PIECE_PAL1

data_63_47fd_PlayerFrame_141:
    player_frame_header   6, $1e, $1d, data_63_4870_PlayerTiles + $3480
    player_piece  -36,   -4, PLAYER_PIECE_PAL0
    player_piece  -37,    2, PLAYER_PIECE_PAL0
    player_piece  -25,   -5, PLAYER_PIECE_PAL1
    player_piece  -25,    2, PLAYER_PIECE_PAL1
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,    2, PLAYER_PIECE_PAL1

data_63_481a_PlayerFrame_142:
    player_frame_header   6, $1e, $1c, data_63_4870_PlayerTiles + $3540
    player_piece  -36,   -4, PLAYER_PIECE_PAL0
    player_piece  -37,    1, PLAYER_PIECE_PAL0
    player_piece  -25,   -4, PLAYER_PIECE_PAL1
    player_piece  -25,    1, PLAYER_PIECE_PAL1
    player_piece  -16,   -4, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1

data_63_4837_PlayerFrame_143:
    player_frame_header   5, $1e, $1c, data_63_4870_PlayerTiles + $3600
    player_piece  -36,   -4, PLAYER_PIECE_PAL0
    player_piece  -37,    1, PLAYER_PIECE_PAL0
    player_piece  -25,   -5, PLAYER_PIECE_PAL1
    player_piece  -25,    1, PLAYER_PIECE_PAL1
    player_piece  -16,   -3, PLAYER_PIECE_PAL1

data_63_4850_PlayerFrame_144:
    player_frame_header   5, $1d, $1c, data_63_4870_PlayerTiles + $36a0
    player_piece  -35,   -4, PLAYER_PIECE_PAL0
    player_piece  -36,    1, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -17,    1, PLAYER_PIECE_PAL1
    player_piece  -32,   -3, PLAYER_PIECE_PAL1

    ds   $4870 - @, 0                    ; the bank pads to a 16-byte boundary here
data_63_4870_PlayerTiles:
; INCBINd by main.asm - see the header above
