; ==================================================================
; Bank $7a. Gex's animation frames 58 to 130 of PLAYER_GFX_SET_HOLIDAY_TV.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $4858, then 886 tiles of graphics from $4860 to $7fbf, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/sprite_data/bank7F.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_7a_4000_PlayerFrame_058:
    player_frame_header   6, $24, $27, data_7a_4860_PlayerTiles + $0000
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -42,   -5, PLAYER_PIECE_PAL0
    player_piece  -42,    0, PLAYER_PIECE_PAL0
    player_piece  -20,   -3, PLAYER_PIECE_PAL1
    player_piece  -36,   -6, PLAYER_PIECE_PAL1

data_7a_401d_PlayerFrame_059:
    player_frame_header   7, $24, $27, data_7a_4860_PlayerTiles + $00c0
    player_piece  -25,   -9, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -41,   -5, PLAYER_PIECE_PAL0
    player_piece  -42,    0, PLAYER_PIECE_PAL0
    player_piece  -19,   -8, PLAYER_PIECE_PAL1
    player_piece  -25,    0, PLAYER_PIECE_PAL1
    player_piece  -35,   -6, PLAYER_PIECE_PAL1

data_7a_403e_PlayerFrame_060:
    player_frame_header   7, $24, $27, data_7a_4860_PlayerTiles + $01a0
    player_piece  -28,   -9, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL0
    player_piece  -12,   -7, PLAYER_PIECE_PAL0
    player_piece  -44,    1, PLAYER_PIECE_PAL0
    player_piece  -34,   -5, PLAYER_PIECE_PAL1
    player_piece  -11,   -8, PLAYER_PIECE_PAL1
    player_piece  -18,    0, PLAYER_PIECE_PAL1

data_7a_405f_PlayerFrame_061:
    player_frame_header   7, $24, $27, data_7a_4860_PlayerTiles + $0280
    player_piece  -28,   -9, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL0
    player_piece  -12,   -7, PLAYER_PIECE_PAL0
    player_piece  -44,    1, PLAYER_PIECE_PAL0
    player_piece  -34,   -5, PLAYER_PIECE_PAL1
    player_piece  -18,   -4, PLAYER_PIECE_PAL1
    player_piece   -9,    4, PLAYER_PIECE_PAL1

data_7a_4080_PlayerFrame_062:
    player_frame_header   6, $24, $27, data_7a_4860_PlayerTiles + $0360
    player_piece  -28,   -8, PLAYER_PIECE_PAL0
    player_piece  -28,    0, PLAYER_PIECE_PAL0
    player_piece  -12,   -6, PLAYER_PIECE_PAL0
    player_piece  -44,    2, PLAYER_PIECE_PAL0
    player_piece  -34,   -4, PLAYER_PIECE_PAL1
    player_piece  -18,   -3, PLAYER_PIECE_PAL1

data_7a_409d_PlayerFrame_063:
    player_frame_header   6, $23, $29, data_7a_4860_PlayerTiles + $0420
    player_piece  -26,   -9, PLAYER_PIECE_PAL0
    player_piece  -25,   -1, PLAYER_PIECE_PAL0
    player_piece  -37,    2, PLAYER_PIECE_PAL0
    player_piece  -41,   -2, PLAYER_PIECE_PAL0
    player_piece  -20,   -3, PLAYER_PIECE_PAL1
    player_piece  -36,   -3, PLAYER_PIECE_PAL1

data_7a_40ba_PlayerFrame_064:
    player_frame_header   9, $22, $2a, data_7a_4860_PlayerTiles + $04e0
    player_piece  -26,   -9, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL0
    player_piece  -12,   -1, PLAYER_PIECE_PAL0
    player_piece  -31,    7, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,   -4, PLAYER_PIECE_PAL1
    player_piece  -16,   -4, PLAYER_PIECE_PAL1
    player_piece  -44,    4, PLAYER_PIECE_PAL1
    player_piece   -9,   -7, PLAYER_PIECE_PAL1

data_7a_40e3_PlayerFrame_065:
    player_frame_header   8, $21, $29, data_7a_4860_PlayerTiles + $0600
    player_piece  -24,   -9, PLAYER_PIECE_PAL0
    player_piece  -27,   -1, PLAYER_PIECE_PAL0
    player_piece  -11,   -1, PLAYER_PIECE_PAL0
    player_piece  -30,    7, PLAYER_PIECE_PAL0
    player_piece  -31,   -4, PLAYER_PIECE_PAL1
    player_piece  -15,   -4, PLAYER_PIECE_PAL1
    player_piece  -42,    4, PLAYER_PIECE_PAL1
    player_piece  -10,  -10, PLAYER_PIECE_PAL1

data_7a_4108_PlayerFrame_066:
    player_frame_header   6, $1f, $2b, data_7a_4860_PlayerTiles + $0700
    player_piece  -21,   -8, PLAYER_PIECE_PAL0
    player_piece  -22,    0, PLAYER_PIECE_PAL0
    player_piece  -27,    4, PLAYER_PIECE_PAL0
    player_piece  -19,  -11, PLAYER_PIECE_PAL1
    player_piece  -22,   -3, PLAYER_PIECE_PAL1
    player_piece  -38,    0, PLAYER_PIECE_PAL1

data_7a_4125_PlayerFrame_067:
    player_frame_header   6, $1b, $2d, data_7a_4860_PlayerTiles + $07c0
    player_piece  -20,   -8, PLAYER_PIECE_PAL0
    player_piece  -24,    3, PLAYER_PIECE_PAL0
    player_piece  -27,   11, PLAYER_PIECE_PAL0
    player_piece  -12,  -14, PLAYER_PIECE_PAL1
    player_piece  -24,   -4, PLAYER_PIECE_PAL1
    player_piece  -33,    4, PLAYER_PIECE_PAL1

data_7a_4142_PlayerFrame_068:
    player_frame_header   7, $20, $28, data_7a_4860_PlayerTiles + $0880
    player_piece  -24,   -9, PLAYER_PIECE_PAL0
    player_piece  -24,   -1, PLAYER_PIECE_PAL0
    player_piece   -8,   -7, PLAYER_PIECE_PAL0
    player_piece   -8,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,    3, PLAYER_PIECE_PAL1

data_7a_4163_PlayerFrame_069:
    player_frame_header   7, $20, $28, data_7a_4860_PlayerTiles + $0960
    player_piece  -17,   -9, PLAYER_PIECE_PAL0
    player_piece  -22,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,   -4, PLAYER_PIECE_PAL0
    player_piece  -38,    4, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,    3, PLAYER_PIECE_PAL1
    player_piece  -32,   -3, PLAYER_PIECE_PAL1

data_7a_4184_PlayerFrame_070:
    player_frame_header   7, $20, $28, data_7a_4860_PlayerTiles + $0a40
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece   -8,   -8, PLAYER_PIECE_PAL0
    player_piece  -10,    0, PLAYER_PIECE_PAL0
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,    3, PLAYER_PIECE_PAL1

data_7a_41a5_PlayerFrame_071:
    player_frame_header   7, $20, $28, data_7a_4860_PlayerTiles + $0b20
    player_piece  -25,   -7, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece   -9,   -8, PLAYER_PIECE_PAL0
    player_piece  -10,    0, PLAYER_PIECE_PAL0
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,    3, PLAYER_PIECE_PAL1

data_7a_41c6_PlayerFrame_072:
    player_frame_header   5, $15, $26, data_7a_4860_PlayerTiles + $0c00
    player_piece  -22,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -20,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,    5, PLAYER_PIECE_PAL0
    player_piece  -20,   11, PLAYER_PIECE_PAL0

data_7a_41df_PlayerFrame_073:
    player_frame_header   5, $15, $27, data_7a_4860_PlayerTiles + $0ca0
    player_piece  -22,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece  -19,    5, PLAYER_PIECE_PAL0
    player_piece  -20,   12, PLAYER_PIECE_PAL0

data_7a_41f8_PlayerFrame_074:
    player_frame_header   5, $15, $27, data_7a_4860_PlayerTiles + $0d40
    player_piece  -23,  -14, PLAYER_PIECE_PAL0
    player_piece  -23,   -6, PLAYER_PIECE_PAL0
    player_piece  -19,    2, PLAYER_PIECE_PAL0
    player_piece  -20,   10, PLAYER_PIECE_PAL0
    player_piece   -3,    7, PLAYER_PIECE_PAL0

data_7a_4211_PlayerFrame_075:
    player_frame_header   5, $14, $27, data_7a_4860_PlayerTiles + $0de0
    player_piece  -20,  -19, PLAYER_PIECE_PAL0
    player_piece  -22,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -19,    5, PLAYER_PIECE_PAL0
    player_piece  -22,   12, PLAYER_PIECE_PAL0

data_7a_422a_PlayerFrame_076:
    player_frame_header   4, $14, $25, data_7a_4860_PlayerTiles + $0e80
    player_piece  -23,  -16, PLAYER_PIECE_PAL0
    player_piece  -23,   -8, PLAYER_PIECE_PAL0
    player_piece  -20,    0, PLAYER_PIECE_PAL0
    player_piece  -20,    8, PLAYER_PIECE_PAL0

data_7a_423f_PlayerFrame_077:
    player_frame_header   5, $14, $26, data_7a_4860_PlayerTiles + $0f00
    player_piece  -21,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    5, PLAYER_PIECE_PAL0
    player_piece  -26,   11, PLAYER_PIECE_PAL0

data_7a_4258_PlayerFrame_078:
    player_frame_header   6, $15, $26, data_7a_4860_PlayerTiles + $0fa0
    player_piece  -21,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece  -19,    5, PLAYER_PIECE_PAL0
    player_piece   -3,    5, PLAYER_PIECE_PAL0
    player_piece  -23,   11, PLAYER_PIECE_PAL0

data_7a_4275_PlayerFrame_079:
    player_frame_header   4, $1e, $26, data_7a_4860_PlayerTiles + $1060
    player_piece  -16,  -14, PLAYER_PIECE_PAL0
    player_piece  -21,   -6, PLAYER_PIECE_PAL0
    player_piece  -26,   -2, PLAYER_PIECE_PAL0
    player_piece  -33,    6, PLAYER_PIECE_PAL0

data_7a_428a_PlayerFrame_080:
    player_frame_header   4, $1e, $26, data_7a_4860_PlayerTiles + $10e0
    player_piece  -16,  -14, PLAYER_PIECE_PAL0
    player_piece  -22,   -6, PLAYER_PIECE_PAL0
    player_piece  -29,   -1, PLAYER_PIECE_PAL0
    player_piece  -32,    7, PLAYER_PIECE_PAL0

data_7a_429f_PlayerFrame_081:
    player_frame_header   5, $1e, $26, data_7a_4860_PlayerTiles + $1160
    player_piece   -4,  -19, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece  -28,    5, PLAYER_PIECE_PAL0

data_7a_42b8_PlayerFrame_082:
    player_frame_header   6, $1f, $26, data_7a_4860_PlayerTiles + $1200
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL0
    player_piece  -39,   11, PLAYER_PIECE_PAL0
    player_piece  -11,  -13, PLAYER_PIECE_PAL0
    player_piece  -18,   -5, PLAYER_PIECE_PAL0
    player_piece  -13,    6, PLAYER_PIECE_PAL0

data_7a_42d5_PlayerFrame_083:
    player_frame_header   4, $1f, $26, data_7a_4860_PlayerTiles + $12c0
    player_piece  -17,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -28,    2, PLAYER_PIECE_PAL0
    player_piece  -36,    8, PLAYER_PIECE_PAL0

data_7a_42ea_PlayerFrame_084:
    player_frame_header   5, $1f, $26, data_7a_4860_PlayerTiles + $1340
    player_piece  -15,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL0
    player_piece  -32,   11, PLAYER_PIECE_PAL0

data_7a_4303_PlayerFrame_085:
    player_frame_header   5, $1f, $26, data_7a_4860_PlayerTiles + $13e0
    player_piece  -18,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -36,   11, PLAYER_PIECE_PAL0

data_7a_431c_PlayerFrame_086:
    player_frame_header   5, $1e, $26, data_7a_4860_PlayerTiles + $1480
    player_piece  -33,  -14, PLAYER_PIECE_PAL0
    player_piece  -25,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -20,   10, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0

data_7a_4335_PlayerFrame_087:
    player_frame_header   4, $1d, $26, data_7a_4860_PlayerTiles + $1520
    player_piece  -33,  -15, PLAYER_PIECE_PAL0
    player_piece  -26,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -19,    7, PLAYER_PIECE_PAL0

data_7a_434a_PlayerFrame_088:
    player_frame_header   4, $1b, $26, data_7a_4860_PlayerTiles + $15a0
    player_piece  -33,  -15, PLAYER_PIECE_PAL0
    player_piece  -23,   -7, PLAYER_PIECE_PAL0
    player_piece  -17,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0

data_7a_435f_PlayerFrame_089:
    player_frame_header   5, $1e, $26, data_7a_4860_PlayerTiles + $1620
    player_piece  -35,  -19, PLAYER_PIECE_PAL0
    player_piece  -29,  -11, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0
    player_piece  -11,   11, PLAYER_PIECE_PAL0

data_7a_4378_PlayerFrame_090:
    player_frame_header   4, $1d, $26, data_7a_4860_PlayerTiles + $16c0
    player_piece  -35,  -12, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    2, PLAYER_PIECE_PAL0
    player_piece  -16,    9, PLAYER_PIECE_PAL0

data_7a_438d_PlayerFrame_091:
    player_frame_header   4, $1c, $26, data_7a_4860_PlayerTiles + $1740
    player_piece  -32,  -13, PLAYER_PIECE_PAL0
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -19,   10, PLAYER_PIECE_PAL0

data_7a_43a2_PlayerFrame_092:
    player_frame_header   4, $1d, $26, data_7a_4860_PlayerTiles + $17c0
    player_piece  -32,  -14, PLAYER_PIECE_PAL0
    player_piece  -24,   -6, PLAYER_PIECE_PAL0
    player_piece  -14,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    5, PLAYER_PIECE_PAL0

data_7a_43b7_PlayerFrame_093:
    player_frame_header   7, $1f, $23, data_7a_4860_PlayerTiles + $1840
    player_piece  -24,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -31,    5, PLAYER_PIECE_PAL0
    player_piece  -29,   -2, PLAYER_PIECE_PAL1
    player_piece  -41,    6, PLAYER_PIECE_PAL1
    player_piece   -9,   -7, PLAYER_PIECE_PAL1
    player_piece  -10,    2, PLAYER_PIECE_PAL1

data_7a_43d8_PlayerFrame_094:
    player_frame_header   7, $1f, $23, data_7a_4860_PlayerTiles + $1920
    player_piece  -20,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -29,   -2, PLAYER_PIECE_PAL1
    player_piece  -39,    6, PLAYER_PIECE_PAL1
    player_piece  -10,   -6, PLAYER_PIECE_PAL1
    player_piece  -10,    2, PLAYER_PIECE_PAL1

data_7a_43f9_PlayerFrame_095:
    player_frame_header   8, $1f, $23, data_7a_4860_PlayerTiles + $1a00
    player_piece  -14,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece   -9,    0, PLAYER_PIECE_PAL0
    player_piece  -29,   -2, PLAYER_PIECE_PAL1
    player_piece  -40,    6, PLAYER_PIECE_PAL1
    player_piece   -9,   -5, PLAYER_PIECE_PAL1
    player_piece  -20,    3, PLAYER_PIECE_PAL1

data_7a_441e_PlayerFrame_096:
    player_frame_header   6, $20, $22, data_7a_4860_PlayerTiles + $1b00
    player_piece  -13,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -36,    5, PLAYER_PIECE_PAL0
    player_piece   -9,    0, PLAYER_PIECE_PAL0
    player_piece  -34,   -1, PLAYER_PIECE_PAL1
    player_piece  -18,   -3, PLAYER_PIECE_PAL1

data_7a_443b_PlayerFrame_097:
    player_frame_header   7, $20, $22, data_7a_4860_PlayerTiles + $1bc0
    player_piece  -13,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -31,    5, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -25,    4, PLAYER_PIECE_PAL1

data_7a_445c_PlayerFrame_098:
    player_frame_header   8, $21, $22, data_7a_4860_PlayerTiles + $1ca0
    player_piece  -22,  -11, PLAYER_PIECE_PAL0
    player_piece  -26,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -31,   -3, PLAYER_PIECE_PAL1
    player_piece  -40,    5, PLAYER_PIECE_PAL1
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -14,    3, PLAYER_PIECE_PAL1

data_7a_4481_PlayerFrame_099:
    player_frame_header   8, $1e, $22, data_7a_4860_PlayerTiles + $1da0
    player_piece  -22,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -31,    5, PLAYER_PIECE_PAL0
    player_piece   -9,   -1, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -39,    5, PLAYER_PIECE_PAL1
    player_piece   -9,   -6, PLAYER_PIECE_PAL1
    player_piece  -12,    2, PLAYER_PIECE_PAL1

data_7a_44a6_PlayerFrame_100:
    player_frame_header   7, $1f, $22, data_7a_4860_PlayerTiles + $1ea0
    player_piece  -20,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece  -31,    5, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -38,    5, PLAYER_PIECE_PAL1
    player_piece   -9,   -7, PLAYER_PIECE_PAL1
    player_piece  -11,    2, PLAYER_PIECE_PAL1

data_7a_44c7_PlayerFrame_101:
    player_frame_header   7, $1f, $22, data_7a_4860_PlayerTiles + $1f80
    player_piece  -14,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -38,    5, PLAYER_PIECE_PAL1
    player_piece  -11,   -6, PLAYER_PIECE_PAL1
    player_piece  -19,    2, PLAYER_PIECE_PAL1

data_7a_44e8_PlayerFrame_102:
    player_frame_header   8, $21, $22, data_7a_4860_PlayerTiles + $2060
    player_piece  -14,   -9, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,    7, PLAYER_PIECE_PAL0
    player_piece  -10,    5, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL1
    player_piece  -41,    8, PLAYER_PIECE_PAL1
    player_piece  -15,   -3, PLAYER_PIECE_PAL1
    player_piece  -21,    5, PLAYER_PIECE_PAL1

data_7a_450d_PlayerFrame_103:
    player_frame_header   6, $21, $22, data_7a_4860_PlayerTiles + $2160
    player_piece  -14,   -9, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -37,    7, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -33,    1, PLAYER_PIECE_PAL1
    player_piece  -19,   -2, PLAYER_PIECE_PAL1

data_7a_452a_PlayerFrame_104:
    player_frame_header   5, $20, $22, data_7a_4860_PlayerTiles + $2220
    player_piece  -14,   -9, PLAYER_PIECE_PAL0
    player_piece  -25,   -1, PLAYER_PIECE_PAL0
    player_piece  -32,    7, PLAYER_PIECE_PAL0
    player_piece  -32,    1, PLAYER_PIECE_PAL1
    player_piece  -11,   -2, PLAYER_PIECE_PAL1

data_7a_4543_PlayerFrame_105:
    player_frame_header   7, $21, $22, data_7a_4860_PlayerTiles + $22c0
    player_piece  -23,   -9, PLAYER_PIECE_PAL0
    player_piece  -27,   -1, PLAYER_PIECE_PAL0
    player_piece  -32,    7, PLAYER_PIECE_PAL0
    player_piece  -11,   -1, PLAYER_PIECE_PAL0
    player_piece  -32,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1
    player_piece  -11,    6, PLAYER_PIECE_PAL1

data_7a_4564_PlayerFrame_106:
    player_frame_header   7, $21, $22, data_7a_4860_PlayerTiles + $23a0
    player_piece  -23,   -9, PLAYER_PIECE_PAL0
    player_piece  -27,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,    7, PLAYER_PIECE_PAL0
    player_piece  -11,   -1, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL1
    player_piece  -17,   -3, PLAYER_PIECE_PAL1
    player_piece  -14,    5, PLAYER_PIECE_PAL1

data_7a_4585_PlayerFrame_107:
    player_frame_header   7, $19, $1c, data_7a_4860_PlayerTiles + $2480
    player_piece  -18,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,    0, PLAYER_PIECE_PAL0
    player_piece   -3,    0, PLAYER_PIECE_PAL0
    player_piece  -23,   -4, PLAYER_PIECE_PAL1
    player_piece   -6,   -4, PLAYER_PIECE_PAL1
    player_piece   -1,    0, PLAYER_PIECE_PAL1

data_7a_45a6_PlayerFrame_108:
    player_frame_header   6, $19, $1b, data_7a_4860_PlayerTiles + $2560
    player_piece  -17,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,    3, PLAYER_PIECE_PAL0
    player_piece  -32,   -4, PLAYER_PIECE_PAL0
    player_piece  -32,    4, PLAYER_PIECE_PAL0
    player_piece  -16,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,   -3, PLAYER_PIECE_PAL1

data_7a_45c3_PlayerFrame_109:
    player_frame_header   7, $19, $24, data_7a_4860_PlayerTiles + $2620
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece  -18,    4, PLAYER_PIECE_PAL0
    player_piece  -22,    8, PLAYER_PIECE_PAL0
    player_piece   -3,    2, PLAYER_PIECE_PAL0
    player_piece  -23,   -1, PLAYER_PIECE_PAL1
    player_piece   -6,   -4, PLAYER_PIECE_PAL1
    player_piece   -3,    4, PLAYER_PIECE_PAL1

data_7a_45e4_PlayerFrame_110:
    player_frame_header   8, $19, $28, data_7a_4860_PlayerTiles + $2700
    player_piece  -29,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece   -3,   -4, PLAYER_PIECE_PAL0
    player_piece  -11,    4, PLAYER_PIECE_PAL0
    player_piece  -21,   12, PLAYER_PIECE_PAL0
    player_piece  -23,   -4, PLAYER_PIECE_PAL1
    player_piece   -7,   -4, PLAYER_PIECE_PAL1
    player_piece  -16,    4, PLAYER_PIECE_PAL1

data_7a_4609_PlayerFrame_111:
    player_frame_header   7, $19, $22, data_7a_4860_PlayerTiles + $2800
    player_piece  -19,   -7, PLAYER_PIECE_PAL0
    player_piece  -18,    1, PLAYER_PIECE_PAL0
    player_piece  -21,    6, PLAYER_PIECE_PAL0
    player_piece   -2,    2, PLAYER_PIECE_PAL0
    player_piece  -23,   -4, PLAYER_PIECE_PAL1
    player_piece  -22,    4, PLAYER_PIECE_PAL1
    player_piece   -7,   -4, PLAYER_PIECE_PAL1

data_7a_462a_PlayerFrame_112:
    player_frame_header   6, $19, $1c, data_7a_4860_PlayerTiles + $28e0
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,    0, PLAYER_PIECE_PAL0
    player_piece   -3,    0, PLAYER_PIECE_PAL0
    player_piece  -23,   -2, PLAYER_PIECE_PAL1
    player_piece   -7,   -4, PLAYER_PIECE_PAL1
    player_piece   -2,    0, PLAYER_PIECE_PAL1

data_7a_4647_PlayerFrame_113:
    player_frame_header   6, $19, $1c, data_7a_4860_PlayerTiles + $29a0
    player_piece  -18,  -12, PLAYER_PIECE_PAL0
    player_piece  -18,   -4, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,    0, PLAYER_PIECE_PAL1
    player_piece  -32,   -3, PLAYER_PIECE_PAL1

data_7a_4664_PlayerFrame_114:
    player_frame_header   8, $19, $1e, data_7a_4860_PlayerTiles + $2a60
    player_piece  -11,  -20, PLAYER_PIECE_PAL0
    player_piece  -18,  -12, PLAYER_PIECE_PAL0
    player_piece  -18,   -4, PLAYER_PIECE_PAL0
    player_piece   -2,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -17,  -12, PLAYER_PIECE_PAL1
    player_piece  -23,   -4, PLAYER_PIECE_PAL1
    player_piece   -7,   -4, PLAYER_PIECE_PAL1

data_7a_4689_PlayerFrame_115:
    player_frame_header   7, $21, $1d, data_7a_4860_PlayerTiles + $2b60
    player_piece  -27,   -9, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -31,    5, PLAYER_PIECE_PAL0
    player_piece  -10,   -2, PLAYER_PIECE_PAL0
    player_piece  -31,   -2, PLAYER_PIECE_PAL1
    player_piece  -26,    5, PLAYER_PIECE_PAL1
    player_piece  -15,   -3, PLAYER_PIECE_PAL1

data_7a_46aa_PlayerFrame_116:
    player_frame_header   8, $21, $1f, data_7a_4860_PlayerTiles + $2c40
    player_piece  -28,   -7, PLAYER_PIECE_PAL0
    player_piece  -28,    1, PLAYER_PIECE_PAL0
    player_piece  -35,    7, PLAYER_PIECE_PAL0
    player_piece  -12,   -4, PLAYER_PIECE_PAL0
    player_piece  -12,    4, PLAYER_PIECE_PAL0
    player_piece  -31,   -2, PLAYER_PIECE_PAL1
    player_piece  -15,   -5, PLAYER_PIECE_PAL1
    player_piece  -15,    3, PLAYER_PIECE_PAL1

data_7a_46cf_PlayerFrame_117:
    player_frame_header   7, $20, $1d, data_7a_4860_PlayerTiles + $2d40
    player_piece  -28,  -10, PLAYER_PIECE_PAL0
    player_piece  -27,   -2, PLAYER_PIECE_PAL0
    player_piece  -25,    5, PLAYER_PIECE_PAL0
    player_piece  -11,   -2, PLAYER_PIECE_PAL0
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece  -14,   -7, PLAYER_PIECE_PAL1
    player_piece  -19,    1, PLAYER_PIECE_PAL1

data_7a_46f0_PlayerFrame_118:
    player_frame_header   7, $21, $1a, data_7a_4860_PlayerTiles + $2e20
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -25,    2, PLAYER_PIECE_PAL0
    player_piece  -32,  -11, PLAYER_PIECE_PAL0
    player_piece  -38,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,   -9, PLAYER_PIECE_PAL1
    player_piece  -20,   -1, PLAYER_PIECE_PAL1
    player_piece  -36,   -2, PLAYER_PIECE_PAL1

data_7a_4711_PlayerFrame_119:
    player_frame_header   7, $20, $1d, data_7a_4860_PlayerTiles + $2f00
    player_piece  -28,  -10, PLAYER_PIECE_PAL0
    player_piece  -27,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    5, PLAYER_PIECE_PAL0
    player_piece  -11,   -1, PLAYER_PIECE_PAL0
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece  -13,   -7, PLAYER_PIECE_PAL1
    player_piece  -11,    4, PLAYER_PIECE_PAL1

data_7a_4732_PlayerFrame_120:
    player_frame_header   8, $20, $1e, data_7a_4860_PlayerTiles + $2fe0
    player_piece  -25,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL0
    player_piece  -11,   -4, PLAYER_PIECE_PAL0
    player_piece  -14,    4, PLAYER_PIECE_PAL0
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece   -8,   -6, PLAYER_PIECE_PAL1
    player_piece  -14,    4, PLAYER_PIECE_PAL1

data_7a_4757_PlayerFrame_121:
    player_frame_header   7, $20, $1f, data_7a_4860_PlayerTiles + $30e0
    player_piece  -26,   -7, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece  -34,    7, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,   -2, PLAYER_PIECE_PAL1
    player_piece  -18,   -5, PLAYER_PIECE_PAL1
    player_piece  -14,    3, PLAYER_PIECE_PAL1

data_7a_4778_PlayerFrame_122:
    player_frame_header   7, $1f, $1c, data_7a_4860_PlayerTiles + $31c0
    player_piece  -28,   -9, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -24,    4, PLAYER_PIECE_PAL0
    player_piece  -10,    0, PLAYER_PIECE_PAL0
    player_piece  -29,   -2, PLAYER_PIECE_PAL1
    player_piece  -12,   -6, PLAYER_PIECE_PAL1
    player_piece   -9,    3, PLAYER_PIECE_PAL1

data_7a_4799_PlayerFrame_123:
    player_frame_header   7, $21, $1b, data_7a_4860_PlayerTiles + $32a0
    player_piece  -30,  -10, PLAYER_PIECE_PAL0
    player_piece  -26,   -3, PLAYER_PIECE_PAL0
    player_piece  -31,    5, PLAYER_PIECE_PAL0
    player_piece  -10,   -1, PLAYER_PIECE_PAL0
    player_piece  -31,   -2, PLAYER_PIECE_PAL1
    player_piece  -15,   -6, PLAYER_PIECE_PAL1
    player_piece  -15,    2, PLAYER_PIECE_PAL1

data_7a_47ba_PlayerFrame_124:
    player_frame_header   7, $21, $1c, data_7a_4860_PlayerTiles + $3380
    player_piece  -28,  -10, PLAYER_PIECE_PAL0
    player_piece  -26,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    3, PLAYER_PIECE_PAL0
    player_piece  -12,   -1, PLAYER_PIECE_PAL0
    player_piece  -31,   -2, PLAYER_PIECE_PAL1
    player_piece  -15,   -6, PLAYER_PIECE_PAL1
    player_piece  -11,    3, PLAYER_PIECE_PAL1

data_7a_47db_PlayerFrame_125:
    player_frame_header   4, $21, $19, data_7a_4860_PlayerTiles + $3460
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_7a_47f0_PlayerFrame_126:
    player_frame_header   4, $20, $18, data_7a_4860_PlayerTiles + $34e0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_7a_4805_PlayerFrame_127:
    player_frame_header   4, $20, $18, data_7a_4860_PlayerTiles + $3560
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_7a_481a_PlayerFrame_128:
    player_frame_header   4, $20, $18, data_7a_4860_PlayerTiles + $35e0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_7a_482f_PlayerFrame_129:
    player_frame_header   4, $21, $18, data_7a_4860_PlayerTiles + $3660
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_7a_4844_PlayerFrame_130:
    player_frame_header   4, $20, $18, data_7a_4860_PlayerTiles + $36e0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

    ds   $4860 - @, 0                    ; the bank pads to a 16-byte boundary here
data_7a_4860_PlayerTiles:
; INCBINd by main.asm - see the header above
