; ==================================================================
; Bank $6d. Gex's animation frames 61 to 81 of PLAYER_GFX_SET_GEXTREME_SPORTS1.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $42c4, then 302 tiles of graphics from $42d0 to $55af, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/sprite_data/bank7F.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_6d_4000_PlayerFrame_061:
    player_frame_header   2, $1e, $19, data_6d_42d0_PlayerTiles + $0000
    player_piece  -40,  -11, PLAYER_PIECE_PAL1
    player_piece  -37,   -3, PLAYER_PIECE_PAL1

data_6d_400d_PlayerFrame_062:
    player_frame_header   9, $1e, $21, data_6d_42d0_PlayerTiles + $0040
    player_piece  -26,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -27,    5, PLAYER_PIECE_PAL0
    player_piece  -27,  -11, PLAYER_PIECE_PAL1
    player_piece   -2,  -11, PLAYER_PIECE_PAL1
    player_piece  -28,   -3, PLAYER_PIECE_PAL1
    player_piece  -12,   -3, PLAYER_PIECE_PAL1
    player_piece  -16,    5, PLAYER_PIECE_PAL1

data_6d_4036_PlayerFrame_063:
    player_frame_header   9, $1d, $21, data_6d_42d0_PlayerTiles + $0160
    player_piece  -26,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -27,    5, PLAYER_PIECE_PAL0
    player_piece  -27,  -11, PLAYER_PIECE_PAL1
    player_piece   -2,  -11, PLAYER_PIECE_PAL1
    player_piece  -27,   -3, PLAYER_PIECE_PAL1
    player_piece  -11,   -3, PLAYER_PIECE_PAL1
    player_piece  -16,    5, PLAYER_PIECE_PAL1

data_6d_405f_PlayerFrame_064:
    player_frame_header   9, $1c, $20, data_6d_42d0_PlayerTiles + $0280
    player_piece  -26,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -27,    5, PLAYER_PIECE_PAL0
    player_piece  -27,  -11, PLAYER_PIECE_PAL1
    player_piece   -2,  -11, PLAYER_PIECE_PAL1
    player_piece  -26,   -3, PLAYER_PIECE_PAL1
    player_piece  -10,   -3, PLAYER_PIECE_PAL1
    player_piece  -16,    5, PLAYER_PIECE_PAL1

data_6d_4088_PlayerFrame_065:
    player_frame_header   7, $1b, $1e, data_6d_42d0_PlayerTiles + $03a0
    player_piece  -25,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -19,   -8, PLAYER_PIECE_PAL1
    player_piece  -19,    0, PLAYER_PIECE_PAL1
    player_piece  -16,    3, PLAYER_PIECE_PAL1
    player_piece   -3,   -5, PLAYER_PIECE_PAL1

data_6d_40a9_PlayerFrame_066:
    player_frame_header   7, $19, $1d, data_6d_42d0_PlayerTiles + $0480
    player_piece  -23,   -7, PLAYER_PIECE_PAL0
    player_piece  -22,    1, PLAYER_PIECE_PAL0
    player_piece   -7,   -2, PLAYER_PIECE_PAL0
    player_piece  -19,   -8, PLAYER_PIECE_PAL1
    player_piece  -19,    0, PLAYER_PIECE_PAL1
    player_piece  -16,    2, PLAYER_PIECE_PAL1
    player_piece   -3,   -5, PLAYER_PIECE_PAL1

data_6d_40ca_PlayerFrame_067:
    player_frame_header   4, $15, $1a, data_6d_42d0_PlayerTiles + $0560
    player_piece  -21,   -6, PLAYER_PIECE_PAL0
    player_piece  -25,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1

data_6d_40df_PlayerFrame_068:
    player_frame_header   3, $10, $1a, data_6d_42d0_PlayerTiles + $05e0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1

data_6d_40f0_PlayerFrame_069:
    player_frame_header   3, $0c, $19, data_6d_42d0_PlayerTiles + $0640
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece   -1,  -11, PLAYER_PIECE_PAL1
    player_piece  -16,   -3, PLAYER_PIECE_PAL1

data_6d_4101_PlayerFrame_070:
    player_frame_header   9, $1d, $21, data_6d_42d0_PlayerTiles + $06a0
    player_piece  -27,  -13, PLAYER_PIECE_PAL0
    player_piece  -23,   -5, PLAYER_PIECE_PAL0
    player_piece  -23,    3, PLAYER_PIECE_PAL0
    player_piece   -2,    6, PLAYER_PIECE_PAL0
    player_piece  -27,   -6, PLAYER_PIECE_PAL1
    player_piece  -25,    2, PLAYER_PIECE_PAL1
    player_piece  -11,  -10, PLAYER_PIECE_PAL1
    player_piece  -11,   -2, PLAYER_PIECE_PAL1
    player_piece   -7,    6, PLAYER_PIECE_PAL1

data_6d_412a_PlayerFrame_071:
    player_frame_header   7, $22, $1f, data_6d_42d0_PlayerTiles + $07c0
    player_piece  -24,  -12, PLAYER_PIECE_PAL0
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -33,    4, PLAYER_PIECE_PAL0
    player_piece   -8,  -10, PLAYER_PIECE_PAL0
    player_piece  -32,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1

data_6d_414b_PlayerFrame_072:
    player_frame_header   8, $23, $1f, data_6d_42d0_PlayerTiles + $08a0
    player_piece  -25,  -12, PLAYER_PIECE_PAL0
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -34,    4, PLAYER_PIECE_PAL0
    player_piece  -11,   -4, PLAYER_PIECE_PAL0
    player_piece  -33,   -5, PLAYER_PIECE_PAL1
    player_piece  -17,   -7, PLAYER_PIECE_PAL1
    player_piece  -17,    1, PLAYER_PIECE_PAL1
    player_piece   -1,   -6, PLAYER_PIECE_PAL1

data_6d_4170_PlayerFrame_073:
    player_frame_header   7, $23, $1f, data_6d_42d0_PlayerTiles + $09a0
    player_piece  -25,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -34,    5, PLAYER_PIECE_PAL0
    player_piece  -33,   -5, PLAYER_PIECE_PAL1
    player_piece  -17,   -7, PLAYER_PIECE_PAL1
    player_piece  -18,    1, PLAYER_PIECE_PAL1

data_6d_4191_PlayerFrame_074:
    player_frame_header   7, $23, $21, data_6d_42d0_PlayerTiles + $0a80
    player_piece  -27,  -10, PLAYER_PIECE_PAL0
    player_piece  -27,   -2, PLAYER_PIECE_PAL0
    player_piece  -34,    6, PLAYER_PIECE_PAL0
    player_piece  -11,   -2, PLAYER_PIECE_PAL0
    player_piece  -33,   -3, PLAYER_PIECE_PAL1
    player_piece  -17,   -9, PLAYER_PIECE_PAL1
    player_piece  -17,   -1, PLAYER_PIECE_PAL1

data_6d_41b2_PlayerFrame_075:
    player_frame_header  11, $23, $22, data_6d_42d0_PlayerTiles + $0b60
    player_piece  -27,  -14, PLAYER_PIECE_PAL0
    player_piece  -25,   -6, PLAYER_PIECE_PAL0
    player_piece  -33,    2, PLAYER_PIECE_PAL0
    player_piece  -36,    7, PLAYER_PIECE_PAL0
    player_piece  -20,   -6, PLAYER_PIECE_PAL0
    player_piece  -28,  -15, PLAYER_PIECE_PAL1
    player_piece  -33,   -7, PLAYER_PIECE_PAL1
    player_piece  -31,    1, PLAYER_PIECE_PAL1
    player_piece  -34,    7, PLAYER_PIECE_PAL1
    player_piece  -17,   -8, PLAYER_PIECE_PAL1
    player_piece  -17,    0, PLAYER_PIECE_PAL1

data_6d_41e3_PlayerFrame_076:
    player_frame_header  10, $23, $22, data_6d_42d0_PlayerTiles + $0cc0
    player_piece  -26,  -11, PLAYER_PIECE_PAL0
    player_piece  -33,   -3, PLAYER_PIECE_PAL0
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece  -10,   -6, PLAYER_PIECE_PAL0
    player_piece  -28,  -18, PLAYER_PIECE_PAL1
    player_piece  -32,  -10, PLAYER_PIECE_PAL1
    player_piece  -33,   -2, PLAYER_PIECE_PAL1
    player_piece  -33,    6, PLAYER_PIECE_PAL1
    player_piece  -16,  -10, PLAYER_PIECE_PAL1
    player_piece  -17,   -2, PLAYER_PIECE_PAL1

data_6d_4210_PlayerFrame_077:
    player_frame_header   7, $21, $20, data_6d_42d0_PlayerTiles + $0e00
    player_piece  -27,   -9, PLAYER_PIECE_PAL0
    player_piece  -11,   -9, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -31,   -8, PLAYER_PIECE_PAL1
    player_piece   -9,   -9, PLAYER_PIECE_PAL1
    player_piece  -18,   -1, PLAYER_PIECE_PAL1
    player_piece  -26,    7, PLAYER_PIECE_PAL1

data_6d_4231_PlayerFrame_078:
    player_frame_header   9, $20, $1d, data_6d_42d0_PlayerTiles + $0ee0
    player_piece  -26,   -9, PLAYER_PIECE_PAL0
    player_piece  -25,   -1, PLAYER_PIECE_PAL0
    player_piece  -10,   -8, PLAYER_PIECE_PAL0
    player_piece   -9,    0, PLAYER_PIECE_PAL0
    player_piece  -31,   -9, PLAYER_PIECE_PAL1
    player_piece  -21,   -1, PLAYER_PIECE_PAL1
    player_piece  -20,    2, PLAYER_PIECE_PAL1
    player_piece   -7,   -9, PLAYER_PIECE_PAL1
    player_piece   -5,    0, PLAYER_PIECE_PAL1

data_6d_425a_PlayerFrame_079:
    player_frame_header   7, $1b, $20, data_6d_42d0_PlayerTiles + $1000
    player_piece  -20,  -12, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece   -4,   -9, PLAYER_PIECE_PAL0
    player_piece  -25,  -11, PLAYER_PIECE_PAL1
    player_piece  -16,   -3, PLAYER_PIECE_PAL1
    player_piece  -16,    5, PLAYER_PIECE_PAL1
    player_piece   -9,   -5, PLAYER_PIECE_PAL1

data_6d_427b_PlayerFrame_080:
    player_frame_header   8, $16, $1d, data_6d_42d0_PlayerTiles + $10e0
    player_piece  -10,  -13, PLAYER_PIECE_PAL0
    player_piece  -22,   -5, PLAYER_PIECE_PAL0
    player_piece  -26,    2, PLAYER_PIECE_PAL0
    player_piece  -20,   -9, PLAYER_PIECE_PAL1
    player_piece  -20,   -1, PLAYER_PIECE_PAL1
    player_piece   -4,  -10, PLAYER_PIECE_PAL1
    player_piece   -4,   -2, PLAYER_PIECE_PAL1
    player_piece   -4,    2, PLAYER_PIECE_PAL1

data_6d_42a0_PlayerFrame_081:
    player_frame_header   8, $15, $1d, data_6d_42d0_PlayerTiles + $11e0
    player_piece   -9,  -19, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL0
    player_piece  -20,   -3, PLAYER_PIECE_PAL0
    player_piece  -27,    2, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL1
    player_piece  -19,   -3, PLAYER_PIECE_PAL1
    player_piece   -3,   -3, PLAYER_PIECE_PAL1
    player_piece   -4,    2, PLAYER_PIECE_PAL1

    ds   $42d0 - @, 0                    ; the bank pads to a 16-byte boundary here
data_6d_42d0_PlayerTiles:
; INCBINd by main.asm - see the header above
