; ==================================================================
; Bank $7d. Gex's animation frames 73 to 156 of PLAYER_GFX_SET_GEX_CAVE.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $4887, then 882 tiles of graphics from $4890 to $7faf, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/sprite_data/bank7F.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_7d_4000_PlayerFrame_073:
    player_frame_header   6, $14, $27, data_7d_4890_PlayerTiles + $0000
    player_piece  -14,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece  -19,    5, PLAYER_PIECE_PAL0
    player_piece  -20,   12, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL1

data_7d_401d_PlayerFrame_074:
    player_frame_header   5, $14, $27, data_7d_4890_PlayerTiles + $00c0
    player_piece  -13,  -14, PLAYER_PIECE_PAL0
    player_piece  -23,   -6, PLAYER_PIECE_PAL0
    player_piece  -18,    2, PLAYER_PIECE_PAL0
    player_piece  -20,   10, PLAYER_PIECE_PAL0
    player_piece  -30,   10, PLAYER_PIECE_PAL1

data_7d_4036_PlayerFrame_075:
    player_frame_header   6, $14, $27, data_7d_4890_PlayerTiles + $0160
    player_piece  -13,  -19, PLAYER_PIECE_PAL0
    player_piece  -22,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -19,    5, PLAYER_PIECE_PAL0
    player_piece  -22,   12, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL1

data_7d_4053_PlayerFrame_076:
    player_frame_header   5, $14, $25, data_7d_4890_PlayerTiles + $0220
    player_piece  -13,  -16, PLAYER_PIECE_PAL0
    player_piece  -23,   -8, PLAYER_PIECE_PAL0
    player_piece  -20,    0, PLAYER_PIECE_PAL0
    player_piece  -20,    8, PLAYER_PIECE_PAL0
    player_piece  -30,    8, PLAYER_PIECE_PAL1

data_7d_406c_PlayerFrame_077:
    player_frame_header   6, $14, $26, data_7d_4890_PlayerTiles + $02c0
    player_piece  -14,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    5, PLAYER_PIECE_PAL0
    player_piece  -26,   11, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL1

data_7d_4089_PlayerFrame_078:
    player_frame_header   6, $15, $26, data_7d_4890_PlayerTiles + $0380
    player_piece  -15,  -16, PLAYER_PIECE_PAL0
    player_piece  -23,   -8, PLAYER_PIECE_PAL0
    player_piece  -18,    0, PLAYER_PIECE_PAL0
    player_piece  -20,    8, PLAYER_PIECE_PAL0
    player_piece  -29,   11, PLAYER_PIECE_PAL0
    player_piece  -31,   10, PLAYER_PIECE_PAL1

data_7d_40a6_PlayerFrame_079:
    player_frame_header   7, $1e, $26, data_7d_4890_PlayerTiles + $0440
    player_piece  -26,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    3, PLAYER_PIECE_PAL0
    player_piece  -34,   11, PLAYER_PIECE_PAL0
    player_piece  -16,  -14, PLAYER_PIECE_PAL0
    player_piece  -21,   -6, PLAYER_PIECE_PAL0
    player_piece  -12,    3, PLAYER_PIECE_PAL0
    player_piece  -39,    2, PLAYER_PIECE_PAL1

data_7d_40c7_PlayerFrame_080:
    player_frame_header   6, $1e, $26, data_7d_4890_PlayerTiles + $0520
    player_piece  -17,  -19, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL1

data_7d_40e4_PlayerFrame_081:
    player_frame_header   6, $1e, $26, data_7d_4890_PlayerTiles + $05e0
    player_piece   -4,  -19, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece  -28,    5, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL1

data_7d_4101_PlayerFrame_082:
    player_frame_header   7, $1f, $26, data_7d_4890_PlayerTiles + $06a0
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL0
    player_piece  -39,   11, PLAYER_PIECE_PAL0
    player_piece  -17,  -13, PLAYER_PIECE_PAL0
    player_piece  -18,   -5, PLAYER_PIECE_PAL0
    player_piece  -13,    6, PLAYER_PIECE_PAL0
    player_piece  -40,    3, PLAYER_PIECE_PAL1

data_7d_4122_PlayerFrame_083:
    player_frame_header   7, $1f, $26, data_7d_4890_PlayerTiles + $0780
    player_piece  -17,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -13,    5, PLAYER_PIECE_PAL0
    player_piece  -36,   11, PLAYER_PIECE_PAL0
    player_piece  -41,    5, PLAYER_PIECE_PAL1

data_7d_4143_PlayerFrame_084:
    player_frame_header   5, $1f, $26, data_7d_4890_PlayerTiles + $0860
    player_piece  -15,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL0
    player_piece  -32,   11, PLAYER_PIECE_PAL0

data_7d_415c_PlayerFrame_085:
    player_frame_header   5, $1f, $26, data_7d_4890_PlayerTiles + $0900
    player_piece  -18,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -36,   11, PLAYER_PIECE_PAL0

data_7d_4175_PlayerFrame_086:
    player_frame_header   6, $1e, $26, data_7d_4890_PlayerTiles + $09a0
    player_piece  -33,  -14, PLAYER_PIECE_PAL0
    player_piece  -25,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -20,   10, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -25,    9, PLAYER_PIECE_PAL1

data_7d_4192_PlayerFrame_087:
    player_frame_header   6, $1d, $26, data_7d_4890_PlayerTiles + $0a60
    player_piece  -36,  -19, PLAYER_PIECE_PAL0
    player_piece  -28,  -11, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece   -6,   -3, PLAYER_PIECE_PAL0
    player_piece  -17,    5, PLAYER_PIECE_PAL0
    player_piece  -11,    5, PLAYER_PIECE_PAL1

data_7d_41af_PlayerFrame_088:
    player_frame_header   6, $1b, $26, data_7d_4890_PlayerTiles + $0b20
    player_piece  -36,  -19, PLAYER_PIECE_PAL0
    player_piece  -27,  -11, PLAYER_PIECE_PAL0
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece   -3,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0
    player_piece  -11,    5, PLAYER_PIECE_PAL1

data_7d_41cc_PlayerFrame_089:
    player_frame_header   6, $1e, $26, data_7d_4890_PlayerTiles + $0be0
    player_piece  -35,  -19, PLAYER_PIECE_PAL0
    player_piece  -29,  -11, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0
    player_piece  -11,   11, PLAYER_PIECE_PAL0
    player_piece  -25,    5, PLAYER_PIECE_PAL1

data_7d_41e9_PlayerFrame_090:
    player_frame_header   5, $1d, $26, data_7d_4890_PlayerTiles + $0ca0
    player_piece  -35,  -12, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -17,   10, PLAYER_PIECE_PAL0
    player_piece  -26,   12, PLAYER_PIECE_PAL1

data_7d_4202_PlayerFrame_091:
    player_frame_header   4, $1c, $26, data_7d_4890_PlayerTiles + $0d40
    player_piece  -32,  -13, PLAYER_PIECE_PAL0
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -19,   10, PLAYER_PIECE_PAL0

data_7d_4217_PlayerFrame_092:
    player_frame_header   4, $1d, $26, data_7d_4890_PlayerTiles + $0dc0
    player_piece  -32,  -14, PLAYER_PIECE_PAL0
    player_piece  -24,   -6, PLAYER_PIECE_PAL0
    player_piece  -14,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    5, PLAYER_PIECE_PAL0

data_7d_422c_PlayerFrame_093:
    player_frame_header   6, $1d, $23, data_7d_4890_PlayerTiles + $0e40
    player_piece  -19,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -31,    5, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece   -8,    5, PLAYER_PIECE_PAL0
    player_piece  -39,    3, PLAYER_PIECE_PAL1

data_7d_4249_PlayerFrame_094:
    player_frame_header   6, $1d, $23, data_7d_4890_PlayerTiles + $0f00
    player_piece  -20,  -11, PLAYER_PIECE_PAL0
    player_piece  -26,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,    5, PLAYER_PIECE_PAL0
    player_piece  -39,    4, PLAYER_PIECE_PAL1

data_7d_4266_PlayerFrame_095:
    player_frame_header   6, $1e, $23, data_7d_4890_PlayerTiles + $0fc0
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -31,    4, PLAYER_PIECE_PAL0
    player_piece  -12,  -11, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,    5, PLAYER_PIECE_PAL0
    player_piece  -40,    4, PLAYER_PIECE_PAL1

data_7d_4283_PlayerFrame_096:
    player_frame_header   5, $1e, $22, data_7d_4890_PlayerTiles + $1080
    player_piece  -28,   -4, PLAYER_PIECE_PAL0
    player_piece  -31,    4, PLAYER_PIECE_PAL0
    player_piece  -12,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -40,    3, PLAYER_PIECE_PAL1

data_7d_429c_PlayerFrame_097:
    player_frame_header   5, $1e, $22, data_7d_4890_PlayerTiles + $1120
    player_piece  -28,   -4, PLAYER_PIECE_PAL0
    player_piece  -30,    4, PLAYER_PIECE_PAL0
    player_piece  -12,  -11, PLAYER_PIECE_PAL0
    player_piece  -17,   -3, PLAYER_PIECE_PAL0
    player_piece  -40,    2, PLAYER_PIECE_PAL1

data_7d_42b5_PlayerFrame_098:
    player_frame_header   6, $1f, $22, data_7d_4890_PlayerTiles + $11c0
    player_piece  -29,   -4, PLAYER_PIECE_PAL0
    player_piece  -31,    4, PLAYER_PIECE_PAL0
    player_piece  -13,  -11, PLAYER_PIECE_PAL0
    player_piece  -13,   -3, PLAYER_PIECE_PAL0
    player_piece  -24,    5, PLAYER_PIECE_PAL0
    player_piece  -41,    4, PLAYER_PIECE_PAL1

data_7d_42d2_PlayerFrame_099:
    player_frame_header   6, $1e, $22, data_7d_4890_PlayerTiles + $1280
    player_piece  -27,   -5, PLAYER_PIECE_PAL0
    player_piece  -31,    3, PLAYER_PIECE_PAL0
    player_piece  -11,  -11, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -23,    5, PLAYER_PIECE_PAL0
    player_piece  -40,    4, PLAYER_PIECE_PAL1

data_7d_42ef_PlayerFrame_100:
    player_frame_header   6, $1d, $22, data_7d_4890_PlayerTiles + $1340
    player_piece  -20,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -31,    5, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -11,    1, PLAYER_PIECE_PAL0
    player_piece  -39,    5, PLAYER_PIECE_PAL1

data_7d_430c_PlayerFrame_101:
    player_frame_header   6, $1d, $22, data_7d_4890_PlayerTiles + $1400
    player_piece  -14,  -11, PLAYER_PIECE_PAL0
    player_piece  -26,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,    5, PLAYER_PIECE_PAL0
    player_piece  -39,    6, PLAYER_PIECE_PAL1

data_7d_4329_PlayerFrame_102:
    player_frame_header   6, $1f, $22, data_7d_4890_PlayerTiles + $14c0
    player_piece  -12,  -10, PLAYER_PIECE_PAL0
    player_piece  -28,   -2, PLAYER_PIECE_PAL0
    player_piece  -12,   -2, PLAYER_PIECE_PAL0
    player_piece  -33,    6, PLAYER_PIECE_PAL0
    player_piece  -21,    6, PLAYER_PIECE_PAL0
    player_piece  -41,    6, PLAYER_PIECE_PAL1

data_7d_4346_PlayerFrame_103:
    player_frame_header   5, $1f, $22, data_7d_4890_PlayerTiles + $1580
    player_piece  -29,   -2, PLAYER_PIECE_PAL0
    player_piece  -31,    6, PLAYER_PIECE_PAL0
    player_piece  -13,   -9, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece  -41,    5, PLAYER_PIECE_PAL1

data_7d_435f_PlayerFrame_104:
    player_frame_header   5, $1e, $22, data_7d_4890_PlayerTiles + $1620
    player_piece  -28,   -2, PLAYER_PIECE_PAL0
    player_piece  -31,    6, PLAYER_PIECE_PAL0
    player_piece  -12,   -9, PLAYER_PIECE_PAL0
    player_piece  -18,   -1, PLAYER_PIECE_PAL0
    player_piece  -40,    4, PLAYER_PIECE_PAL1

data_7d_4378_PlayerFrame_105:
    player_frame_header   6, $1f, $22, data_7d_4890_PlayerTiles + $16c0
    player_piece  -12,  -10, PLAYER_PIECE_PAL0
    player_piece  -29,   -2, PLAYER_PIECE_PAL0
    player_piece  -13,   -2, PLAYER_PIECE_PAL0
    player_piece  -32,    6, PLAYER_PIECE_PAL0
    player_piece  -24,    6, PLAYER_PIECE_PAL0
    player_piece  -41,   -2, PLAYER_PIECE_PAL1

data_7d_4395_PlayerFrame_106:
    player_frame_header   6, $1f, $22, data_7d_4890_PlayerTiles + $1780
    player_piece  -29,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -13,   -9, PLAYER_PIECE_PAL0
    player_piece  -13,   -1, PLAYER_PIECE_PAL0
    player_piece  -25,    7, PLAYER_PIECE_PAL0
    player_piece  -41,    3, PLAYER_PIECE_PAL1

data_7d_43b2_PlayerFrame_107:
    player_frame_header   6, $17, $1c, data_7d_4890_PlayerTiles + $1840
    player_piece  -12,  -12, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece   -5,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,    0, PLAYER_PIECE_PAL0
    player_piece   -3,    0, PLAYER_PIECE_PAL0
    player_piece  -33,   -4, PLAYER_PIECE_PAL1

data_7d_43cf_PlayerFrame_108:
    player_frame_header   5, $17, $1b, data_7d_4890_PlayerTiles + $1900
    player_piece  -21,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,   -1, PLAYER_PIECE_PAL0
    player_piece   -5,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,   -3, PLAYER_PIECE_PAL1

data_7d_43e8_PlayerFrame_109:
    player_frame_header   6, $17, $24, data_7d_4890_PlayerTiles + $19a0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece   -5,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,    4, PLAYER_PIECE_PAL0
    player_piece   -3,    4, PLAYER_PIECE_PAL0
    player_piece  -11,    8, PLAYER_PIECE_PAL0
    player_piece  -33,   -4, PLAYER_PIECE_PAL1

data_7d_4405_PlayerFrame_110:
    player_frame_header   6, $17, $28, data_7d_4890_PlayerTiles + $1a60
    player_piece  -29,  -12, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece   -5,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece  -11,   12, PLAYER_PIECE_PAL0
    player_piece  -33,   -4, PLAYER_PIECE_PAL1

data_7d_4422_PlayerFrame_111:
    player_frame_header   6, $17, $22, data_7d_4890_PlayerTiles + $1b20
    player_piece  -29,  -12, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece   -5,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    4, PLAYER_PIECE_PAL0
    player_piece  -10,    6, PLAYER_PIECE_PAL0
    player_piece  -34,   -4, PLAYER_PIECE_PAL1

data_7d_443f_PlayerFrame_112:
    player_frame_header   4, $17, $1c, data_7d_4890_PlayerTiles + $1be0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece   -5,   -4, PLAYER_PIECE_PAL0
    player_piece  -20,    0, PLAYER_PIECE_PAL0
    player_piece   -4,    0, PLAYER_PIECE_PAL0

data_7d_4454_PlayerFrame_113:
    player_frame_header   6, $17, $1c, data_7d_4890_PlayerTiles + $1c60
    player_piece  -16,  -12, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece   -5,   -4, PLAYER_PIECE_PAL0
    player_piece  -18,    0, PLAYER_PIECE_PAL0
    player_piece   -2,    0, PLAYER_PIECE_PAL0
    player_piece  -34,   -4, PLAYER_PIECE_PAL1

data_7d_4471_PlayerFrame_114:
    player_frame_header   6, $17, $1e, data_7d_4890_PlayerTiles + $1d20
    player_piece  -11,  -20, PLAYER_PIECE_PAL0
    player_piece  -17,  -12, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece   -5,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -33,   -4, PLAYER_PIECE_PAL1

data_7d_448e_PlayerFrame_115:
    player_frame_header   6, $20, $1d, data_7d_4890_PlayerTiles + $1de0
    player_piece  -28,   -9, PLAYER_PIECE_PAL0
    player_piece  -30,   -1, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -14,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -13,    5, PLAYER_PIECE_PAL0

data_7d_44ab_PlayerFrame_116:
    player_frame_header   5, $20, $1f, data_7d_4890_PlayerTiles + $1ea0
    player_piece  -30,   -7, PLAYER_PIECE_PAL0
    player_piece  -30,    1, PLAYER_PIECE_PAL0
    player_piece  -24,    7, PLAYER_PIECE_PAL0
    player_piece  -14,   -5, PLAYER_PIECE_PAL0
    player_piece  -14,    3, PLAYER_PIECE_PAL0

data_7d_44c4_PlayerFrame_117:
    player_frame_header   6, $1f, $1d, data_7d_4890_PlayerTiles + $1f40
    player_piece  -40,  -16, PLAYER_PIECE_PAL0
    player_piece  -29,   -8, PLAYER_PIECE_PAL0
    player_piece  -13,   -8, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL0
    player_piece  -13,    0, PLAYER_PIECE_PAL0
    player_piece  -18,    5, PLAYER_PIECE_PAL0

data_7d_44e1_PlayerFrame_118:
    player_frame_header   5, $21, $1a, data_7d_4890_PlayerTiles + $2000
    player_piece  -31,  -11, PLAYER_PIECE_PAL0
    player_piece  -30,   -3, PLAYER_PIECE_PAL0
    player_piece  -27,    2, PLAYER_PIECE_PAL0
    player_piece  -15,   -9, PLAYER_PIECE_PAL0
    player_piece  -14,   -1, PLAYER_PIECE_PAL0

data_7d_44fa_PlayerFrame_119:
    player_frame_header   6, $1f, $1d, data_7d_4890_PlayerTiles + $20a0
    player_piece  -27,  -10, PLAYER_PIECE_PAL0
    player_piece  -29,   -2, PLAYER_PIECE_PAL0
    player_piece  -13,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    6, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -11,    6, PLAYER_PIECE_PAL0

data_7d_4517_PlayerFrame_120:
    player_frame_header   5, $20, $1e, data_7d_4890_PlayerTiles + $2160
    player_piece  -25,  -11, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL0
    player_piece  -13,   -6, PLAYER_PIECE_PAL0
    player_piece  -14,    2, PLAYER_PIECE_PAL0

data_7d_4530_PlayerFrame_121:
    player_frame_header   5, $1f, $1f, data_7d_4890_PlayerTiles + $2200
    player_piece  -28,   -8, PLAYER_PIECE_PAL0
    player_piece  -12,   -8, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL0
    player_piece  -13,    0, PLAYER_PIECE_PAL0
    player_piece  -23,    7, PLAYER_PIECE_PAL0

data_7d_4549_PlayerFrame_122:
    player_frame_header   6, $1e, $1c, data_7d_4890_PlayerTiles + $22a0
    player_piece  -40,  -16, PLAYER_PIECE_PAL0
    player_piece  -28,   -8, PLAYER_PIECE_PAL0
    player_piece  -12,   -8, PLAYER_PIECE_PAL0
    player_piece  -28,    0, PLAYER_PIECE_PAL0
    player_piece  -12,    0, PLAYER_PIECE_PAL0
    player_piece  -18,    4, PLAYER_PIECE_PAL0

data_7d_4566_PlayerFrame_123:
    player_frame_header   5, $20, $1b, data_7d_4890_PlayerTiles + $2360
    player_piece  -30,  -10, PLAYER_PIECE_PAL0
    player_piece  -30,   -2, PLAYER_PIECE_PAL0
    player_piece  -26,    3, PLAYER_PIECE_PAL0
    player_piece  -14,   -6, PLAYER_PIECE_PAL0
    player_piece  -14,    2, PLAYER_PIECE_PAL0

data_7d_457f_PlayerFrame_124:
    player_frame_header   6, $20, $1c, data_7d_4890_PlayerTiles + $2400
    player_piece  -28,  -10, PLAYER_PIECE_PAL0
    player_piece  -30,   -2, PLAYER_PIECE_PAL0
    player_piece  -14,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,    3, PLAYER_PIECE_PAL0
    player_piece  -10,   -6, PLAYER_PIECE_PAL0
    player_piece  -11,    3, PLAYER_PIECE_PAL0

data_7d_459c_PlayerFrame_125:
    player_frame_header   4, $21, $19, data_7d_4890_PlayerTiles + $24c0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_7d_45b1_PlayerFrame_126:
    player_frame_header   4, $20, $18, data_7d_4890_PlayerTiles + $2540
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_7d_45c6_PlayerFrame_127:
    player_frame_header   4, $20, $18, data_7d_4890_PlayerTiles + $25c0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_7d_45db_PlayerFrame_128:
    player_frame_header   4, $20, $18, data_7d_4890_PlayerTiles + $2640
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_7d_45f0_PlayerFrame_129:
    player_frame_header   4, $21, $18, data_7d_4890_PlayerTiles + $26c0
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_7d_4605_PlayerFrame_130:
    player_frame_header   4, $20, $18, data_7d_4890_PlayerTiles + $2740
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_7d_461a_PlayerFrame_131:
    player_frame_header   4, $20, $18, data_7d_4890_PlayerTiles + $27c0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0

data_7d_462f_PlayerFrame_132:
    player_frame_header   5, $1e, $1a, data_7d_4890_PlayerTiles + $2840
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece  -12,   -8, PLAYER_PIECE_PAL0
    player_piece  -17,    0, PLAYER_PIECE_PAL0
    player_piece  -37,   -5, PLAYER_PIECE_PAL1

data_7d_4648_PlayerFrame_133:
    player_frame_header   5, $1d, $19, data_7d_4890_PlayerTiles + $28e0
    player_piece  -31,  -10, PLAYER_PIECE_PAL0
    player_piece  -10,  -10, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL0
    player_piece  -17,   -2, PLAYER_PIECE_PAL0
    player_piece  -36,  -10, PLAYER_PIECE_PAL1

data_7d_4661_PlayerFrame_134:
    player_frame_header   5, $1d, $19, data_7d_4890_PlayerTiles + $2980
    player_piece  -28,  -10, PLAYER_PIECE_PAL0
    player_piece  -10,  -10, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL0
    player_piece  -17,   -2, PLAYER_PIECE_PAL0
    player_piece  -36,  -10, PLAYER_PIECE_PAL1

data_7d_467a_PlayerFrame_135:
    player_frame_header   6, $18, $1e, data_7d_4890_PlayerTiles + $2a20
    player_piece  -23,  -10, PLAYER_PIECE_PAL0
    player_piece   -5,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece   -4,   -2, PLAYER_PIECE_PAL0
    player_piece   -4,    4, PLAYER_PIECE_PAL0
    player_piece  -31,  -10, PLAYER_PIECE_PAL1

data_7d_4697_PlayerFrame_136:
    player_frame_header   5, $14, $1e, data_7d_4890_PlayerTiles + $2ae0
    player_piece  -10,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece   -2,   -3, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL1

data_7d_46b0_PlayerFrame_137:
    player_frame_header   5, $13, $1e, data_7d_4890_PlayerTiles + $2b80
    player_piece  -10,  -11, PLAYER_PIECE_PAL0
    player_piece  -17,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece   -1,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL1

data_7d_46c9_PlayerFrame_138:
    player_frame_header   6, $17, $1f, data_7d_4890_PlayerTiles + $2c20
    player_piece  -15,  -10, PLAYER_PIECE_PAL0
    player_piece  -21,   -2, PLAYER_PIECE_PAL0
    player_piece  -20,    5, PLAYER_PIECE_PAL0
    player_piece   -5,   -2, PLAYER_PIECE_PAL0
    player_piece   -4,    5, PLAYER_PIECE_PAL0
    player_piece  -33,    4, PLAYER_PIECE_PAL1

data_7d_46e6_PlayerFrame_139:
    player_frame_header   5, $17, $1d, data_7d_4890_PlayerTiles + $2ce0
    player_piece  -17,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece  -18,    3, PLAYER_PIECE_PAL0
    player_piece   -5,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,    2, PLAYER_PIECE_PAL1

data_7d_46ff_PlayerFrame_140:
    player_frame_header   5, $17, $21, data_7d_4890_PlayerTiles + $2d80
    player_piece  -20,  -14, PLAYER_PIECE_PAL0
    player_piece  -16,   -6, PLAYER_PIECE_PAL0
    player_piece  -21,    2, PLAYER_PIECE_PAL0
    player_piece  -28,    7, PLAYER_PIECE_PAL0
    player_piece   -5,    2, PLAYER_PIECE_PAL0

data_7d_4718_PlayerFrame_141:
    player_frame_header   5, $1e, $1d, data_7d_4890_PlayerTiles + $2e20
    player_piece  -28,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    2, PLAYER_PIECE_PAL0
    player_piece  -12,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -40,   -2, PLAYER_PIECE_PAL1

data_7d_4731_PlayerFrame_142:
    player_frame_header   5, $1e, $1c, data_7d_4890_PlayerTiles + $2ec0
    player_piece  -28,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece  -12,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -40,   -2, PLAYER_PIECE_PAL1

data_7d_474a_PlayerFrame_143:
    player_frame_header   5, $1e, $1c, data_7d_4890_PlayerTiles + $2f60
    player_piece  -28,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    1, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -12,    1, PLAYER_PIECE_PAL0
    player_piece  -40,   -2, PLAYER_PIECE_PAL1

data_7d_4763_PlayerFrame_144:
    player_frame_header   5, $1d, $1c, data_7d_4890_PlayerTiles + $3000
    player_piece  -27,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece  -11,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    1, PLAYER_PIECE_PAL0
    player_piece  -39,   -2, PLAYER_PIECE_PAL1

data_7d_477c_PlayerFrame_145:
    player_frame_header   5, $1e, $1c, data_7d_4890_PlayerTiles + $30a0
    player_piece  -28,   -6, PLAYER_PIECE_PAL0
    player_piece  -28,    1, PLAYER_PIECE_PAL0
    player_piece  -12,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    1, PLAYER_PIECE_PAL0
    player_piece  -40,   -2, PLAYER_PIECE_PAL1

data_7d_4795_PlayerFrame_146:
    player_frame_header   5, $1e, $1b, data_7d_4890_PlayerTiles + $3140
    player_piece  -28,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    0, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -20,    0, PLAYER_PIECE_PAL0
    player_piece  -40,   -2, PLAYER_PIECE_PAL1

data_7d_47ae_PlayerFrame_147:
    player_frame_header   5, $1e, $1c, data_7d_4890_PlayerTiles + $31e0
    player_piece  -28,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    1, PLAYER_PIECE_PAL0
    player_piece  -12,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -40,   -2, PLAYER_PIECE_PAL1

data_7d_47c7_PlayerFrame_148:
    player_frame_header   5, $1d, $1c, data_7d_4890_PlayerTiles + $3280
    player_piece  -27,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece  -11,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -39,   -2, PLAYER_PIECE_PAL1

data_7d_47e0_PlayerFrame_149:
    player_frame_header   4, $1e, $1d, data_7d_4890_PlayerTiles + $3320
    player_piece  -28,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    2, PLAYER_PIECE_PAL0
    player_piece  -12,   -5, PLAYER_PIECE_PAL0
    player_piece  -12,    2, PLAYER_PIECE_PAL0

data_7d_47f5_PlayerFrame_150:
    player_frame_header   4, $1e, $1c, data_7d_4890_PlayerTiles + $33a0
    player_piece  -28,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece  -12,   -4, PLAYER_PIECE_PAL0
    player_piece  -11,    1, PLAYER_PIECE_PAL0

data_7d_480a_PlayerFrame_151:
    player_frame_header   4, $1e, $1c, data_7d_4890_PlayerTiles + $3420
    player_piece  -28,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    1, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -12,    1, PLAYER_PIECE_PAL0

data_7d_481f_PlayerFrame_152:
    player_frame_header   4, $1d, $1c, data_7d_4890_PlayerTiles + $34a0
    player_piece  -27,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece  -11,   -4, PLAYER_PIECE_PAL0
    player_piece  -11,    1, PLAYER_PIECE_PAL0

data_7d_4834_PlayerFrame_153:
    player_frame_header   4, $1e, $1c, data_7d_4890_PlayerTiles + $3520
    player_piece  -28,   -6, PLAYER_PIECE_PAL0
    player_piece  -28,    1, PLAYER_PIECE_PAL0
    player_piece  -12,   -4, PLAYER_PIECE_PAL0
    player_piece  -12,    1, PLAYER_PIECE_PAL0

data_7d_4849_PlayerFrame_154:
    player_frame_header   4, $1e, $1b, data_7d_4890_PlayerTiles + $35a0
    player_piece  -28,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    0, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,    0, PLAYER_PIECE_PAL0

data_7d_485e_PlayerFrame_155:
    player_frame_header   4, $1e, $1c, data_7d_4890_PlayerTiles + $3620
    player_piece  -28,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    1, PLAYER_PIECE_PAL0
    player_piece  -12,   -4, PLAYER_PIECE_PAL0
    player_piece  -12,    1, PLAYER_PIECE_PAL0

data_7d_4873_PlayerFrame_156:
    player_frame_header   4, $1d, $1c, data_7d_4890_PlayerTiles + $36a0
    player_piece  -27,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece  -11,   -4, PLAYER_PIECE_PAL0
    player_piece  -11,    1, PLAYER_PIECE_PAL0

    ds   $4890 - @, 0                    ; the bank pads to a 16-byte boundary here
data_7d_4890_PlayerTiles:
; INCBINd by main.asm - see the header above
