; ==================================================================
; Bank $7c. Gex's animation frames 1 to 72 of PLAYER_GFX_SET_GEX_CAVE.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $484b, then 882 tiles of graphics from $4850 to $7f6f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/sprite_data/bank7F.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_7c_4000_PlayerFrame_001:
    player_frame_header   7, $1c, $22, data_7c_4850_PlayerTiles + $0000
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -28,    4, PLAYER_PIECE_PAL0
    player_piece  -24,    8, PLAYER_PIECE_PAL0
    player_piece   -8,  -13, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -19,    4, PLAYER_PIECE_PAL0
    player_piece  -39,    7, PLAYER_PIECE_PAL1

data_7c_4021_PlayerFrame_002:
    player_frame_header   7, $1c, $22, data_7c_4850_PlayerTiles + $00e0
    player_piece  -23,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    6, PLAYER_PIECE_PAL0
    player_piece  -22,    8, PLAYER_PIECE_PAL0
    player_piece   -7,  -11, PLAYER_PIECE_PAL0
    player_piece   -7,   -3, PLAYER_PIECE_PAL0
    player_piece  -17,    5, PLAYER_PIECE_PAL0
    player_piece  -38,    7, PLAYER_PIECE_PAL1

data_7c_4042_PlayerFrame_003:
    player_frame_header   6, $1b, $22, data_7c_4850_PlayerTiles + $01c0
    player_piece  -23,   -1, PLAYER_PIECE_PAL0
    player_piece  -27,    7, PLAYER_PIECE_PAL0
    player_piece   -8,   -9, PLAYER_PIECE_PAL0
    player_piece   -7,   -1, PLAYER_PIECE_PAL0
    player_piece  -17,    7, PLAYER_PIECE_PAL0
    player_piece  -37,    7, PLAYER_PIECE_PAL1

data_7c_405f_PlayerFrame_004:
    player_frame_header   7, $1b, $23, data_7c_4850_PlayerTiles + $0280
    player_piece  -20,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    5, PLAYER_PIECE_PAL0
    player_piece  -34,    9, PLAYER_PIECE_PAL0
    player_piece   -8,  -10, PLAYER_PIECE_PAL0
    player_piece   -4,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,    6, PLAYER_PIECE_PAL0
    player_piece  -37,    8, PLAYER_PIECE_PAL1

data_7c_4080_PlayerFrame_005:
    player_frame_header   7, $1a, $23, data_7c_4850_PlayerTiles + $0360
    player_piece  -11,  -11, PLAYER_PIECE_PAL0
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece  -25,    5, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece   -3,   -3, PLAYER_PIECE_PAL0
    player_piece   -2,    5, PLAYER_PIECE_PAL0
    player_piece  -36,    8, PLAYER_PIECE_PAL1

data_7c_40a1_PlayerFrame_006:
    player_frame_header   7, $1b, $23, data_7c_4850_PlayerTiles + $0440
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece  -26,    4, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -16,  -12, PLAYER_PIECE_PAL0
    player_piece   -3,   -4, PLAYER_PIECE_PAL0
    player_piece   -9,    4, PLAYER_PIECE_PAL0
    player_piece  -37,    8, PLAYER_PIECE_PAL1

data_7c_40c2_PlayerFrame_007:
    player_frame_header   7, $1c, $23, data_7c_4850_PlayerTiles + $0520
    player_piece  -21,   -3, PLAYER_PIECE_PAL0
    player_piece  -28,    5, PLAYER_PIECE_PAL0
    player_piece  -34,    9, PLAYER_PIECE_PAL0
    player_piece   -9,  -13, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL0
    player_piece  -17,    3, PLAYER_PIECE_PAL0
    player_piece  -38,    9, PLAYER_PIECE_PAL1

data_7c_40e3_PlayerFrame_008:
    player_frame_header   7, $1d, $23, data_7c_4850_PlayerTiles + $0600
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece  -28,    5, PLAYER_PIECE_PAL0
    player_piece  -35,    9, PLAYER_PIECE_PAL0
    player_piece   -9,  -13, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL0
    player_piece  -19,    4, PLAYER_PIECE_PAL0
    player_piece  -39,    9, PLAYER_PIECE_PAL1

data_7c_4104_PlayerFrame_009:
    player_frame_header   7, $1e, $22, data_7c_4850_PlayerTiles + $06e0
    player_piece  -22,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL0
    player_piece  -25,    8, PLAYER_PIECE_PAL0
    player_piece   -8,  -13, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,    4, PLAYER_PIECE_PAL0
    player_piece  -41,    8, PLAYER_PIECE_PAL1

data_7c_4125_PlayerFrame_010:
    player_frame_header   7, $1c, $22, data_7c_4850_PlayerTiles + $07c0
    player_piece  -24,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,    6, PLAYER_PIECE_PAL0
    player_piece   -9,  -11, PLAYER_PIECE_PAL0
    player_piece  -37,   14, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece   -8,    5, PLAYER_PIECE_PAL0
    player_piece  -40,    9, PLAYER_PIECE_PAL1

data_7c_4146_PlayerFrame_011:
    player_frame_header   7, $1b, $23, data_7c_4850_PlayerTiles + $08a0
    player_piece  -23,   -1, PLAYER_PIECE_PAL0
    player_piece  -27,    7, PLAYER_PIECE_PAL0
    player_piece  -21,    9, PLAYER_PIECE_PAL0
    player_piece   -8,   -9, PLAYER_PIECE_PAL0
    player_piece   -7,   -1, PLAYER_PIECE_PAL0
    player_piece   -5,    7, PLAYER_PIECE_PAL0
    player_piece  -37,    9, PLAYER_PIECE_PAL1

data_7c_4167_PlayerFrame_012:
    player_frame_header   7, $1a, $23, data_7c_4850_PlayerTiles + $0980
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    5, PLAYER_PIECE_PAL0
    player_piece   -8,  -10, PLAYER_PIECE_PAL0
    player_piece  -32,   13, PLAYER_PIECE_PAL0
    player_piece   -3,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0
    player_piece  -36,    9, PLAYER_PIECE_PAL1

data_7c_4188_PlayerFrame_013:
    player_frame_header   6, $1a, $23, data_7c_4850_PlayerTiles + $0a60
    player_piece  -19,  -10, PLAYER_PIECE_PAL0
    player_piece  -21,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -26,    6, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -36,    6, PLAYER_PIECE_PAL1

data_7c_41a5_PlayerFrame_014:
    player_frame_header   7, $1b, $23, data_7c_4850_PlayerTiles + $0b20
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece  -26,    4, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -16,  -12, PLAYER_PIECE_PAL0
    player_piece   -3,   -4, PLAYER_PIECE_PAL0
    player_piece   -9,    4, PLAYER_PIECE_PAL0
    player_piece  -37,    8, PLAYER_PIECE_PAL1

data_7c_41c6_PlayerFrame_015:
    player_frame_header   7, $1b, $23, data_7c_4850_PlayerTiles + $0c00
    player_piece  -20,   -3, PLAYER_PIECE_PAL0
    player_piece  -27,    5, PLAYER_PIECE_PAL0
    player_piece  -34,    9, PLAYER_PIECE_PAL0
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    4, PLAYER_PIECE_PAL0
    player_piece  -37,    8, PLAYER_PIECE_PAL1

data_7c_41e7_PlayerFrame_016:
    player_frame_header   7, $1c, $22, data_7c_4850_PlayerTiles + $0ce0
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece  -28,    4, PLAYER_PIECE_PAL0
    player_piece  -23,    8, PLAYER_PIECE_PAL0
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,    4, PLAYER_PIECE_PAL0
    player_piece   -7,    8, PLAYER_PIECE_PAL0
    player_piece  -38,    7, PLAYER_PIECE_PAL1

data_7c_4208_PlayerFrame_017:
    player_frame_header   7, $1d, $20, data_7c_4850_PlayerTiles + $0dc0
    player_piece  -22,   -4, PLAYER_PIECE_PAL0
    player_piece  -28,    4, PLAYER_PIECE_PAL0
    player_piece  -35,    8, PLAYER_PIECE_PAL0
    player_piece   -9,  -14, PLAYER_PIECE_PAL0
    player_piece  -16,   -6, PLAYER_PIECE_PAL0
    player_piece  -19,    3, PLAYER_PIECE_PAL0
    player_piece  -39,    8, PLAYER_PIECE_PAL1

data_7c_4229_PlayerFrame_018:
    player_frame_header   6, $1d, $21, data_7c_4850_PlayerTiles + $0ea0
    player_piece  -11,  -14, PLAYER_PIECE_PAL0
    player_piece  -22,   -6, PLAYER_PIECE_PAL0
    player_piece  -27,    2, PLAYER_PIECE_PAL0
    player_piece  -26,   10, PLAYER_PIECE_PAL0
    player_piece  -23,    3, PLAYER_PIECE_PAL0
    player_piece  -39,    9, PLAYER_PIECE_PAL1

data_7c_4246_PlayerFrame_019:
    player_frame_header   7, $1d, $20, data_7c_4850_PlayerTiles + $0f60
    player_piece  -23,  -15, PLAYER_PIECE_PAL0
    player_piece  -25,   -7, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece  -26,    8, PLAYER_PIECE_PAL0
    player_piece   -9,   -7, PLAYER_PIECE_PAL0
    player_piece  -11,    3, PLAYER_PIECE_PAL0
    player_piece  -39,    8, PLAYER_PIECE_PAL1

data_7c_4267_PlayerFrame_020:
    player_frame_header   8, $1d, $20, data_7c_4850_PlayerTiles + $1040
    player_piece  -11,  -16, PLAYER_PIECE_PAL0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -10,   -8, PLAYER_PIECE_PAL0
    player_piece  -27,    0, PLAYER_PIECE_PAL0
    player_piece  -11,    0, PLAYER_PIECE_PAL0
    player_piece  -30,    8, PLAYER_PIECE_PAL0
    player_piece  -19,    8, PLAYER_PIECE_PAL0
    player_piece  -39,    8, PLAYER_PIECE_PAL1

data_7c_428c_PlayerFrame_021:
    player_frame_header   8, $1e, $20, data_7c_4850_PlayerTiles + $1140
    player_piece  -24,   -4, PLAYER_PIECE_PAL0
    player_piece  -28,    4, PLAYER_PIECE_PAL0
    player_piece  -25,    8, PLAYER_PIECE_PAL0
    player_piece  -11,  -12, PLAYER_PIECE_PAL0
    player_piece   -8,   -4, PLAYER_PIECE_PAL0
    player_piece  -18,    4, PLAYER_PIECE_PAL0
    player_piece   -7,    8, PLAYER_PIECE_PAL0
    player_piece  -40,    7, PLAYER_PIECE_PAL1

data_7c_42b1_PlayerFrame_022:
    player_frame_header   7, $1f, $20, data_7c_4850_PlayerTiles + $1240
    player_piece  -26,   -6, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -38,    5, PLAYER_PIECE_PAL0
    player_piece  -11,  -15, PLAYER_PIECE_PAL0
    player_piece  -19,   -7, PLAYER_PIECE_PAL0
    player_piece  -17,    1, PLAYER_PIECE_PAL0
    player_piece  -41,    4, PLAYER_PIECE_PAL1

data_7c_42d2_PlayerFrame_023:
    player_frame_header   7, $1c, $20, data_7c_4850_PlayerTiles + $1320
    player_piece  -22,  -15, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -35,    9, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0
    player_piece  -38,    4, PLAYER_PIECE_PAL1

data_7c_42f3_PlayerFrame_024:
    player_frame_header   7, $1a, $20, data_7c_4850_PlayerTiles + $1400
    player_piece  -21,  -17, PLAYER_PIECE_PAL0
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -24,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,    3, PLAYER_PIECE_PAL0
    player_piece   -8,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    3, PLAYER_PIECE_PAL0
    player_piece  -36,    2, PLAYER_PIECE_PAL1

data_7c_4314_PlayerFrame_025:
    player_frame_header   7, $1f, $1d, data_7c_4850_PlayerTiles + $14e0
    player_piece  -29,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    3, PLAYER_PIECE_PAL0
    player_piece  -13,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL1

data_7c_4335_PlayerFrame_026:
    player_frame_header   7, $20, $1d, data_7c_4850_PlayerTiles + $15c0
    player_piece  -30,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -39,    3, PLAYER_PIECE_PAL0
    player_piece  -16,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL1

data_7c_4356_PlayerFrame_027:
    player_frame_header   7, $1e, $1d, data_7c_4850_PlayerTiles + $16a0
    player_piece  -27,  -12, PLAYER_PIECE_PAL0
    player_piece  -28,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    3, PLAYER_PIECE_PAL0
    player_piece  -12,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -40,   -3, PLAYER_PIECE_PAL1

data_7c_4377_PlayerFrame_028:
    player_frame_header   6, $1a, $1d, data_7c_4850_PlayerTiles + $1780
    player_piece  -22,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    3, PLAYER_PIECE_PAL0
    player_piece   -8,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -36,   -3, PLAYER_PIECE_PAL1

data_7c_4394_PlayerFrame_029:
    player_frame_header   6, $16, $1d, data_7c_4850_PlayerTiles + $1840
    player_piece  -19,  -11, PLAYER_PIECE_PAL0
    player_piece  -20,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    3, PLAYER_PIECE_PAL0
    player_piece   -4,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -32,   -4, PLAYER_PIECE_PAL1

data_7c_43b1_PlayerFrame_030:
    player_frame_header   6, $1e, $1d, data_7c_4850_PlayerTiles + $1900
    player_piece  -28,   -9, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL0
    player_piece  -18,    3, PLAYER_PIECE_PAL0
    player_piece  -12,   -9, PLAYER_PIECE_PAL0
    player_piece  -12,   -1, PLAYER_PIECE_PAL0
    player_piece  -40,   -3, PLAYER_PIECE_PAL1

data_7c_43ce_PlayerFrame_031:
    player_frame_header   7, $1e, $1d, data_7c_4850_PlayerTiles + $19c0
    player_piece  -27,  -12, PLAYER_PIECE_PAL0
    player_piece  -28,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    3, PLAYER_PIECE_PAL0
    player_piece  -12,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -40,   -3, PLAYER_PIECE_PAL1

data_7c_43ef_PlayerFrame_032:
    player_frame_header   7, $1e, $20, data_7c_4850_PlayerTiles + $1aa0
    player_piece  -18,  -12, PLAYER_PIECE_PAL0
    player_piece   -1,  -12, PLAYER_PIECE_PAL0
    player_piece  -28,   -4, PLAYER_PIECE_PAL0
    player_piece  -12,   -4, PLAYER_PIECE_PAL0
    player_piece  -26,    4, PLAYER_PIECE_PAL0
    player_piece  -10,    4, PLAYER_PIECE_PAL0
    player_piece  -40,   -4, PLAYER_PIECE_PAL1

data_7c_4410_PlayerFrame_033:
    player_frame_header   6, $1e, $21, data_7c_4850_PlayerTiles + $1b80
    player_piece  -19,  -12, PLAYER_PIECE_PAL0
    player_piece  -28,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL0
    player_piece  -12,   -5, PLAYER_PIECE_PAL0
    player_piece  -12,    3, PLAYER_PIECE_PAL0
    player_piece  -40,   -1, PLAYER_PIECE_PAL1

data_7c_442d_PlayerFrame_034:
    player_frame_header   6, $1b, $1f, data_7c_4850_PlayerTiles + $1c40
    player_piece  -21,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    3, PLAYER_PIECE_PAL0
    player_piece   -9,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -37,   -1, PLAYER_PIECE_PAL1

data_7c_444a_PlayerFrame_035:
    player_frame_header   6, $18, $1d, data_7c_4850_PlayerTiles + $1d00
    player_piece  -21,  -12, PLAYER_PIECE_PAL0
    player_piece  -22,   -4, PLAYER_PIECE_PAL0
    player_piece   -6,   -4, PLAYER_PIECE_PAL0
    player_piece  -31,    1, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -34,   -4, PLAYER_PIECE_PAL1

data_7c_4467_PlayerFrame_036:
    player_frame_header   6, $19, $1c, data_7c_4850_PlayerTiles + $1dc0
    player_piece  -23,  -10, PLAYER_PIECE_PAL0
    player_piece  -21,   -2, PLAYER_PIECE_PAL0
    player_piece  -20,    0, PLAYER_PIECE_PAL0
    player_piece   -7,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -32,   -2, PLAYER_PIECE_PAL1

data_7c_4484_PlayerFrame_037:
    player_frame_header   5, $18, $1b, data_7c_4850_PlayerTiles + $1e80
    player_piece  -21,  -10, PLAYER_PIECE_PAL0
    player_piece  -22,   -2, PLAYER_PIECE_PAL0
    player_piece   -6,   -7, PLAYER_PIECE_PAL0
    player_piece   -6,   -1, PLAYER_PIECE_PAL0
    player_piece  -29,   -2, PLAYER_PIECE_PAL1

data_7c_449d_PlayerFrame_038:
    player_frame_header   5, $16, $1b, data_7c_4850_PlayerTiles + $1f20
    player_piece  -20,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece   -4,   -5, PLAYER_PIECE_PAL0
    player_piece   -4,   -1, PLAYER_PIECE_PAL0
    player_piece  -28,   -2, PLAYER_PIECE_PAL1

data_7c_44b6_PlayerFrame_039:
    player_frame_header   3, $15, $1b, data_7c_4850_PlayerTiles + $1fc0
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0

data_7c_44c7_PlayerFrame_040:
    player_frame_header   3, $15, $1b, data_7c_4850_PlayerTiles + $2020
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0

data_7c_44d8_PlayerFrame_041:
    player_frame_header   3, $15, $1b, data_7c_4850_PlayerTiles + $2080
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0

data_7c_44e9_PlayerFrame_042:
    player_frame_header   7, $1c, $23, data_7c_4850_PlayerTiles + $20e0
    player_piece  -26,  -16, PLAYER_PIECE_PAL0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -17,    0, PLAYER_PIECE_PAL0
    player_piece  -10,  -15, PLAYER_PIECE_PAL0
    player_piece  -10,   -7, PLAYER_PIECE_PAL0
    player_piece   -1,    0, PLAYER_PIECE_PAL0
    player_piece  -38,   -9, PLAYER_PIECE_PAL1

data_7c_450a_PlayerFrame_043:
    player_frame_header   6, $1c, $22, data_7c_4850_PlayerTiles + $21c0
    player_piece  -26,  -14, PLAYER_PIECE_PAL0
    player_piece  -26,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -10,  -11, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -38,   -6, PLAYER_PIECE_PAL1

data_7c_4527_PlayerFrame_044:
    player_frame_header   5, $1d, $25, data_7c_4850_PlayerTiles + $2280
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -27,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece  -39,   -1, PLAYER_PIECE_PAL1

data_7c_4540_PlayerFrame_045:
    player_frame_header   6, $1d, $26, data_7c_4850_PlayerTiles + $2320
    player_piece  -20,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    3, PLAYER_PIECE_PAL0
    player_piece   -7,    3, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL1

data_7c_455d_PlayerFrame_046:
    player_frame_header   7, $1c, $30, data_7c_4850_PlayerTiles + $23e0
    player_piece  -19,    0, PLAYER_PIECE_PAL0
    player_piece  -26,    8, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -30,   16, PLAYER_PIECE_PAL0
    player_piece   -3,    3, PLAYER_PIECE_PAL0
    player_piece  -10,    8, PLAYER_PIECE_PAL0
    player_piece  -38,   12, PLAYER_PIECE_PAL1

data_7c_457e_PlayerFrame_047:
    player_frame_header   7, $20, $2b, data_7c_4850_PlayerTiles + $24c0
    player_piece  -30,   -7, PLAYER_PIECE_PAL0
    player_piece  -30,    1, PLAYER_PIECE_PAL0
    player_piece  -10,  -14, PLAYER_PIECE_PAL0
    player_piece  -14,   -6, PLAYER_PIECE_PAL0
    player_piece  -18,    2, PLAYER_PIECE_PAL0
    player_piece  -22,    4, PLAYER_PIECE_PAL0
    player_piece  -42,   -1, PLAYER_PIECE_PAL1

data_7c_459f_PlayerFrame_048:
    player_frame_header   6, $1e, $2a, data_7c_4850_PlayerTiles + $25a0
    player_piece  -28,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,   -5, PLAYER_PIECE_PAL0
    player_piece   -9,  -11, PLAYER_PIECE_PAL0
    player_piece  -20,    3, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -40,   -5, PLAYER_PIECE_PAL1

data_7c_45bc_PlayerFrame_049:
    player_frame_header   6, $1d, $2b, data_7c_4850_PlayerTiles + $2660
    player_piece  -27,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -19,    4, PLAYER_PIECE_PAL0
    player_piece  -11,  -10, PLAYER_PIECE_PAL0
    player_piece  -11,   -2, PLAYER_PIECE_PAL0
    player_piece  -39,   -6, PLAYER_PIECE_PAL1

data_7c_45d9_PlayerFrame_050:
    player_frame_header   6, $1d, $30, data_7c_4850_PlayerTiles + $2720
    player_piece  -27,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -11,   -8, PLAYER_PIECE_PAL0
    player_piece  -20,    0, PLAYER_PIECE_PAL0
    player_piece  -27,    8, PLAYER_PIECE_PAL0
    player_piece  -39,   -6, PLAYER_PIECE_PAL1

data_7c_45f6_PlayerFrame_051:
    player_frame_header   6, $1c, $30, data_7c_4850_PlayerTiles + $27e0
    player_piece  -26,  -11, PLAYER_PIECE_PAL0
    player_piece  -26,   -3, PLAYER_PIECE_PAL0
    player_piece  -10,   -8, PLAYER_PIECE_PAL0
    player_piece  -21,    0, PLAYER_PIECE_PAL0
    player_piece  -28,    8, PLAYER_PIECE_PAL0
    player_piece  -38,   -6, PLAYER_PIECE_PAL1

data_7c_4613_PlayerFrame_052:
    player_frame_header   7, $1c, $2e, data_7c_4850_PlayerTiles + $28a0
    player_piece  -24,  -15, PLAYER_PIECE_PAL0
    player_piece  -26,   -7, PLAYER_PIECE_PAL0
    player_piece  -10,   -7, PLAYER_PIECE_PAL0
    player_piece  -22,    1, PLAYER_PIECE_PAL0
    player_piece   -6,    1, PLAYER_PIECE_PAL0
    player_piece  -26,    7, PLAYER_PIECE_PAL0
    player_piece  -38,   -7, PLAYER_PIECE_PAL1

data_7c_4634_PlayerFrame_053:
    player_frame_header   7, $1b, $2e, data_7c_4850_PlayerTiles + $2980
    player_piece  -24,  -15, PLAYER_PIECE_PAL0
    player_piece  -25,   -7, PLAYER_PIECE_PAL0
    player_piece   -9,   -7, PLAYER_PIECE_PAL0
    player_piece  -21,    1, PLAYER_PIECE_PAL0
    player_piece   -5,    1, PLAYER_PIECE_PAL0
    player_piece  -26,    7, PLAYER_PIECE_PAL0
    player_piece  -37,   -7, PLAYER_PIECE_PAL1

data_7c_4655_PlayerFrame_054:
    player_frame_header   5, $13, $2e, data_7c_4850_PlayerTiles + $2a60
    player_piece  -18,  -12, PLAYER_PIECE_PAL0
    player_piece  -18,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    4, PLAYER_PIECE_PAL0
    player_piece  -23,    7, PLAYER_PIECE_PAL0
    player_piece  -27,   -8, PLAYER_PIECE_PAL1

data_7c_466e_PlayerFrame_055:
    player_frame_header   5, $22, $27, data_7c_4850_PlayerTiles + $2b00
    player_piece  -31,   -9, PLAYER_PIECE_PAL0
    player_piece  -32,   -1, PLAYER_PIECE_PAL0
    player_piece  -15,   -9, PLAYER_PIECE_PAL0
    player_piece  -25,   -1, PLAYER_PIECE_PAL0
    player_piece  -43,   -4, PLAYER_PIECE_PAL1

data_7c_4687_PlayerFrame_056:
    player_frame_header   5, $21, $27, data_7c_4850_PlayerTiles + $2ba0
    player_piece  -31,   -9, PLAYER_PIECE_PAL0
    player_piece  -31,   -1, PLAYER_PIECE_PAL0
    player_piece  -15,   -9, PLAYER_PIECE_PAL0
    player_piece  -23,   -1, PLAYER_PIECE_PAL0
    player_piece  -43,   -4, PLAYER_PIECE_PAL1

data_7c_46a0_PlayerFrame_057:
    player_frame_header   6, $22, $28, data_7c_4850_PlayerTiles + $2c40
    player_piece  -28,  -15, PLAYER_PIECE_PAL0
    player_piece  -32,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,   -7, PLAYER_PIECE_PAL0
    player_piece  -30,    1, PLAYER_PIECE_PAL0
    player_piece  -14,    1, PLAYER_PIECE_PAL0
    player_piece  -44,   -7, PLAYER_PIECE_PAL1

data_7c_46bd_PlayerFrame_058:
    player_frame_header   5, $22, $27, data_7c_4850_PlayerTiles + $2d00
    player_piece  -32,   -8, PLAYER_PIECE_PAL0
    player_piece  -32,    0, PLAYER_PIECE_PAL0
    player_piece  -16,   -8, PLAYER_PIECE_PAL0
    player_piece  -20,    0, PLAYER_PIECE_PAL0
    player_piece  -44,   -3, PLAYER_PIECE_PAL1

data_7c_46d6_PlayerFrame_059:
    player_frame_header   5, $22, $27, data_7c_4850_PlayerTiles + $2da0
    player_piece  -32,   -9, PLAYER_PIECE_PAL0
    player_piece  -32,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -9, PLAYER_PIECE_PAL0
    player_piece  -25,   -1, PLAYER_PIECE_PAL0
    player_piece  -44,   -3, PLAYER_PIECE_PAL1

data_7c_46ef_PlayerFrame_060:
    player_frame_header   5, $22, $27, data_7c_4850_PlayerTiles + $2e40
    player_piece  -31,   -9, PLAYER_PIECE_PAL0
    player_piece  -32,   -1, PLAYER_PIECE_PAL0
    player_piece  -15,   -9, PLAYER_PIECE_PAL0
    player_piece  -23,   -1, PLAYER_PIECE_PAL0
    player_piece  -44,   -2, PLAYER_PIECE_PAL1

data_7c_4708_PlayerFrame_061:
    player_frame_header   5, $22, $27, data_7c_4850_PlayerTiles + $2ee0
    player_piece  -31,   -9, PLAYER_PIECE_PAL0
    player_piece  -32,   -1, PLAYER_PIECE_PAL0
    player_piece  -15,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece  -44,   -2, PLAYER_PIECE_PAL1

data_7c_4721_PlayerFrame_062:
    player_frame_header   5, $22, $27, data_7c_4850_PlayerTiles + $2f80
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -32,    0, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -20,    0, PLAYER_PIECE_PAL0
    player_piece  -44,   -1, PLAYER_PIECE_PAL1

data_7c_473a_PlayerFrame_063:
    player_frame_header   6, $22, $29, data_7c_4850_PlayerTiles + $3020
    player_piece  -27,   -9, PLAYER_PIECE_PAL0
    player_piece  -31,   -1, PLAYER_PIECE_PAL0
    player_piece  -27,    2, PLAYER_PIECE_PAL0
    player_piece  -15,   -5, PLAYER_PIECE_PAL0
    player_piece  -11,    2, PLAYER_PIECE_PAL0
    player_piece  -43,    0, PLAYER_PIECE_PAL1

data_7c_4757_PlayerFrame_064:
    player_frame_header   7, $20, $2a, data_7c_4850_PlayerTiles + $30e0
    player_piece  -26,   -9, PLAYER_PIECE_PAL0
    player_piece  -30,   -1, PLAYER_PIECE_PAL0
    player_piece  -14,   -1, PLAYER_PIECE_PAL0
    player_piece  -31,    7, PLAYER_PIECE_PAL0
    player_piece   -9,   -7, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -42,    0, PLAYER_PIECE_PAL1

data_7c_4778_PlayerFrame_065:
    player_frame_header   6, $1f, $29, data_7c_4850_PlayerTiles + $31c0
    player_piece  -21,   -9, PLAYER_PIECE_PAL0
    player_piece  -29,   -1, PLAYER_PIECE_PAL0
    player_piece  -26,    2, PLAYER_PIECE_PAL0
    player_piece   -8,  -10, PLAYER_PIECE_PAL0
    player_piece  -13,   -1, PLAYER_PIECE_PAL0
    player_piece  -41,    1, PLAYER_PIECE_PAL1

data_7c_4795_PlayerFrame_066:
    player_frame_header   6, $1c, $2b, data_7c_4850_PlayerTiles + $3280
    player_piece  -21,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -27,    4, PLAYER_PIECE_PAL0
    player_piece   -9,  -11, PLAYER_PIECE_PAL0
    player_piece  -10,    0, PLAYER_PIECE_PAL0
    player_piece  -38,    3, PLAYER_PIECE_PAL1

data_7c_47b2_PlayerFrame_067:
    player_frame_header   5, $18, $2d, data_7c_4850_PlayerTiles + $3340
    player_piece  -12,  -15, PLAYER_PIECE_PAL0
    player_piece  -20,   -7, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece  -27,    6, PLAYER_PIECE_PAL0
    player_piece  -34,    1, PLAYER_PIECE_PAL1

data_7c_47cb_PlayerFrame_068:
    player_frame_header   5, $1e, $28, data_7c_4850_PlayerTiles + $33e0
    player_piece  -28,   -8, PLAYER_PIECE_PAL0
    player_piece  -28,    0, PLAYER_PIECE_PAL0
    player_piece  -12,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -40,   -2, PLAYER_PIECE_PAL1

data_7c_47e4_PlayerFrame_069:
    player_frame_header   5, $1e, $28, data_7c_4850_PlayerTiles + $3480
    player_piece  -27,   -8, PLAYER_PIECE_PAL0
    player_piece  -28,    0, PLAYER_PIECE_PAL0
    player_piece  -12,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -40,   -1, PLAYER_PIECE_PAL1

data_7c_47fd_PlayerFrame_070:
    player_frame_header   5, $1e, $28, data_7c_4850_PlayerTiles + $3520
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -28,    0, PLAYER_PIECE_PAL0
    player_piece  -10,   -8, PLAYER_PIECE_PAL0
    player_piece  -16,    0, PLAYER_PIECE_PAL0
    player_piece  -40,    0, PLAYER_PIECE_PAL1

data_7c_4816_PlayerFrame_071:
    player_frame_header   5, $1e, $28, data_7c_4850_PlayerTiles + $35c0
    player_piece  -27,   -6, PLAYER_PIECE_PAL0
    player_piece  -28,    2, PLAYER_PIECE_PAL0
    player_piece  -12,   -8, PLAYER_PIECE_PAL0
    player_piece  -16,    0, PLAYER_PIECE_PAL0
    player_piece  -40,    1, PLAYER_PIECE_PAL1

data_7c_482f_PlayerFrame_072:
    player_frame_header   6, $15, $26, data_7c_4850_PlayerTiles + $3660
    player_piece  -13,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -20,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,    5, PLAYER_PIECE_PAL0
    player_piece  -20,   11, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL1

    ds   $4850 - @, 0                    ; the bank pads to a 16-byte boundary here
data_7c_4850_PlayerTiles:
; INCBINd by main.asm - see the header above
