; ==================================================================
; Bank $69. Gex's animation frames 109 to 170 of PLAYER_GFX_SET_WESTERN_STATION.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $481d, then 884 tiles of graphics from $4820 to $7f5f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/sprite_data/bank7F.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_69_4000_PlayerFrame_109:
    player_frame_header   9, $1a, $24, data_69_4820_PlayerTiles + $0000
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece   -3,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    4, PLAYER_PIECE_PAL0
    player_piece   -1,    4, PLAYER_PIECE_PAL0
    player_piece  -22,    8, PLAYER_PIECE_PAL0
    player_piece  -34,   -4, PLAYER_PIECE_PAL1
    player_piece   -8,   -4, PLAYER_PIECE_PAL1
    player_piece  -24,    4, PLAYER_PIECE_PAL1
    player_piece  -18,    4, PLAYER_PIECE_PAL1

data_69_4029_PlayerFrame_110:
    player_frame_header   9, $1a, $28, data_69_4820_PlayerTiles + $0120
    player_piece  -19,   -8, PLAYER_PIECE_PAL0
    player_piece  -19,    0, PLAYER_PIECE_PAL0
    player_piece   -3,   -4, PLAYER_PIECE_PAL0
    player_piece   -8,    8, PLAYER_PIECE_PAL0
    player_piece   -3,    4, PLAYER_PIECE_PAL0
    player_piece  -23,   13, PLAYER_PIECE_PAL0
    player_piece  -34,   -7, PLAYER_PIECE_PAL1
    player_piece  -23,    1, PLAYER_PIECE_PAL1
    player_piece   -7,    1, PLAYER_PIECE_PAL1

data_69_4052_PlayerFrame_111:
    player_frame_header   8, $19, $22, data_69_4820_PlayerTiles + $0240
    player_piece  -19,   -7, PLAYER_PIECE_PAL0
    player_piece   -4,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,    7, PLAYER_PIECE_PAL0
    player_piece   -6,    4, PLAYER_PIECE_PAL0
    player_piece  -23,   -6, PLAYER_PIECE_PAL1
    player_piece  -22,   -1, PLAYER_PIECE_PAL1
    player_piece   -6,   -3, PLAYER_PIECE_PAL1
    player_piece  -21,    5, PLAYER_PIECE_PAL1

data_69_4077_PlayerFrame_112:
    player_frame_header   6, $18, $1c, data_69_4820_PlayerTiles + $0340
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    0, PLAYER_PIECE_PAL0
    player_piece  -22,   -4, PLAYER_PIECE_PAL1
    player_piece   -6,   -4, PLAYER_PIECE_PAL1
    player_piece  -22,    0, PLAYER_PIECE_PAL1
    player_piece   -6,    0, PLAYER_PIECE_PAL1

data_69_4094_PlayerFrame_113:
    player_frame_header   8, $19, $1c, data_69_4820_PlayerTiles + $0400
    player_piece  -16,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece   -5,   -4, PLAYER_PIECE_PAL0
    player_piece   -3,    4, PLAYER_PIECE_PAL0
    player_piece  -23,   -6, PLAYER_PIECE_PAL1
    player_piece   -7,   -6, PLAYER_PIECE_PAL1
    player_piece  -25,    2, PLAYER_PIECE_PAL1
    player_piece  -20,    2, PLAYER_PIECE_PAL1

data_69_40b9_PlayerFrame_114:
    player_frame_header   9, $1a, $1e, data_69_4820_PlayerTiles + $0500
    player_piece  -11,  -20, PLAYER_PIECE_PAL0
    player_piece   -8,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece   -3,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -20,  -12, PLAYER_PIECE_PAL1
    player_piece  -24,   -4, PLAYER_PIECE_PAL1
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece  -35,    2, PLAYER_PIECE_PAL1

data_69_40e2_PlayerFrame_115:
    player_frame_header   8, $21, $1d, data_69_4820_PlayerTiles + $0620
    player_piece  -29,   -9, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -13,   -8, PLAYER_PIECE_PAL0
    player_piece  -13,    0, PLAYER_PIECE_PAL0
    player_piece  -13,    5, PLAYER_PIECE_PAL0
    player_piece  -31,   -4, PLAYER_PIECE_PAL1
    player_piece  -31,    4, PLAYER_PIECE_PAL1
    player_piece  -15,   -1, PLAYER_PIECE_PAL1

data_69_4107_PlayerFrame_116:
    player_frame_header   8, $21, $1f, data_69_4820_PlayerTiles + $0720
    player_piece  -21,   -7, PLAYER_PIECE_PAL0
    player_piece  -12,    0, PLAYER_PIECE_PAL0
    player_piece  -24,    8, PLAYER_PIECE_PAL0
    player_piece   -8,    8, PLAYER_PIECE_PAL0
    player_piece  -31,   -4, PLAYER_PIECE_PAL1
    player_piece  -31,    4, PLAYER_PIECE_PAL1
    player_piece  -15,   -2, PLAYER_PIECE_PAL1
    player_piece  -28,    6, PLAYER_PIECE_PAL1

data_69_412c_PlayerFrame_117:
    player_frame_header   8, $20, $1d, data_69_4820_PlayerTiles + $0820
    player_piece  -28,  -10, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -12,   -7, PLAYER_PIECE_PAL0
    player_piece  -12,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -7, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -14,    3, PLAYER_PIECE_PAL1

data_69_4151_PlayerFrame_118:
    player_frame_header   8, $22, $1a, data_69_4820_PlayerTiles + $0920
    player_piece  -31,  -11, PLAYER_PIECE_PAL0
    player_piece  -31,    2, PLAYER_PIECE_PAL0
    player_piece  -15,   -9, PLAYER_PIECE_PAL0
    player_piece  -15,   -1, PLAYER_PIECE_PAL0
    player_piece  -32,   -6, PLAYER_PIECE_PAL1
    player_piece  -32,    2, PLAYER_PIECE_PAL1
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,    2, PLAYER_PIECE_PAL1

data_69_4176_PlayerFrame_119:
    player_frame_header   8, $20, $1d, data_69_4820_PlayerTiles + $0a20
    player_piece  -27,  -10, PLAYER_PIECE_PAL0
    player_piece  -27,    5, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -11,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -30,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,    4, PLAYER_PIECE_PAL1

data_69_419b_PlayerFrame_120:
    player_frame_header   7, $20, $1e, data_69_4820_PlayerTiles + $0b20
    player_piece  -19,  -11, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -14,    5, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -30,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -3, PLAYER_PIECE_PAL1

data_69_41bc_PlayerFrame_121:
    player_frame_header   8, $20, $1f, data_69_4820_PlayerTiles + $0c00
    player_piece  -18,   -7, PLAYER_PIECE_PAL0
    player_piece  -22,    1, PLAYER_PIECE_PAL0
    player_piece   -6,    0, PLAYER_PIECE_PAL0
    player_piece  -34,    9, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -29,    4, PLAYER_PIECE_PAL1
    player_piece  -13,    4, PLAYER_PIECE_PAL1

data_69_41e1_PlayerFrame_122:
    player_frame_header   8, $1f, $1c, data_69_4820_PlayerTiles + $0d00
    player_piece  -27,   -9, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL0
    player_piece  -11,   -6, PLAYER_PIECE_PAL0
    player_piece  -11,    2, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    3, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece  -13,    4, PLAYER_PIECE_PAL1

data_69_4206_PlayerFrame_123:
    player_frame_header   8, $21, $1b, data_69_4820_PlayerTiles + $0e00
    player_piece  -30,  -10, PLAYER_PIECE_PAL0
    player_piece  -31,    3, PLAYER_PIECE_PAL0
    player_piece  -14,   -6, PLAYER_PIECE_PAL0
    player_piece  -14,    2, PLAYER_PIECE_PAL0
    player_piece  -31,   -6, PLAYER_PIECE_PAL1
    player_piece  -31,    2, PLAYER_PIECE_PAL1
    player_piece  -15,   -3, PLAYER_PIECE_PAL1
    player_piece  -15,    3, PLAYER_PIECE_PAL1

data_69_422b_PlayerFrame_124:
    player_frame_header   8, $21, $1c, data_69_4820_PlayerTiles + $0f00
    player_piece  -27,  -10, PLAYER_PIECE_PAL0
    player_piece  -27,    4, PLAYER_PIECE_PAL0
    player_piece  -11,   -6, PLAYER_PIECE_PAL0
    player_piece  -11,    2, PLAYER_PIECE_PAL0
    player_piece  -31,   -5, PLAYER_PIECE_PAL1
    player_piece  -31,    3, PLAYER_PIECE_PAL1
    player_piece  -15,   -4, PLAYER_PIECE_PAL1
    player_piece  -15,    4, PLAYER_PIECE_PAL1

data_69_4250_PlayerFrame_125:
    player_frame_header   4, $21, $19, data_69_4820_PlayerTiles + $1000
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_69_4265_PlayerFrame_126:
    player_frame_header   4, $21, $18, data_69_4820_PlayerTiles + $1080
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_69_427a_PlayerFrame_127:
    player_frame_header   4, $21, $18, data_69_4820_PlayerTiles + $1100
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_69_428f_PlayerFrame_128:
    player_frame_header   4, $21, $18, data_69_4820_PlayerTiles + $1180
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_69_42a4_PlayerFrame_129:
    player_frame_header   4, $21, $18, data_69_4820_PlayerTiles + $1200
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_69_42b9_PlayerFrame_130:
    player_frame_header   4, $21, $18, data_69_4820_PlayerTiles + $1280
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_69_42ce_PlayerFrame_131:
    player_frame_header   4, $21, $18, data_69_4820_PlayerTiles + $1300
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_69_42e3_PlayerFrame_132:
    player_frame_header   8, $21, $1a, data_69_4820_PlayerTiles + $1380
    player_piece  -33,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,   -4, PLAYER_PIECE_PAL0
    player_piece   -9,   -8, PLAYER_PIECE_PAL0
    player_piece  -17,    0, PLAYER_PIECE_PAL0
    player_piece  -31,  -11, PLAYER_PIECE_PAL1
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece  -14,   -3, PLAYER_PIECE_PAL1
    player_piece  -24,    5, PLAYER_PIECE_PAL1

data_69_4308_PlayerFrame_133:
    player_frame_header   8, $21, $19, data_69_4820_PlayerTiles + $1480
    player_piece  -33,   -9, PLAYER_PIECE_PAL0
    player_piece  -17,   -9, PLAYER_PIECE_PAL0
    player_piece  -33,   -1, PLAYER_PIECE_PAL0
    player_piece  -17,   -1, PLAYER_PIECE_PAL0
    player_piece  -31,  -12, PLAYER_PIECE_PAL1
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -23,    4, PLAYER_PIECE_PAL1

data_69_432d_PlayerFrame_134:
    player_frame_header   9, $21, $19, data_69_4820_PlayerTiles + $1580
    player_piece  -33,  -10, PLAYER_PIECE_PAL0
    player_piece  -17,  -10, PLAYER_PIECE_PAL0
    player_piece  -32,   -2, PLAYER_PIECE_PAL0
    player_piece  -17,   -2, PLAYER_PIECE_PAL0
    player_piece  -37,  -18, PLAYER_PIECE_PAL1
    player_piece  -31,  -10, PLAYER_PIECE_PAL1
    player_piece  -15,  -10, PLAYER_PIECE_PAL1
    player_piece  -30,   -2, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_69_4356_PlayerFrame_135:
    player_frame_header   9, $1c, $1e, data_69_4820_PlayerTiles + $16a0
    player_piece  -23,  -10, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL0
    player_piece   -6,   -7, PLAYER_PIECE_PAL0
    player_piece   -6,    1, PLAYER_PIECE_PAL0
    player_piece   -6,    4, PLAYER_PIECE_PAL0
    player_piece  -26,  -12, PLAYER_PIECE_PAL1
    player_piece  -26,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,   -5, PLAYER_PIECE_PAL1
    player_piece  -19,    3, PLAYER_PIECE_PAL1

data_69_437f_PlayerFrame_136:
    player_frame_header   6, $17, $1e, data_69_4820_PlayerTiles + $17c0
    player_piece  -16,  -11, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece  -21,   -5, PLAYER_PIECE_PAL1
    player_piece  -21,    3, PLAYER_PIECE_PAL1
    player_piece   -5,   -3, PLAYER_PIECE_PAL1

data_69_439c_PlayerFrame_137:
    player_frame_header   6, $16, $1e, data_69_4820_PlayerTiles + $1880
    player_piece  -16,  -11, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece  -20,   -5, PLAYER_PIECE_PAL1
    player_piece  -21,    3, PLAYER_PIECE_PAL1
    player_piece   -4,   -3, PLAYER_PIECE_PAL1

data_69_43b9_PlayerFrame_138:
    player_frame_header   9, $1a, $1f, data_69_4820_PlayerTiles + $1940
    player_piece  -18,  -10, PLAYER_PIECE_PAL0
    player_piece  -19,   -2, PLAYER_PIECE_PAL0
    player_piece   -3,   -2, PLAYER_PIECE_PAL0
    player_piece  -19,    5, PLAYER_PIECE_PAL0
    player_piece   -3,    5, PLAYER_PIECE_PAL0
    player_piece  -19,  -10, PLAYER_PIECE_PAL1
    player_piece  -24,   -2, PLAYER_PIECE_PAL1
    player_piece   -8,   -2, PLAYER_PIECE_PAL1
    player_piece  -34,    5, PLAYER_PIECE_PAL1

data_69_43e2_PlayerFrame_139:
    player_frame_header   8, $1a, $1d, data_69_4820_PlayerTiles + $1a60
    player_piece  -17,   -9, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -1, PLAYER_PIECE_PAL0
    player_piece  -26,    7, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL1
    player_piece   -8,   -4, PLAYER_PIECE_PAL1
    player_piece  -35,    5, PLAYER_PIECE_PAL1
    player_piece   -7,    4, PLAYER_PIECE_PAL1

data_69_4407_PlayerFrame_140:
    player_frame_header   9, $1a, $21, data_69_4820_PlayerTiles + $1b60
    player_piece  -20,  -14, PLAYER_PIECE_PAL0
    player_piece  -16,   -6, PLAYER_PIECE_PAL0
    player_piece  -19,    2, PLAYER_PIECE_PAL0
    player_piece  -28,   10, PLAYER_PIECE_PAL0
    player_piece   -3,    2, PLAYER_PIECE_PAL0
    player_piece  -23,   -3, PLAYER_PIECE_PAL1
    player_piece  -34,    5, PLAYER_PIECE_PAL1
    player_piece   -7,   -4, PLAYER_PIECE_PAL1
    player_piece   -7,    4, PLAYER_PIECE_PAL1

data_69_4430_PlayerFrame_141:
    player_frame_header   8, $20, $1d, data_69_4820_PlayerTiles + $1c80
    player_piece  -26,   -4, PLAYER_PIECE_PAL0
    player_piece  -26,    2, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -10,    2, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -30,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -14,    2, PLAYER_PIECE_PAL1

data_69_4455_PlayerFrame_142:
    player_frame_header   8, $20, $1c, data_69_4820_PlayerTiles + $1d80
    player_piece  -26,   -4, PLAYER_PIECE_PAL0
    player_piece  -36,    1, PLAYER_PIECE_PAL0
    player_piece  -10,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,    1, PLAYER_PIECE_PAL1

data_69_447a_PlayerFrame_143:
    player_frame_header   7, $20, $1c, data_69_4820_PlayerTiles + $1e80
    player_piece  -26,   -4, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -14,    1, PLAYER_PIECE_PAL1

data_69_449b_PlayerFrame_144:
    player_frame_header   8, $1f, $1c, data_69_4820_PlayerTiles + $1f60
    player_piece  -25,   -4, PLAYER_PIECE_PAL0
    player_piece  -25,    1, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece   -9,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_69_44c0_PlayerFrame_145:
    player_frame_header   8, $20, $1c, data_69_4820_PlayerTiles + $2060
    player_piece  -26,   -4, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -10,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -6, PLAYER_PIECE_PAL1
    player_piece  -14,    1, PLAYER_PIECE_PAL1

data_69_44e5_PlayerFrame_146:
    player_frame_header   8, $20, $1b, data_69_4820_PlayerTiles + $2160
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -36,    0, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -10,    0, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -30,    0, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -14,    0, PLAYER_PIECE_PAL1

data_69_450a_PlayerFrame_147:
    player_frame_header   7, $20, $1c, data_69_4820_PlayerTiles + $2260
    player_piece  -26,   -4, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece  -10,   -1, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -14,    1, PLAYER_PIECE_PAL1

data_69_452b_PlayerFrame_148:
    player_frame_header   8, $1f, $1c, data_69_4820_PlayerTiles + $2340
    player_piece  -25,   -4, PLAYER_PIECE_PAL0
    player_piece  -25,    1, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece   -9,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_69_4550_PlayerFrame_149:
    player_frame_header   6, $1f, $1d, data_69_4820_PlayerTiles + $2440
    player_piece  -16,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    2, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece  -13,    2, PLAYER_PIECE_PAL1

data_69_456d_PlayerFrame_150:
    player_frame_header   6, $1f, $1c, data_69_4820_PlayerTiles + $2500
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -4, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_69_458a_PlayerFrame_151:
    player_frame_header   6, $1f, $1c, data_69_4820_PlayerTiles + $25c0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_69_45a7_PlayerFrame_152:
    player_frame_header   6, $1e, $1c, data_69_4820_PlayerTiles + $2680
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    1, PLAYER_PIECE_PAL0
    player_piece  -28,   -5, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -12,   -5, PLAYER_PIECE_PAL1
    player_piece  -12,    1, PLAYER_PIECE_PAL1

data_69_45c4_PlayerFrame_153:
    player_frame_header   6, $1f, $1c, data_69_4820_PlayerTiles + $2740
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -6, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_69_45e1_PlayerFrame_154:
    player_frame_header   6, $1f, $1b, data_69_4820_PlayerTiles + $2800
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -21,    0, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    0, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -13,    0, PLAYER_PIECE_PAL1

data_69_45fe_PlayerFrame_155:
    player_frame_header   6, $1f, $1c, data_69_4820_PlayerTiles + $28c0
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_69_461b_PlayerFrame_156:
    player_frame_header   6, $1e, $1c, data_69_4820_PlayerTiles + $2980
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -28,   -5, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -12,   -5, PLAYER_PIECE_PAL1
    player_piece  -12,    1, PLAYER_PIECE_PAL1

data_69_4638_PlayerFrame_157:
    player_frame_header   9, $1f, $28, data_69_4820_PlayerTiles + $2a40
    player_piece  -28,  -11, PLAYER_PIECE_PAL0
    player_piece  -35,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL0
    player_piece  -12,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -29,   -6, PLAYER_PIECE_PAL1
    player_piece  -29,    2, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece  -13,    4, PLAYER_PIECE_PAL1

data_69_4661_PlayerFrame_158:
    player_frame_header   9, $20, $20, data_69_4820_PlayerTiles + $2b60
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -10,    2, PLAYER_PIECE_PAL0
    player_piece  -30,   -7, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,    2, PLAYER_PIECE_PAL1

data_69_468a_PlayerFrame_159:
    player_frame_header   9, $20, $20, data_69_4820_PlayerTiles + $2c80
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -10,    2, PLAYER_PIECE_PAL0
    player_piece  -30,   -7, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,    2, PLAYER_PIECE_PAL1

data_69_46b3_PlayerFrame_160:
    player_frame_header   9, $20, $20, data_69_4820_PlayerTiles + $2da0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -10,    2, PLAYER_PIECE_PAL0
    player_piece  -30,   -7, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,    2, PLAYER_PIECE_PAL1

data_69_46dc_PlayerFrame_161:
    player_frame_header   8, $20, $20, data_69_4820_PlayerTiles + $2ec0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,    3, PLAYER_PIECE_PAL0
    player_piece  -30,   -7, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,    4, PLAYER_PIECE_PAL1

data_69_4701_PlayerFrame_162:
    player_frame_header   9, $20, $20, data_69_4820_PlayerTiles + $2fc0
    player_piece  -16,  -14, PLAYER_PIECE_PAL0
    player_piece  -26,   -6, PLAYER_PIECE_PAL0
    player_piece  -10,   -6, PLAYER_PIECE_PAL0
    player_piece  -26,    2, PLAYER_PIECE_PAL0
    player_piece  -10,    2, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -14,   -6, PLAYER_PIECE_PAL1
    player_piece  -30,    2, PLAYER_PIECE_PAL1
    player_piece  -14,    2, PLAYER_PIECE_PAL1

data_69_472a_PlayerFrame_163:
    player_frame_header   8, $20, $20, data_69_4820_PlayerTiles + $30e0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -10,   -7, PLAYER_PIECE_PAL0
    player_piece  -20,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -30,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,    4, PLAYER_PIECE_PAL1

data_69_474f_PlayerFrame_164:
    player_frame_header   9, $20, $23, data_69_4820_PlayerTiles + $31e0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,  -11, PLAYER_PIECE_PAL0
    player_piece  -14,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    5, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -30,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -14,    4, PLAYER_PIECE_PAL1

data_69_4778_PlayerFrame_165:
    player_frame_header   6, $20, $24, data_69_4820_PlayerTiles + $3300
    player_piece  -19,  -14, PLAYER_PIECE_PAL0
    player_piece  -32,   -6, PLAYER_PIECE_PAL0
    player_piece  -32,    2, PLAYER_PIECE_PAL0
    player_piece  -19,    6, PLAYER_PIECE_PAL0
    player_piece  -40,   -6, PLAYER_PIECE_PAL1
    player_piece  -40,    2, PLAYER_PIECE_PAL1

data_69_4795_PlayerFrame_166:
    player_frame_header   5, $1f, $26, data_69_4820_PlayerTiles + $33c0
    player_piece  -25,  -15, PLAYER_PIECE_PAL0
    player_piece  -38,   -7, PLAYER_PIECE_PAL0
    player_piece  -38,    1, PLAYER_PIECE_PAL0
    player_piece  -40,    9, PLAYER_PIECE_PAL0
    player_piece  -43,   -3, PLAYER_PIECE_PAL1

data_69_47ae_PlayerFrame_167:
    player_frame_header   3, $1e, $20, data_69_4820_PlayerTiles + $3460
    player_piece  -40,  -14, PLAYER_PIECE_PAL0
    player_piece  -37,   -6, PLAYER_PIECE_PAL0
    player_piece  -37,    2, PLAYER_PIECE_PAL0

data_69_47bf_PlayerFrame_168:
    player_frame_header   2, $1e, $1b, data_69_4820_PlayerTiles + $34c0
    player_piece  -37,   -6, PLAYER_PIECE_PAL0
    player_piece  -40,   -3, PLAYER_PIECE_PAL0

data_69_47cc_PlayerFrame_169:
    player_frame_header   9, $1d, $19, data_69_4820_PlayerTiles + $3500
    player_piece  -27,  -15, PLAYER_PIECE_PAL0
    player_piece  -23,   -7, PLAYER_PIECE_PAL0
    player_piece   -7,   -7, PLAYER_PIECE_PAL0
    player_piece  -23,    1, PLAYER_PIECE_PAL0
    player_piece   -7,    1, PLAYER_PIECE_PAL0
    player_piece  -27,   -7, PLAYER_PIECE_PAL1
    player_piece  -11,   -7, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -11,    1, PLAYER_PIECE_PAL1

data_69_47f5_PlayerFrame_170:
    player_frame_header   9, $1f, $20, data_69_4820_PlayerTiles + $3620
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -10,    2, PLAYER_PIECE_PAL0
    player_piece  -29,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece  -13,    2, PLAYER_PIECE_PAL1

    ds   $4820 - @, 0                    ; the bank pads to a 16-byte boundary here
data_69_4820_PlayerTiles:
; INCBINd by main.asm - see the header above
