; ==================================================================
; Bank $76. Gex's animation frames 1 to 63 of PLAYER_GFX_SET_MYSTERY_TV.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $482a, then 888 tiles of graphics from $4830 to $7faf, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/sprite_data/bank7F.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_76_4000_PlayerFrame_001:
    player_frame_header   7, $1f, $22, data_76_4830_PlayerTiles + $0000
    player_piece  -21,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    3, PLAYER_PIECE_PAL0
    player_piece  -32,    8, PLAYER_PIECE_PAL0
    player_piece   -8,  -13, PLAYER_PIECE_PAL0
    player_piece   -8,    3, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL1
    player_piece  -39,    8, PLAYER_PIECE_PAL1

data_76_4021_PlayerFrame_002:
    player_frame_header   7, $1e, $22, data_76_4830_PlayerTiles + $00e0
    player_piece  -17,  -11, PLAYER_PIECE_PAL0
    player_piece  -17,   -3, PLAYER_PIECE_PAL0
    player_piece  -17,    5, PLAYER_PIECE_PAL0
    player_piece  -33,    0, PLAYER_PIECE_PAL0
    player_piece  -34,    8, PLAYER_PIECE_PAL0
    player_piece  -27,    2, PLAYER_PIECE_PAL1
    player_piece  -39,    8, PLAYER_PIECE_PAL1

data_76_4042_PlayerFrame_003:
    player_frame_header   7, $1d, $22, data_76_4830_PlayerTiles + $01c0
    player_piece   -8,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece  -27,    7, PLAYER_PIECE_PAL0
    player_piece   -5,   -1, PLAYER_PIECE_PAL0
    player_piece   -5,    7, PLAYER_PIECE_PAL0
    player_piece  -29,    3, PLAYER_PIECE_PAL1
    player_piece  -38,    8, PLAYER_PIECE_PAL1

data_76_4063_PlayerFrame_004:
    player_frame_header   7, $1d, $23, data_76_4830_PlayerTiles + $02a0
    player_piece  -17,  -10, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,    6, PLAYER_PIECE_PAL0
    player_piece  -32,    4, PLAYER_PIECE_PAL0
    player_piece  -33,   12, PLAYER_PIECE_PAL0
    player_piece  -25,   -1, PLAYER_PIECE_PAL1
    player_piece  -36,    6, PLAYER_PIECE_PAL1

data_76_4084_PlayerFrame_005:
    player_frame_header   8, $1c, $23, data_76_4830_PlayerTiles + $0380
    player_piece  -11,  -11, PLAYER_PIECE_PAL0
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece  -25,    5, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece   -3,   -3, PLAYER_PIECE_PAL0
    player_piece   -2,    5, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL1
    player_piece  -35,    6, PLAYER_PIECE_PAL1

data_76_40a9_PlayerFrame_006:
    player_frame_header   6, $1d, $23, data_76_4830_PlayerTiles + $0480
    player_piece  -16,  -12, PLAYER_PIECE_PAL0
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -22,    1, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL1
    player_piece  -36,    7, PLAYER_PIECE_PAL1

data_76_40c6_PlayerFrame_007:
    player_frame_header   8, $1e, $23, data_76_4830_PlayerTiles + $0540
    player_piece   -9,  -13, PLAYER_PIECE_PAL0
    player_piece  -18,   -5, PLAYER_PIECE_PAL0
    player_piece  -23,    3, PLAYER_PIECE_PAL0
    player_piece  -34,    9, PLAYER_PIECE_PAL0
    player_piece   -2,   -5, PLAYER_PIECE_PAL0
    player_piece  -17,    3, PLAYER_PIECE_PAL0
    player_piece  -27,   -1, PLAYER_PIECE_PAL1
    player_piece  -37,    7, PLAYER_PIECE_PAL1

data_76_40eb_PlayerFrame_008:
    player_frame_header   8, $1f, $23, data_76_4830_PlayerTiles + $0640
    player_piece   -9,  -13, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece  -24,    5, PLAYER_PIECE_PAL0
    player_piece  -35,   13, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL0
    player_piece   -8,    4, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL1
    player_piece  -38,    7, PLAYER_PIECE_PAL1

data_76_4110_PlayerFrame_009:
    player_frame_header   8, $20, $22, data_76_4830_PlayerTiles + $0740
    player_piece  -21,   -5, PLAYER_PIECE_PAL0
    player_piece  -25,    3, PLAYER_PIECE_PAL0
    player_piece  -31,    8, PLAYER_PIECE_PAL0
    player_piece   -8,  -13, PLAYER_PIECE_PAL0
    player_piece   -9,    3, PLAYER_PIECE_PAL0
    player_piece   -9,    8, PLAYER_PIECE_PAL0
    player_piece  -29,   -1, PLAYER_PIECE_PAL1
    player_piece  -39,    7, PLAYER_PIECE_PAL1

data_76_4135_PlayerFrame_010:
    player_frame_header   7, $1f, $22, data_76_4830_PlayerTiles + $0840
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,    4, PLAYER_PIECE_PAL0
    player_piece  -35,    8, PLAYER_PIECE_PAL0
    player_piece   -8,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,    4, PLAYER_PIECE_PAL0
    player_piece  -29,   -1, PLAYER_PIECE_PAL1
    player_piece  -38,    7, PLAYER_PIECE_PAL1

data_76_4156_PlayerFrame_011:
    player_frame_header   7, $1d, $23, data_76_4830_PlayerTiles + $0920
    player_piece  -17,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -17,    7, PLAYER_PIECE_PAL0
    player_piece  -32,    1, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -27,    0, PLAYER_PIECE_PAL1
    player_piece  -37,    8, PLAYER_PIECE_PAL1

data_76_4177_PlayerFrame_012:
    player_frame_header   7, $1c, $23, data_76_4830_PlayerTiles + $0a00
    player_piece  -17,  -10, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,    6, PLAYER_PIECE_PAL0
    player_piece  -32,    4, PLAYER_PIECE_PAL0
    player_piece  -32,    9, PLAYER_PIECE_PAL0
    player_piece  -31,    2, PLAYER_PIECE_PAL1
    player_piece  -36,    9, PLAYER_PIECE_PAL1

data_76_4198_PlayerFrame_013:
    player_frame_header   6, $1c, $23, data_76_4830_PlayerTiles + $0ae0
    player_piece  -19,  -10, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -26,    3, PLAYER_PIECE_PAL0
    player_piece  -32,   11, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL1
    player_piece  -35,    7, PLAYER_PIECE_PAL1

data_76_41b5_PlayerFrame_014:
    player_frame_header   7, $1d, $23, data_76_4830_PlayerTiles + $0ba0
    player_piece  -16,  -12, PLAYER_PIECE_PAL0
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -18,    4, PLAYER_PIECE_PAL0
    player_piece  -32,    0, PLAYER_PIECE_PAL0
    player_piece  -33,    8, PLAYER_PIECE_PAL0
    player_piece  -30,    2, PLAYER_PIECE_PAL1
    player_piece  -37,    9, PLAYER_PIECE_PAL1

data_76_41d6_PlayerFrame_015:
    player_frame_header   8, $1d, $23, data_76_4830_PlayerTiles + $0c80
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece  -22,    4, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece   -3,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    4, PLAYER_PIECE_PAL0
    player_piece  -28,    2, PLAYER_PIECE_PAL1
    player_piece  -37,    9, PLAYER_PIECE_PAL1

data_76_41fb_PlayerFrame_016:
    player_frame_header   8, $1e, $22, data_76_4830_PlayerTiles + $0d80
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece  -23,    4, PLAYER_PIECE_PAL0
    player_piece  -23,    8, PLAYER_PIECE_PAL0
    player_piece   -7,    4, PLAYER_PIECE_PAL0
    player_piece   -7,    8, PLAYER_PIECE_PAL0
    player_piece  -27,    0, PLAYER_PIECE_PAL1
    player_piece  -38,    8, PLAYER_PIECE_PAL1

data_76_4220_PlayerFrame_017:
    player_frame_header   8, $1f, $20, data_76_4830_PlayerTiles + $0e80
    player_piece   -9,  -14, PLAYER_PIECE_PAL0
    player_piece  -19,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,   -6, PLAYER_PIECE_PAL0
    player_piece  -24,    3, PLAYER_PIECE_PAL0
    player_piece   -8,    3, PLAYER_PIECE_PAL0
    player_piece  -35,   11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL1
    player_piece  -33,    5, PLAYER_PIECE_PAL1

data_76_4245_PlayerFrame_018:
    player_frame_header   6, $1f, $21, data_76_4830_PlayerTiles + $0f80
    player_piece  -11,  -16, PLAYER_PIECE_PAL0
    player_piece  -20,   -8, PLAYER_PIECE_PAL0
    player_piece  -23,    0, PLAYER_PIECE_PAL0
    player_piece  -24,    8, PLAYER_PIECE_PAL0
    player_piece  -32,    0, PLAYER_PIECE_PAL1
    player_piece  -39,    8, PLAYER_PIECE_PAL1

data_76_4262_PlayerFrame_019:
    player_frame_header   7, $1f, $20, data_76_4830_PlayerTiles + $1040
    player_piece  -14,  -15, PLAYER_PIECE_PAL0
    player_piece  -25,   -7, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece  -27,    8, PLAYER_PIECE_PAL0
    player_piece  -23,   -7, PLAYER_PIECE_PAL0
    player_piece  -30,   -1, PLAYER_PIECE_PAL1
    player_piece  -39,    7, PLAYER_PIECE_PAL1

data_76_4283_PlayerFrame_020:
    player_frame_header   8, $1f, $20, data_76_4830_PlayerTiles + $1120
    player_piece  -21,  -12, PLAYER_PIECE_PAL0
    player_piece  -23,   -4, PLAYER_PIECE_PAL0
    player_piece  -23,    4, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL0
    player_piece  -19,    5, PLAYER_PIECE_PAL0
    player_piece  -35,    7, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL1
    player_piece  -39,    8, PLAYER_PIECE_PAL1

data_76_42a8_PlayerFrame_021:
    player_frame_header   8, $20, $20, data_76_4830_PlayerTiles + $1220
    player_piece  -21,  -12, PLAYER_PIECE_PAL0
    player_piece  -22,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,   -2, PLAYER_PIECE_PAL0
    player_piece  -18,    6, PLAYER_PIECE_PAL0
    player_piece  -35,    6, PLAYER_PIECE_PAL0
    player_piece  -38,   14, PLAYER_PIECE_PAL0
    player_piece  -29,   -1, PLAYER_PIECE_PAL1
    player_piece  -40,    6, PLAYER_PIECE_PAL1

data_76_42cd_PlayerFrame_022:
    player_frame_header   8, $21, $20, data_76_4830_PlayerTiles + $1320
    player_piece  -22,  -15, PLAYER_PIECE_PAL0
    player_piece  -19,   -7, PLAYER_PIECE_PAL0
    player_piece  -17,    1, PLAYER_PIECE_PAL0
    player_piece  -35,   -5, PLAYER_PIECE_PAL0
    player_piece  -36,    3, PLAYER_PIECE_PAL0
    player_piece  -39,   11, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -41,    2, PLAYER_PIECE_PAL1

data_76_42f2_PlayerFrame_023:
    player_frame_header   8, $1e, $20, data_76_4830_PlayerTiles + $1420
    player_piece  -11,  -19, PLAYER_PIECE_PAL0
    player_piece  -22,  -11, PLAYER_PIECE_PAL0
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    5, PLAYER_PIECE_PAL0
    player_piece   -6,    5, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -38,    5, PLAYER_PIECE_PAL1

data_76_4317_PlayerFrame_024:
    player_frame_header   8, $1c, $20, data_76_4830_PlayerTiles + $1520
    player_piece  -10,  -17, PLAYER_PIECE_PAL0
    player_piece  -16,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,    3, PLAYER_PIECE_PAL0
    player_piece   -5,   -1, PLAYER_PIECE_PAL0
    player_piece  -18,    3, PLAYER_PIECE_PAL0
    player_piece  -28,   -6, PLAYER_PIECE_PAL1
    player_piece  -36,    2, PLAYER_PIECE_PAL1

data_76_433c_PlayerFrame_025:
    player_frame_header   8, $1f, $1d, data_76_4830_PlayerTiles + $1620
    player_piece  -29,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    3, PLAYER_PIECE_PAL0
    player_piece  -13,   -7, PLAYER_PIECE_PAL0
    player_piece  -13,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -29,   -6, PLAYER_PIECE_PAL1
    player_piece  -31,    2, PLAYER_PIECE_PAL1

data_76_4361_PlayerFrame_026:
    player_frame_header   8, $20, $1d, data_76_4830_PlayerTiles + $1720
    player_piece  -33,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -39,    5, PLAYER_PIECE_PAL0
    player_piece  -16,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    9, PLAYER_PIECE_PAL0
    player_piece  -29,   -6, PLAYER_PIECE_PAL1
    player_piece  -28,   -3, PLAYER_PIECE_PAL1

data_76_4386_PlayerFrame_027:
    player_frame_header   8, $20, $1d, data_76_4830_PlayerTiles + $1820
    player_piece  -27,  -12, PLAYER_PIECE_PAL0
    player_piece  -26,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    4, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -11,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    9, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -29,   -4, PLAYER_PIECE_PAL1

data_76_43ab_PlayerFrame_028:
    player_frame_header   7, $1c, $1d, data_76_4830_PlayerTiles + $1920
    player_piece  -20,  -11, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    3, PLAYER_PIECE_PAL0
    player_piece   -6,   -6, PLAYER_PIECE_PAL0
    player_piece   -6,    2, PLAYER_PIECE_PAL0
    player_piece  -27,   -7, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1

data_76_43cc_PlayerFrame_029:
    player_frame_header   6, $18, $1d, data_76_4830_PlayerTiles + $1a00
    player_piece  -16,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    3, PLAYER_PIECE_PAL0
    player_piece   -2,   -3, PLAYER_PIECE_PAL0
    player_piece  -23,   -8, PLAYER_PIECE_PAL1
    player_piece  -25,    0, PLAYER_PIECE_PAL1

data_76_43e9_PlayerFrame_030:
    player_frame_header   8, $20, $1d, data_76_4830_PlayerTiles + $1ac0
    player_piece  -26,   -9, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -15,    3, PLAYER_PIECE_PAL0
    player_piece  -10,   -6, PLAYER_PIECE_PAL0
    player_piece  -10,    2, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -32,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1

data_76_440e_PlayerFrame_031:
    player_frame_header   8, $20, $1d, data_76_4830_PlayerTiles + $1bc0
    player_piece  -27,  -12, PLAYER_PIECE_PAL0
    player_piece  -26,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    3, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -32,    2, PLAYER_PIECE_PAL1

data_76_4433_PlayerFrame_032:
    player_frame_header   7, $20, $20, data_76_4830_PlayerTiles + $1cc0
    player_piece  -16,  -12, PLAYER_PIECE_PAL0
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece  -32,   -5, PLAYER_PIECE_PAL0
    player_piece  -36,    3, PLAYER_PIECE_PAL0
    player_piece  -27,   -4, PLAYER_PIECE_PAL1
    player_piece  -41,   -2, PLAYER_PIECE_PAL1

data_76_4454_PlayerFrame_033:
    player_frame_header   8, $20, $21, data_76_4830_PlayerTiles + $1da0
    player_piece  -19,  -12, PLAYER_PIECE_PAL0
    player_piece  -26,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -41,    4, PLAYER_PIECE_PAL1
    player_piece  -14,   -3, PLAYER_PIECE_PAL1

data_76_4479_PlayerFrame_034:
    player_frame_header   8, $1d, $1f, data_76_4830_PlayerTiles + $1ea0
    player_piece  -21,  -11, PLAYER_PIECE_PAL0
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    3, PLAYER_PIECE_PAL0
    player_piece   -7,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -27,   -4, PLAYER_PIECE_PAL1
    player_piece  -38,    3, PLAYER_PIECE_PAL1
    player_piece  -11,   -3, PLAYER_PIECE_PAL1

data_76_449e_PlayerFrame_035:
    player_frame_header   7, $1a, $1d, data_76_4830_PlayerTiles + $1fa0
    player_piece  -21,  -11, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece   -5,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece  -24,   -6, PLAYER_PIECE_PAL1
    player_piece  -23,   -3, PLAYER_PIECE_PAL1

data_76_44bf_PlayerFrame_036:
    player_frame_header   6, $19, $1c, data_76_4830_PlayerTiles + $2080
    player_piece  -23,  -10, PLAYER_PIECE_PAL0
    player_piece  -16,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece   -5,   -1, PLAYER_PIECE_PAL0
    player_piece  -23,   -6, PLAYER_PIECE_PAL1
    player_piece  -32,    2, PLAYER_PIECE_PAL1

data_76_44dc_PlayerFrame_037:
    player_frame_header   6, $18, $1b, data_76_4830_PlayerTiles + $2140
    player_piece  -21,  -10, PLAYER_PIECE_PAL0
    player_piece  -22,   -2, PLAYER_PIECE_PAL0
    player_piece   -6,   -7, PLAYER_PIECE_PAL0
    player_piece   -6,   -1, PLAYER_PIECE_PAL0
    player_piece  -23,   -7, PLAYER_PIECE_PAL1
    player_piece  -25,   -1, PLAYER_PIECE_PAL1

data_76_44f9_PlayerFrame_038:
    player_frame_header   6, $16, $1b, data_76_4830_PlayerTiles + $2200
    player_piece  -20,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece   -4,   -5, PLAYER_PIECE_PAL0
    player_piece   -4,   -1, PLAYER_PIECE_PAL0
    player_piece  -22,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,   -1, PLAYER_PIECE_PAL1

data_76_4516_PlayerFrame_039:
    player_frame_header   5, $15, $1b, data_76_4830_PlayerTiles + $22c0
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL1
    player_piece  -27,   -1, PLAYER_PIECE_PAL1

data_76_452f_PlayerFrame_040:
    player_frame_header   5, $15, $1b, data_76_4830_PlayerTiles + $2360
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL1
    player_piece  -27,   -1, PLAYER_PIECE_PAL1

data_76_4548_PlayerFrame_041:
    player_frame_header   5, $15, $1b, data_76_4830_PlayerTiles + $2400
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL1
    player_piece  -27,   -1, PLAYER_PIECE_PAL1

data_76_4561_PlayerFrame_042:
    player_frame_header   8, $1e, $23, data_76_4830_PlayerTiles + $24a0
    player_piece  -23,  -16, PLAYER_PIECE_PAL0
    player_piece  -23,   -8, PLAYER_PIECE_PAL0
    player_piece   -7,  -15, PLAYER_PIECE_PAL0
    player_piece  -17,    0, PLAYER_PIECE_PAL0
    player_piece   -7,   -4, PLAYER_PIECE_PAL0
    player_piece   -1,    4, PLAYER_PIECE_PAL0
    player_piece  -28,  -13, PLAYER_PIECE_PAL1
    player_piece  -26,   -8, PLAYER_PIECE_PAL1

data_76_4586_PlayerFrame_043:
    player_frame_header   7, $1e, $22, data_76_4830_PlayerTiles + $25a0
    player_piece  -23,  -14, PLAYER_PIECE_PAL0
    player_piece  -23,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece   -7,   -9, PLAYER_PIECE_PAL0
    player_piece  -28,  -10, PLAYER_PIECE_PAL1
    player_piece  -26,   -2, PLAYER_PIECE_PAL1
    player_piece  -12,   -7, PLAYER_PIECE_PAL1

data_76_45a7_PlayerFrame_044:
    player_frame_header   6, $1f, $25, data_76_4830_PlayerTiles + $2680
    player_piece  -18,   -8, PLAYER_PIECE_PAL0
    player_piece  -16,    0, PLAYER_PIECE_PAL0
    player_piece  -33,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -26,   -3, PLAYER_PIECE_PAL1
    player_piece  -30,   -1, PLAYER_PIECE_PAL1

data_76_45c4_PlayerFrame_045:
    player_frame_header   7, $1f, $26, data_76_4830_PlayerTiles + $2740
    player_piece  -19,  -10, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -32,   -2, PLAYER_PIECE_PAL0
    player_piece  -20,    6, PLAYER_PIECE_PAL0
    player_piece  -36,    6, PLAYER_PIECE_PAL0
    player_piece  -26,   -2, PLAYER_PIECE_PAL1
    player_piece  -32,    0, PLAYER_PIECE_PAL1

data_76_45e5_PlayerFrame_046:
    player_frame_header   8, $1e, $30, data_76_4830_PlayerTiles + $2820
    player_piece  -10,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece   -2,   -3, PLAYER_PIECE_PAL0
    player_piece  -23,    5, PLAYER_PIECE_PAL0
    player_piece   -7,    5, PLAYER_PIECE_PAL0
    player_piece  -27,   13, PLAYER_PIECE_PAL0
    player_piece  -27,    5, PLAYER_PIECE_PAL1
    player_piece  -38,   13, PLAYER_PIECE_PAL1

data_76_460a_PlayerFrame_047:
    player_frame_header   8, $22, $2b, data_76_4830_PlayerTiles + $2920
    player_piece  -27,   -7, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece  -10,  -14, PLAYER_PIECE_PAL0
    player_piece  -11,   -6, PLAYER_PIECE_PAL0
    player_piece  -11,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   10, PLAYER_PIECE_PAL0
    player_piece  -32,   -4, PLAYER_PIECE_PAL1
    player_piece  -30,   -2, PLAYER_PIECE_PAL1

data_76_462f_PlayerFrame_048:
    player_frame_header   7, $20, $2a, data_76_4830_PlayerTiles + $2a20
    player_piece  -25,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece   -9,  -11, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,    5, PLAYER_PIECE_PAL0
    player_piece  -30,   -8, PLAYER_PIECE_PAL1
    player_piece  -28,   -3, PLAYER_PIECE_PAL1

data_76_4650_PlayerFrame_049:
    player_frame_header   7, $1f, $2b, data_76_4830_PlayerTiles + $2b00
    player_piece  -24,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece   -8,  -10, PLAYER_PIECE_PAL0
    player_piece  -24,    5, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,   -9, PLAYER_PIECE_PAL1
    player_piece  -26,   -4, PLAYER_PIECE_PAL1

data_76_4671_PlayerFrame_050:
    player_frame_header   8, $1f, $30, data_76_4830_PlayerTiles + $2be0
    player_piece  -24,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece   -8,   -7, PLAYER_PIECE_PAL0
    player_piece  -26,    5, PLAYER_PIECE_PAL0
    player_piece  -27,   13, PLAYER_PIECE_PAL0
    player_piece   -8,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -8, PLAYER_PIECE_PAL1
    player_piece  -27,   -3, PLAYER_PIECE_PAL1

data_76_4696_PlayerFrame_051:
    player_frame_header   7, $1e, $30, data_76_4830_PlayerTiles + $2ce0
    player_piece  -19,  -11, PLAYER_PIECE_PAL0
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece  -35,   -8, PLAYER_PIECE_PAL0
    player_piece  -27,    0, PLAYER_PIECE_PAL0
    player_piece  -28,    8, PLAYER_PIECE_PAL0
    player_piece  -28,   -8, PLAYER_PIECE_PAL1
    player_piece  -28,    0, PLAYER_PIECE_PAL1

data_76_46b7_PlayerFrame_052:
    player_frame_header   8, $1e, $2e, data_76_4830_PlayerTiles + $2dc0
    player_piece  -24,  -13, PLAYER_PIECE_PAL0
    player_piece  -23,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,    3, PLAYER_PIECE_PAL0
    player_piece  -26,    7, PLAYER_PIECE_PAL0
    player_piece   -7,   -2, PLAYER_PIECE_PAL0
    player_piece  -28,   -8, PLAYER_PIECE_PAL1
    player_piece  -27,    0, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1

data_76_46dc_PlayerFrame_053:
    player_frame_header   7, $1d, $2e, data_76_4830_PlayerTiles + $2ec0
    player_piece  -24,  -12, PLAYER_PIECE_PAL0
    player_piece  -22,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,    0, PLAYER_PIECE_PAL0
    player_piece  -26,    8, PLAYER_PIECE_PAL0
    player_piece  -27,   -9, PLAYER_PIECE_PAL1
    player_piece  -25,   -4, PLAYER_PIECE_PAL1
    player_piece   -9,   -4, PLAYER_PIECE_PAL1

data_76_46fd_PlayerFrame_054:
    player_frame_header   6, $14, $2e, data_76_4830_PlayerTiles + $2fa0
    player_piece  -18,  -12, PLAYER_PIECE_PAL0
    player_piece  -18,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    4, PLAYER_PIECE_PAL0
    player_piece  -23,    7, PLAYER_PIECE_PAL0
    player_piece  -20,  -10, PLAYER_PIECE_PAL1
    player_piece  -18,   -2, PLAYER_PIECE_PAL1

data_76_471a_PlayerFrame_055:
    player_frame_header   6, $23, $27, data_76_4830_PlayerTiles + $3060
    player_piece  -29,   -9, PLAYER_PIECE_PAL0
    player_piece  -32,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -8, PLAYER_PIECE_PAL0
    player_piece  -16,    0, PLAYER_PIECE_PAL0
    player_piece  -33,   -7, PLAYER_PIECE_PAL1
    player_piece  -32,   -3, PLAYER_PIECE_PAL1

data_76_4737_PlayerFrame_056:
    player_frame_header   7, $23, $27, data_76_4830_PlayerTiles + $3120
    player_piece  -29,   -9, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL0
    player_piece  -13,   -8, PLAYER_PIECE_PAL0
    player_piece  -12,    0, PLAYER_PIECE_PAL0
    player_piece  -33,   -7, PLAYER_PIECE_PAL1
    player_piece  -31,    0, PLAYER_PIECE_PAL1
    player_piece  -17,   -3, PLAYER_PIECE_PAL1

data_76_4758_PlayerFrame_057:
    player_frame_header   6, $24, $28, data_76_4830_PlayerTiles + $3200
    player_piece  -23,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece  -37,   -6, PLAYER_PIECE_PAL0
    player_piece  -34,    2, PLAYER_PIECE_PAL0
    player_piece  -31,   -7, PLAYER_PIECE_PAL1
    player_piece  -34,   -5, PLAYER_PIECE_PAL1

data_76_4775_PlayerFrame_058:
    player_frame_header   7, $24, $27, data_76_4830_PlayerTiles + $32c0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL0
    player_piece  -14,   -7, PLAYER_PIECE_PAL0
    player_piece  -13,    0, PLAYER_PIECE_PAL0
    player_piece  -34,   -6, PLAYER_PIECE_PAL1
    player_piece  -31,    0, PLAYER_PIECE_PAL1
    player_piece  -18,   -3, PLAYER_PIECE_PAL1

data_76_4796_PlayerFrame_059:
    player_frame_header   6, $24, $27, data_76_4830_PlayerTiles + $33a0
    player_piece  -30,   -9, PLAYER_PIECE_PAL0
    player_piece  -31,   -1, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0
    player_piece  -34,   -6, PLAYER_PIECE_PAL1
    player_piece  -32,   -3, PLAYER_PIECE_PAL1

data_76_47b3_PlayerFrame_060:
    player_frame_header   7, $24, $27, data_76_4830_PlayerTiles + $3460
    player_piece  -21,  -15, PLAYER_PIECE_PAL0
    player_piece  -30,   -7, PLAYER_PIECE_PAL0
    player_piece  -14,   -7, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL0
    player_piece  -13,    0, PLAYER_PIECE_PAL0
    player_piece  -43,   -7, PLAYER_PIECE_PAL1
    player_piece  -45,    0, PLAYER_PIECE_PAL1

data_76_47d4_PlayerFrame_061:
    player_frame_header   6, $24, $27, data_76_4830_PlayerTiles + $3540
    player_piece  -30,   -9, PLAYER_PIECE_PAL0
    player_piece  -30,   -1, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0
    player_piece  -34,   -5, PLAYER_PIECE_PAL1
    player_piece  -31,   -2, PLAYER_PIECE_PAL1

data_76_47f1_PlayerFrame_062:
    player_frame_header   6, $24, $27, data_76_4830_PlayerTiles + $3600
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,   -7, PLAYER_PIECE_PAL0
    player_piece  -14,    1, PLAYER_PIECE_PAL0
    player_piece  -34,   -4, PLAYER_PIECE_PAL1
    player_piece  -32,   -2, PLAYER_PIECE_PAL1

data_76_480e_PlayerFrame_063:
    player_frame_header   6, $23, $29, data_76_4830_PlayerTiles + $36c0
    player_piece  -21,   -9, PLAYER_PIECE_PAL0
    player_piece  -20,   -1, PLAYER_PIECE_PAL0
    player_piece  -36,   -2, PLAYER_PIECE_PAL0
    player_piece  -36,    6, PLAYER_PIECE_PAL0
    player_piece  -31,   -3, PLAYER_PIECE_PAL1
    player_piece  -44,    0, PLAYER_PIECE_PAL1

    ds   $4830 - @, 0                    ; the bank pads to a 16-byte boundary here
data_76_4830_PlayerTiles:
; INCBINd by main.asm - see the header above
