; ==================================================================
; Bank $62. Gex's animation frames 1 to 67 of PLAYER_GFX_SET_ANIME_CHANNEL.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $4836, then 884 tiles of graphics from $4840 to $7f7f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/player_sprite_data/bank7f_player_sprite_data.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_62_4000_PlayerFrame_001:
    player_frame_header   7, $1c, $22, data_62_4840_PlayerTiles + $0000
    player_piece  -35,    5, PLAYER_PIECE_PAL0
    player_piece  -36,    8, PLAYER_PIECE_PAL0
    player_piece  -21,   -5, PLAYER_PIECE_PAL1
    player_piece  -25,    3, PLAYER_PIECE_PAL1
    player_piece  -17,    8, PLAYER_PIECE_PAL1
    player_piece   -8,  -13, PLAYER_PIECE_PAL1
    player_piece  -19,    3, PLAYER_PIECE_PAL1

data_62_4021_PlayerFrame_002:
    player_frame_header   7, $1c, $22, data_62_4840_PlayerTiles + $00e0
    player_piece  -34,    5, PLAYER_PIECE_PAL0
    player_piece  -35,    8, PLAYER_PIECE_PAL0
    player_piece  -21,   -2, PLAYER_PIECE_PAL1
    player_piece  -27,    6, PLAYER_PIECE_PAL1
    player_piece   -7,  -11, PLAYER_PIECE_PAL1
    player_piece  -17,   -3, PLAYER_PIECE_PAL1
    player_piece  -17,    5, PLAYER_PIECE_PAL1

data_62_4042_PlayerFrame_003:
    player_frame_header   7, $1b, $22, data_62_4840_PlayerTiles + $01c0
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece  -34,    8, PLAYER_PIECE_PAL0
    player_piece  -18,   -6, PLAYER_PIECE_PAL1
    player_piece  -23,    2, PLAYER_PIECE_PAL1
    player_piece   -7,   -9, PLAYER_PIECE_PAL1
    player_piece  -16,    2, PLAYER_PIECE_PAL1
    player_piece  -18,    8, PLAYER_PIECE_PAL1

data_62_4063_PlayerFrame_004:
    player_frame_header   7, $1b, $23, data_62_4840_PlayerTiles + $02a0
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece  -34,    9, PLAYER_PIECE_PAL0
    player_piece  -10,  -10, PLAYER_PIECE_PAL1
    player_piece  -20,   -2, PLAYER_PIECE_PAL1
    player_piece  -26,    6, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,    6, PLAYER_PIECE_PAL1

data_62_4084_PlayerFrame_005:
    player_frame_header   7, $1a, $23, data_62_4840_PlayerTiles + $0380
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -11,  -11, PLAYER_PIECE_PAL1
    player_piece  -19,   -3, PLAYER_PIECE_PAL1
    player_piece  -25,    5, PLAYER_PIECE_PAL1
    player_piece   -3,   -3, PLAYER_PIECE_PAL1
    player_piece  -16,    5, PLAYER_PIECE_PAL1

data_62_40a5_PlayerFrame_006:
    player_frame_header   6, $1b, $23, data_62_4840_PlayerTiles + $0460
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece  -34,   13, PLAYER_PIECE_PAL0
    player_piece  -16,  -12, PLAYER_PIECE_PAL1
    player_piece  -20,   -1, PLAYER_PIECE_PAL1
    player_piece  -27,    7, PLAYER_PIECE_PAL1
    player_piece  -16,   -4, PLAYER_PIECE_PAL1

data_62_40c2_PlayerFrame_007:
    player_frame_header   7, $1c, $23, data_62_4840_PlayerTiles + $0520
    player_piece  -34,    5, PLAYER_PIECE_PAL0
    player_piece  -34,    9, PLAYER_PIECE_PAL0
    player_piece  -16,  -13, PLAYER_PIECE_PAL1
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -17,    3, PLAYER_PIECE_PAL1
    player_piece  -32,   -1, PLAYER_PIECE_PAL1
    player_piece  -33,    7, PLAYER_PIECE_PAL1

data_62_40e3_PlayerFrame_008:
    player_frame_header   7, $1d, $23, data_62_4840_PlayerTiles + $0600
    player_piece  -35,    5, PLAYER_PIECE_PAL0
    player_piece  -35,    9, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    4, PLAYER_PIECE_PAL1
    player_piece   -9,  -13, PLAYER_PIECE_PAL1
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -19,    4, PLAYER_PIECE_PAL1

data_62_4104_PlayerFrame_009:
    player_frame_header   7, $1e, $22, data_62_4840_PlayerTiles + $06e0
    player_piece  -36,    5, PLAYER_PIECE_PAL0
    player_piece  -37,    8, PLAYER_PIECE_PAL0
    player_piece  -22,   -4, PLAYER_PIECE_PAL1
    player_piece  -29,    4, PLAYER_PIECE_PAL1
    player_piece   -8,  -13, PLAYER_PIECE_PAL1
    player_piece  -21,   -5, PLAYER_PIECE_PAL1
    player_piece  -20,    4, PLAYER_PIECE_PAL1

data_62_4125_PlayerFrame_010:
    player_frame_header   7, $1c, $22, data_62_4840_PlayerTiles + $07c0
    player_piece  -35,    5, PLAYER_PIECE_PAL0
    player_piece  -36,    8, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL1
    player_piece  -28,    5, PLAYER_PIECE_PAL1
    player_piece   -9,  -11, PLAYER_PIECE_PAL1
    player_piece  -18,   -3, PLAYER_PIECE_PAL1
    player_piece  -18,    5, PLAYER_PIECE_PAL1

data_62_4146_PlayerFrame_011:
    player_frame_header   7, $1b, $23, data_62_4840_PlayerTiles + $08a0
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -17,   -9, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1
    player_piece  -17,    7, PLAYER_PIECE_PAL1
    player_piece  -32,    1, PLAYER_PIECE_PAL1
    player_piece  -37,    9, PLAYER_PIECE_PAL1

data_62_4167_PlayerFrame_012:
    player_frame_header   7, $1a, $23, data_62_4840_PlayerTiles + $0980
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -32,    9, PLAYER_PIECE_PAL0
    player_piece   -9,  -10, PLAYER_PIECE_PAL1
    player_piece  -19,   -2, PLAYER_PIECE_PAL1
    player_piece  -22,    6, PLAYER_PIECE_PAL1
    player_piece   -3,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,    6, PLAYER_PIECE_PAL1

data_62_4188_PlayerFrame_013:
    player_frame_header   6, $1a, $23, data_62_4840_PlayerTiles + $0a60
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -11,  -10, PLAYER_PIECE_PAL1
    player_piece  -19,   -2, PLAYER_PIECE_PAL1
    player_piece  -26,    6, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1

data_62_41a5_PlayerFrame_014:
    player_frame_header   6, $1b, $23, data_62_4840_PlayerTiles + $0b20
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece  -34,   13, PLAYER_PIECE_PAL0
    player_piece  -16,  -12, PLAYER_PIECE_PAL1
    player_piece  -16,   -4, PLAYER_PIECE_PAL1
    player_piece  -18,    0, PLAYER_PIECE_PAL1
    player_piece  -34,    3, PLAYER_PIECE_PAL1

data_62_41c2_PlayerFrame_015:
    player_frame_header   7, $1b, $23, data_62_4840_PlayerTiles + $0be0
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece  -34,    9, PLAYER_PIECE_PAL0
    player_piece  -16,  -12, PLAYER_PIECE_PAL1
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece  -23,    4, PLAYER_PIECE_PAL1
    player_piece   -3,   -4, PLAYER_PIECE_PAL1
    player_piece  -17,    4, PLAYER_PIECE_PAL1

data_62_41e3_PlayerFrame_016:
    player_frame_header   7, $1c, $22, data_62_4840_PlayerTiles + $0cc0
    player_piece  -34,    4, PLAYER_PIECE_PAL0
    player_piece  -35,    8, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL1
    player_piece  -21,   -3, PLAYER_PIECE_PAL1
    player_piece  -24,    5, PLAYER_PIECE_PAL1
    player_piece   -8,  -12, PLAYER_PIECE_PAL1
    player_piece  -19,    5, PLAYER_PIECE_PAL1

data_62_4204_PlayerFrame_017:
    player_frame_header   7, $1d, $20, data_62_4840_PlayerTiles + $0da0
    player_piece  -35,    4, PLAYER_PIECE_PAL0
    player_piece  -35,    8, PLAYER_PIECE_PAL0
    player_piece  -21,   -5, PLAYER_PIECE_PAL1
    player_piece  -28,    3, PLAYER_PIECE_PAL1
    player_piece   -9,  -14, PLAYER_PIECE_PAL1
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -19,    3, PLAYER_PIECE_PAL1

data_62_4225_PlayerFrame_018:
    player_frame_header   7, $1d, $21, data_62_4840_PlayerTiles + $0e80
    player_piece  -36,    0, PLAYER_PIECE_PAL0
    player_piece  -35,    8, PLAYER_PIECE_PAL0
    player_piece  -11,  -16, PLAYER_PIECE_PAL1
    player_piece  -20,   -8, PLAYER_PIECE_PAL1
    player_piece  -23,    0, PLAYER_PIECE_PAL1
    player_piece  -25,    8, PLAYER_PIECE_PAL1
    player_piece   -9,    8, PLAYER_PIECE_PAL1

data_62_4246_PlayerFrame_019:
    player_frame_header   7, $1d, $20, data_62_4840_PlayerTiles + $0f60
    player_piece  -36,    0, PLAYER_PIECE_PAL0
    player_piece  -35,    8, PLAYER_PIECE_PAL0
    player_piece  -14,  -16, PLAYER_PIECE_PAL1
    player_piece  -25,   -8, PLAYER_PIECE_PAL1
    player_piece   -9,   -8, PLAYER_PIECE_PAL1
    player_piece  -24,    0, PLAYER_PIECE_PAL1
    player_piece  -26,    8, PLAYER_PIECE_PAL1

data_62_4267_PlayerFrame_020:
    player_frame_header   8, $1d, $20, data_62_4840_PlayerTiles + $1040
    player_piece  -35,    5, PLAYER_PIECE_PAL0
    player_piece  -36,   13, PLAYER_PIECE_PAL0
    player_piece  -15,  -12, PLAYER_PIECE_PAL1
    player_piece  -26,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,   -4, PLAYER_PIECE_PAL1
    player_piece  -25,    4, PLAYER_PIECE_PAL1
    player_piece  -19,    4, PLAYER_PIECE_PAL1
    player_piece   -7,   12, PLAYER_PIECE_PAL1

data_62_428c_PlayerFrame_021:
    player_frame_header   8, $1e, $20, data_62_4840_PlayerTiles + $1140
    player_piece  -36,    4, PLAYER_PIECE_PAL0
    player_piece  -37,    8, PLAYER_PIECE_PAL0
    player_piece  -24,   -5, PLAYER_PIECE_PAL1
    player_piece  -26,    3, PLAYER_PIECE_PAL1
    player_piece  -21,  -12, PLAYER_PIECE_PAL1
    player_piece  -10,   -4, PLAYER_PIECE_PAL1
    player_piece  -18,    4, PLAYER_PIECE_PAL1
    player_piece   -7,    8, PLAYER_PIECE_PAL1

data_62_42b1_PlayerFrame_022:
    player_frame_header   7, $1f, $20, data_62_4840_PlayerTiles + $1240
    player_piece  -37,    1, PLAYER_PIECE_PAL0
    player_piece  -38,    5, PLAYER_PIECE_PAL0
    player_piece  -23,   -6, PLAYER_PIECE_PAL1
    player_piece  -27,    2, PLAYER_PIECE_PAL1
    player_piece  -11,  -15, PLAYER_PIECE_PAL1
    player_piece  -19,   -7, PLAYER_PIECE_PAL1
    player_piece  -17,    1, PLAYER_PIECE_PAL1

data_62_42d2_PlayerFrame_023:
    player_frame_header   7, $1c, $20, data_62_4840_PlayerTiles + $1320
    player_piece  -34,    1, PLAYER_PIECE_PAL0
    player_piece  -35,    5, PLAYER_PIECE_PAL0
    player_piece  -11,  -15, PLAYER_PIECE_PAL1
    player_piece  -21,   -7, PLAYER_PIECE_PAL1
    player_piece  -24,    1, PLAYER_PIECE_PAL1
    player_piece   -8,   -3, PLAYER_PIECE_PAL1
    player_piece  -16,    5, PLAYER_PIECE_PAL1

data_62_42f3_PlayerFrame_024:
    player_frame_header   7, $1a, $20, data_62_4840_PlayerTiles + $1400
    player_piece  -32,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,    3, PLAYER_PIECE_PAL0
    player_piece  -10,  -17, PLAYER_PIECE_PAL1
    player_piece  -19,   -9, PLAYER_PIECE_PAL1
    player_piece  -22,   -1, PLAYER_PIECE_PAL1
    player_piece   -6,   -4, PLAYER_PIECE_PAL1
    player_piece  -16,    3, PLAYER_PIECE_PAL1

data_62_4314_PlayerFrame_025:
    player_frame_header   8, $1f, $1d, data_62_4840_PlayerTiles + $14e0
    player_piece  -35,   -5, PLAYER_PIECE_PAL0
    player_piece  -35,    3, PLAYER_PIECE_PAL0
    player_piece  -29,  -11, PLAYER_PIECE_PAL1
    player_piece  -28,   -3, PLAYER_PIECE_PAL1
    player_piece  -29,    3, PLAYER_PIECE_PAL1
    player_piece  -16,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1
    player_piece  -10,    3, PLAYER_PIECE_PAL1

data_62_4339_PlayerFrame_026:
    player_frame_header   8, $20, $1d, data_62_4840_PlayerTiles + $15e0
    player_piece  -35,   -5, PLAYER_PIECE_PAL0
    player_piece  -35,    3, PLAYER_PIECE_PAL0
    player_piece  -30,  -11, PLAYER_PIECE_PAL1
    player_piece  -28,   -3, PLAYER_PIECE_PAL1
    player_piece  -39,    3, PLAYER_PIECE_PAL1
    player_piece  -16,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1
    player_piece  -10,    3, PLAYER_PIECE_PAL1

data_62_435e_PlayerFrame_027:
    player_frame_header   8, $1e, $1d, data_62_4840_PlayerTiles + $16e0
    player_piece  -36,   -5, PLAYER_PIECE_PAL0
    player_piece  -37,    3, PLAYER_PIECE_PAL0
    player_piece  -27,  -12, PLAYER_PIECE_PAL1
    player_piece  -26,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    3, PLAYER_PIECE_PAL1
    player_piece  -16,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1
    player_piece  -10,    3, PLAYER_PIECE_PAL1

data_62_4383_PlayerFrame_028:
    player_frame_header   7, $1a, $1d, data_62_4840_PlayerTiles + $17e0
    player_piece  -32,   -5, PLAYER_PIECE_PAL0
    player_piece  -33,    3, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL1
    player_piece  -16,   -3, PLAYER_PIECE_PAL1
    player_piece  -18,    3, PLAYER_PIECE_PAL1
    player_piece  -32,  -10, PLAYER_PIECE_PAL1
    player_piece  -36,   -1, PLAYER_PIECE_PAL1

data_62_43a4_PlayerFrame_029:
    player_frame_header   6, $16, $1d, data_62_4840_PlayerTiles + $18c0
    player_piece  -28,   -6, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -18,  -11, PLAYER_PIECE_PAL1
    player_piece  -17,   -3, PLAYER_PIECE_PAL1
    player_piece  -16,    3, PLAYER_PIECE_PAL1
    player_piece   -2,   -5, PLAYER_PIECE_PAL1

data_62_43c1_PlayerFrame_030:
    player_frame_header   7, $1e, $1d, data_62_4840_PlayerTiles + $1980
    player_piece  -37,  -10, PLAYER_PIECE_PAL0
    player_piece  -36,   -2, PLAYER_PIECE_PAL0
    player_piece  -26,  -10, PLAYER_PIECE_PAL1
    player_piece  -10,  -10, PLAYER_PIECE_PAL1
    player_piece  -25,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -17,    3, PLAYER_PIECE_PAL1

data_62_43e2_PlayerFrame_031:
    player_frame_header   8, $1e, $1d, data_62_4840_PlayerTiles + $1a60
    player_piece  -36,   -5, PLAYER_PIECE_PAL0
    player_piece  -37,    3, PLAYER_PIECE_PAL0
    player_piece  -27,  -12, PLAYER_PIECE_PAL1
    player_piece  -26,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    3, PLAYER_PIECE_PAL1
    player_piece  -16,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1
    player_piece  -10,    3, PLAYER_PIECE_PAL1

data_62_4407_PlayerFrame_032:
    player_frame_header   6, $1e, $20, data_62_4840_PlayerTiles + $1b60
    player_piece  -36,   -3, PLAYER_PIECE_PAL0
    player_piece  -37,    5, PLAYER_PIECE_PAL0
    player_piece  -18,  -12, PLAYER_PIECE_PAL1
    player_piece  -26,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,    3, PLAYER_PIECE_PAL1

data_62_4424_PlayerFrame_033:
    player_frame_header   8, $1e, $21, data_62_4840_PlayerTiles + $1c20
    player_piece  -36,   -4, PLAYER_PIECE_PAL0
    player_piece  -36,    4, PLAYER_PIECE_PAL0
    player_piece  -19,  -12, PLAYER_PIECE_PAL1
    player_piece   -3,  -12, PLAYER_PIECE_PAL1
    player_piece  -26,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,   -4, PLAYER_PIECE_PAL1
    player_piece  -18,    4, PLAYER_PIECE_PAL1
    player_piece   -2,    4, PLAYER_PIECE_PAL1

data_62_4449_PlayerFrame_034:
    player_frame_header   7, $1b, $1f, data_62_4840_PlayerTiles + $1d20
    player_piece  -33,   -3, PLAYER_PIECE_PAL0
    player_piece  -34,    3, PLAYER_PIECE_PAL0
    player_piece  -21,  -11, PLAYER_PIECE_PAL1
    player_piece  -23,   -3, PLAYER_PIECE_PAL1
    player_piece  -21,    3, PLAYER_PIECE_PAL1
    player_piece  -16,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1

data_62_446a_PlayerFrame_035:
    player_frame_header   7, $18, $1d, data_62_4840_PlayerTiles + $1e00
    player_piece  -30,   -4, PLAYER_PIECE_PAL0
    player_piece  -31,    1, PLAYER_PIECE_PAL0
    player_piece  -21,  -12, PLAYER_PIECE_PAL1
    player_piece  -20,   -4, PLAYER_PIECE_PAL1
    player_piece   -4,   -4, PLAYER_PIECE_PAL1
    player_piece  -32,    1, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1

data_62_448b_PlayerFrame_036:
    player_frame_header   6, $19, $1c, data_62_4840_PlayerTiles + $1ee0
    player_piece  -28,   -4, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -16,  -10, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -32,   -9, PLAYER_PIECE_PAL1
    player_piece  -32,   -1, PLAYER_PIECE_PAL1

data_62_44a8_PlayerFrame_037:
    player_frame_header   5, $18, $1b, data_62_4840_PlayerTiles + $1fa0
    player_piece  -26,   -4, PLAYER_PIECE_PAL0
    player_piece  -21,  -10, PLAYER_PIECE_PAL1
    player_piece  -22,   -2, PLAYER_PIECE_PAL1
    player_piece   -6,   -7, PLAYER_PIECE_PAL1
    player_piece   -6,   -1, PLAYER_PIECE_PAL1

data_62_44c1_PlayerFrame_038:
    player_frame_header   5, $16, $1b, data_62_4840_PlayerTiles + $2040
    player_piece  -25,   -4, PLAYER_PIECE_PAL0
    player_piece  -20,  -10, PLAYER_PIECE_PAL1
    player_piece  -20,   -2, PLAYER_PIECE_PAL1
    player_piece   -4,   -5, PLAYER_PIECE_PAL1
    player_piece   -4,   -1, PLAYER_PIECE_PAL1

data_62_44da_PlayerFrame_039:
    player_frame_header   4, $15, $1b, data_62_4840_PlayerTiles + $20e0
    player_piece  -23,   -2, PLAYER_PIECE_PAL0
    player_piece  -19,   -9, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1
    player_piece   -3,   -5, PLAYER_PIECE_PAL1

data_62_44ef_PlayerFrame_040:
    player_frame_header   4, $15, $1b, data_62_4840_PlayerTiles + $2160
    player_piece  -23,   -1, PLAYER_PIECE_PAL0
    player_piece  -19,   -9, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1
    player_piece   -3,   -5, PLAYER_PIECE_PAL1

data_62_4504_PlayerFrame_041:
    player_frame_header   4, $15, $1b, data_62_4840_PlayerTiles + $21e0
    player_piece  -23,   -1, PLAYER_PIECE_PAL0
    player_piece  -19,   -9, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1
    player_piece   -3,   -5, PLAYER_PIECE_PAL1

data_62_4519_PlayerFrame_042:
    player_frame_header   7, $1c, $23, data_62_4840_PlayerTiles + $2260
    player_piece  -34,  -14, PLAYER_PIECE_PAL0
    player_piece  -36,   -6, PLAYER_PIECE_PAL0
    player_piece  -23,  -16, PLAYER_PIECE_PAL1
    player_piece  -18,  -15, PLAYER_PIECE_PAL1
    player_piece  -24,   -7, PLAYER_PIECE_PAL1
    player_piece   -8,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1

data_62_453a_PlayerFrame_043:
    player_frame_header   6, $1c, $22, data_62_4840_PlayerTiles + $2340
    player_piece  -34,  -11, PLAYER_PIECE_PAL0
    player_piece  -35,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,  -14, PLAYER_PIECE_PAL1
    player_piece  -24,   -6, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1
    player_piece   -8,   -6, PLAYER_PIECE_PAL1

data_62_4557_PlayerFrame_044:
    player_frame_header   6, $1d, $25, data_62_4840_PlayerTiles + $2400
    player_piece  -35,   -3, PLAYER_PIECE_PAL0
    player_piece  -36,    2, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL1
    player_piece  -24,   -3, PLAYER_PIECE_PAL1
    player_piece   -8,   -3, PLAYER_PIECE_PAL1
    player_piece  -18,    2, PLAYER_PIECE_PAL1

data_62_4574_PlayerFrame_045:
    player_frame_header   6, $1d, $26, data_62_4840_PlayerTiles + $24c0
    player_piece  -35,   -3, PLAYER_PIECE_PAL0
    player_piece  -35,    3, PLAYER_PIECE_PAL0
    player_piece  -17,  -11, PLAYER_PIECE_PAL1
    player_piece  -25,   -3, PLAYER_PIECE_PAL1
    player_piece   -9,   -3, PLAYER_PIECE_PAL1
    player_piece  -19,    3, PLAYER_PIECE_PAL1

data_62_4591_PlayerFrame_046:
    player_frame_header   7, $1c, $30, data_62_4840_PlayerTiles + $2580
    player_piece  -34,   10, PLAYER_PIECE_PAL0
    player_piece  -35,   13, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -20,    3, PLAYER_PIECE_PAL1
    player_piece  -24,   11, PLAYER_PIECE_PAL1
    player_piece   -4,    3, PLAYER_PIECE_PAL1
    player_piece  -18,   11, PLAYER_PIECE_PAL1

data_62_45b2_PlayerFrame_047:
    player_frame_header   8, $20, $2b, data_62_4840_PlayerTiles + $2660
    player_piece  -38,   -7, PLAYER_PIECE_PAL0
    player_piece  -38,    1, PLAYER_PIECE_PAL0
    player_piece  -10,  -15, PLAYER_PIECE_PAL1
    player_piece  -28,   -7, PLAYER_PIECE_PAL1
    player_piece  -12,   -7, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -18,    1, PLAYER_PIECE_PAL1
    player_piece  -21,    4, PLAYER_PIECE_PAL1

data_62_45d7_PlayerFrame_048:
    player_frame_header   6, $1e, $2a, data_62_4840_PlayerTiles + $2760
    player_piece  -36,   -7, PLAYER_PIECE_PAL0
    player_piece  -37,    1, PLAYER_PIECE_PAL0
    player_piece  -19,  -11, PLAYER_PIECE_PAL1
    player_piece  -19,   -3, PLAYER_PIECE_PAL1
    player_piece  -21,    3, PLAYER_PIECE_PAL1
    player_piece  -35,   -5, PLAYER_PIECE_PAL1

data_62_45f4_PlayerFrame_049:
    player_frame_header   6, $1d, $2b, data_62_4840_PlayerTiles + $2820
    player_piece  -34,   -7, PLAYER_PIECE_PAL0
    player_piece  -37,    1, PLAYER_PIECE_PAL0
    player_piece  -18,  -11, PLAYER_PIECE_PAL1
    player_piece  -19,   -3, PLAYER_PIECE_PAL1
    player_piece  -24,    4, PLAYER_PIECE_PAL1
    player_piece  -34,   -6, PLAYER_PIECE_PAL1

data_62_4611_PlayerFrame_050:
    player_frame_header   8, $1d, $30, data_62_4840_PlayerTiles + $28e0
    player_piece  -37,  -15, PLAYER_PIECE_PAL0
    player_piece  -34,   -7, PLAYER_PIECE_PAL0
    player_piece  -37,    1, PLAYER_PIECE_PAL0
    player_piece  -15,  -15, PLAYER_PIECE_PAL1
    player_piece  -24,   -7, PLAYER_PIECE_PAL1
    player_piece   -8,   -7, PLAYER_PIECE_PAL1
    player_piece  -20,    1, PLAYER_PIECE_PAL1
    player_piece  -17,    9, PLAYER_PIECE_PAL1

data_62_4636_PlayerFrame_051:
    player_frame_header   8, $1c, $30, data_62_4840_PlayerTiles + $29e0
    player_piece  -36,  -15, PLAYER_PIECE_PAL0
    player_piece  -33,   -7, PLAYER_PIECE_PAL0
    player_piece  -36,    1, PLAYER_PIECE_PAL0
    player_piece  -15,  -15, PLAYER_PIECE_PAL1
    player_piece  -23,   -7, PLAYER_PIECE_PAL1
    player_piece   -7,   -7, PLAYER_PIECE_PAL1
    player_piece  -20,    1, PLAYER_PIECE_PAL1
    player_piece  -18,    9, PLAYER_PIECE_PAL1

data_62_465b_PlayerFrame_052:
    player_frame_header   9, $1c, $2e, data_62_4840_PlayerTiles + $2ae0
    player_piece  -36,  -15, PLAYER_PIECE_PAL0
    player_piece  -34,   -7, PLAYER_PIECE_PAL0
    player_piece  -36,    1, PLAYER_PIECE_PAL0
    player_piece  -14,  -15, PLAYER_PIECE_PAL1
    player_piece  -23,   -7, PLAYER_PIECE_PAL1
    player_piece   -7,   -7, PLAYER_PIECE_PAL1
    player_piece  -20,    1, PLAYER_PIECE_PAL1
    player_piece   -4,    1, PLAYER_PIECE_PAL1
    player_piece  -16,    7, PLAYER_PIECE_PAL1

data_62_4684_PlayerFrame_053:
    player_frame_header   8, $1b, $2e, data_62_4840_PlayerTiles + $2c00
    player_piece  -35,  -15, PLAYER_PIECE_PAL0
    player_piece  -33,   -7, PLAYER_PIECE_PAL0
    player_piece  -35,    1, PLAYER_PIECE_PAL0
    player_piece  -13,  -15, PLAYER_PIECE_PAL1
    player_piece  -22,   -7, PLAYER_PIECE_PAL1
    player_piece   -6,   -7, PLAYER_PIECE_PAL1
    player_piece  -19,    1, PLAYER_PIECE_PAL1
    player_piece  -16,    7, PLAYER_PIECE_PAL1

data_62_46a9_PlayerFrame_054:
    player_frame_header   6, $13, $2e, data_62_4840_PlayerTiles + $2d00
    player_piece  -24,   -9, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL0
    player_piece  -12,  -12, PLAYER_PIECE_PAL1
    player_piece  -18,   -4, PLAYER_PIECE_PAL1
    player_piece  -17,    4, PLAYER_PIECE_PAL1
    player_piece  -23,    7, PLAYER_PIECE_PAL1

data_62_46c6_PlayerFrame_055:
    player_frame_header   5, $22, $27, data_62_4840_PlayerTiles + $2dc0
    player_piece  -38,   -6, PLAYER_PIECE_PAL0
    player_piece  -29,   -9, PLAYER_PIECE_PAL1
    player_piece  -32,   -1, PLAYER_PIECE_PAL1
    player_piece  -19,   -8, PLAYER_PIECE_PAL1
    player_piece  -16,    0, PLAYER_PIECE_PAL1

data_62_46df_PlayerFrame_056:
    player_frame_header   6, $21, $27, data_62_4840_PlayerTiles + $2e60
    player_piece  -38,   -6, PLAYER_PIECE_PAL0
    player_piece  -43,    0, PLAYER_PIECE_PAL0
    player_piece  -29,   -9, PLAYER_PIECE_PAL1
    player_piece  -28,   -1, PLAYER_PIECE_PAL1
    player_piece  -21,   -8, PLAYER_PIECE_PAL1
    player_piece  -23,    0, PLAYER_PIECE_PAL1

data_62_46fc_PlayerFrame_057:
    player_frame_header   6, $22, $28, data_62_4840_PlayerTiles + $2f20
    player_piece  -39,   -6, PLAYER_PIECE_PAL0
    player_piece  -41,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -9, PLAYER_PIECE_PAL1
    player_piece  -23,   -1, PLAYER_PIECE_PAL1
    player_piece  -21,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -8, PLAYER_PIECE_PAL1

data_62_4719_PlayerFrame_058:
    player_frame_header   5, $22, $27, data_62_4840_PlayerTiles + $2fe0
    player_piece  -39,   -5, PLAYER_PIECE_PAL0
    player_piece  -41,    0, PLAYER_PIECE_PAL0
    player_piece  -20,   -8, PLAYER_PIECE_PAL1
    player_piece  -20,    0, PLAYER_PIECE_PAL1
    player_piece  -36,   -3, PLAYER_PIECE_PAL1

data_62_4732_PlayerFrame_059:
    player_frame_header   6, $22, $27, data_62_4840_PlayerTiles + $3080
    player_piece  -39,   -5, PLAYER_PIECE_PAL0
    player_piece  -41,    0, PLAYER_PIECE_PAL0
    player_piece  -29,   -9, PLAYER_PIECE_PAL1
    player_piece  -31,   -1, PLAYER_PIECE_PAL1
    player_piece  -19,   -8, PLAYER_PIECE_PAL1
    player_piece  -25,    0, PLAYER_PIECE_PAL1

data_62_474f_PlayerFrame_060:
    player_frame_header   6, $22, $27, data_62_4840_PlayerTiles + $3140
    player_piece  -39,   -4, PLAYER_PIECE_PAL0
    player_piece  -41,    0, PLAYER_PIECE_PAL0
    player_piece  -29,   -9, PLAYER_PIECE_PAL1
    player_piece  -30,   -1, PLAYER_PIECE_PAL1
    player_piece  -21,   -8, PLAYER_PIECE_PAL1
    player_piece  -23,    0, PLAYER_PIECE_PAL1

data_62_476c_PlayerFrame_061:
    player_frame_header   5, $22, $27, data_62_4840_PlayerTiles + $3200
    player_piece  -39,   -4, PLAYER_PIECE_PAL0
    player_piece  -41,    0, PLAYER_PIECE_PAL0
    player_piece  -23,   -9, PLAYER_PIECE_PAL1
    player_piece  -21,   -1, PLAYER_PIECE_PAL1
    player_piece  -37,   -2, PLAYER_PIECE_PAL1

data_62_4785_PlayerFrame_062:
    player_frame_header   5, $22, $27, data_62_4840_PlayerTiles + $32a0
    player_piece  -40,   -3, PLAYER_PIECE_PAL0
    player_piece  -41,    0, PLAYER_PIECE_PAL0
    player_piece  -20,   -8, PLAYER_PIECE_PAL1
    player_piece  -20,    0, PLAYER_PIECE_PAL1
    player_piece  -36,   -4, PLAYER_PIECE_PAL1

data_62_479e_PlayerFrame_063:
    player_frame_header   6, $22, $29, data_62_4840_PlayerTiles + $3340
    player_piece  -38,   -2, PLAYER_PIECE_PAL0
    player_piece  -41,    2, PLAYER_PIECE_PAL0
    player_piece  -22,   -9, PLAYER_PIECE_PAL1
    player_piece  -29,   -1, PLAYER_PIECE_PAL1
    player_piece  -25,    2, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1

data_62_47bb_PlayerFrame_064:
    player_frame_header   7, $20, $2a, data_62_4840_PlayerTiles + $3400
    player_piece  -37,   -2, PLAYER_PIECE_PAL0
    player_piece  -39,    3, PLAYER_PIECE_PAL0
    player_piece  -22,   -9, PLAYER_PIECE_PAL1
    player_piece  -28,   -1, PLAYER_PIECE_PAL1
    player_piece  -24,    3, PLAYER_PIECE_PAL1
    player_piece  -12,   -7, PLAYER_PIECE_PAL1
    player_piece  -21,    1, PLAYER_PIECE_PAL1

data_62_47dc_PlayerFrame_065:
    player_frame_header   8, $1f, $29, data_62_4840_PlayerTiles + $34e0
    player_piece  -37,   -7, PLAYER_PIECE_PAL0
    player_piece  -36,    1, PLAYER_PIECE_PAL0
    player_piece  -20,  -15, PLAYER_PIECE_PAL1
    player_piece   -4,  -15, PLAYER_PIECE_PAL1
    player_piece  -21,   -7, PLAYER_PIECE_PAL1
    player_piece   -5,   -7, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -11,    1, PLAYER_PIECE_PAL1

data_62_4801_PlayerFrame_066:
    player_frame_header   5, $1c, $2b, data_62_4840_PlayerTiles + $35e0
    player_piece  -33,    1, PLAYER_PIECE_PAL0
    player_piece  -35,    9, PLAYER_PIECE_PAL0
    player_piece  -19,  -11, PLAYER_PIECE_PAL1
    player_piece  -21,   -6, PLAYER_PIECE_PAL1
    player_piece  -27,    2, PLAYER_PIECE_PAL1

data_62_481a_PlayerFrame_067:
    player_frame_header   6, $18, $2d, data_62_4840_PlayerTiles + $3680
    player_piece  -30,    1, PLAYER_PIECE_PAL0
    player_piece  -30,    6, PLAYER_PIECE_PAL0
    player_piece  -12,  -15, PLAYER_PIECE_PAL1
    player_piece  -20,   -7, PLAYER_PIECE_PAL1
    player_piece  -24,    1, PLAYER_PIECE_PAL1
    player_piece  -14,    6, PLAYER_PIECE_PAL1

    ds   $4840 - @, 0                    ; the bank pads to a 16-byte boundary here
data_62_4840_PlayerTiles:
; INCBINd by main.asm - see the header above
