; ==================================================================
; Bank $78. Gex's animation frames 136 to 198 of PLAYER_GFX_SET_MYSTERY_TV.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $4742, then 772 tiles of graphics from $4750 to $778f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/player_sprite_data/bank7f_player_sprite_data.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_78_4000_PlayerFrame_136:
    player_frame_header   5, $16, $1e, data_78_4750_PlayerTiles + $0000
    player_piece  -10,  -11, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL1
    player_piece  -31,    4, PLAYER_PIECE_PAL1

data_78_4019_PlayerFrame_137:
    player_frame_header   5, $15, $1e, data_78_4750_PlayerTiles + $00a0
    player_piece  -10,  -11, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL1
    player_piece  -30,    4, PLAYER_PIECE_PAL1

data_78_4032_PlayerFrame_138:
    player_frame_header   6, $19, $1f, data_78_4750_PlayerTiles + $0140
    player_piece  -18,  -10, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -17,    5, PLAYER_PIECE_PAL0
    player_piece  -32,    4, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL1
    player_piece  -33,    5, PLAYER_PIECE_PAL1

data_78_404f_PlayerFrame_139:
    player_frame_header   5, $19, $1d, data_78_4750_PlayerTiles + $0200
    player_piece  -17,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -26,    2, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL1
    player_piece  -34,    1, PLAYER_PIECE_PAL1

data_78_4068_PlayerFrame_140:
    player_frame_header   6, $19, $21, data_78_4750_PlayerTiles + $02a0
    player_piece  -20,  -14, PLAYER_PIECE_PAL0
    player_piece  -16,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -28,    6, PLAYER_PIECE_PAL0
    player_piece  -22,   -1, PLAYER_PIECE_PAL1
    player_piece  -34,    5, PLAYER_PIECE_PAL1

data_78_4085_PlayerFrame_141:
    player_frame_header   7, $20, $1d, data_78_4750_PlayerTiles + $0360
    player_piece  -25,   -5, PLAYER_PIECE_PAL0
    player_piece  -25,    2, PLAYER_PIECE_PAL0
    player_piece   -9,   -5, PLAYER_PIECE_PAL0
    player_piece   -9,    2, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    2, PLAYER_PIECE_PAL1
    player_piece  -14,    1, PLAYER_PIECE_PAL1

data_78_40a6_PlayerFrame_142:
    player_frame_header   7, $20, $1c, data_78_4750_PlayerTiles + $0440
    player_piece  -25,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -9,   -4, PLAYER_PIECE_PAL0
    player_piece   -1,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -12,    1, PLAYER_PIECE_PAL1

data_78_40c7_PlayerFrame_143:
    player_frame_header   6, $20, $1c, data_78_4750_PlayerTiles + $0520
    player_piece  -25,   -5, PLAYER_PIECE_PAL0
    player_piece  -25,    1, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -14,    0, PLAYER_PIECE_PAL1

data_78_40e4_PlayerFrame_144:
    player_frame_header   7, $1f, $1c, data_78_4750_PlayerTiles + $05e0
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1

data_78_4105_PlayerFrame_145:
    player_frame_header   7, $20, $1c, data_78_4750_PlayerTiles + $06c0
    player_piece  -25,   -6, PLAYER_PIECE_PAL0
    player_piece  -25,    1, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_78_4126_PlayerFrame_146:
    player_frame_header   7, $20, $1b, data_78_4750_PlayerTiles + $07a0
    player_piece  -25,   -5, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece   -6,    0, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    0, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_78_4147_PlayerFrame_147:
    player_frame_header   6, $20, $1c, data_78_4750_PlayerTiles + $0880
    player_piece  -25,   -5, PLAYER_PIECE_PAL0
    player_piece  -25,    1, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_78_4164_PlayerFrame_148:
    player_frame_header   7, $1f, $1c, data_78_4750_PlayerTiles + $0940
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece   -1,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1

data_78_4185_PlayerFrame_149:
    player_frame_header   7, $20, $1d, data_78_4750_PlayerTiles + $0a20
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -5, PLAYER_PIECE_PAL0
    player_piece   -8,    2, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_78_41a6_PlayerFrame_150:
    player_frame_header   7, $20, $1c, data_78_4750_PlayerTiles + $0b00
    player_piece  -24,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -4, PLAYER_PIECE_PAL0
    player_piece   -1,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_78_41c7_PlayerFrame_151:
    player_frame_header   6, $20, $1c, data_78_4750_PlayerTiles + $0be0
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_78_41e4_PlayerFrame_152:
    player_frame_header   7, $1f, $1c, data_78_4750_PlayerTiles + $0ca0
    player_piece  -23,   -5, PLAYER_PIECE_PAL0
    player_piece  -23,    1, PLAYER_PIECE_PAL0
    player_piece   -7,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1

data_78_4205_PlayerFrame_153:
    player_frame_header   7, $20, $1c, data_78_4750_PlayerTiles + $0d80
    player_piece  -24,   -6, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_78_4226_PlayerFrame_154:
    player_frame_header   7, $20, $1b, data_78_4750_PlayerTiles + $0e60
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    0, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece   -6,    0, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    0, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_78_4247_PlayerFrame_155:
    player_frame_header   6, $20, $1c, data_78_4750_PlayerTiles + $0f40
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_78_4264_PlayerFrame_156:
    player_frame_header   7, $1f, $1c, data_78_4750_PlayerTiles + $1000
    player_piece  -23,   -5, PLAYER_PIECE_PAL0
    player_piece  -23,    1, PLAYER_PIECE_PAL0
    player_piece   -7,   -3, PLAYER_PIECE_PAL0
    player_piece   -1,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1

data_78_4285_PlayerFrame_157:
    player_frame_header   7, $20, $28, data_78_4750_PlayerTiles + $10e0
    player_piece  -20,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL0
    player_piece  -12,   -6, PLAYER_PIECE_PAL0
    player_piece  -12,    2, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_78_42a6_PlayerFrame_158:
    player_frame_header   7, $1e, $20, data_78_4750_PlayerTiles + $11c0
    player_piece  -25,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -9,   -5, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -28,    2, PLAYER_PIECE_PAL1
    player_piece  -13,   -3, PLAYER_PIECE_PAL1

data_78_42c7_PlayerFrame_159:
    player_frame_header   8, $1e, $20, data_78_4750_PlayerTiles + $12a0
    player_piece  -25,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -9,   -5, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -28,    2, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece   -1,    2, PLAYER_PIECE_PAL1

data_78_42ec_PlayerFrame_160:
    player_frame_header   8, $1e, $20, data_78_4750_PlayerTiles + $13a0
    player_piece  -25,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -9,   -5, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -28,    2, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece   -1,    2, PLAYER_PIECE_PAL1

data_78_4311_PlayerFrame_161:
    player_frame_header   8, $1e, $20, data_78_4750_PlayerTiles + $14a0
    player_piece  -25,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -9,   -5, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -28,    2, PLAYER_PIECE_PAL1
    player_piece  -13,   -6, PLAYER_PIECE_PAL1
    player_piece  -12,    2, PLAYER_PIECE_PAL1

data_78_4336_PlayerFrame_162:
    player_frame_header   9, $1e, $20, data_78_4750_PlayerTiles + $15a0
    player_piece  -25,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece  -18,    2, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -8, PLAYER_PIECE_PAL1
    player_piece  -13,    0, PLAYER_PIECE_PAL1
    player_piece   -1,    2, PLAYER_PIECE_PAL1

data_78_435f_PlayerFrame_163:
    player_frame_header   8, $1e, $20, data_78_4750_PlayerTiles + $16c0
    player_piece  -25,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece  -23,    2, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -7, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_78_4384_PlayerFrame_164:
    player_frame_header   8, $1e, $23, data_78_4750_PlayerTiles + $17c0
    player_piece  -29,   -8, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -29,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,  -11, PLAYER_PIECE_PAL1
    player_piece  -13,   -3, PLAYER_PIECE_PAL1
    player_piece  -13,    5, PLAYER_PIECE_PAL1

data_78_43a9_PlayerFrame_165:
    player_frame_header   6, $1e, $24, data_78_4750_PlayerTiles + $18c0
    player_piece  -36,   -6, PLAYER_PIECE_PAL0
    player_piece  -37,    2, PLAYER_PIECE_PAL0
    player_piece  -19,  -14, PLAYER_PIECE_PAL1
    player_piece  -32,   -6, PLAYER_PIECE_PAL1
    player_piece  -32,    2, PLAYER_PIECE_PAL1
    player_piece  -19,    6, PLAYER_PIECE_PAL1

data_78_43c6_PlayerFrame_166:
    player_frame_header   4, $1d, $26, data_78_4750_PlayerTiles + $1980
    player_piece  -40,  -15, PLAYER_PIECE_PAL1
    player_piece  -38,   -7, PLAYER_PIECE_PAL1
    player_piece  -38,    1, PLAYER_PIECE_PAL1
    player_piece  -40,    8, PLAYER_PIECE_PAL1

data_78_43db_PlayerFrame_167:
    player_frame_header   3, $1e, $20, data_78_4750_PlayerTiles + $1a00
    player_piece  -40,  -14, PLAYER_PIECE_PAL1
    player_piece  -37,   -6, PLAYER_PIECE_PAL1
    player_piece  -37,    2, PLAYER_PIECE_PAL1

data_78_43ec_PlayerFrame_168:
    player_frame_header   2, $1e, $1b, data_78_4750_PlayerTiles + $1a60
    player_piece  -37,   -6, PLAYER_PIECE_PAL1
    player_piece  -40,   -3, PLAYER_PIECE_PAL1

data_78_43f9_PlayerFrame_169:
    player_frame_header   8, $1d, $19, data_78_4750_PlayerTiles + $1aa0
    player_piece  -19,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece   -5,    2, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL1
    player_piece  -36,    2, PLAYER_PIECE_PAL1
    player_piece  -11,   -3, PLAYER_PIECE_PAL1

data_78_441e_PlayerFrame_170:
    player_frame_header   6, $1e, $20, data_78_4750_PlayerTiles + $1ba0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL1
    player_piece  -12,   -3, PLAYER_PIECE_PAL1

data_78_443b_PlayerFrame_171:
    player_frame_header   5, $1d, $20, data_78_4750_PlayerTiles + $1c60
    player_piece  -27,   -8, PLAYER_PIECE_PAL0
    player_piece  -27,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -11,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL1

data_78_4454_PlayerFrame_172:
    player_frame_header   5, $1c, $1f, data_78_4750_PlayerTiles + $1d00
    player_piece  -26,   -7, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -10,    1, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL1

data_78_446d_PlayerFrame_173:
    player_frame_header   4, $1b, $1d, data_78_4750_PlayerTiles + $1da0
    player_piece  -16,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -32,   -3, PLAYER_PIECE_PAL0
    player_piece  -27,   -2, PLAYER_PIECE_PAL1

data_78_4482_PlayerFrame_174:
    player_frame_header   4, $19, $1d, data_78_4750_PlayerTiles + $1e20
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece   -3,   -1, PLAYER_PIECE_PAL0
    player_piece  -25,   -1, PLAYER_PIECE_PAL1

data_78_4497_PlayerFrame_175:
    player_frame_header   4, $15, $1d, data_78_4750_PlayerTiles + $1ea0
    player_piece  -19,   -2, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0
    player_piece   -3,   -1, PLAYER_PIECE_PAL0
    player_piece  -23,   -1, PLAYER_PIECE_PAL1

data_78_44ac_PlayerFrame_176:
    player_frame_header   3, $10, $1d, data_78_4750_PlayerTiles + $1f20
    player_piece  -16,   -5, PLAYER_PIECE_PAL0
    player_piece   -2,   -1, PLAYER_PIECE_PAL0
    player_piece  -22,   -1, PLAYER_PIECE_PAL1

data_78_44bd_PlayerFrame_177:
    player_frame_header   2, $0c, $1c, data_78_4750_PlayerTiles + $1f80
    player_piece  -16,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0

data_78_44ca_PlayerFrame_178:
    player_frame_header   6, $0f, $2e, data_78_4750_PlayerTiles + $1fc0
    player_piece  -16,  -17, PLAYER_PIECE_PAL0
    player_piece  -16,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -16,    7, PLAYER_PIECE_PAL0
    player_piece  -16,   -4, PLAYER_PIECE_PAL1
    player_piece  -17,    4, PLAYER_PIECE_PAL1

data_78_44e7_PlayerFrame_179:
    player_frame_header   6, $25, $16, data_78_4750_PlayerTiles + $2080
    player_piece  -36,   -4, PLAYER_PIECE_PAL0
    player_piece  -34,    3, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece  -18,   -2, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    3, PLAYER_PIECE_PAL1

data_78_4504_PlayerFrame_180:
    player_frame_header   6, $27, $16, data_78_4750_PlayerTiles + $2140
    player_piece  -36,   -3, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece  -18,   -5, PLAYER_PIECE_PAL0
    player_piece  -38,   -4, PLAYER_PIECE_PAL1
    player_piece  -36,    4, PLAYER_PIECE_PAL1

data_78_4521_PlayerFrame_181:
    player_frame_header   6, $28, $16, data_78_4750_PlayerTiles + $2200
    player_piece  -37,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -35,    4, PLAYER_PIECE_PAL0
    player_piece  -19,   -2, PLAYER_PIECE_PAL0
    player_piece  -38,   -4, PLAYER_PIECE_PAL1
    player_piece  -49,    4, PLAYER_PIECE_PAL1

data_78_453e_PlayerFrame_182:
    player_frame_header   7, $28, $16, data_78_4750_PlayerTiles + $22c0
    player_piece  -37,   -3, PLAYER_PIECE_PAL0
    player_piece  -33,    3, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece   -7,    3, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -47,   -4, PLAYER_PIECE_PAL1
    player_piece  -49,    3, PLAYER_PIECE_PAL1

data_78_455f_PlayerFrame_183:
    player_frame_header   7, $28, $16, data_78_4750_PlayerTiles + $23a0
    player_piece  -37,   -3, PLAYER_PIECE_PAL0
    player_piece  -33,    3, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece   -5,   -2, PLAYER_PIECE_PAL0
    player_piece  -38,   -3, PLAYER_PIECE_PAL1
    player_piece  -49,    3, PLAYER_PIECE_PAL1
    player_piece  -22,    0, PLAYER_PIECE_PAL1

data_78_4580_PlayerFrame_184:
    player_frame_header   8, $28, $16, data_78_4750_PlayerTiles + $2480
    player_piece  -15,  -11, PLAYER_PIECE_PAL0
    player_piece  -37,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL0
    player_piece   -5,   -3, PLAYER_PIECE_PAL0
    player_piece  -33,    3, PLAYER_PIECE_PAL0
    player_piece  -38,   -3, PLAYER_PIECE_PAL1
    player_piece  -22,   -3, PLAYER_PIECE_PAL1
    player_piece  -49,    3, PLAYER_PIECE_PAL1

data_78_45a5_PlayerFrame_185:
    player_frame_header   7, $27, $16, data_78_4750_PlayerTiles + $2580
    player_piece  -36,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    3, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece   -7,    3, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -39,   -4, PLAYER_PIECE_PAL1
    player_piece  -48,    3, PLAYER_PIECE_PAL1

data_78_45c6_PlayerFrame_186:
    player_frame_header   7, $27, $1c, data_78_4750_PlayerTiles + $2660
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -12,   -4, PLAYER_PIECE_PAL0
    player_piece  -20,    4, PLAYER_PIECE_PAL0
    player_piece  -39,    0, PLAYER_PIECE_PAL1
    player_piece  -43,    8, PLAYER_PIECE_PAL1

data_78_45e7_PlayerFrame_187:
    player_frame_header   6, $27, $1f, data_78_4750_PlayerTiles + $2740
    player_piece  -24,   -9, PLAYER_PIECE_PAL0
    player_piece  -25,   -1, PLAYER_PIECE_PAL0
    player_piece  -34,    3, PLAYER_PIECE_PAL0
    player_piece  -30,   11, PLAYER_PIECE_PAL0
    player_piece  -46,   12, PLAYER_PIECE_PAL0
    player_piece  -40,   14, PLAYER_PIECE_PAL1

data_78_4604_PlayerFrame_188:
    player_frame_header   5, $27, $21, data_78_4750_PlayerTiles + $2800
    player_piece  -30,  -11, PLAYER_PIECE_PAL0
    player_piece  -31,   -3, PLAYER_PIECE_PAL0
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece  -29,   13, PLAYER_PIECE_PAL0
    player_piece  -13,   13, PLAYER_PIECE_PAL0

data_78_461d_PlayerFrame_189:
    player_frame_header   5, $27, $20, data_78_4750_PlayerTiles + $28a0
    player_piece  -33,  -11, PLAYER_PIECE_PAL0
    player_piece  -35,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -13,    5, PLAYER_PIECE_PAL0
    player_piece  -26,   13, PLAYER_PIECE_PAL0

data_78_4636_PlayerFrame_190:
    player_frame_header   5, $20, $1d, data_78_4750_PlayerTiles + $2940
    player_piece  -35,  -11, PLAYER_PIECE_PAL0
    player_piece  -34,   -3, PLAYER_PIECE_PAL0
    player_piece  -25,    5, PLAYER_PIECE_PAL0
    player_piece   -9,    5, PLAYER_PIECE_PAL0
    player_piece  -19,   10, PLAYER_PIECE_PAL0

data_78_464f_PlayerFrame_191:
    player_frame_header   6, $23, $1e, data_78_4750_PlayerTiles + $29e0
    player_piece  -27,  -11, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    5, PLAYER_PIECE_PAL0
    player_piece  -42,    4, PLAYER_PIECE_PAL0
    player_piece  -43,    3, PLAYER_PIECE_PAL1

data_78_466c_PlayerFrame_192:
    player_frame_header   6, $23, $1e, data_78_4750_PlayerTiles + $2aa0
    player_piece  -30,  -10, PLAYER_PIECE_PAL0
    player_piece  -33,   -2, PLAYER_PIECE_PAL0
    player_piece  -23,    5, PLAYER_PIECE_PAL0
    player_piece  -17,   -3, PLAYER_PIECE_PAL0
    player_piece   -1,   -1, PLAYER_PIECE_PAL0
    player_piece  -43,   -2, PLAYER_PIECE_PAL1

data_78_4689_PlayerFrame_193:
    player_frame_header   6, $23, $1f, data_78_4750_PlayerTiles + $2b60
    player_piece  -18,   -4, PLAYER_PIECE_PAL0
    player_piece  -34,  -10, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -34,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    6, PLAYER_PIECE_PAL0
    player_piece  -43,   -4, PLAYER_PIECE_PAL1

data_78_46a6_PlayerFrame_194:
    player_frame_header   6, $23, $20, data_78_4750_PlayerTiles + $2c20
    player_piece  -35,  -13, PLAYER_PIECE_PAL0
    player_piece  -33,   -5, PLAYER_PIECE_PAL0
    player_piece  -17,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -18,    7, PLAYER_PIECE_PAL0
    player_piece  -43,   -8, PLAYER_PIECE_PAL1

data_78_46c3_PlayerFrame_195:
    player_frame_header   7, $23, $1f, data_78_4750_PlayerTiles + $2ce0
    player_piece  -34,  -12, PLAYER_PIECE_PAL0
    player_piece  -33,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,    4, PLAYER_PIECE_PAL0
    player_piece   -8,   -1, PLAYER_PIECE_PAL0
    player_piece  -18,   12, PLAYER_PIECE_PAL0
    player_piece  -44,   -5, PLAYER_PIECE_PAL1

data_78_46e4_PlayerFrame_196:
    player_frame_header   5, $23, $1f, data_78_4750_PlayerTiles + $2dc0
    player_piece  -30,   -9, PLAYER_PIECE_PAL0
    player_piece  -33,   -1, PLAYER_PIECE_PAL0
    player_piece  -34,    6, PLAYER_PIECE_PAL0
    player_piece  -17,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0

data_78_46fd_PlayerFrame_197:
    player_frame_header   8, $23, $21, data_78_4750_PlayerTiles + $2e60
    player_piece  -18,  -17, PLAYER_PIECE_PAL0
    player_piece  -24,   -9, PLAYER_PIECE_PAL0
    player_piece   -8,   -9, PLAYER_PIECE_PAL0
    player_piece  -33,   -1, PLAYER_PIECE_PAL0
    player_piece  -17,   -1, PLAYER_PIECE_PAL0
    player_piece   -1,   -1, PLAYER_PIECE_PAL0
    player_piece  -34,    7, PLAYER_PIECE_PAL0
    player_piece  -44,    7, PLAYER_PIECE_PAL1

data_78_4722_PlayerFrame_198:
    player_frame_header   7, $23, $22, data_78_4750_PlayerTiles + $2f60
    player_piece  -18,  -11, PLAYER_PIECE_PAL0
    player_piece  -33,    1, PLAYER_PIECE_PAL0
    player_piece  -39,    9, PLAYER_PIECE_PAL0
    player_piece  -17,   -3, PLAYER_PIECE_PAL0
    player_piece  -17,    5, PLAYER_PIECE_PAL0
    player_piece   -1,    2, PLAYER_PIECE_PAL0
    player_piece  -43,    9, PLAYER_PIECE_PAL1

    ds   $4750 - @, 0                    ; the bank pads to a 16-byte boundary here
data_78_4750_PlayerTiles:
; INCBINd by main.asm - see the header above
