; ==================================================================
; Bank $74. Gex's animation frames 117 to 183 of PLAYER_GFX_SET_TUT_TV.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $4832, then 882 tiles of graphics from $4840 to $7f5f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/player_sprite_data/bank7f_player_sprite_data.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_74_4000_PlayerFrame_117:
    player_frame_header   8, $20, $1d, data_74_4840_PlayerTiles + $0000
    player_piece  -28,  -10, PLAYER_PIECE_PAL0
    player_piece  -21,   -2, PLAYER_PIECE_PAL0
    player_piece  -19,    5, PLAYER_PIECE_PAL0
    player_piece  -12,   -7, PLAYER_PIECE_PAL0
    player_piece   -5,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -3, PLAYER_PIECE_PAL1

data_74_4025_PlayerFrame_118:
    player_frame_header   8, $21, $1a, data_74_4840_PlayerTiles + $0100
    player_piece  -31,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece  -20,    2, PLAYER_PIECE_PAL0
    player_piece  -15,   -9, PLAYER_PIECE_PAL0
    player_piece   -8,   -1, PLAYER_PIECE_PAL0
    player_piece  -31,   -4, PLAYER_PIECE_PAL1
    player_piece  -37,    2, PLAYER_PIECE_PAL1
    player_piece  -15,   -5, PLAYER_PIECE_PAL1

data_74_404a_PlayerFrame_119:
    player_frame_header   8, $20, $1d, data_74_4840_PlayerTiles + $0200
    player_piece  -25,  -10, PLAYER_PIECE_PAL0
    player_piece  -22,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    5, PLAYER_PIECE_PAL0
    player_piece   -9,   -7, PLAYER_PIECE_PAL0
    player_piece  -17,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -3, PLAYER_PIECE_PAL1

data_74_406f_PlayerFrame_120:
    player_frame_header   8, $20, $1e, data_74_4840_PlayerTiles + $0300
    player_piece  -21,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL0
    player_piece   -8,   -6, PLAYER_PIECE_PAL0
    player_piece  -14,    2, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -30,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -3, PLAYER_PIECE_PAL1

data_74_4094_PlayerFrame_121:
    player_frame_header   8, $20, $1f, data_74_4840_PlayerTiles + $0400
    player_piece  -20,   -7, PLAYER_PIECE_PAL0
    player_piece  -22,    1, PLAYER_PIECE_PAL0
    player_piece  -34,    7, PLAYER_PIECE_PAL0
    player_piece   -6,   -4, PLAYER_PIECE_PAL0
    player_piece  -21,    5, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1

data_74_40b9_PlayerFrame_122:
    player_frame_header   9, $1f, $1c, data_74_4840_PlayerTiles + $0500
    player_piece  -27,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece  -19,    4, PLAYER_PIECE_PAL0
    player_piece  -11,   -6, PLAYER_PIECE_PAL0
    player_piece   -5,    2, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -36,    3, PLAYER_PIECE_PAL1
    player_piece  -13,   -3, PLAYER_PIECE_PAL1
    player_piece  -24,    4, PLAYER_PIECE_PAL1

data_74_40e2_PlayerFrame_123:
    player_frame_header   9, $21, $1b, data_74_4840_PlayerTiles + $0620
    player_piece  -30,  -10, PLAYER_PIECE_PAL0
    player_piece  -24,   -2, PLAYER_PIECE_PAL0
    player_piece  -20,    3, PLAYER_PIECE_PAL0
    player_piece  -14,   -6, PLAYER_PIECE_PAL0
    player_piece   -8,    2, PLAYER_PIECE_PAL0
    player_piece  -31,   -5, PLAYER_PIECE_PAL1
    player_piece  -38,    3, PLAYER_PIECE_PAL1
    player_piece  -15,   -3, PLAYER_PIECE_PAL1
    player_piece  -26,    3, PLAYER_PIECE_PAL1

data_74_410b_PlayerFrame_124:
    player_frame_header   9, $21, $1c, data_74_4840_PlayerTiles + $0740
    player_piece  -25,  -10, PLAYER_PIECE_PAL0
    player_piece  -22,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    4, PLAYER_PIECE_PAL0
    player_piece   -9,   -6, PLAYER_PIECE_PAL0
    player_piece  -11,    2, PLAYER_PIECE_PAL0
    player_piece  -38,   -5, PLAYER_PIECE_PAL1
    player_piece  -38,    3, PLAYER_PIECE_PAL1
    player_piece  -15,   -3, PLAYER_PIECE_PAL1
    player_piece  -28,    4, PLAYER_PIECE_PAL1

data_74_4134_PlayerFrame_125:
    player_frame_header   4, $21, $19, data_74_4840_PlayerTiles + $0860
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_74_4149_PlayerFrame_126:
    player_frame_header   4, $21, $18, data_74_4840_PlayerTiles + $08e0
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_74_415e_PlayerFrame_127:
    player_frame_header   4, $21, $18, data_74_4840_PlayerTiles + $0960
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_74_4173_PlayerFrame_128:
    player_frame_header   4, $21, $18, data_74_4840_PlayerTiles + $09e0
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_74_4188_PlayerFrame_129:
    player_frame_header   4, $21, $18, data_74_4840_PlayerTiles + $0a60
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_74_419d_PlayerFrame_130:
    player_frame_header   4, $21, $18, data_74_4840_PlayerTiles + $0ae0
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_74_41b2_PlayerFrame_131:
    player_frame_header   4, $21, $18, data_74_4840_PlayerTiles + $0b60
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_74_41c7_PlayerFrame_132:
    player_frame_header   7, $20, $1a, data_74_4840_PlayerTiles + $0be0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -17,   -8, PLAYER_PIECE_PAL0
    player_piece  -17,    0, PLAYER_PIECE_PAL0
    player_piece  -36,  -11, PLAYER_PIECE_PAL1
    player_piece  -37,   -3, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1

data_74_41e8_PlayerFrame_133:
    player_frame_header   7, $1f, $19, data_74_4840_PlayerTiles + $0cc0
    player_piece  -30,   -9, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL0
    player_piece  -10,   -9, PLAYER_PIECE_PAL0
    player_piece  -17,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,  -12, PLAYER_PIECE_PAL1
    player_piece  -23,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,   -1, PLAYER_PIECE_PAL1

data_74_4209_PlayerFrame_134:
    player_frame_header   6, $1f, $19, data_74_4840_PlayerTiles + $0da0
    player_piece  -28,   -9, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL0
    player_piece  -10,   -7, PLAYER_PIECE_PAL0
    player_piece  -17,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,  -12, PLAYER_PIECE_PAL1
    player_piece  -23,   -4, PLAYER_PIECE_PAL1

data_74_4226_PlayerFrame_135:
    player_frame_header   8, $1a, $1e, data_74_4840_PlayerTiles + $0e60
    player_piece  -23,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece   -5,   -7, PLAYER_PIECE_PAL0
    player_piece   -4,    1, PLAYER_PIECE_PAL0
    player_piece   -2,    4, PLAYER_PIECE_PAL0
    player_piece  -28,  -12, PLAYER_PIECE_PAL1
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece   -5,    4, PLAYER_PIECE_PAL1

data_74_424b_PlayerFrame_136:
    player_frame_header   8, $16, $1e, data_74_4840_PlayerTiles + $0f60
    player_piece  -10,  -11, PLAYER_PIECE_PAL0
    player_piece  -17,   -3, PLAYER_PIECE_PAL0
    player_piece  -17,    4, PLAYER_PIECE_PAL0
    player_piece   -1,   -3, PLAYER_PIECE_PAL0
    player_piece   -1,    4, PLAYER_PIECE_PAL0
    player_piece  -20,   -5, PLAYER_PIECE_PAL1
    player_piece  -27,    3, PLAYER_PIECE_PAL1
    player_piece   -4,   -3, PLAYER_PIECE_PAL1

data_74_4270_PlayerFrame_137:
    player_frame_header   6, $15, $1e, data_74_4840_PlayerTiles + $1060
    player_piece  -10,  -11, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece  -19,   -5, PLAYER_PIECE_PAL1
    player_piece  -26,    3, PLAYER_PIECE_PAL1
    player_piece   -3,   -3, PLAYER_PIECE_PAL1

data_74_428d_PlayerFrame_138:
    player_frame_header   8, $18, $1f, data_74_4840_PlayerTiles + $1120
    player_piece  -15,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece  -26,    5, PLAYER_PIECE_PAL0
    player_piece   -4,   -2, PLAYER_PIECE_PAL0
    player_piece   -4,    5, PLAYER_PIECE_PAL0
    player_piece  -22,   -4, PLAYER_PIECE_PAL1
    player_piece  -33,    4, PLAYER_PIECE_PAL1
    player_piece   -6,   -4, PLAYER_PIECE_PAL1

data_74_42b2_PlayerFrame_139:
    player_frame_header   7, $18, $1d, data_74_4840_PlayerTiles + $1220
    player_piece  -17,   -9, PLAYER_PIECE_PAL0
    player_piece  -20,   -1, PLAYER_PIECE_PAL0
    player_piece  -18,    3, PLAYER_PIECE_PAL0
    player_piece   -4,   -1, PLAYER_PIECE_PAL0
    player_piece  -22,   -5, PLAYER_PIECE_PAL1
    player_piece  -33,    3, PLAYER_PIECE_PAL1
    player_piece   -6,   -4, PLAYER_PIECE_PAL1

data_74_42d3_PlayerFrame_140:
    player_frame_header   8, $18, $21, data_74_4840_PlayerTiles + $1300
    player_piece  -20,  -14, PLAYER_PIECE_PAL0
    player_piece  -16,   -6, PLAYER_PIECE_PAL0
    player_piece  -20,    2, PLAYER_PIECE_PAL0
    player_piece  -28,    7, PLAYER_PIECE_PAL0
    player_piece   -4,    2, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL1
    player_piece  -35,    4, PLAYER_PIECE_PAL1
    player_piece   -5,   -4, PLAYER_PIECE_PAL1

data_74_42f8_PlayerFrame_141:
    player_frame_header   7, $1f, $1d, data_74_4840_PlayerTiles + $1400
    player_piece  -26,   -5, PLAYER_PIECE_PAL0
    player_piece  -26,    2, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    2, PLAYER_PIECE_PAL1
    player_piece  -12,   -1, PLAYER_PIECE_PAL1

data_74_4319_PlayerFrame_142:
    player_frame_header   7, $1f, $1c, data_74_4840_PlayerTiles + $14e0
    player_piece  -26,   -4, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece  -10,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    1, PLAYER_PIECE_PAL1
    player_piece  -12,   -1, PLAYER_PIECE_PAL1

data_74_433a_PlayerFrame_143:
    player_frame_header   6, $1f, $1c, data_74_4840_PlayerTiles + $15c0
    player_piece  -26,   -5, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    1, PLAYER_PIECE_PAL1
    player_piece  -12,   -1, PLAYER_PIECE_PAL1

data_74_4357_PlayerFrame_144:
    player_frame_header   7, $1e, $1c, data_74_4840_PlayerTiles + $1680
    player_piece  -25,   -5, PLAYER_PIECE_PAL0
    player_piece  -25,    1, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -17,    1, PLAYER_PIECE_PAL0
    player_piece  -35,   -5, PLAYER_PIECE_PAL1
    player_piece  -36,    1, PLAYER_PIECE_PAL1
    player_piece  -11,   -3, PLAYER_PIECE_PAL1

data_74_4378_PlayerFrame_145:
    player_frame_header   8, $1f, $1c, data_74_4840_PlayerTiles + $1760
    player_piece  -26,   -6, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -17,    1, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    1, PLAYER_PIECE_PAL1
    player_piece  -12,   -3, PLAYER_PIECE_PAL1
    player_piece  -10,    1, PLAYER_PIECE_PAL1

data_74_439d_PlayerFrame_146:
    player_frame_header   8, $1f, $1b, data_74_4840_PlayerTiles + $1860
    player_piece  -26,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,    0, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece  -21,    0, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    0, PLAYER_PIECE_PAL1
    player_piece  -12,   -3, PLAYER_PIECE_PAL1
    player_piece  -10,    0, PLAYER_PIECE_PAL1

data_74_43c2_PlayerFrame_147:
    player_frame_header   7, $1f, $1c, data_74_4840_PlayerTiles + $1960
    player_piece  -26,   -5, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece  -10,   -1, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    1, PLAYER_PIECE_PAL1
    player_piece  -12,   -3, PLAYER_PIECE_PAL1
    player_piece  -11,    1, PLAYER_PIECE_PAL1

data_74_43e3_PlayerFrame_148:
    player_frame_header   8, $1e, $1c, data_74_4840_PlayerTiles + $1a40
    player_piece  -25,   -5, PLAYER_PIECE_PAL0
    player_piece  -25,    1, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -35,   -5, PLAYER_PIECE_PAL1
    player_piece  -36,    1, PLAYER_PIECE_PAL1
    player_piece  -11,   -4, PLAYER_PIECE_PAL1
    player_piece   -8,    1, PLAYER_PIECE_PAL1

data_74_4408_PlayerFrame_149:
    player_frame_header   8, $1f, $1d, data_74_4840_PlayerTiles + $1b40
    player_piece  -20,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,    2, PLAYER_PIECE_PAL0
    player_piece   -4,   -5, PLAYER_PIECE_PAL0
    player_piece   -3,    2, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -36,    2, PLAYER_PIECE_PAL1
    player_piece  -23,   -3, PLAYER_PIECE_PAL1
    player_piece  -23,    2, PLAYER_PIECE_PAL1

data_74_442d_PlayerFrame_150:
    player_frame_header   7, $1f, $1c, data_74_4840_PlayerTiles + $1c40
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,    1, PLAYER_PIECE_PAL0
    player_piece   -4,   -2, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -36,    1, PLAYER_PIECE_PAL1
    player_piece  -23,   -3, PLAYER_PIECE_PAL1
    player_piece  -23,    1, PLAYER_PIECE_PAL1

data_74_444e_PlayerFrame_151:
    player_frame_header   7, $1f, $1c, data_74_4840_PlayerTiles + $1d20
    player_piece  -20,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,    1, PLAYER_PIECE_PAL0
    player_piece   -4,   -3, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -36,    1, PLAYER_PIECE_PAL1
    player_piece  -23,   -3, PLAYER_PIECE_PAL1
    player_piece  -23,    1, PLAYER_PIECE_PAL1

data_74_446f_PlayerFrame_152:
    player_frame_header   8, $1e, $1c, data_74_4840_PlayerTiles + $1e00
    player_piece  -19,   -5, PLAYER_PIECE_PAL0
    player_piece  -19,    1, PLAYER_PIECE_PAL0
    player_piece   -3,   -3, PLAYER_PIECE_PAL0
    player_piece   -3,    1, PLAYER_PIECE_PAL0
    player_piece  -35,   -5, PLAYER_PIECE_PAL1
    player_piece  -35,    1, PLAYER_PIECE_PAL1
    player_piece  -22,   -3, PLAYER_PIECE_PAL1
    player_piece  -22,    1, PLAYER_PIECE_PAL1

data_74_4494_PlayerFrame_153:
    player_frame_header   8, $1f, $1c, data_74_4840_PlayerTiles + $1f00
    player_piece  -20,   -6, PLAYER_PIECE_PAL0
    player_piece  -20,    1, PLAYER_PIECE_PAL0
    player_piece   -4,   -3, PLAYER_PIECE_PAL0
    player_piece   -4,    1, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -36,    1, PLAYER_PIECE_PAL1
    player_piece  -23,   -3, PLAYER_PIECE_PAL1
    player_piece  -23,    1, PLAYER_PIECE_PAL1

data_74_44b9_PlayerFrame_154:
    player_frame_header   7, $1f, $1b, data_74_4840_PlayerTiles + $2000
    player_piece  -20,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,    0, PLAYER_PIECE_PAL0
    player_piece   -4,   -2, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -36,    0, PLAYER_PIECE_PAL1
    player_piece  -23,   -3, PLAYER_PIECE_PAL1
    player_piece  -23,    0, PLAYER_PIECE_PAL1

data_74_44da_PlayerFrame_155:
    player_frame_header   7, $1f, $1c, data_74_4840_PlayerTiles + $20e0
    player_piece  -20,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,    1, PLAYER_PIECE_PAL0
    player_piece   -4,   -1, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -36,    1, PLAYER_PIECE_PAL1
    player_piece  -23,   -3, PLAYER_PIECE_PAL1
    player_piece  -23,    1, PLAYER_PIECE_PAL1

data_74_44fb_PlayerFrame_156:
    player_frame_header   8, $1e, $1c, data_74_4840_PlayerTiles + $21c0
    player_piece  -19,   -5, PLAYER_PIECE_PAL0
    player_piece  -19,    1, PLAYER_PIECE_PAL0
    player_piece   -3,   -3, PLAYER_PIECE_PAL0
    player_piece   -1,    1, PLAYER_PIECE_PAL0
    player_piece  -35,   -5, PLAYER_PIECE_PAL1
    player_piece  -35,    1, PLAYER_PIECE_PAL1
    player_piece  -22,   -3, PLAYER_PIECE_PAL1
    player_piece  -22,    1, PLAYER_PIECE_PAL1

data_74_4520_PlayerFrame_157:
    player_frame_header   9, $1f, $28, data_74_4840_PlayerTiles + $22c0
    player_piece  -22,  -11, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,    5, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -37,   -5, PLAYER_PIECE_PAL1
    player_piece  -42,    3, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1
    player_piece  -23,    4, PLAYER_PIECE_PAL1

data_74_4549_PlayerFrame_158:
    player_frame_header   8, $1f, $20, data_74_4840_PlayerTiles + $23e0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece  -36,   -6, PLAYER_PIECE_PAL1
    player_piece  -37,    2, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,    2, PLAYER_PIECE_PAL1

data_74_456e_PlayerFrame_159:
    player_frame_header   8, $1f, $20, data_74_4840_PlayerTiles + $24e0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece  -36,   -6, PLAYER_PIECE_PAL1
    player_piece  -37,    2, PLAYER_PIECE_PAL1
    player_piece  -16,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,    2, PLAYER_PIECE_PAL1

data_74_4593_PlayerFrame_160:
    player_frame_header   8, $1f, $20, data_74_4840_PlayerTiles + $25e0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece  -36,   -6, PLAYER_PIECE_PAL1
    player_piece  -37,    2, PLAYER_PIECE_PAL1
    player_piece  -16,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,    2, PLAYER_PIECE_PAL1

data_74_45b8_PlayerFrame_161:
    player_frame_header   8, $1f, $20, data_74_4840_PlayerTiles + $26e0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece  -36,   -6, PLAYER_PIECE_PAL1
    player_piece  -37,    2, PLAYER_PIECE_PAL1
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -16,    2, PLAYER_PIECE_PAL1

data_74_45dd_PlayerFrame_162:
    player_frame_header   9, $1f, $20, data_74_4840_PlayerTiles + $27e0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -18,    2, PLAYER_PIECE_PAL0
    player_piece   -7,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -8, PLAYER_PIECE_PAL1
    player_piece  -13,    0, PLAYER_PIECE_PAL1
    player_piece   -1,    2, PLAYER_PIECE_PAL1

data_74_4606_PlayerFrame_163:
    player_frame_header   7, $1f, $20, data_74_4840_PlayerTiles + $2900
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -29,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -7, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_74_4627_PlayerFrame_164:
    player_frame_header   8, $1f, $23, data_74_4840_PlayerTiles + $29e0
    player_piece  -29,   -8, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -29,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,  -11, PLAYER_PIECE_PAL1
    player_piece  -13,   -3, PLAYER_PIECE_PAL1
    player_piece  -13,    5, PLAYER_PIECE_PAL1

data_74_464c_PlayerFrame_165:
    player_frame_header   6, $1f, $24, data_74_4840_PlayerTiles + $2ae0
    player_piece  -36,   -6, PLAYER_PIECE_PAL0
    player_piece  -36,    2, PLAYER_PIECE_PAL0
    player_piece  -19,  -14, PLAYER_PIECE_PAL1
    player_piece  -32,   -6, PLAYER_PIECE_PAL1
    player_piece  -32,    2, PLAYER_PIECE_PAL1
    player_piece  -19,    6, PLAYER_PIECE_PAL1

data_74_4669_PlayerFrame_166:
    player_frame_header   4, $1f, $26, data_74_4840_PlayerTiles + $2ba0
    player_piece  -40,  -15, PLAYER_PIECE_PAL1
    player_piece  -38,   -7, PLAYER_PIECE_PAL1
    player_piece  -38,    1, PLAYER_PIECE_PAL1
    player_piece  -40,    8, PLAYER_PIECE_PAL1

data_74_467e_PlayerFrame_167:
    player_frame_header   3, $1e, $20, data_74_4840_PlayerTiles + $2c20
    player_piece  -40,  -14, PLAYER_PIECE_PAL1
    player_piece  -37,   -6, PLAYER_PIECE_PAL1
    player_piece  -37,    2, PLAYER_PIECE_PAL1

data_74_468f_PlayerFrame_168:
    player_frame_header   2, $1e, $1b, data_74_4840_PlayerTiles + $2c80
    player_piece  -37,   -6, PLAYER_PIECE_PAL1
    player_piece  -40,   -3, PLAYER_PIECE_PAL1

data_74_469c_PlayerFrame_169:
    player_frame_header   8, $1c, $19, data_74_4840_PlayerTiles + $2cc0
    player_piece  -16,  -15, PLAYER_PIECE_PAL0
    player_piece  -23,   -7, PLAYER_PIECE_PAL0
    player_piece   -7,   -7, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,    1, PLAYER_PIECE_PAL0
    player_piece  -32,   -7, PLAYER_PIECE_PAL1
    player_piece  -17,   -7, PLAYER_PIECE_PAL1
    player_piece  -39,    1, PLAYER_PIECE_PAL1

data_74_46c1_PlayerFrame_170:
    player_frame_header   8, $1f, $20, data_74_4840_PlayerTiles + $2dc0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece  -36,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    2, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,    2, PLAYER_PIECE_PAL1

data_74_46e6_PlayerFrame_171:
    player_frame_header   8, $1e, $20, data_74_4840_PlayerTiles + $2ec0
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece  -36,   -4, PLAYER_PIECE_PAL1
    player_piece  -25,    2, PLAYER_PIECE_PAL1
    player_piece  -23,   -4, PLAYER_PIECE_PAL1
    player_piece   -9,    2, PLAYER_PIECE_PAL1

data_74_470b_PlayerFrame_172:
    player_frame_header   6, $1c, $1f, data_74_4840_PlayerTiles + $2fc0
    player_piece  -26,   -7, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece   -7,    1, PLAYER_PIECE_PAL0
    player_piece  -23,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,    1, PLAYER_PIECE_PAL1

data_74_4728_PlayerFrame_173:
    player_frame_header   6, $1b, $1d, data_74_4840_PlayerTiles + $3080
    player_piece  -26,   -5, PLAYER_PIECE_PAL0
    player_piece  -18,   -1, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece   -2,   -1, PLAYER_PIECE_PAL0
    player_piece  -23,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,   -1, PLAYER_PIECE_PAL1

data_74_4745_PlayerFrame_174:
    player_frame_header   4, $19, $1d, data_74_4840_PlayerTiles + $3140
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece   -3,   -1, PLAYER_PIECE_PAL0
    player_piece  -23,   -3, PLAYER_PIECE_PAL1

data_74_475a_PlayerFrame_175:
    player_frame_header   4, $15, $1d, data_74_4840_PlayerTiles + $31c0
    player_piece  -19,   -2, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0
    player_piece   -3,   -1, PLAYER_PIECE_PAL0
    player_piece  -22,   -2, PLAYER_PIECE_PAL1

data_74_476f_PlayerFrame_176:
    player_frame_header   2, $10, $1d, data_74_4840_PlayerTiles + $3240
    player_piece  -16,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0

data_74_477c_PlayerFrame_177:
    player_frame_header   2, $0c, $1c, data_74_4840_PlayerTiles + $3280
    player_piece  -16,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0

data_74_4789_PlayerFrame_178:
    player_frame_header   6, $0f, $2e, data_74_4840_PlayerTiles + $32c0
    player_piece  -16,  -17, PLAYER_PIECE_PAL0
    player_piece  -16,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,    7, PLAYER_PIECE_PAL0
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -18,    2, PLAYER_PIECE_PAL1

data_74_47a6_PlayerFrame_179:
    player_frame_header   6, $26, $16, data_74_4840_PlayerTiles + $3380
    player_piece  -36,   -7, PLAYER_PIECE_PAL0
    player_piece  -36,    1, PLAYER_PIECE_PAL0
    player_piece  -23,    3, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece  -18,   -2, PLAYER_PIECE_PAL0
    player_piece  -47,   -2, PLAYER_PIECE_PAL1

data_74_47c3_PlayerFrame_180:
    player_frame_header   6, $26, $16, data_74_4840_PlayerTiles + $3440
    player_piece  -36,   -6, PLAYER_PIECE_PAL0
    player_piece  -36,    2, PLAYER_PIECE_PAL0
    player_piece  -20,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,    3, PLAYER_PIECE_PAL0
    player_piece  -18,   -2, PLAYER_PIECE_PAL0
    player_piece  -47,   -1, PLAYER_PIECE_PAL1

data_74_47e0_PlayerFrame_181:
    player_frame_header   6, $27, $16, data_74_4840_PlayerTiles + $3500
    player_piece  -37,   -6, PLAYER_PIECE_PAL0
    player_piece  -37,    2, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -32,    3, PLAYER_PIECE_PAL0
    player_piece  -19,   -2, PLAYER_PIECE_PAL0
    player_piece  -48,   -1, PLAYER_PIECE_PAL1

data_74_47fd_PlayerFrame_182:
    player_frame_header   6, $27, $16, data_74_4840_PlayerTiles + $35c0
    player_piece  -37,   -6, PLAYER_PIECE_PAL0
    player_piece  -37,    2, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -20,    3, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -48,   -1, PLAYER_PIECE_PAL1

data_74_481a_PlayerFrame_183:
    player_frame_header   5, $27, $16, data_74_4840_PlayerTiles + $3680
    player_piece  -37,   -5, PLAYER_PIECE_PAL0
    player_piece  -38,    3, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,   -2, PLAYER_PIECE_PAL0
    player_piece  -48,    0, PLAYER_PIECE_PAL1

    ds   $4840 - @, 0                    ; the bank pads to a 16-byte boundary here
data_74_4840_PlayerTiles:
; INCBINd by main.asm - see the header above
