; ==================================================================
; Bank $65. Gex's animation frames 223 to 236 of PLAYER_GFX_SET_ANIME_CHANNEL.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $41d1, then 198 tiles of graphics from $41e0 to $4e3f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/player_sprite_data/bank7f_player_sprite_data.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_65_4000_PlayerFrame_223:
    player_frame_header   7, $1c, $1d, data_65_41e0_PlayerTiles + $0000
    player_piece  -10,   -6, PLAYER_PIECE_PAL0
    player_piece  -21,    2, PLAYER_PIECE_PAL0
    player_piece  -29,  -14, PLAYER_PIECE_PAL1
    player_piece  -26,   -6, PLAYER_PIECE_PAL1
    player_piece  -10,   -6, PLAYER_PIECE_PAL1
    player_piece  -27,    2, PLAYER_PIECE_PAL1
    player_piece  -29,    7, PLAYER_PIECE_PAL1

data_65_4021_PlayerFrame_224:
    player_frame_header   8, $1d, $21, data_65_41e0_PlayerTiles + $00e0
    player_piece  -12,    2, PLAYER_PIECE_PAL0
    player_piece  -23,   10, PLAYER_PIECE_PAL0
    player_piece  -32,  -14, PLAYER_PIECE_PAL1
    player_piece  -11,  -14, PLAYER_PIECE_PAL1
    player_piece  -26,   -6, PLAYER_PIECE_PAL1
    player_piece  -10,   -6, PLAYER_PIECE_PAL1
    player_piece  -24,    2, PLAYER_PIECE_PAL1
    player_piece  -27,   10, PLAYER_PIECE_PAL1

data_65_4046_PlayerFrame_225:
    player_frame_header   7, $1c, $1c, data_65_41e0_PlayerTiles + $01e0
    player_piece  -12,    0, PLAYER_PIECE_PAL0
    player_piece  -21,    8, PLAYER_PIECE_PAL0
    player_piece  -25,  -13, PLAYER_PIECE_PAL1
    player_piece  -26,   -5, PLAYER_PIECE_PAL1
    player_piece  -10,   -6, PLAYER_PIECE_PAL1
    player_piece  -25,    2, PLAYER_PIECE_PAL1
    player_piece  -32,   10, PLAYER_PIECE_PAL1

data_65_4067_PlayerFrame_226:
    player_frame_header   6, $1e, $18, data_65_41e0_PlayerTiles + $02c0
    player_piece   -9,   -6, PLAYER_PIECE_PAL0
    player_piece  -13,    2, PLAYER_PIECE_PAL0
    player_piece  -29,  -14, PLAYER_PIECE_PAL1
    player_piece  -28,   -6, PLAYER_PIECE_PAL1
    player_piece  -12,   -6, PLAYER_PIECE_PAL1
    player_piece  -27,    2, PLAYER_PIECE_PAL1

data_65_4084_PlayerFrame_227:
    player_frame_header   6, $20, $1a, data_65_41e0_PlayerTiles + $0380
    player_piece  -14,    2, PLAYER_PIECE_PAL0
    player_piece  -12,    4, PLAYER_PIECE_PAL0
    player_piece  -30,  -13, PLAYER_PIECE_PAL1
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -27,    3, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1

data_65_40a1_PlayerFrame_228:
    player_frame_header   7, $1e, $1b, data_65_41e0_PlayerTiles + $0440
    player_piece  -10,   -6, PLAYER_PIECE_PAL0
    player_piece  -14,    2, PLAYER_PIECE_PAL0
    player_piece  -31,  -14, PLAYER_PIECE_PAL1
    player_piece  -28,   -6, PLAYER_PIECE_PAL1
    player_piece  -12,   -6, PLAYER_PIECE_PAL1
    player_piece  -27,    2, PLAYER_PIECE_PAL1
    player_piece  -29,    5, PLAYER_PIECE_PAL1

data_65_40c2_PlayerFrame_229:
    player_frame_header   8, $21, $1d, data_65_41e0_PlayerTiles + $0520
    player_piece  -40,   -4, PLAYER_PIECE_PAL0
    player_piece  -40,    4, PLAYER_PIECE_PAL0
    player_piece  -28,  -11, PLAYER_PIECE_PAL1
    player_piece  -24,   -3, PLAYER_PIECE_PAL1
    player_piece  -28,    5, PLAYER_PIECE_PAL1
    player_piece  -12,  -12, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1
    player_piece  -22,    4, PLAYER_PIECE_PAL1

data_65_40e7_PlayerFrame_230:
    player_frame_header   7, $20, $1e, data_65_41e0_PlayerTiles + $0620
    player_piece  -35,    2, PLAYER_PIECE_PAL0
    player_piece  -37,    5, PLAYER_PIECE_PAL0
    player_piece  -27,  -16, PLAYER_PIECE_PAL1
    player_piece  -30,   -8, PLAYER_PIECE_PAL1
    player_piece  -30,    0, PLAYER_PIECE_PAL1
    player_piece  -18,    5, PLAYER_PIECE_PAL1
    player_piece  -20,   -7, PLAYER_PIECE_PAL1

data_65_4108_PlayerFrame_231:
    player_frame_header   6, $21, $1d, data_65_41e0_PlayerTiles + $0700
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -31,  -11, PLAYER_PIECE_PAL1
    player_piece  -27,   -3, PLAYER_PIECE_PAL1
    player_piece  -29,    5, PLAYER_PIECE_PAL1
    player_piece  -15,  -11, PLAYER_PIECE_PAL1
    player_piece  -13,    5, PLAYER_PIECE_PAL1

data_65_4125_PlayerFrame_232:
    player_frame_header   8, $21, $1f, data_65_41e0_PlayerTiles + $07c0
    player_piece  -15,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    7, PLAYER_PIECE_PAL0
    player_piece  -33,  -16, PLAYER_PIECE_PAL1
    player_piece  -31,   -8, PLAYER_PIECE_PAL1
    player_piece  -12,   -8, PLAYER_PIECE_PAL1
    player_piece  -32,    0, PLAYER_PIECE_PAL1
    player_piece  -16,    0, PLAYER_PIECE_PAL1
    player_piece  -32,    7, PLAYER_PIECE_PAL1

data_65_414a_PlayerFrame_233:
    player_frame_header   8, $21, $1f, data_65_41e0_PlayerTiles + $08c0
    player_piece  -13,   -5, PLAYER_PIECE_PAL0
    player_piece  -13,    3, PLAYER_PIECE_PAL0
    player_piece  -31,   -8, PLAYER_PIECE_PAL1
    player_piece  -31,    0, PLAYER_PIECE_PAL1
    player_piece  -15,  -11, PLAYER_PIECE_PAL1
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -27,    5, PLAYER_PIECE_PAL1
    player_piece  -11,    7, PLAYER_PIECE_PAL1

data_65_416f_PlayerFrame_234:
    player_frame_header   7, $21, $1f, data_65_41e0_PlayerTiles + $09c0
    player_piece  -17,  -16, PLAYER_PIECE_PAL0
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -34,  -16, PLAYER_PIECE_PAL1
    player_piece  -23,   -8, PLAYER_PIECE_PAL1
    player_piece  -32,    0, PLAYER_PIECE_PAL1
    player_piece  -16,    0, PLAYER_PIECE_PAL1
    player_piece  -30,    7, PLAYER_PIECE_PAL1

data_65_4190_PlayerFrame_235:
    player_frame_header   6, $21, $1d, data_65_41e0_PlayerTiles + $0aa0
    player_piece  -31,  -11, PLAYER_PIECE_PAL0
    player_piece  -31,   -8, PLAYER_PIECE_PAL1
    player_piece  -26,    0, PLAYER_PIECE_PAL1
    player_piece  -28,    5, PLAYER_PIECE_PAL1
    player_piece  -15,   -8, PLAYER_PIECE_PAL1
    player_piece  -12,    5, PLAYER_PIECE_PAL1

data_65_41ad_PlayerFrame_236:
    player_frame_header   8, $21, $1d, data_65_41e0_PlayerTiles + $0b60
    player_piece  -39,  -16, PLAYER_PIECE_PAL0
    player_piece  -38,   -8, PLAYER_PIECE_PAL0
    player_piece  -21,  -16, PLAYER_PIECE_PAL1
    player_piece  -27,   -8, PLAYER_PIECE_PAL1
    player_piece  -11,   -8, PLAYER_PIECE_PAL1
    player_piece  -32,    0, PLAYER_PIECE_PAL1
    player_piece  -16,    0, PLAYER_PIECE_PAL1
    player_piece  -20,    5, PLAYER_PIECE_PAL1

    ds   $41e0 - @, 0                    ; the bank pads to a 16-byte boundary here
data_65_41e0_PlayerTiles:
; INCBINd by main.asm - see the header above
