; ==================================================================
; Bank $72. Gex's animation frames 1 to 53 of PLAYER_GFX_SET_TUT_TV.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $47f8, then 888 tiles of graphics from $4800 to $7f7f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/player_sprite_data/bank7f_player_sprite_data.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_72_4000_PlayerFrame_001:
    player_frame_header   9, $1e, $22, data_72_4800_PlayerTiles + $0000
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -28,    4, PLAYER_PIECE_PAL0
    player_piece  -24,    8, PLAYER_PIECE_PAL0
    player_piece   -8,  -13, PLAYER_PIECE_PAL0
    player_piece   -9,   -5, PLAYER_PIECE_PAL0
    player_piece  -10,    4, PLAYER_PIECE_PAL0
    player_piece  -26,   -4, PLAYER_PIECE_PAL1
    player_piece  -38,    4, PLAYER_PIECE_PAL1
    player_piece  -25,   -6, PLAYER_PIECE_PAL1

data_72_4029_PlayerFrame_002:
    player_frame_header  10, $1d, $22, data_72_4800_PlayerTiles + $0120
    player_piece  -23,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    6, PLAYER_PIECE_PAL0
    player_piece  -22,    8, PLAYER_PIECE_PAL0
    player_piece   -7,  -11, PLAYER_PIECE_PAL0
    player_piece   -7,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,    5, PLAYER_PIECE_PAL0
    player_piece  -27,   -1, PLAYER_PIECE_PAL1
    player_piece  -38,    7, PLAYER_PIECE_PAL1
    player_piece  -11,   -4, PLAYER_PIECE_PAL1
    player_piece  -26,    4, PLAYER_PIECE_PAL1

data_72_4056_PlayerFrame_003:
    player_frame_header   8, $1c, $22, data_72_4800_PlayerTiles + $0260
    player_piece  -23,   -1, PLAYER_PIECE_PAL0
    player_piece  -27,    7, PLAYER_PIECE_PAL0
    player_piece   -8,   -9, PLAYER_PIECE_PAL0
    player_piece   -7,   -1, PLAYER_PIECE_PAL0
    player_piece   -5,    7, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL1
    player_piece  -26,    4, PLAYER_PIECE_PAL1
    player_piece  -10,   -2, PLAYER_PIECE_PAL1

data_72_407b_PlayerFrame_004:
    player_frame_header   8, $1c, $23, data_72_4800_PlayerTiles + $0360
    player_piece  -23,   -1, PLAYER_PIECE_PAL0
    player_piece  -26,    7, PLAYER_PIECE_PAL0
    player_piece  -35,    9, PLAYER_PIECE_PAL0
    player_piece   -8,  -10, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,    6, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL1
    player_piece  -36,    4, PLAYER_PIECE_PAL1

data_72_40a0_PlayerFrame_005:
    player_frame_header   9, $1b, $23, data_72_4800_PlayerTiles + $0460
    player_piece   -9,  -11, PLAYER_PIECE_PAL0
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece  -25,    5, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece   -3,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0
    player_piece  -23,   -5, PLAYER_PIECE_PAL1
    player_piece  -34,    3, PLAYER_PIECE_PAL1
    player_piece   -9,    3, PLAYER_PIECE_PAL1

data_72_40c9_PlayerFrame_006:
    player_frame_header   9, $1c, $23, data_72_4800_PlayerTiles + $0580
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    4, PLAYER_PIECE_PAL0
    player_piece  -33,   12, PLAYER_PIECE_PAL0
    player_piece   -8,    6, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL1
    player_piece  -26,    4, PLAYER_PIECE_PAL1
    player_piece  -10,    4, PLAYER_PIECE_PAL1

data_72_40f2_PlayerFrame_007:
    player_frame_header  11, $1d, $23, data_72_4800_PlayerTiles + $06a0
    player_piece   -9,  -18, PLAYER_PIECE_PAL0
    player_piece  -16,  -10, PLAYER_PIECE_PAL0
    player_piece  -21,   -2, PLAYER_PIECE_PAL0
    player_piece   -5,   -2, PLAYER_PIECE_PAL0
    player_piece  -28,    6, PLAYER_PIECE_PAL0
    player_piece   -8,    6, PLAYER_PIECE_PAL0
    player_piece  -35,    9, PLAYER_PIECE_PAL0
    player_piece  -25,  -10, PLAYER_PIECE_PAL1
    player_piece  -26,   -2, PLAYER_PIECE_PAL1
    player_piece  -10,   -2, PLAYER_PIECE_PAL1
    player_piece  -38,    6, PLAYER_PIECE_PAL1

data_72_4123_PlayerFrame_008:
    player_frame_header  10, $1e, $23, data_72_4800_PlayerTiles + $0800
    player_piece   -9,  -13, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    3, PLAYER_PIECE_PAL0
    player_piece  -35,   11, PLAYER_PIECE_PAL0
    player_piece  -19,    5, PLAYER_PIECE_PAL0
    player_piece  -25,   -4, PLAYER_PIECE_PAL1
    player_piece  -37,    4, PLAYER_PIECE_PAL1
    player_piece  -22,   -1, PLAYER_PIECE_PAL1
    player_piece  -43,    7, PLAYER_PIECE_PAL1

data_72_4150_PlayerFrame_009:
    player_frame_header  10, $1f, $22, data_72_4800_PlayerTiles + $0940
    player_piece  -22,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL0
    player_piece  -25,    8, PLAYER_PIECE_PAL0
    player_piece   -8,  -13, PLAYER_PIECE_PAL0
    player_piece   -8,   -5, PLAYER_PIECE_PAL0
    player_piece   -9,    4, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL1
    player_piece  -39,    5, PLAYER_PIECE_PAL1
    player_piece  -12,   -5, PLAYER_PIECE_PAL1
    player_piece  -24,    3, PLAYER_PIECE_PAL1

data_72_417d_PlayerFrame_010:
    player_frame_header  10, $1e, $22, data_72_4800_PlayerTiles + $0a80
    player_piece  -22,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,    6, PLAYER_PIECE_PAL0
    player_piece  -23,    8, PLAYER_PIECE_PAL0
    player_piece   -8,  -11, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,    5, PLAYER_PIECE_PAL0
    player_piece  -27,   -2, PLAYER_PIECE_PAL1
    player_piece  -40,    6, PLAYER_PIECE_PAL1
    player_piece  -11,   -5, PLAYER_PIECE_PAL1
    player_piece  -24,    3, PLAYER_PIECE_PAL1

data_72_41aa_PlayerFrame_011:
    player_frame_header  10, $1c, $23, data_72_4800_PlayerTiles + $0bc0
    player_piece   -8,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece   -4,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    6, PLAYER_PIECE_PAL0
    player_piece  -17,    6, PLAYER_PIECE_PAL0
    player_piece  -34,    9, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL1
    player_piece   -9,   -2, PLAYER_PIECE_PAL1
    player_piece  -37,    6, PLAYER_PIECE_PAL1
    player_piece  -23,    6, PLAYER_PIECE_PAL1

data_72_41d7_PlayerFrame_012:
    player_frame_header   9, $1b, $23, data_72_4800_PlayerTiles + $0d00
    player_piece   -9,  -10, PLAYER_PIECE_PAL0
    player_piece  -19,   -2, PLAYER_PIECE_PAL0
    player_piece   -3,   -2, PLAYER_PIECE_PAL0
    player_piece  -26,    6, PLAYER_PIECE_PAL0
    player_piece  -16,    6, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -24,   -2, PLAYER_PIECE_PAL1
    player_piece   -8,   -2, PLAYER_PIECE_PAL1
    player_piece  -36,    6, PLAYER_PIECE_PAL1

data_72_4200_PlayerFrame_013:
    player_frame_header   8, $1b, $23, data_72_4800_PlayerTiles + $0e20
    player_piece  -19,  -10, PLAYER_PIECE_PAL0
    player_piece  -21,   -2, PLAYER_PIECE_PAL0
    player_piece  -26,    6, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL1
    player_piece  -36,    5, PLAYER_PIECE_PAL1
    player_piece   -8,    0, PLAYER_PIECE_PAL1

data_72_4225_PlayerFrame_014:
    player_frame_header  10, $1c, $23, data_72_4800_PlayerTiles + $0f20
    player_piece  -16,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -32,    4, PLAYER_PIECE_PAL0
    player_piece   -3,    4, PLAYER_PIECE_PAL0
    player_piece  -33,   12, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL1
    player_piece  -25,    4, PLAYER_PIECE_PAL1
    player_piece   -8,   -2, PLAYER_PIECE_PAL1
    player_piece  -41,    6, PLAYER_PIECE_PAL1

data_72_4252_PlayerFrame_015:
    player_frame_header  10, $1c, $23, data_72_4800_PlayerTiles + $1060
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -2, PLAYER_PIECE_PAL0
    player_piece   -8,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,    4, PLAYER_PIECE_PAL0
    player_piece  -17,    4, PLAYER_PIECE_PAL0
    player_piece  -33,   12, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL1
    player_piece  -25,    4, PLAYER_PIECE_PAL1
    player_piece   -8,   -3, PLAYER_PIECE_PAL1
    player_piece  -41,    6, PLAYER_PIECE_PAL1

data_72_427f_PlayerFrame_016:
    player_frame_header   9, $1d, $22, data_72_4800_PlayerTiles + $11a0
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece  -25,    4, PLAYER_PIECE_PAL0
    player_piece  -23,    8, PLAYER_PIECE_PAL0
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece   -9,    4, PLAYER_PIECE_PAL0
    player_piece   -7,    8, PLAYER_PIECE_PAL0
    player_piece  -26,   -2, PLAYER_PIECE_PAL1
    player_piece  -38,    6, PLAYER_PIECE_PAL1
    player_piece  -23,   -4, PLAYER_PIECE_PAL1

data_72_42a8_PlayerFrame_017:
    player_frame_header  10, $1e, $20, data_72_4800_PlayerTiles + $12c0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -28,    4, PLAYER_PIECE_PAL0
    player_piece  -35,    8, PLAYER_PIECE_PAL0
    player_piece   -9,  -14, PLAYER_PIECE_PAL0
    player_piece   -8,   -6, PLAYER_PIECE_PAL0
    player_piece  -19,    4, PLAYER_PIECE_PAL0
    player_piece  -26,   -4, PLAYER_PIECE_PAL1
    player_piece  -38,    4, PLAYER_PIECE_PAL1
    player_piece  -22,   -7, PLAYER_PIECE_PAL1
    player_piece  -23,    1, PLAYER_PIECE_PAL1

data_72_42d5_PlayerFrame_018:
    player_frame_header   8, $1e, $21, data_72_4800_PlayerTiles + $1400
    player_piece  -11,  -14, PLAYER_PIECE_PAL0
    player_piece  -22,   -6, PLAYER_PIECE_PAL0
    player_piece  -26,    2, PLAYER_PIECE_PAL0
    player_piece  -26,    9, PLAYER_PIECE_PAL0
    player_piece  -10,    4, PLAYER_PIECE_PAL0
    player_piece  -25,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    4, PLAYER_PIECE_PAL1
    player_piece  -27,   -5, PLAYER_PIECE_PAL1

data_72_42fa_PlayerFrame_019:
    player_frame_header   8, $1e, $20, data_72_4800_PlayerTiles + $1500
    player_piece  -23,  -15, PLAYER_PIECE_PAL0
    player_piece  -25,   -7, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece  -27,    8, PLAYER_PIECE_PAL0
    player_piece   -9,   -7, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -25,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    3, PLAYER_PIECE_PAL1

data_72_431f_PlayerFrame_020:
    player_frame_header  10, $1e, $20, data_72_4800_PlayerTiles + $1600
    player_piece  -26,   -9, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -29,    7, PLAYER_PIECE_PAL0
    player_piece  -10,  -12, PLAYER_PIECE_PAL0
    player_piece  -10,   -4, PLAYER_PIECE_PAL0
    player_piece  -10,    4, PLAYER_PIECE_PAL0
    player_piece   -7,    8, PLAYER_PIECE_PAL0
    player_piece  -27,   -3, PLAYER_PIECE_PAL1
    player_piece  -28,    5, PLAYER_PIECE_PAL1
    player_piece  -12,    2, PLAYER_PIECE_PAL1

data_72_434c_PlayerFrame_021:
    player_frame_header  10, $1f, $20, data_72_4800_PlayerTiles + $1740
    player_piece  -11,  -12, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL0
    player_piece   -8,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL0
    player_piece  -11,    4, PLAYER_PIECE_PAL0
    player_piece  -37,   12, PLAYER_PIECE_PAL0
    player_piece  -21,   12, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL1
    player_piece  -29,    5, PLAYER_PIECE_PAL1
    player_piece  -13,    0, PLAYER_PIECE_PAL1

data_72_4379_PlayerFrame_022:
    player_frame_header  10, $20, $20, data_72_4800_PlayerTiles + $1880
    player_piece  -26,   -6, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece  -38,    5, PLAYER_PIECE_PAL0
    player_piece  -11,  -15, PLAYER_PIECE_PAL0
    player_piece  -10,   -7, PLAYER_PIECE_PAL0
    player_piece  -17,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece  -41,    5, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -25,    3, PLAYER_PIECE_PAL1

data_72_43a6_PlayerFrame_023:
    player_frame_header  10, $1d, $20, data_72_4800_PlayerTiles + $19c0
    player_piece  -11,  -15, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL0
    player_piece  -25,    1, PLAYER_PIECE_PAL0
    player_piece  -35,    5, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece   -6,    5, PLAYER_PIECE_PAL0
    player_piece  -27,   -5, PLAYER_PIECE_PAL1
    player_piece  -38,    3, PLAYER_PIECE_PAL1
    player_piece  -11,   -5, PLAYER_PIECE_PAL1
    player_piece  -26,    3, PLAYER_PIECE_PAL1

data_72_43d3_PlayerFrame_024:
    player_frame_header   9, $1b, $20, data_72_4800_PlayerTiles + $1b00
    player_piece  -10,  -17, PLAYER_PIECE_PAL0
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -23,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,    3, PLAYER_PIECE_PAL0
    player_piece   -7,   -4, PLAYER_PIECE_PAL0
    player_piece   -4,    3, PLAYER_PIECE_PAL0
    player_piece  -23,  -10, PLAYER_PIECE_PAL1
    player_piece  -35,   -2, PLAYER_PIECE_PAL1
    player_piece  -23,   -2, PLAYER_PIECE_PAL1

data_72_43fc_PlayerFrame_025:
    player_frame_header   8, $1f, $1d, data_72_4800_PlayerTiles + $1c20
    player_piece  -29,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    3, PLAYER_PIECE_PAL0
    player_piece  -13,   -7, PLAYER_PIECE_PAL0
    player_piece  -13,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -28,   -5, PLAYER_PIECE_PAL1
    player_piece  -12,   -2, PLAYER_PIECE_PAL1

data_72_4421_PlayerFrame_026:
    player_frame_header   8, $20, $1d, data_72_4800_PlayerTiles + $1d20
    player_piece  -30,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -39,    3, PLAYER_PIECE_PAL0
    player_piece  -14,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -28,   -5, PLAYER_PIECE_PAL1
    player_piece  -12,   -2, PLAYER_PIECE_PAL1

data_72_4446_PlayerFrame_027:
    player_frame_header   9, $1f, $1d, data_72_4800_PlayerTiles + $1e20
    player_piece  -27,  -12, PLAYER_PIECE_PAL0
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    3, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -11,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -29,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1

data_72_446f_PlayerFrame_028:
    player_frame_header   8, $1b, $1d, data_72_4800_PlayerTiles + $1f40
    player_piece  -22,  -11, PLAYER_PIECE_PAL0
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    3, PLAYER_PIECE_PAL0
    player_piece   -7,   -6, PLAYER_PIECE_PAL0
    player_piece   -7,    2, PLAYER_PIECE_PAL0
    player_piece  -25,   -7, PLAYER_PIECE_PAL1
    player_piece  -25,    1, PLAYER_PIECE_PAL1
    player_piece   -9,   -1, PLAYER_PIECE_PAL1

data_72_4494_PlayerFrame_029:
    player_frame_header   7, $17, $1d, data_72_4800_PlayerTiles + $2040
    player_piece  -19,  -11, PLAYER_PIECE_PAL0
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    3, PLAYER_PIECE_PAL0
    player_piece   -3,   -6, PLAYER_PIECE_PAL0
    player_piece   -3,    2, PLAYER_PIECE_PAL0
    player_piece  -23,   -8, PLAYER_PIECE_PAL1
    player_piece  -22,    0, PLAYER_PIECE_PAL1

data_72_44b5_PlayerFrame_030:
    player_frame_header   8, $1f, $1d, data_72_4800_PlayerTiles + $2120
    player_piece  -27,  -10, PLAYER_PIECE_PAL0
    player_piece  -11,  -10, PLAYER_PIECE_PAL0
    player_piece  -27,   -2, PLAYER_PIECE_PAL0
    player_piece  -11,   -2, PLAYER_PIECE_PAL0
    player_piece  -17,    3, PLAYER_PIECE_PAL0
    player_piece  -37,  -10, PLAYER_PIECE_PAL1
    player_piece  -29,   -2, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1

data_72_44da_PlayerFrame_031:
    player_frame_header   9, $1f, $1d, data_72_4800_PlayerTiles + $2220
    player_piece  -27,  -12, PLAYER_PIECE_PAL0
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    3, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -11,    1, PLAYER_PIECE_PAL0
    player_piece  -10,    3, PLAYER_PIECE_PAL0
    player_piece  -29,   -6, PLAYER_PIECE_PAL1
    player_piece  -28,    2, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1

data_72_4503_PlayerFrame_032:
    player_frame_header  10, $1f, $20, data_72_4800_PlayerTiles + $2340
    player_piece  -22,  -12, PLAYER_PIECE_PAL0
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    4, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -11,    1, PLAYER_PIECE_PAL0
    player_piece  -26,    4, PLAYER_PIECE_PAL0
    player_piece  -37,   -5, PLAYER_PIECE_PAL1
    player_piece  -42,    3, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,    4, PLAYER_PIECE_PAL1

data_72_4530_PlayerFrame_033:
    player_frame_header   9, $1f, $21, data_72_4800_PlayerTiles + $2480
    player_piece  -22,  -12, PLAYER_PIECE_PAL0
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -37,   -5, PLAYER_PIECE_PAL1
    player_piece  -42,    3, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1
    player_piece  -23,    4, PLAYER_PIECE_PAL1

data_72_4559_PlayerFrame_034:
    player_frame_header   8, $1c, $1f, data_72_4800_PlayerTiles + $25a0
    player_piece  -21,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    3, PLAYER_PIECE_PAL0
    player_piece   -7,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -26,   -5, PLAYER_PIECE_PAL1
    player_piece  -39,    3, PLAYER_PIECE_PAL1
    player_piece  -10,   -4, PLAYER_PIECE_PAL1

data_72_457e_PlayerFrame_035:
    player_frame_header   7, $19, $1d, data_72_4800_PlayerTiles + $26a0
    player_piece  -21,  -12, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece   -5,   -4, PLAYER_PIECE_PAL0
    player_piece  -31,    1, PLAYER_PIECE_PAL0
    player_piece   -3,    1, PLAYER_PIECE_PAL0
    player_piece  -22,  -12, PLAYER_PIECE_PAL1
    player_piece  -23,   -4, PLAYER_PIECE_PAL1

data_72_459f_PlayerFrame_036:
    player_frame_header   6, $19, $1c, data_72_4800_PlayerTiles + $2780
    player_piece  -23,  -10, PLAYER_PIECE_PAL0
    player_piece  -16,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece   -5,   -1, PLAYER_PIECE_PAL0
    player_piece  -22,   -6, PLAYER_PIECE_PAL1
    player_piece  -32,    2, PLAYER_PIECE_PAL1

data_72_45bc_PlayerFrame_037:
    player_frame_header   6, $18, $1b, data_72_4800_PlayerTiles + $2840
    player_piece  -21,  -10, PLAYER_PIECE_PAL0
    player_piece  -22,   -2, PLAYER_PIECE_PAL0
    player_piece   -6,   -7, PLAYER_PIECE_PAL0
    player_piece   -6,   -1, PLAYER_PIECE_PAL0
    player_piece  -23,   -7, PLAYER_PIECE_PAL1
    player_piece  -31,   -1, PLAYER_PIECE_PAL1

data_72_45d9_PlayerFrame_038:
    player_frame_header   6, $16, $1b, data_72_4800_PlayerTiles + $2900
    player_piece  -20,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece   -4,   -5, PLAYER_PIECE_PAL0
    player_piece   -4,   -1, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,   -1, PLAYER_PIECE_PAL1

data_72_45f6_PlayerFrame_039:
    player_frame_header   4, $15, $1b, data_72_4800_PlayerTiles + $29c0
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,   -7, PLAYER_PIECE_PAL1

data_72_460b_PlayerFrame_040:
    player_frame_header   4, $15, $1b, data_72_4800_PlayerTiles + $2a40
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,   -7, PLAYER_PIECE_PAL1

data_72_4620_PlayerFrame_041:
    player_frame_header   4, $15, $1b, data_72_4800_PlayerTiles + $2ac0
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,   -7, PLAYER_PIECE_PAL1

data_72_4635_PlayerFrame_042:
    player_frame_header   9, $1d, $23, data_72_4800_PlayerTiles + $2b40
    player_piece  -25,  -16, PLAYER_PIECE_PAL0
    player_piece  -25,   -8, PLAYER_PIECE_PAL0
    player_piece  -17,    0, PLAYER_PIECE_PAL0
    player_piece   -9,  -15, PLAYER_PIECE_PAL0
    player_piece   -9,   -7, PLAYER_PIECE_PAL0
    player_piece   -1,    0, PLAYER_PIECE_PAL0
    player_piece  -27,  -10, PLAYER_PIECE_PAL1
    player_piece  -24,   -2, PLAYER_PIECE_PAL1
    player_piece  -11,   -7, PLAYER_PIECE_PAL1

data_72_465e_PlayerFrame_043:
    player_frame_header   7, $1d, $22, data_72_4800_PlayerTiles + $2c60
    player_piece  -25,  -14, PLAYER_PIECE_PAL0
    player_piece  -25,   -6, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece   -9,   -9, PLAYER_PIECE_PAL0
    player_piece  -27,   -9, PLAYER_PIECE_PAL1
    player_piece  -24,   -1, PLAYER_PIECE_PAL1
    player_piece  -11,   -4, PLAYER_PIECE_PAL1

data_72_467f_PlayerFrame_044:
    player_frame_header   7, $1e, $25, data_72_4800_PlayerTiles + $2d40
    player_piece  -25,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -35,   -4, PLAYER_PIECE_PAL1
    player_piece  -35,    2, PLAYER_PIECE_PAL1
    player_piece  -11,    2, PLAYER_PIECE_PAL1

data_72_46a0_PlayerFrame_045:
    player_frame_header   7, $1e, $26, data_72_4800_PlayerTiles + $2e20
    player_piece  -20,  -11, PLAYER_PIECE_PAL0
    player_piece  -26,   -3, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    3, PLAYER_PIECE_PAL0
    player_piece  -19,    3, PLAYER_PIECE_PAL0
    player_piece  -36,   -3, PLAYER_PIECE_PAL1
    player_piece  -41,    3, PLAYER_PIECE_PAL1

data_72_46c1_PlayerFrame_046:
    player_frame_header   9, $1d, $30, data_72_4800_PlayerTiles + $2f00
    player_piece  -17,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,    4, PLAYER_PIECE_PAL0
    player_piece  -27,   12, PLAYER_PIECE_PAL0
    player_piece   -9,   -5, PLAYER_PIECE_PAL0
    player_piece   -8,    3, PLAYER_PIECE_PAL0
    player_piece   -8,   11, PLAYER_PIECE_PAL0
    player_piece  -27,    4, PLAYER_PIECE_PAL1
    player_piece  -38,   12, PLAYER_PIECE_PAL1
    player_piece  -22,    0, PLAYER_PIECE_PAL1

data_72_46ea_PlayerFrame_047:
    player_frame_header  10, $21, $2b, data_72_4800_PlayerTiles + $3020
    player_piece  -10,  -15, PLAYER_PIECE_PAL0
    player_piece  -30,   -7, PLAYER_PIECE_PAL0
    player_piece  -12,   -7, PLAYER_PIECE_PAL0
    player_piece  -29,    1, PLAYER_PIECE_PAL0
    player_piece  -13,    1, PLAYER_PIECE_PAL0
    player_piece   -8,    4, PLAYER_PIECE_PAL0
    player_piece  -31,   -7, PLAYER_PIECE_PAL1
    player_piece  -25,   -7, PLAYER_PIECE_PAL1
    player_piece  -42,    1, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1

data_72_4717_PlayerFrame_048:
    player_frame_header   9, $1f, $2a, data_72_4800_PlayerTiles + $3160
    player_piece  -27,   -9, PLAYER_PIECE_PAL0
    player_piece  -27,   -1, PLAYER_PIECE_PAL0
    player_piece  -20,    3, PLAYER_PIECE_PAL0
    player_piece  -11,  -11, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,   -9, PLAYER_PIECE_PAL1
    player_piece  -29,   -1, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece  -13,    3, PLAYER_PIECE_PAL1

data_72_4740_PlayerFrame_049:
    player_frame_header   8, $1e, $2b, data_72_4800_PlayerTiles + $3280
    player_piece  -25,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -24,    4, PLAYER_PIECE_PAL0
    player_piece   -9,  -10, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece  -28,   -9, PLAYER_PIECE_PAL1
    player_piece  -28,   -1, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1

data_72_4765_PlayerFrame_050:
    player_frame_header   8, $1e, $30, data_72_4800_PlayerTiles + $3380
    player_piece  -25,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece   -9,   -7, PLAYER_PIECE_PAL0
    player_piece  -18,    1, PLAYER_PIECE_PAL0
    player_piece  -27,    9, PLAYER_PIECE_PAL0
    player_piece  -35,   -9, PLAYER_PIECE_PAL1
    player_piece  -28,   -1, PLAYER_PIECE_PAL1
    player_piece  -12,   -1, PLAYER_PIECE_PAL1

data_72_478a_PlayerFrame_051:
    player_frame_header   9, $1d, $30, data_72_4800_PlayerTiles + $3480
    player_piece  -24,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece  -17,    5, PLAYER_PIECE_PAL0
    player_piece  -28,    9, PLAYER_PIECE_PAL0
    player_piece   -8,   -6, PLAYER_PIECE_PAL0
    player_piece   -8,    2, PLAYER_PIECE_PAL0
    player_piece  -34,   -9, PLAYER_PIECE_PAL1
    player_piece  -27,   -1, PLAYER_PIECE_PAL1
    player_piece  -11,   -1, PLAYER_PIECE_PAL1

data_72_47b3_PlayerFrame_052:
    player_frame_header   8, $1d, $2e, data_72_4800_PlayerTiles + $35a0
    player_piece  -24,  -13, PLAYER_PIECE_PAL0
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,    3, PLAYER_PIECE_PAL0
    player_piece  -16,    7, PLAYER_PIECE_PAL0
    player_piece   -8,   -4, PLAYER_PIECE_PAL0
    player_piece  -34,   -9, PLAYER_PIECE_PAL1
    player_piece  -27,   -1, PLAYER_PIECE_PAL1
    player_piece  -11,   -3, PLAYER_PIECE_PAL1

data_72_47d8_PlayerFrame_053:
    player_frame_header   7, $1c, $2e, data_72_4800_PlayerTiles + $36a0
    player_piece  -24,  -12, PLAYER_PIECE_PAL0
    player_piece  -23,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,    1, PLAYER_PIECE_PAL0
    player_piece  -16,    9, PLAYER_PIECE_PAL0
    player_piece  -33,   -9, PLAYER_PIECE_PAL1
    player_piece  -26,   -1, PLAYER_PIECE_PAL1
    player_piece  -10,   -1, PLAYER_PIECE_PAL1

    ds   $4800 - @, 0                    ; the bank pads to a 16-byte boundary here
data_72_4800_PlayerTiles:
; INCBINd by main.asm - see the header above
