; ==================================================================
; Bank $68. Gex's animation frames 50 to 108 of PLAYER_GFX_SET_WESTERN_STATION.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $4812, then 886 tiles of graphics from $4820 to $7f7f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/player_sprite_data/bank7f_player_sprite_data.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_68_4000_PlayerFrame_050:
    player_frame_header  10, $1f, $30, data_68_4820_PlayerTiles + $0000
    player_piece  -25,  -11, PLAYER_PIECE_PAL0
    player_piece  -33,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    5, PLAYER_PIECE_PAL0
    player_piece  -27,    9, PLAYER_PIECE_PAL0
    player_piece   -9,   -7, PLAYER_PIECE_PAL0
    player_piece   -9,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -9, PLAYER_PIECE_PAL1
    player_piece  -29,   -1, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -13,    3, PLAYER_PIECE_PAL1

data_68_402d_PlayerFrame_051:
    player_frame_header  10, $1e, $30, data_68_4820_PlayerTiles + $0140
    player_piece  -24,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece  -28,    5, PLAYER_PIECE_PAL0
    player_piece  -28,    9, PLAYER_PIECE_PAL0
    player_piece   -8,   -6, PLAYER_PIECE_PAL0
    player_piece   -8,    2, PLAYER_PIECE_PAL0
    player_piece  -28,   -9, PLAYER_PIECE_PAL1
    player_piece  -28,   -1, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1
    player_piece  -12,    4, PLAYER_PIECE_PAL1

data_68_405a_PlayerFrame_052:
    player_frame_header   9, $1d, $2e, data_68_4820_PlayerTiles + $0280
    player_piece  -24,  -13, PLAYER_PIECE_PAL0
    player_piece  -23,   -5, PLAYER_PIECE_PAL0
    player_piece  -23,    3, PLAYER_PIECE_PAL0
    player_piece  -26,    7, PLAYER_PIECE_PAL0
    player_piece   -7,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,  -10, PLAYER_PIECE_PAL1
    player_piece  -27,   -2, PLAYER_PIECE_PAL1
    player_piece  -11,   -4, PLAYER_PIECE_PAL1
    player_piece  -11,    4, PLAYER_PIECE_PAL1

data_68_4083_PlayerFrame_053:
    player_frame_header   8, $1d, $2e, data_68_4820_PlayerTiles + $03a0
    player_piece  -24,  -12, PLAYER_PIECE_PAL0
    player_piece  -23,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,    1, PLAYER_PIECE_PAL0
    player_piece  -26,    9, PLAYER_PIECE_PAL0
    player_piece  -27,  -10, PLAYER_PIECE_PAL1
    player_piece  -27,   -2, PLAYER_PIECE_PAL1
    player_piece  -11,   -7, PLAYER_PIECE_PAL1
    player_piece  -11,    1, PLAYER_PIECE_PAL1

data_68_40a8_PlayerFrame_054:
    player_frame_header   7, $15, $2e, data_68_4820_PlayerTiles + $04a0
    player_piece  -18,  -12, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL0
    player_piece  -17,    4, PLAYER_PIECE_PAL0
    player_piece  -23,   12, PLAYER_PIECE_PAL0
    player_piece  -19,  -11, PLAYER_PIECE_PAL1
    player_piece  -18,   -3, PLAYER_PIECE_PAL1
    player_piece  -17,    5, PLAYER_PIECE_PAL1

data_68_40c9_PlayerFrame_055:
    player_frame_header   7, $24, $27, data_68_4820_PlayerTiles + $0580
    player_piece  -32,   -9, PLAYER_PIECE_PAL0
    player_piece  -32,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -34,   -8, PLAYER_PIECE_PAL1
    player_piece  -34,    0, PLAYER_PIECE_PAL1
    player_piece  -18,   -5, PLAYER_PIECE_PAL1

data_68_40ea_PlayerFrame_056:
    player_frame_header   8, $24, $27, data_68_4820_PlayerTiles + $0660
    player_piece  -29,   -9, PLAYER_PIECE_PAL0
    player_piece  -29,   -1, PLAYER_PIECE_PAL0
    player_piece  -13,   -8, PLAYER_PIECE_PAL0
    player_piece  -13,    0, PLAYER_PIECE_PAL0
    player_piece  -34,   -8, PLAYER_PIECE_PAL1
    player_piece  -34,    0, PLAYER_PIECE_PAL1
    player_piece  -18,   -5, PLAYER_PIECE_PAL1
    player_piece  -18,    0, PLAYER_PIECE_PAL1

data_68_410f_PlayerFrame_057:
    player_frame_header   7, $25, $28, data_68_4820_PlayerTiles + $0760
    player_piece  -30,   -9, PLAYER_PIECE_PAL0
    player_piece  -33,   -1, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -21,    0, PLAYER_PIECE_PAL0
    player_piece  -35,   -8, PLAYER_PIECE_PAL1
    player_piece  -34,   -4, PLAYER_PIECE_PAL1
    player_piece  -18,   -5, PLAYER_PIECE_PAL1

data_68_4130_PlayerFrame_058:
    player_frame_header   7, $25, $27, data_68_4820_PlayerTiles + $0840
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,   -7, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0
    player_piece  -35,   -7, PLAYER_PIECE_PAL1
    player_piece  -35,    0, PLAYER_PIECE_PAL1
    player_piece  -19,   -4, PLAYER_PIECE_PAL1

data_68_4151_PlayerFrame_059:
    player_frame_header   7, $25, $27, data_68_4820_PlayerTiles + $0920
    player_piece  -30,   -9, PLAYER_PIECE_PAL0
    player_piece  -30,   -1, PLAYER_PIECE_PAL0
    player_piece  -19,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0
    player_piece  -35,   -7, PLAYER_PIECE_PAL1
    player_piece  -35,    0, PLAYER_PIECE_PAL1
    player_piece  -19,   -5, PLAYER_PIECE_PAL1

data_68_4172_PlayerFrame_060:
    player_frame_header   8, $25, $27, data_68_4820_PlayerTiles + $0a00
    player_piece  -30,   -9, PLAYER_PIECE_PAL0
    player_piece  -39,   -1, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -23,    0, PLAYER_PIECE_PAL0
    player_piece  -35,   -6, PLAYER_PIECE_PAL1
    player_piece  -35,    0, PLAYER_PIECE_PAL1
    player_piece  -19,   -5, PLAYER_PIECE_PAL1
    player_piece  -19,    0, PLAYER_PIECE_PAL1

data_68_4197_PlayerFrame_061:
    player_frame_header   7, $25, $27, data_68_4820_PlayerTiles + $0b00
    player_piece  -30,   -9, PLAYER_PIECE_PAL0
    player_piece  -30,   -1, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0
    player_piece  -35,   -6, PLAYER_PIECE_PAL1
    player_piece  -35,    0, PLAYER_PIECE_PAL1
    player_piece  -19,   -3, PLAYER_PIECE_PAL1

data_68_41b8_PlayerFrame_062:
    player_frame_header   7, $25, $27, data_68_4820_PlayerTiles + $0be0
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -30,    0, PLAYER_PIECE_PAL0
    player_piece  -14,   -7, PLAYER_PIECE_PAL0
    player_piece  -14,    0, PLAYER_PIECE_PAL0
    player_piece  -35,   -5, PLAYER_PIECE_PAL1
    player_piece  -45,    0, PLAYER_PIECE_PAL1
    player_piece  -27,   -3, PLAYER_PIECE_PAL1

data_68_41d9_PlayerFrame_063:
    player_frame_header   9, $24, $29, data_68_4820_PlayerTiles + $0cc0
    player_piece  -28,  -15, PLAYER_PIECE_PAL0
    player_piece  -28,   -7, PLAYER_PIECE_PAL0
    player_piece  -12,   -7, PLAYER_PIECE_PAL0
    player_piece  -29,    1, PLAYER_PIECE_PAL0
    player_piece  -13,    1, PLAYER_PIECE_PAL0
    player_piece  -34,   -7, PLAYER_PIECE_PAL1
    player_piece  -18,   -7, PLAYER_PIECE_PAL1
    player_piece  -34,    1, PLAYER_PIECE_PAL1
    player_piece  -18,    1, PLAYER_PIECE_PAL1

data_68_4202_PlayerFrame_064:
    player_frame_header   9, $23, $2a, data_68_4820_PlayerTiles + $0de0
    player_piece  -28,   -9, PLAYER_PIECE_PAL0
    player_piece  -32,   -1, PLAYER_PIECE_PAL0
    player_piece  -31,    3, PLAYER_PIECE_PAL0
    player_piece  -12,   -7, PLAYER_PIECE_PAL0
    player_piece  -12,    1, PLAYER_PIECE_PAL0
    player_piece  -33,   -4, PLAYER_PIECE_PAL1
    player_piece  -33,    3, PLAYER_PIECE_PAL1
    player_piece  -17,   -5, PLAYER_PIECE_PAL1
    player_piece  -17,    3, PLAYER_PIECE_PAL1

data_68_422b_PlayerFrame_065:
    player_frame_header   9, $22, $29, data_68_4820_PlayerTiles + $0f00
    player_piece  -27,   -9, PLAYER_PIECE_PAL0
    player_piece  -30,   -1, PLAYER_PIECE_PAL0
    player_piece  -30,    2, PLAYER_PIECE_PAL0
    player_piece  -11,  -10, PLAYER_PIECE_PAL0
    player_piece  -11,   -2, PLAYER_PIECE_PAL0
    player_piece  -32,   -4, PLAYER_PIECE_PAL1
    player_piece  -32,    2, PLAYER_PIECE_PAL1
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -16,    2, PLAYER_PIECE_PAL1

data_68_4254_PlayerFrame_066:
    player_frame_header   9, $1f, $2b, data_68_4820_PlayerTiles + $1020
    player_piece  -24,   -9, PLAYER_PIECE_PAL0
    player_piece  -24,   -1, PLAYER_PIECE_PAL0
    player_piece  -27,    4, PLAYER_PIECE_PAL0
    player_piece   -8,  -11, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,   -4, PLAYER_PIECE_PAL1
    player_piece  -29,    4, PLAYER_PIECE_PAL1
    player_piece  -13,   -7, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_68_427d_PlayerFrame_067:
    player_frame_header   8, $1b, $2d, data_68_4820_PlayerTiles + $1140
    player_piece  -12,  -15, PLAYER_PIECE_PAL0
    player_piece  -20,   -7, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece  -27,    6, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL1
    player_piece  -25,    1, PLAYER_PIECE_PAL1
    player_piece   -9,    1, PLAYER_PIECE_PAL1
    player_piece  -35,    6, PLAYER_PIECE_PAL1

data_68_42a2_PlayerFrame_068:
    player_frame_header   8, $20, $28, data_68_4820_PlayerTiles + $1240
    player_piece  -26,   -9, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -10,   -7, PLAYER_PIECE_PAL0
    player_piece  -10,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -30,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -14,    3, PLAYER_PIECE_PAL1

data_68_42c7_PlayerFrame_069:
    player_frame_header   8, $21, $28, data_68_4820_PlayerTiles + $1340
    player_piece  -26,   -9, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -10,   -7, PLAYER_PIECE_PAL0
    player_piece  -10,    1, PLAYER_PIECE_PAL0
    player_piece  -31,   -6, PLAYER_PIECE_PAL1
    player_piece  -31,    2, PLAYER_PIECE_PAL1
    player_piece  -15,   -6, PLAYER_PIECE_PAL1
    player_piece  -15,    2, PLAYER_PIECE_PAL1

data_68_42ec_PlayerFrame_070:
    player_frame_header   8, $21, $28, data_68_4820_PlayerTiles + $1440
    player_piece  -26,   -8, PLAYER_PIECE_PAL0
    player_piece  -27,    0, PLAYER_PIECE_PAL0
    player_piece  -10,   -8, PLAYER_PIECE_PAL0
    player_piece  -10,    0, PLAYER_PIECE_PAL0
    player_piece  -31,   -6, PLAYER_PIECE_PAL1
    player_piece  -31,    2, PLAYER_PIECE_PAL1
    player_piece  -15,   -6, PLAYER_PIECE_PAL1
    player_piece  -15,    2, PLAYER_PIECE_PAL1

data_68_4311_PlayerFrame_071:
    player_frame_header   8, $21, $28, data_68_4820_PlayerTiles + $1540
    player_piece  -26,   -7, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece  -10,   -8, PLAYER_PIECE_PAL0
    player_piece  -10,    0, PLAYER_PIECE_PAL0
    player_piece  -31,   -6, PLAYER_PIECE_PAL1
    player_piece  -31,    2, PLAYER_PIECE_PAL1
    player_piece  -15,   -6, PLAYER_PIECE_PAL1
    player_piece  -15,    2, PLAYER_PIECE_PAL1

data_68_4336_PlayerFrame_072:
    player_frame_header   5, $17, $26, data_68_4820_PlayerTiles + $1640
    player_piece  -22,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -20,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,    5, PLAYER_PIECE_PAL0
    player_piece  -20,   11, PLAYER_PIECE_PAL0

data_68_434f_PlayerFrame_073:
    player_frame_header   5, $17, $27, data_68_4820_PlayerTiles + $16e0
    player_piece  -22,  -15, PLAYER_PIECE_PAL0
    player_piece  -24,   -7, PLAYER_PIECE_PAL0
    player_piece  -22,    1, PLAYER_PIECE_PAL0
    player_piece  -21,    9, PLAYER_PIECE_PAL0
    player_piece  -19,   11, PLAYER_PIECE_PAL0

data_68_4368_PlayerFrame_074:
    player_frame_header   5, $17, $27, data_68_4820_PlayerTiles + $1780
    player_piece  -23,  -14, PLAYER_PIECE_PAL0
    player_piece  -23,   -6, PLAYER_PIECE_PAL0
    player_piece  -21,    2, PLAYER_PIECE_PAL0
    player_piece  -21,   10, PLAYER_PIECE_PAL0
    player_piece   -5,    7, PLAYER_PIECE_PAL0

data_68_4381_PlayerFrame_075:
    player_frame_header   6, $17, $27, data_68_4820_PlayerTiles + $1820
    player_piece  -20,  -19, PLAYER_PIECE_PAL0
    player_piece  -22,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,    5, PLAYER_PIECE_PAL0
    player_piece   -5,    5, PLAYER_PIECE_PAL0
    player_piece  -22,   12, PLAYER_PIECE_PAL0

data_68_439e_PlayerFrame_076:
    player_frame_header   6, $17, $25, data_68_4820_PlayerTiles + $18e0
    player_piece  -23,  -16, PLAYER_PIECE_PAL0
    player_piece  -23,   -8, PLAYER_PIECE_PAL0
    player_piece  -21,    0, PLAYER_PIECE_PAL0
    player_piece  -21,    8, PLAYER_PIECE_PAL0
    player_piece   -5,    2, PLAYER_PIECE_PAL0
    player_piece   -5,   10, PLAYER_PIECE_PAL0

data_68_43bb_PlayerFrame_077:
    player_frame_header   6, $17, $26, data_68_4820_PlayerTiles + $19a0
    player_piece  -21,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,    5, PLAYER_PIECE_PAL0
    player_piece   -5,    5, PLAYER_PIECE_PAL0
    player_piece  -26,   11, PLAYER_PIECE_PAL0

data_68_43d8_PlayerFrame_078:
    player_frame_header   6, $18, $26, data_68_4820_PlayerTiles + $1a60
    player_piece  -21,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece  -22,    5, PLAYER_PIECE_PAL0
    player_piece   -6,    5, PLAYER_PIECE_PAL0
    player_piece  -23,   11, PLAYER_PIECE_PAL0

data_68_43f5_PlayerFrame_079:
    player_frame_header   7, $1e, $26, data_68_4820_PlayerTiles + $1b20
    player_piece  -28,   -6, PLAYER_PIECE_PAL0
    player_piece  -28,    2, PLAYER_PIECE_PAL0
    player_piece  -34,   10, PLAYER_PIECE_PAL0
    player_piece  -16,  -14, PLAYER_PIECE_PAL0
    player_piece  -21,   -6, PLAYER_PIECE_PAL0
    player_piece  -12,    2, PLAYER_PIECE_PAL0
    player_piece  -39,    2, PLAYER_PIECE_PAL1

data_68_4416_PlayerFrame_080:
    player_frame_header   7, $1e, $26, data_68_4820_PlayerTiles + $1c00
    player_piece  -10,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece   -7,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL1

data_68_4437_PlayerFrame_081:
    player_frame_header   5, $1e, $26, data_68_4820_PlayerTiles + $1ce0
    player_piece  -16,  -12, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL0
    player_piece  -28,    5, PLAYER_PIECE_PAL0
    player_piece  -39,    3, PLAYER_PIECE_PAL1

data_68_4450_PlayerFrame_082:
    player_frame_header   7, $1f, $26, data_68_4820_PlayerTiles + $1d80
    player_piece  -29,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL0
    player_piece  -39,   11, PLAYER_PIECE_PAL0
    player_piece  -17,  -13, PLAYER_PIECE_PAL0
    player_piece  -18,   -5, PLAYER_PIECE_PAL0
    player_piece  -13,    6, PLAYER_PIECE_PAL0
    player_piece  -40,    3, PLAYER_PIECE_PAL1

data_68_4471_PlayerFrame_083:
    player_frame_header   7, $1f, $26, data_68_4820_PlayerTiles + $1e60
    player_piece  -29,   -5, PLAYER_PIECE_PAL0
    player_piece  -29,    3, PLAYER_PIECE_PAL0
    player_piece  -13,   -9, PLAYER_PIECE_PAL0
    player_piece  -13,   -1, PLAYER_PIECE_PAL0
    player_piece  -24,   11, PLAYER_PIECE_PAL0
    player_piece   -8,  -11, PLAYER_PIECE_PAL0
    player_piece  -40,    3, PLAYER_PIECE_PAL1

data_68_4492_PlayerFrame_084:
    player_frame_header   6, $20, $26, data_68_4820_PlayerTiles + $1f40
    player_piece  -30,   -4, PLAYER_PIECE_PAL0
    player_piece  -30,    4, PLAYER_PIECE_PAL0
    player_piece  -14,  -11, PLAYER_PIECE_PAL0
    player_piece  -14,   -3, PLAYER_PIECE_PAL0
    player_piece  -22,   12, PLAYER_PIECE_PAL0
    player_piece  -41,    5, PLAYER_PIECE_PAL1

data_68_44af_PlayerFrame_085:
    player_frame_header   6, $20, $26, data_68_4820_PlayerTiles + $2000
    player_piece  -14,  -11, PLAYER_PIECE_PAL0
    player_piece  -30,   -1, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,    7, PLAYER_PIECE_PAL0
    player_piece  -14,   10, PLAYER_PIECE_PAL0
    player_piece  -41,    5, PLAYER_PIECE_PAL1

data_68_44cc_PlayerFrame_086:
    player_frame_header   8, $1e, $26, data_68_4820_PlayerTiles + $20c0
    player_piece  -32,  -14, PLAYER_PIECE_PAL0
    player_piece  -28,   -6, PLAYER_PIECE_PAL0
    player_piece  -28,    2, PLAYER_PIECE_PAL0
    player_piece  -28,   10, PLAYER_PIECE_PAL0
    player_piece  -12,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece  -12,   11, PLAYER_PIECE_PAL0
    player_piece  -12,    9, PLAYER_PIECE_PAL1

data_68_44f1_PlayerFrame_087:
    player_frame_header   6, $1d, $26, data_68_4820_PlayerTiles + $21c0
    player_piece  -36,  -19, PLAYER_PIECE_PAL0
    player_piece  -28,  -11, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece   -6,   -3, PLAYER_PIECE_PAL0
    player_piece  -17,    5, PLAYER_PIECE_PAL0
    player_piece  -11,    5, PLAYER_PIECE_PAL1

data_68_450e_PlayerFrame_088:
    player_frame_header   6, $1b, $26, data_68_4820_PlayerTiles + $2280
    player_piece  -36,  -19, PLAYER_PIECE_PAL0
    player_piece  -27,  -11, PLAYER_PIECE_PAL0
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece   -3,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,    5, PLAYER_PIECE_PAL0
    player_piece  -10,    5, PLAYER_PIECE_PAL1

data_68_452b_PlayerFrame_089:
    player_frame_header   7, $1e, $26, data_68_4820_PlayerTiles + $2340
    player_piece  -35,  -19, PLAYER_PIECE_PAL0
    player_piece  -29,  -11, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    5, PLAYER_PIECE_PAL0
    player_piece   -2,    5, PLAYER_PIECE_PAL0
    player_piece  -20,   11, PLAYER_PIECE_PAL0
    player_piece  -12,    5, PLAYER_PIECE_PAL1

data_68_454c_PlayerFrame_090:
    player_frame_header   6, $1d, $26, data_68_4820_PlayerTiles + $2420
    player_piece  -33,  -12, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL0
    player_piece  -19,    2, PLAYER_PIECE_PAL0
    player_piece  -19,   10, PLAYER_PIECE_PAL0
    player_piece   -3,    7, PLAYER_PIECE_PAL0
    player_piece  -13,   11, PLAYER_PIECE_PAL1

data_68_4569_PlayerFrame_091:
    player_frame_header   5, $1c, $26, data_68_4820_PlayerTiles + $24e0
    player_piece  -32,  -13, PLAYER_PIECE_PAL0
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece  -19,   10, PLAYER_PIECE_PAL0
    player_piece  -23,   11, PLAYER_PIECE_PAL1

data_68_4582_PlayerFrame_092:
    player_frame_header   7, $1d, $26, data_68_4820_PlayerTiles + $2580
    player_piece  -35,  -19, PLAYER_PIECE_PAL0
    player_piece  -28,  -11, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL0
    player_piece   -5,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    5, PLAYER_PIECE_PAL0
    player_piece  -21,   11, PLAYER_PIECE_PAL0
    player_piece  -11,    5, PLAYER_PIECE_PAL1

data_68_45a3_PlayerFrame_093:
    player_frame_header   9, $20, $23, data_68_4820_PlayerTiles + $2660
    player_piece  -19,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece   -8,    5, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -30,    4, PLAYER_PIECE_PAL1
    player_piece  -14,   -7, PLAYER_PIECE_PAL1
    player_piece  -14,    1, PLAYER_PIECE_PAL1

data_68_45cc_PlayerFrame_094:
    player_frame_header   9, $20, $23, data_68_4820_PlayerTiles + $2780
    player_piece  -25,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL0
    player_piece  -33,    6, PLAYER_PIECE_PAL0
    player_piece   -9,   -9, PLAYER_PIECE_PAL0
    player_piece   -9,   -1, PLAYER_PIECE_PAL0
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -30,    4, PLAYER_PIECE_PAL1
    player_piece  -14,   -6, PLAYER_PIECE_PAL1
    player_piece  -14,    2, PLAYER_PIECE_PAL1

data_68_45f5_PlayerFrame_095:
    player_frame_header   9, $21, $23, data_68_4820_PlayerTiles + $28a0
    player_piece  -12,  -18, PLAYER_PIECE_PAL0
    player_piece  -12,  -10, PLAYER_PIECE_PAL0
    player_piece  -26,   -2, PLAYER_PIECE_PAL0
    player_piece  -10,   -2, PLAYER_PIECE_PAL0
    player_piece  -33,    6, PLAYER_PIECE_PAL0
    player_piece  -25,  -10, PLAYER_PIECE_PAL1
    player_piece  -31,   -2, PLAYER_PIECE_PAL1
    player_piece  -25,   -2, PLAYER_PIECE_PAL1
    player_piece  -41,    6, PLAYER_PIECE_PAL1

data_68_461e_PlayerFrame_096:
    player_frame_header   8, $21, $22, data_68_4820_PlayerTiles + $29c0
    player_piece  -22,  -11, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -36,    7, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -31,   -3, PLAYER_PIECE_PAL1
    player_piece  -15,   -3, PLAYER_PIECE_PAL1
    player_piece  -41,    5, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1

data_68_4643_PlayerFrame_097:
    player_frame_header   7, $21, $22, data_68_4820_PlayerTiles + $2ac0
    player_piece  -11,  -11, PLAYER_PIECE_PAL0
    player_piece  -26,   -2, PLAYER_PIECE_PAL0
    player_piece  -17,   -3, PLAYER_PIECE_PAL0
    player_piece  -36,    6, PLAYER_PIECE_PAL0
    player_piece  -31,   -3, PLAYER_PIECE_PAL1
    player_piece  -26,   -4, PLAYER_PIECE_PAL1
    player_piece  -42,    5, PLAYER_PIECE_PAL1

data_68_4664_PlayerFrame_098:
    player_frame_header   9, $22, $22, data_68_4820_PlayerTiles + $2ba0
    player_piece  -27,   -1, PLAYER_PIECE_PAL0
    player_piece  -33,    7, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL0
    player_piece  -17,   -3, PLAYER_PIECE_PAL0
    player_piece  -11,    5, PLAYER_PIECE_PAL0
    player_piece  -32,   -4, PLAYER_PIECE_PAL1
    player_piece  -32,    4, PLAYER_PIECE_PAL1
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    3, PLAYER_PIECE_PAL1

data_68_468d_PlayerFrame_099:
    player_frame_header   9, $21, $22, data_68_4820_PlayerTiles + $2cc0
    player_piece  -18,  -11, PLAYER_PIECE_PAL0
    player_piece  -26,   -1, PLAYER_PIECE_PAL0
    player_piece  -34,    7, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -10,    5, PLAYER_PIECE_PAL0
    player_piece  -31,   -5, PLAYER_PIECE_PAL1
    player_piece  -31,    3, PLAYER_PIECE_PAL1
    player_piece  -15,   -5, PLAYER_PIECE_PAL1
    player_piece  -28,    3, PLAYER_PIECE_PAL1

data_68_46b6_PlayerFrame_100:
    player_frame_header   9, $20, $22, data_68_4820_PlayerTiles + $2de0
    player_piece  -12,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,    2, PLAYER_PIECE_PAL0
    player_piece  -36,   10, PLAYER_PIECE_PAL0
    player_piece  -20,   -3, PLAYER_PIECE_PAL0
    player_piece   -8,    5, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -30,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -27,    3, PLAYER_PIECE_PAL1

data_68_46df_PlayerFrame_101:
    player_frame_header   8, $1f, $22, data_68_4820_PlayerTiles + $2f00
    player_piece  -12,  -11, PLAYER_PIECE_PAL0
    player_piece  -22,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    5, PLAYER_PIECE_PAL0
    player_piece   -8,    1, PLAYER_PIECE_PAL0
    player_piece  -29,   -4, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    4, PLAYER_PIECE_PAL1
    player_piece  -27,    3, PLAYER_PIECE_PAL1

data_68_4704_PlayerFrame_102:
    player_frame_header   9, $21, $22, data_68_4820_PlayerTiles + $3000
    player_piece  -12,  -10, PLAYER_PIECE_PAL0
    player_piece  -24,   -2, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece  -33,    6, PLAYER_PIECE_PAL0
    player_piece   -8,    6, PLAYER_PIECE_PAL0
    player_piece  -14,  -10, PLAYER_PIECE_PAL1
    player_piece  -31,   -2, PLAYER_PIECE_PAL1
    player_piece  -26,   -2, PLAYER_PIECE_PAL1
    player_piece  -41,    6, PLAYER_PIECE_PAL1

data_68_472d_PlayerFrame_103:
    player_frame_header   7, $21, $22, data_68_4820_PlayerTiles + $3120
    player_piece  -12,   -9, PLAYER_PIECE_PAL0
    player_piece  -26,    2, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece  -37,    7, PLAYER_PIECE_PAL0
    player_piece  -31,   -2, PLAYER_PIECE_PAL1
    player_piece  -15,   -3, PLAYER_PIECE_PAL1
    player_piece  -34,    6, PLAYER_PIECE_PAL1

data_68_474e_PlayerFrame_104:
    player_frame_header   8, $21, $22, data_68_4820_PlayerTiles + $3200
    player_piece  -12,  -10, PLAYER_PIECE_PAL0
    player_piece  -26,   -2, PLAYER_PIECE_PAL0
    player_piece  -10,   -2, PLAYER_PIECE_PAL0
    player_piece  -26,    6, PLAYER_PIECE_PAL0
    player_piece  -27,  -10, PLAYER_PIECE_PAL1
    player_piece  -31,   -2, PLAYER_PIECE_PAL1
    player_piece  -25,   -2, PLAYER_PIECE_PAL1
    player_piece  -41,    6, PLAYER_PIECE_PAL1

data_68_4773_PlayerFrame_105:
    player_frame_header   9, $22, $22, data_68_4820_PlayerTiles + $3300
    player_piece  -12,  -10, PLAYER_PIECE_PAL0
    player_piece  -27,   -2, PLAYER_PIECE_PAL0
    player_piece  -11,   -2, PLAYER_PIECE_PAL0
    player_piece  -32,    6, PLAYER_PIECE_PAL0
    player_piece  -11,    6, PLAYER_PIECE_PAL0
    player_piece  -27,  -10, PLAYER_PIECE_PAL1
    player_piece  -32,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -43,    6, PLAYER_PIECE_PAL1

data_68_479c_PlayerFrame_106:
    player_frame_header   9, $22, $22, data_68_4820_PlayerTiles + $3420
    player_piece  -12,   -9, PLAYER_PIECE_PAL0
    player_piece  -27,   -1, PLAYER_PIECE_PAL0
    player_piece  -11,   -1, PLAYER_PIECE_PAL0
    player_piece  -27,    7, PLAYER_PIECE_PAL0
    player_piece  -11,    7, PLAYER_PIECE_PAL0
    player_piece  -32,   -3, PLAYER_PIECE_PAL1
    player_piece  -16,   -3, PLAYER_PIECE_PAL1
    player_piece  -31,    5, PLAYER_PIECE_PAL1
    player_piece  -30,    5, PLAYER_PIECE_PAL1

data_68_47c5_PlayerFrame_107:
    player_frame_header   9, $1a, $1c, data_68_4820_PlayerTiles + $3540
    player_piece  -20,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL0
    player_piece   -3,   -4, PLAYER_PIECE_PAL0
    player_piece   -3,    0, PLAYER_PIECE_PAL0
    player_piece  -24,   -6, PLAYER_PIECE_PAL1
    player_piece  -24,    0, PLAYER_PIECE_PAL1
    player_piece   -8,   -7, PLAYER_PIECE_PAL1
    player_piece   -8,    0, PLAYER_PIECE_PAL1

data_68_47ee_PlayerFrame_108:
    player_frame_header   8, $19, $1b, data_68_4820_PlayerTiles + $3660
    player_piece  -19,   -5, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -4, PLAYER_PIECE_PAL0
    player_piece   -3,   -1, PLAYER_PIECE_PAL0
    player_piece  -23,   -6, PLAYER_PIECE_PAL1
    player_piece  -23,   -1, PLAYER_PIECE_PAL1
    player_piece   -7,   -6, PLAYER_PIECE_PAL1
    player_piece   -7,   -1, PLAYER_PIECE_PAL1

    ds   $4820 - @, 0                    ; the bank pads to a 16-byte boundary here
data_68_4820_PlayerTiles:
; INCBINd by main.asm - see the header above
