; ==================================================================
; Bank $67. Gex's animation frames 1 to 49 of PLAYER_GFX_SET_WESTERN_STATION.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $47e8, then 890 tiles of graphics from $47f0 to $7f8f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/player_sprite_data/bank7f_player_sprite_data.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_67_4000_PlayerFrame_001:
    player_frame_header  10, $20, $22, data_67_47f0_PlayerTiles + $0000
    player_piece  -25,   -4, PLAYER_PIECE_PAL0
    player_piece  -25,    4, PLAYER_PIECE_PAL0
    player_piece  -36,    8, PLAYER_PIECE_PAL0
    player_piece   -9,  -13, PLAYER_PIECE_PAL0
    player_piece   -9,   -5, PLAYER_PIECE_PAL0
    player_piece  -19,    3, PLAYER_PIECE_PAL0
    player_piece  -30,   -2, PLAYER_PIECE_PAL1
    player_piece  -30,    6, PLAYER_PIECE_PAL1
    player_piece  -14,   -6, PLAYER_PIECE_PAL1
    player_piece  -14,    2, PLAYER_PIECE_PAL1

data_67_402d_PlayerFrame_002:
    player_frame_header  10, $1f, $22, data_67_47f0_PlayerTiles + $0140
    player_piece  -28,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    6, PLAYER_PIECE_PAL0
    player_piece  -36,    8, PLAYER_PIECE_PAL0
    player_piece   -8,  -11, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -17,    5, PLAYER_PIECE_PAL0
    player_piece  -29,   -1, PLAYER_PIECE_PAL1
    player_piece  -34,    7, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece  -13,    4, PLAYER_PIECE_PAL1

data_67_405a_PlayerFrame_003:
    player_frame_header   9, $1e, $22, data_67_47f0_PlayerTiles + $0280
    player_piece   -8,   -9, PLAYER_PIECE_PAL0
    player_piece  -23,   -1, PLAYER_PIECE_PAL0
    player_piece   -7,   -1, PLAYER_PIECE_PAL0
    player_piece  -27,    7, PLAYER_PIECE_PAL0
    player_piece   -5,    7, PLAYER_PIECE_PAL0
    player_piece  -24,   -4, PLAYER_PIECE_PAL1
    player_piece  -30,    4, PLAYER_PIECE_PAL1
    player_piece  -11,   -2, PLAYER_PIECE_PAL1
    player_piece  -39,    6, PLAYER_PIECE_PAL1

data_67_4083_PlayerFrame_004:
    player_frame_header   8, $1e, $23, data_67_47f0_PlayerTiles + $03a0
    player_piece   -8,  -10, PLAYER_PIECE_PAL0
    player_piece  -21,    0, PLAYER_PIECE_PAL0
    player_piece  -26,    8, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece   -3,    6, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL1
    player_piece  -37,    7, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1

data_67_40a8_PlayerFrame_005:
    player_frame_header  10, $1d, $23, data_67_47f0_PlayerTiles + $04a0
    player_piece   -9,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,   -2, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -25,    6, PLAYER_PIECE_PAL0
    player_piece   -2,    5, PLAYER_PIECE_PAL0
    player_piece  -33,   14, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -27,    3, PLAYER_PIECE_PAL1
    player_piece  -23,    3, PLAYER_PIECE_PAL1
    player_piece  -37,   11, PLAYER_PIECE_PAL1

data_67_40d5_PlayerFrame_006:
    player_frame_header  10, $1e, $23, data_67_47f0_PlayerTiles + $05e0
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -20,   -1, PLAYER_PIECE_PAL0
    player_piece  -27,    7, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -35,   15, PLAYER_PIECE_PAL0
    player_piece   -9,   -4, PLAYER_PIECE_PAL0
    player_piece  -28,   -1, PLAYER_PIECE_PAL1
    player_piece  -37,    7, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1
    player_piece  -25,    4, PLAYER_PIECE_PAL1

data_67_4102_PlayerFrame_007:
    player_frame_header  10, $1f, $23, data_67_47f0_PlayerTiles + $0720
    player_piece   -9,  -13, PLAYER_PIECE_PAL0
    player_piece  -19,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    3, PLAYER_PIECE_PAL0
    player_piece   -8,    3, PLAYER_PIECE_PAL0
    player_piece  -34,   11, PLAYER_PIECE_PAL0
    player_piece  -23,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    3, PLAYER_PIECE_PAL1
    player_piece  -24,    3, PLAYER_PIECE_PAL1
    player_piece  -39,   11, PLAYER_PIECE_PAL1

data_67_412f_PlayerFrame_008:
    player_frame_header  10, $20, $23, data_67_47f0_PlayerTiles + $0860
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -28,    4, PLAYER_PIECE_PAL0
    player_piece   -9,  -13, PLAYER_PIECE_PAL0
    player_piece  -35,   12, PLAYER_PIECE_PAL0
    player_piece   -9,   -5, PLAYER_PIECE_PAL0
    player_piece  -19,    4, PLAYER_PIECE_PAL0
    player_piece  -30,   -1, PLAYER_PIECE_PAL1
    player_piece  -30,    7, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -24,    4, PLAYER_PIECE_PAL1

data_67_415c_PlayerFrame_009:
    player_frame_header  10, $20, $22, data_67_47f0_PlayerTiles + $09a0
    player_piece  -22,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL0
    player_piece  -25,    9, PLAYER_PIECE_PAL0
    player_piece   -8,  -13, PLAYER_PIECE_PAL0
    player_piece   -8,   -5, PLAYER_PIECE_PAL0
    player_piece   -9,    4, PLAYER_PIECE_PAL0
    player_piece  -30,   -1, PLAYER_PIECE_PAL1
    player_piece  -30,    7, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -24,    3, PLAYER_PIECE_PAL1

data_67_4189_PlayerFrame_010:
    player_frame_header  10, $1f, $22, data_67_47f0_PlayerTiles + $0ae0
    player_piece  -28,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,    6, PLAYER_PIECE_PAL0
    player_piece  -37,    8, PLAYER_PIECE_PAL0
    player_piece   -9,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,   -3, PLAYER_PIECE_PAL0
    player_piece  -18,    5, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL1
    player_piece  -38,    8, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -13,    3, PLAYER_PIECE_PAL1

data_67_41b6_PlayerFrame_011:
    player_frame_header  10, $1e, $23, data_67_47f0_PlayerTiles + $0c20
    player_piece  -23,   -6, PLAYER_PIECE_PAL0
    player_piece  -27,    2, PLAYER_PIECE_PAL0
    player_piece  -29,    9, PLAYER_PIECE_PAL0
    player_piece   -7,   -9, PLAYER_PIECE_PAL0
    player_piece   -7,   -1, PLAYER_PIECE_PAL0
    player_piece   -7,    7, PLAYER_PIECE_PAL0
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -38,    9, PLAYER_PIECE_PAL1
    player_piece  -21,   -2, PLAYER_PIECE_PAL1
    player_piece  -12,    6, PLAYER_PIECE_PAL1

data_67_41e3_PlayerFrame_012:
    player_frame_header   9, $1d, $23, data_67_47f0_PlayerTiles + $0d60
    player_piece   -9,  -10, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece  -26,    7, PLAYER_PIECE_PAL0
    player_piece  -34,   15, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece   -3,    6, PLAYER_PIECE_PAL0
    player_piece  -27,   -1, PLAYER_PIECE_PAL1
    player_piece  -36,    7, PLAYER_PIECE_PAL1
    player_piece  -11,   -2, PLAYER_PIECE_PAL1

data_67_420c_PlayerFrame_013:
    player_frame_header   9, $1d, $23, data_67_47f0_PlayerTiles + $0e80
    player_piece   -9,  -10, PLAYER_PIECE_PAL0
    player_piece  -18,   -2, PLAYER_PIECE_PAL0
    player_piece  -26,    6, PLAYER_PIECE_PAL0
    player_piece  -21,   14, PLAYER_PIECE_PAL0
    player_piece   -2,   -2, PLAYER_PIECE_PAL0
    player_piece  -26,   -2, PLAYER_PIECE_PAL1
    player_piece  -35,    6, PLAYER_PIECE_PAL1
    player_piece  -22,   -3, PLAYER_PIECE_PAL1
    player_piece  -37,   14, PLAYER_PIECE_PAL1

data_67_4235_PlayerFrame_014:
    player_frame_header  10, $1e, $23, data_67_47f0_PlayerTiles + $0fa0
    player_piece  -16,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -4, PLAYER_PIECE_PAL0
    player_piece  -32,    6, PLAYER_PIECE_PAL0
    player_piece   -3,    4, PLAYER_PIECE_PAL0
    player_piece  -34,   14, PLAYER_PIECE_PAL0
    player_piece  -23,   -4, PLAYER_PIECE_PAL1
    player_piece  -31,    4, PLAYER_PIECE_PAL1
    player_piece  -11,    4, PLAYER_PIECE_PAL1
    player_piece  -38,   12, PLAYER_PIECE_PAL1

data_67_4262_PlayerFrame_015:
    player_frame_header  10, $1e, $23, data_67_47f0_PlayerTiles + $10e0
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -2, PLAYER_PIECE_PAL0
    player_piece   -8,   -4, PLAYER_PIECE_PAL0
    player_piece  -23,    6, PLAYER_PIECE_PAL0
    player_piece  -17,    4, PLAYER_PIECE_PAL0
    player_piece  -34,   14, PLAYER_PIECE_PAL0
    player_piece  -22,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    4, PLAYER_PIECE_PAL1
    player_piece  -25,    4, PLAYER_PIECE_PAL1
    player_piece  -38,   12, PLAYER_PIECE_PAL1

data_67_428f_PlayerFrame_016:
    player_frame_header  11, $1f, $22, data_67_47f0_PlayerTiles + $1220
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,    4, PLAYER_PIECE_PAL0
    player_piece   -8,    4, PLAYER_PIECE_PAL0
    player_piece  -23,   12, PLAYER_PIECE_PAL0
    player_piece   -7,   12, PLAYER_PIECE_PAL0
    player_piece  -25,   -4, PLAYER_PIECE_PAL1
    player_piece   -9,   -4, PLAYER_PIECE_PAL1
    player_piece  -29,    4, PLAYER_PIECE_PAL1
    player_piece  -26,    4, PLAYER_PIECE_PAL1
    player_piece  -40,   12, PLAYER_PIECE_PAL1

data_67_42c0_PlayerFrame_017:
    player_frame_header  10, $20, $20, data_67_47f0_PlayerTiles + $1380
    player_piece   -9,  -16, PLAYER_PIECE_PAL0
    player_piece  -16,   -8, PLAYER_PIECE_PAL0
    player_piece  -29,    0, PLAYER_PIECE_PAL0
    player_piece   -9,    0, PLAYER_PIECE_PAL0
    player_piece  -30,    8, PLAYER_PIECE_PAL0
    player_piece   -8,    8, PLAYER_PIECE_PAL0
    player_piece  -22,   -8, PLAYER_PIECE_PAL1
    player_piece  -30,    0, PLAYER_PIECE_PAL1
    player_piece  -22,    0, PLAYER_PIECE_PAL1
    player_piece  -40,    8, PLAYER_PIECE_PAL1

data_67_42ed_PlayerFrame_018:
    player_frame_header   9, $20, $21, data_67_47f0_PlayerTiles + $14c0
    player_piece  -11,  -14, PLAYER_PIECE_PAL0
    player_piece  -11,   -6, PLAYER_PIECE_PAL0
    player_piece  -25,    3, PLAYER_PIECE_PAL0
    player_piece  -35,   11, PLAYER_PIECE_PAL0
    player_piece   -9,    4, PLAYER_PIECE_PAL0
    player_piece  -22,   -5, PLAYER_PIECE_PAL1
    player_piece  -31,    3, PLAYER_PIECE_PAL1
    player_piece  -27,    3, PLAYER_PIECE_PAL1
    player_piece  -40,   11, PLAYER_PIECE_PAL1

data_67_4316_PlayerFrame_019:
    player_frame_header   9, $20, $20, data_67_47f0_PlayerTiles + $15e0
    player_piece  -14,  -15, PLAYER_PIECE_PAL0
    player_piece  -23,   -7, PLAYER_PIECE_PAL0
    player_piece  -25,    3, PLAYER_PIECE_PAL0
    player_piece  -35,   11, PLAYER_PIECE_PAL0
    player_piece   -9,    4, PLAYER_PIECE_PAL0
    player_piece  -26,   -4, PLAYER_PIECE_PAL1
    player_piece  -30,    4, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece  -41,   12, PLAYER_PIECE_PAL1

data_67_433f_PlayerFrame_020:
    player_frame_header  10, $20, $20, data_67_47f0_PlayerTiles + $1700
    player_piece  -11,  -16, PLAYER_PIECE_PAL0
    player_piece  -21,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece   -9,    0, PLAYER_PIECE_PAL0
    player_piece  -30,    8, PLAYER_PIECE_PAL0
    player_piece   -9,    8, PLAYER_PIECE_PAL0
    player_piece  -28,   -8, PLAYER_PIECE_PAL1
    player_piece  -30,    0, PLAYER_PIECE_PAL1
    player_piece  -14,    0, PLAYER_PIECE_PAL1
    player_piece  -40,    8, PLAYER_PIECE_PAL1

data_67_436c_PlayerFrame_021:
    player_frame_header  10, $21, $20, data_67_47f0_PlayerTiles + $1840
    player_piece  -10,  -16, PLAYER_PIECE_PAL0
    player_piece  -21,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece  -10,    0, PLAYER_PIECE_PAL0
    player_piece  -30,    8, PLAYER_PIECE_PAL0
    player_piece  -10,    8, PLAYER_PIECE_PAL0
    player_piece  -28,   -8, PLAYER_PIECE_PAL1
    player_piece  -31,    0, PLAYER_PIECE_PAL1
    player_piece  -15,    0, PLAYER_PIECE_PAL1
    player_piece  -41,    8, PLAYER_PIECE_PAL1

data_67_4399_PlayerFrame_022:
    player_frame_header  10, $22, $20, data_67_47f0_PlayerTiles + $1980
    player_piece  -11,  -19, PLAYER_PIECE_PAL0
    player_piece  -19,  -11, PLAYER_PIECE_PAL0
    player_piece  -26,   -3, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -37,    5, PLAYER_PIECE_PAL0
    player_piece   -6,    5, PLAYER_PIECE_PAL0
    player_piece  -27,  -11, PLAYER_PIECE_PAL1
    player_piece  -32,   -3, PLAYER_PIECE_PAL1
    player_piece  -25,   -3, PLAYER_PIECE_PAL1
    player_piece  -42,    5, PLAYER_PIECE_PAL1

data_67_43c6_PlayerFrame_023:
    player_frame_header  10, $1f, $20, data_67_47f0_PlayerTiles + $1ac0
    player_piece  -11,  -15, PLAYER_PIECE_PAL0
    player_piece  -17,   -7, PLAYER_PIECE_PAL0
    player_piece  -24,    2, PLAYER_PIECE_PAL0
    player_piece  -10,    1, PLAYER_PIECE_PAL0
    player_piece  -35,   10, PLAYER_PIECE_PAL0
    player_piece   -4,    9, PLAYER_PIECE_PAL0
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -29,    3, PLAYER_PIECE_PAL1
    player_piece  -26,    3, PLAYER_PIECE_PAL1

data_67_43f3_PlayerFrame_024:
    player_frame_header  10, $1d, $20, data_67_47f0_PlayerTiles + $1c00
    player_piece  -10,  -21, PLAYER_PIECE_PAL0
    player_piece   -9,  -13, PLAYER_PIECE_PAL0
    player_piece  -21,   -5, PLAYER_PIECE_PAL0
    player_piece   -5,   -5, PLAYER_PIECE_PAL0
    player_piece  -25,    3, PLAYER_PIECE_PAL0
    player_piece   -4,    3, PLAYER_PIECE_PAL0
    player_piece  -24,  -13, PLAYER_PIECE_PAL1
    player_piece  -27,   -5, PLAYER_PIECE_PAL1
    player_piece  -23,   -5, PLAYER_PIECE_PAL1
    player_piece  -37,    3, PLAYER_PIECE_PAL1

data_67_4420_PlayerFrame_025:
    player_frame_header  10, $20, $1d, data_67_47f0_PlayerTiles + $1d40
    player_piece  -35,  -11, PLAYER_PIECE_PAL0
    player_piece  -34,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    3, PLAYER_PIECE_PAL0
    player_piece  -16,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -13,    3, PLAYER_PIECE_PAL0
    player_piece  -30,   -7, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -6, PLAYER_PIECE_PAL1
    player_piece  -14,    2, PLAYER_PIECE_PAL1

data_67_444d_PlayerFrame_026:
    player_frame_header  10, $20, $1d, data_67_47f0_PlayerTiles + $1e80
    player_piece  -35,  -11, PLAYER_PIECE_PAL0
    player_piece  -34,   -3, PLAYER_PIECE_PAL0
    player_piece  -39,    3, PLAYER_PIECE_PAL0
    player_piece  -16,   -7, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -14,    3, PLAYER_PIECE_PAL0
    player_piece  -30,   -7, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -6, PLAYER_PIECE_PAL1
    player_piece  -14,    2, PLAYER_PIECE_PAL1

data_67_447a_PlayerFrame_027:
    player_frame_header  10, $21, $1d, data_67_47f0_PlayerTiles + $1fc0
    player_piece  -27,  -12, PLAYER_PIECE_PAL0
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    3, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -11,    1, PLAYER_PIECE_PAL0
    player_piece  -11,    3, PLAYER_PIECE_PAL0
    player_piece  -31,   -7, PLAYER_PIECE_PAL1
    player_piece  -31,    1, PLAYER_PIECE_PAL1
    player_piece  -15,   -6, PLAYER_PIECE_PAL1
    player_piece  -15,    2, PLAYER_PIECE_PAL1

data_67_44a7_PlayerFrame_028:
    player_frame_header   9, $1d, $1d, data_67_47f0_PlayerTiles + $2100
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece  -23,    3, PLAYER_PIECE_PAL0
    player_piece   -7,   -6, PLAYER_PIECE_PAL0
    player_piece   -7,    2, PLAYER_PIECE_PAL0
    player_piece  -27,   -7, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -11,   -7, PLAYER_PIECE_PAL1
    player_piece  -11,    1, PLAYER_PIECE_PAL1

data_67_44d0_PlayerFrame_029:
    player_frame_header   7, $19, $1d, data_67_47f0_PlayerTiles + $2220
    player_piece  -19,  -11, PLAYER_PIECE_PAL0
    player_piece  -18,   -6, PLAYER_PIECE_PAL0
    player_piece  -18,    2, PLAYER_PIECE_PAL0
    player_piece   -2,   -5, PLAYER_PIECE_PAL0
    player_piece   -2,    3, PLAYER_PIECE_PAL0
    player_piece  -23,   -8, PLAYER_PIECE_PAL1
    player_piece  -22,    0, PLAYER_PIECE_PAL1

data_67_44f1_PlayerFrame_030:
    player_frame_header   9, $21, $1d, data_67_47f0_PlayerTiles + $2300
    player_piece  -27,  -10, PLAYER_PIECE_PAL0
    player_piece  -11,  -10, PLAYER_PIECE_PAL0
    player_piece  -26,   -2, PLAYER_PIECE_PAL0
    player_piece  -10,   -2, PLAYER_PIECE_PAL0
    player_piece  -22,    3, PLAYER_PIECE_PAL0
    player_piece  -31,  -10, PLAYER_PIECE_PAL1
    player_piece  -15,  -10, PLAYER_PIECE_PAL1
    player_piece  -31,   -2, PLAYER_PIECE_PAL1
    player_piece  -15,   -2, PLAYER_PIECE_PAL1

data_67_451a_PlayerFrame_031:
    player_frame_header  10, $21, $1d, data_67_47f0_PlayerTiles + $2420
    player_piece  -27,  -12, PLAYER_PIECE_PAL0
    player_piece  -27,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    3, PLAYER_PIECE_PAL0
    player_piece  -11,   -7, PLAYER_PIECE_PAL0
    player_piece  -11,    1, PLAYER_PIECE_PAL0
    player_piece  -11,    3, PLAYER_PIECE_PAL0
    player_piece  -31,   -7, PLAYER_PIECE_PAL1
    player_piece  -31,    1, PLAYER_PIECE_PAL1
    player_piece  -15,   -7, PLAYER_PIECE_PAL1
    player_piece  -15,    1, PLAYER_PIECE_PAL1

data_67_4547_PlayerFrame_032:
    player_frame_header   9, $21, $20, data_67_47f0_PlayerTiles + $2560
    player_piece  -15,  -12, PLAYER_PIECE_PAL0
    player_piece  -34,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    5, PLAYER_PIECE_PAL0
    player_piece   -7,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    4, PLAYER_PIECE_PAL0
    player_piece  -31,   -6, PLAYER_PIECE_PAL1
    player_piece  -31,    2, PLAYER_PIECE_PAL1
    player_piece  -15,   -6, PLAYER_PIECE_PAL1
    player_piece  -23,    2, PLAYER_PIECE_PAL1

data_67_4570_PlayerFrame_033:
    player_frame_header   9, $21, $21, data_67_47f0_PlayerTiles + $2680
    player_piece  -27,  -12, PLAYER_PIECE_PAL0
    player_piece  -34,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -11,   -8, PLAYER_PIECE_PAL0
    player_piece  -16,    0, PLAYER_PIECE_PAL0
    player_piece  -31,   -6, PLAYER_PIECE_PAL1
    player_piece  -31,    2, PLAYER_PIECE_PAL1
    player_piece  -15,   -5, PLAYER_PIECE_PAL1
    player_piece  -15,    3, PLAYER_PIECE_PAL1

data_67_4599_PlayerFrame_034:
    player_frame_header   9, $1e, $1f, data_67_47f0_PlayerTiles + $27a0
    player_piece  -24,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    3, PLAYER_PIECE_PAL0
    player_piece   -8,   -8, PLAYER_PIECE_PAL0
    player_piece  -16,    0, PLAYER_PIECE_PAL0
    player_piece  -28,   -7, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -12,   -5, PLAYER_PIECE_PAL1
    player_piece  -12,    3, PLAYER_PIECE_PAL1

data_67_45c2_PlayerFrame_035:
    player_frame_header   9, $1b, $1d, data_67_47f0_PlayerTiles + $28c0
    player_piece  -21,  -11, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL0
    player_piece  -32,    1, PLAYER_PIECE_PAL0
    player_piece   -5,   -4, PLAYER_PIECE_PAL0
    player_piece  -16,    1, PLAYER_PIECE_PAL0
    player_piece  -25,   -7, PLAYER_PIECE_PAL1
    player_piece  -25,    1, PLAYER_PIECE_PAL1
    player_piece   -9,   -7, PLAYER_PIECE_PAL1
    player_piece   -9,    1, PLAYER_PIECE_PAL1

data_67_45eb_PlayerFrame_036:
    player_frame_header   7, $19, $1c, data_67_47f0_PlayerTiles + $29e0
    player_piece  -23,  -10, PLAYER_PIECE_PAL0
    player_piece  -23,   -2, PLAYER_PIECE_PAL0
    player_piece  -34,    0, PLAYER_PIECE_PAL0
    player_piece   -7,   -9, PLAYER_PIECE_PAL0
    player_piece  -16,   -1, PLAYER_PIECE_PAL0
    player_piece  -21,   -8, PLAYER_PIECE_PAL1
    player_piece  -22,    0, PLAYER_PIECE_PAL1

data_67_460c_PlayerFrame_037:
    player_frame_header   6, $18, $1b, data_67_47f0_PlayerTiles + $2ac0
    player_piece  -22,  -10, PLAYER_PIECE_PAL0
    player_piece  -26,   -2, PLAYER_PIECE_PAL0
    player_piece   -6,   -8, PLAYER_PIECE_PAL0
    player_piece   -6,   -1, PLAYER_PIECE_PAL0
    player_piece  -21,   -8, PLAYER_PIECE_PAL1
    player_piece  -21,   -1, PLAYER_PIECE_PAL1

data_67_4629_PlayerFrame_038:
    player_frame_header   6, $16, $1b, data_67_47f0_PlayerTiles + $2b80
    player_piece  -20,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece   -4,   -5, PLAYER_PIECE_PAL0
    player_piece   -4,   -1, PLAYER_PIECE_PAL0
    player_piece  -20,   -8, PLAYER_PIECE_PAL1
    player_piece  -21,   -1, PLAYER_PIECE_PAL1

data_67_4646_PlayerFrame_039:
    player_frame_header   6, $15, $1b, data_67_47f0_PlayerTiles + $2c40
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0
    player_piece   -3,   -1, PLAYER_PIECE_PAL0
    player_piece  -18,   -9, PLAYER_PIECE_PAL1
    player_piece  -20,   -1, PLAYER_PIECE_PAL1

data_67_4663_PlayerFrame_040:
    player_frame_header   6, $15, $1b, data_67_47f0_PlayerTiles + $2d00
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0
    player_piece   -3,   -1, PLAYER_PIECE_PAL0
    player_piece  -18,   -9, PLAYER_PIECE_PAL1
    player_piece  -20,   -1, PLAYER_PIECE_PAL1

data_67_4680_PlayerFrame_041:
    player_frame_header   6, $15, $1b, data_67_47f0_PlayerTiles + $2dc0
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece   -3,   -5, PLAYER_PIECE_PAL0
    player_piece   -3,   -1, PLAYER_PIECE_PAL0
    player_piece  -18,   -9, PLAYER_PIECE_PAL1
    player_piece  -20,   -1, PLAYER_PIECE_PAL1

data_67_469d_PlayerFrame_042:
    player_frame_header  10, $1f, $23, data_67_47f0_PlayerTiles + $2e80
    player_piece  -24,  -16, PLAYER_PIECE_PAL0
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -28,    0, PLAYER_PIECE_PAL0
    player_piece   -8,  -15, PLAYER_PIECE_PAL0
    player_piece   -8,   -7, PLAYER_PIECE_PAL0
    player_piece   -8,    0, PLAYER_PIECE_PAL0
    player_piece  -29,  -13, PLAYER_PIECE_PAL1
    player_piece  -29,   -5, PLAYER_PIECE_PAL1
    player_piece  -13,  -10, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1

data_67_46ca_PlayerFrame_043:
    player_frame_header   8, $1f, $22, data_67_47f0_PlayerTiles + $2fc0
    player_piece  -25,  -14, PLAYER_PIECE_PAL0
    player_piece  -25,   -6, PLAYER_PIECE_PAL0
    player_piece   -9,   -9, PLAYER_PIECE_PAL0
    player_piece   -9,   -1, PLAYER_PIECE_PAL0
    player_piece  -29,  -11, PLAYER_PIECE_PAL1
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -13,   -9, PLAYER_PIECE_PAL1
    player_piece  -13,   -1, PLAYER_PIECE_PAL1

data_67_46ef_PlayerFrame_044:
    player_frame_header   7, $1f, $25, data_67_47f0_PlayerTiles + $30c0
    player_piece  -25,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece  -29,    2, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,   -4, PLAYER_PIECE_PAL1
    player_piece  -29,    2, PLAYER_PIECE_PAL1
    player_piece  -13,   -2, PLAYER_PIECE_PAL1

data_67_4710_PlayerFrame_045:
    player_frame_header   9, $20, $26, data_67_47f0_PlayerTiles + $31a0
    player_piece  -26,  -10, PLAYER_PIECE_PAL0
    player_piece  -26,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,    3, PLAYER_PIECE_PAL0
    player_piece  -10,   -9, PLAYER_PIECE_PAL0
    player_piece  -10,   -1, PLAYER_PIECE_PAL0
    player_piece  -30,   -5, PLAYER_PIECE_PAL1
    player_piece  -30,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -2, PLAYER_PIECE_PAL1
    player_piece  -14,    3, PLAYER_PIECE_PAL1

data_67_4739_PlayerFrame_046:
    player_frame_header  10, $1f, $30, data_67_47f0_PlayerTiles + $32c0
    player_piece  -16,   -5, PLAYER_PIECE_PAL0
    player_piece  -22,    3, PLAYER_PIECE_PAL0
    player_piece  -24,   11, PLAYER_PIECE_PAL0
    player_piece   -8,   11, PLAYER_PIECE_PAL0
    player_piece  -36,   19, PLAYER_PIECE_PAL0
    player_piece   -6,    3, PLAYER_PIECE_PAL0
    player_piece  -29,    4, PLAYER_PIECE_PAL1
    player_piece  -29,   12, PLAYER_PIECE_PAL1
    player_piece  -13,    0, PLAYER_PIECE_PAL1
    player_piece  -13,    8, PLAYER_PIECE_PAL1

data_67_4766_PlayerFrame_047:
    player_frame_header  10, $23, $2b, data_67_47f0_PlayerTiles + $3400
    player_piece  -10,  -15, PLAYER_PIECE_PAL0
    player_piece  -30,   -7, PLAYER_PIECE_PAL0
    player_piece  -12,   -7, PLAYER_PIECE_PAL0
    player_piece  -28,    1, PLAYER_PIECE_PAL0
    player_piece  -12,    1, PLAYER_PIECE_PAL0
    player_piece   -8,    4, PLAYER_PIECE_PAL0
    player_piece  -33,   -7, PLAYER_PIECE_PAL1
    player_piece  -17,   -7, PLAYER_PIECE_PAL1
    player_piece  -32,    1, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1

data_67_4793_PlayerFrame_048:
    player_frame_header  10, $21, $2a, data_67_47f0_PlayerTiles + $3540
    player_piece  -27,   -8, PLAYER_PIECE_PAL0
    player_piece  -27,    0, PLAYER_PIECE_PAL0
    player_piece  -27,    3, PLAYER_PIECE_PAL0
    player_piece  -11,  -11, PLAYER_PIECE_PAL0
    player_piece  -11,   -3, PLAYER_PIECE_PAL0
    player_piece  -11,    3, PLAYER_PIECE_PAL0
    player_piece  -31,   -9, PLAYER_PIECE_PAL1
    player_piece  -31,   -1, PLAYER_PIECE_PAL1
    player_piece  -15,   -4, PLAYER_PIECE_PAL1
    player_piece  -15,    3, PLAYER_PIECE_PAL1

data_67_47c0_PlayerFrame_049:
    player_frame_header   9, $1f, $2b, data_67_47f0_PlayerTiles + $3680
    player_piece  -25,  -11, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece   -9,  -10, PLAYER_PIECE_PAL0
    player_piece  -24,    5, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,   -9, PLAYER_PIECE_PAL1
    player_piece  -29,   -1, PLAYER_PIECE_PAL1
    player_piece  -13,   -6, PLAYER_PIECE_PAL1
    player_piece  -13,    2, PLAYER_PIECE_PAL1

    ds   $47f0 - @, 0                    ; the bank pads to a 16-byte boundary here
data_67_47f0_PlayerTiles:
; INCBINd by main.asm - see the header above
