; ==================================================================
; Bank $70. Gex's animation frames 120 to 190 of PLAYER_GFX_SET_SUPERHERO_SHOW.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $484a, then 884 tiles of graphics from $4850 to $7f8f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/player_sprite_data/bank7f_player_sprite_data.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_70_4000_PlayerFrame_120:
    player_frame_header   8, $20, $1e, data_70_4850_PlayerTiles + $0000
    player_piece  -25,   -5, PLAYER_PIECE_PAL0
    player_piece  -30,    3, PLAYER_PIECE_PAL0
    player_piece   -9,    0, PLAYER_PIECE_PAL0
    player_piece  -19,  -11, PLAYER_PIECE_PAL1
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece  -30,    5, PLAYER_PIECE_PAL1
    player_piece  -14,   -3, PLAYER_PIECE_PAL1
    player_piece  -14,    5, PLAYER_PIECE_PAL1

data_70_4025_PlayerFrame_121:
    player_frame_header   8, $20, $1f, data_70_4850_PlayerTiles + $0100
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -26,    0, PLAYER_PIECE_PAL0
    player_piece   -8,    0, PLAYER_PIECE_PAL0
    player_piece  -29,   -8, PLAYER_PIECE_PAL1
    player_piece  -13,   -8, PLAYER_PIECE_PAL1
    player_piece  -30,    0, PLAYER_PIECE_PAL1
    player_piece  -14,    0, PLAYER_PIECE_PAL1
    player_piece  -23,    7, PLAYER_PIECE_PAL1

data_70_404a_PlayerFrame_122:
    player_frame_header   8, $1f, $1c, data_70_4850_PlayerTiles + $0200
    player_piece  -35,   -4, PLAYER_PIECE_PAL0
    player_piece  -34,    4, PLAYER_PIECE_PAL0
    player_piece   -7,    0, PLAYER_PIECE_PAL0
    player_piece  -27,   -9, PLAYER_PIECE_PAL1
    player_piece  -29,   -1, PLAYER_PIECE_PAL1
    player_piece  -18,    4, PLAYER_PIECE_PAL1
    player_piece  -13,   -6, PLAYER_PIECE_PAL1
    player_piece  -19,    2, PLAYER_PIECE_PAL1

data_70_406f_PlayerFrame_123:
    player_frame_header   8, $21, $1b, data_70_4850_PlayerTiles + $0300
    player_piece  -30,   -5, PLAYER_PIECE_PAL0
    player_piece  -32,    3, PLAYER_PIECE_PAL0
    player_piece  -10,   -1, PLAYER_PIECE_PAL0
    player_piece  -30,  -10, PLAYER_PIECE_PAL1
    player_piece  -31,   -2, PLAYER_PIECE_PAL1
    player_piece  -20,    3, PLAYER_PIECE_PAL1
    player_piece  -15,   -6, PLAYER_PIECE_PAL1
    player_piece  -15,    2, PLAYER_PIECE_PAL1

data_70_4094_PlayerFrame_124:
    player_frame_header   8, $21, $1c, data_70_4850_PlayerTiles + $0400
    player_piece  -34,   -4, PLAYER_PIECE_PAL0
    player_piece  -27,    4, PLAYER_PIECE_PAL0
    player_piece   -9,   -1, PLAYER_PIECE_PAL0
    player_piece  -28,  -10, PLAYER_PIECE_PAL1
    player_piece  -31,   -2, PLAYER_PIECE_PAL1
    player_piece  -27,    4, PLAYER_PIECE_PAL1
    player_piece  -15,   -6, PLAYER_PIECE_PAL1
    player_piece  -15,    2, PLAYER_PIECE_PAL1

data_70_40b9_PlayerFrame_125:
    player_frame_header   4, $21, $19, data_70_4850_PlayerTiles + $0500
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_70_40ce_PlayerFrame_126:
    player_frame_header   4, $21, $18, data_70_4850_PlayerTiles + $0580
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_70_40e3_PlayerFrame_127:
    player_frame_header   4, $21, $18, data_70_4850_PlayerTiles + $0600
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_70_40f8_PlayerFrame_128:
    player_frame_header   4, $21, $18, data_70_4850_PlayerTiles + $0680
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_70_410d_PlayerFrame_129:
    player_frame_header   4, $21, $18, data_70_4850_PlayerTiles + $0700
    player_piece  -31,   -8, PLAYER_PIECE_PAL0
    player_piece  -15,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_70_4122_PlayerFrame_130:
    player_frame_header   4, $21, $18, data_70_4850_PlayerTiles + $0780
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_70_4137_PlayerFrame_131:
    player_frame_header   4, $21, $18, data_70_4850_PlayerTiles + $0800
    player_piece  -30,   -8, PLAYER_PIECE_PAL0
    player_piece  -14,   -8, PLAYER_PIECE_PAL0
    player_piece  -31,    0, PLAYER_PIECE_PAL0
    player_piece  -15,    0, PLAYER_PIECE_PAL0

data_70_414c_PlayerFrame_132:
    player_frame_header   8, $20, $1a, data_70_4850_PlayerTiles + $0880
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -24,    0, PLAYER_PIECE_PAL0
    player_piece   -8,   -8, PLAYER_PIECE_PAL0
    player_piece   -8,    0, PLAYER_PIECE_PAL0
    player_piece  -30,   -8, PLAYER_PIECE_PAL1
    player_piece  -26,    0, PLAYER_PIECE_PAL1
    player_piece  -14,   -8, PLAYER_PIECE_PAL1
    player_piece   -7,    0, PLAYER_PIECE_PAL1

data_70_4171_PlayerFrame_133:
    player_frame_header   8, $1f, $19, data_70_4850_PlayerTiles + $0980
    player_piece  -24,  -10, PLAYER_PIECE_PAL0
    player_piece   -8,  -10, PLAYER_PIECE_PAL0
    player_piece  -25,   -2, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,  -10, PLAYER_PIECE_PAL1
    player_piece  -13,  -10, PLAYER_PIECE_PAL1
    player_piece  -21,   -2, PLAYER_PIECE_PAL1
    player_piece   -5,   -2, PLAYER_PIECE_PAL1

data_70_4196_PlayerFrame_134:
    player_frame_header   8, $1f, $19, data_70_4850_PlayerTiles + $0a80
    player_piece  -32,  -10, PLAYER_PIECE_PAL0
    player_piece   -8,  -10, PLAYER_PIECE_PAL0
    player_piece  -24,   -2, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,  -10, PLAYER_PIECE_PAL1
    player_piece  -13,  -10, PLAYER_PIECE_PAL1
    player_piece  -25,   -2, PLAYER_PIECE_PAL1
    player_piece   -7,   -2, PLAYER_PIECE_PAL1

data_70_41bb_PlayerFrame_135:
    player_frame_header   8, $1b, $1e, data_70_4850_PlayerTiles + $0b80
    player_piece  -25,  -10, PLAYER_PIECE_PAL0
    player_piece   -3,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece   -4,   -2, PLAYER_PIECE_PAL0
    player_piece  -25,  -10, PLAYER_PIECE_PAL1
    player_piece   -9,  -10, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1
    player_piece  -16,    4, PLAYER_PIECE_PAL1

data_70_41e0_PlayerFrame_136:
    player_frame_header   7, $16, $1e, data_70_4850_PlayerTiles + $0c80
    player_piece  -20,  -11, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -20,    5, PLAYER_PIECE_PAL0
    player_piece  -11,  -11, PLAYER_PIECE_PAL1
    player_piece  -29,   -2, PLAYER_PIECE_PAL1
    player_piece   -4,   -3, PLAYER_PIECE_PAL1
    player_piece   -4,    5, PLAYER_PIECE_PAL1

data_70_4201_PlayerFrame_137:
    player_frame_header   7, $15, $1e, data_70_4850_PlayerTiles + $0d60
    player_piece  -20,  -11, PLAYER_PIECE_PAL0
    player_piece  -16,   -3, PLAYER_PIECE_PAL0
    player_piece  -20,    5, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL1
    player_piece  -19,   -2, PLAYER_PIECE_PAL1
    player_piece   -3,   -3, PLAYER_PIECE_PAL1
    player_piece   -4,    5, PLAYER_PIECE_PAL1

data_70_4222_PlayerFrame_138:
    player_frame_header   8, $19, $1f, data_70_4850_PlayerTiles + $0e40
    player_piece  -19,  -10, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece  -18,    5, PLAYER_PIECE_PAL0
    player_piece   -2,    5, PLAYER_PIECE_PAL0
    player_piece  -21,   -6, PLAYER_PIECE_PAL1
    player_piece  -24,    2, PLAYER_PIECE_PAL1
    player_piece   -5,   -5, PLAYER_PIECE_PAL1
    player_piece   -4,    3, PLAYER_PIECE_PAL1

data_70_4247_PlayerFrame_139:
    player_frame_header   8, $19, $1d, data_70_4850_PlayerTiles + $0f40
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -19,   -1, PLAYER_PIECE_PAL0
    player_piece  -18,    3, PLAYER_PIECE_PAL0
    player_piece   -2,    3, PLAYER_PIECE_PAL0
    player_piece  -23,   -5, PLAYER_PIECE_PAL1
    player_piece  -24,    3, PLAYER_PIECE_PAL1
    player_piece   -7,   -6, PLAYER_PIECE_PAL1
    player_piece   -5,    2, PLAYER_PIECE_PAL1

data_70_426c_PlayerFrame_140:
    player_frame_header   8, $19, $21, data_70_4850_PlayerTiles + $1040
    player_piece  -20,  -14, PLAYER_PIECE_PAL0
    player_piece  -19,   -6, PLAYER_PIECE_PAL0
    player_piece  -17,    2, PLAYER_PIECE_PAL0
    player_piece  -28,   10, PLAYER_PIECE_PAL0
    player_piece   -1,    5, PLAYER_PIECE_PAL0
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -24,    2, PLAYER_PIECE_PAL1
    player_piece   -4,    2, PLAYER_PIECE_PAL1

data_70_4291_PlayerFrame_141:
    player_frame_header   7, $20, $1d, data_70_4850_PlayerTiles + $1140
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece  -27,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -6, PLAYER_PIECE_PAL1
    player_piece  -11,    2, PLAYER_PIECE_PAL1

data_70_42b2_PlayerFrame_142:
    player_frame_header   7, $21, $1c, data_70_4850_PlayerTiles + $1220
    player_piece  -24,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,    1, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -11,    1, PLAYER_PIECE_PAL1

data_70_42d3_PlayerFrame_143:
    player_frame_header   7, $21, $1c, data_70_4850_PlayerTiles + $1300
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -11,    1, PLAYER_PIECE_PAL1

data_70_42f4_PlayerFrame_144:
    player_frame_header   7, $21, $1c, data_70_4850_PlayerTiles + $13e0
    player_piece  -23,   -5, PLAYER_PIECE_PAL0
    player_piece  -23,    1, PLAYER_PIECE_PAL0
    player_piece   -7,   -2, PLAYER_PIECE_PAL0
    player_piece  -38,   -3, PLAYER_PIECE_PAL1
    player_piece  -26,    1, PLAYER_PIECE_PAL1
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -10,    1, PLAYER_PIECE_PAL1

data_70_4315_PlayerFrame_145:
    player_frame_header   7, $20, $1c, data_70_4850_PlayerTiles + $14c0
    player_piece  -24,   -6, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece  -30,   -3, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -14,   -6, PLAYER_PIECE_PAL1
    player_piece  -11,    1, PLAYER_PIECE_PAL1

data_70_4336_PlayerFrame_146:
    player_frame_header   7, $21, $1b, data_70_4850_PlayerTiles + $15a0
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    0, PLAYER_PIECE_PAL0
    player_piece   -8,   -1, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL1
    player_piece  -27,    0, PLAYER_PIECE_PAL1
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -11,    0, PLAYER_PIECE_PAL1

data_70_4357_PlayerFrame_147:
    player_frame_header   7, $21, $1c, data_70_4850_PlayerTiles + $1680
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece  -39,   -3, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -11,    1, PLAYER_PIECE_PAL1

data_70_4378_PlayerFrame_148:
    player_frame_header   7, $21, $1c, data_70_4850_PlayerTiles + $1760
    player_piece  -23,   -5, PLAYER_PIECE_PAL0
    player_piece  -23,    1, PLAYER_PIECE_PAL0
    player_piece   -7,   -3, PLAYER_PIECE_PAL0
    player_piece  -38,   -3, PLAYER_PIECE_PAL1
    player_piece  -26,    1, PLAYER_PIECE_PAL1
    player_piece  -16,   -6, PLAYER_PIECE_PAL1
    player_piece  -10,    1, PLAYER_PIECE_PAL1

data_70_4399_PlayerFrame_149:
    player_frame_header   7, $1f, $1d, data_70_4850_PlayerTiles + $1840
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -26,    2, PLAYER_PIECE_PAL1
    player_piece  -12,   -5, PLAYER_PIECE_PAL1
    player_piece  -10,    2, PLAYER_PIECE_PAL1

data_70_43ba_PlayerFrame_150:
    player_frame_header   7, $1f, $1c, data_70_4850_PlayerTiles + $1920
    player_piece  -24,   -4, PLAYER_PIECE_PAL0
    player_piece  -29,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -1, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -26,    1, PLAYER_PIECE_PAL1
    player_piece  -12,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,    1, PLAYER_PIECE_PAL1

data_70_43db_PlayerFrame_151:
    player_frame_header   7, $1f, $1c, data_70_4850_PlayerTiles + $1a00
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -26,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,    1, PLAYER_PIECE_PAL1

data_70_43fc_PlayerFrame_152:
    player_frame_header   7, $1e, $1c, data_70_4850_PlayerTiles + $1ae0
    player_piece  -23,   -5, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece   -7,   -2, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL1
    player_piece  -25,    1, PLAYER_PIECE_PAL1
    player_piece  -12,   -5, PLAYER_PIECE_PAL1
    player_piece   -9,    1, PLAYER_PIECE_PAL1

data_70_441d_PlayerFrame_153:
    player_frame_header   7, $1f, $1c, data_70_4850_PlayerTiles + $1bc0
    player_piece  -24,   -6, PLAYER_PIECE_PAL0
    player_piece  -24,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -26,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,    1, PLAYER_PIECE_PAL1

data_70_443e_PlayerFrame_154:
    player_frame_header   7, $1f, $1b, data_70_4850_PlayerTiles + $1ca0
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,    0, PLAYER_PIECE_PAL0
    player_piece   -8,   -1, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -26,    0, PLAYER_PIECE_PAL1
    player_piece  -13,   -4, PLAYER_PIECE_PAL1
    player_piece  -10,    0, PLAYER_PIECE_PAL1

data_70_445f_PlayerFrame_155:
    player_frame_header   7, $1f, $1c, data_70_4850_PlayerTiles + $1d80
    player_piece  -24,   -5, PLAYER_PIECE_PAL0
    player_piece  -27,    1, PLAYER_PIECE_PAL0
    player_piece   -8,   -1, PLAYER_PIECE_PAL0
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -26,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -5, PLAYER_PIECE_PAL1
    player_piece  -10,    1, PLAYER_PIECE_PAL1

data_70_4480_PlayerFrame_156:
    player_frame_header   7, $1e, $1c, data_70_4850_PlayerTiles + $1e60
    player_piece  -23,   -5, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece   -7,   -3, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL1
    player_piece  -25,    1, PLAYER_PIECE_PAL1
    player_piece  -12,   -5, PLAYER_PIECE_PAL1
    player_piece   -9,    1, PLAYER_PIECE_PAL1

data_70_44a1_PlayerFrame_157:
    player_frame_header  11, $1f, $28, data_70_4850_PlayerTiles + $1f40
    player_piece  -23,   -9, PLAYER_PIECE_PAL0
    player_piece  -23,   -1, PLAYER_PIECE_PAL0
    player_piece   -7,   -7, PLAYER_PIECE_PAL0
    player_piece  -39,    1, PLAYER_PIECE_PAL0
    player_piece   -7,    1, PLAYER_PIECE_PAL0
    player_piece  -42,    9, PLAYER_PIECE_PAL0
    player_piece  -28,  -11, PLAYER_PIECE_PAL1
    player_piece  -38,   -3, PLAYER_PIECE_PAL1
    player_piece  -12,   -7, PLAYER_PIECE_PAL1
    player_piece  -21,    5, PLAYER_PIECE_PAL1
    player_piece   -5,    1, PLAYER_PIECE_PAL1

data_70_44d2_PlayerFrame_158:
    player_frame_header   8, $20, $20, data_70_4850_PlayerTiles + $20a0
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -24,    0, PLAYER_PIECE_PAL0
    player_piece  -21,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -29,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -7, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_70_44f7_PlayerFrame_159:
    player_frame_header   8, $20, $20, data_70_4850_PlayerTiles + $21a0
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -24,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -4, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -29,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -7, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_70_451c_PlayerFrame_160:
    player_frame_header   8, $20, $20, data_70_4850_PlayerTiles + $22a0
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -24,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -6, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -29,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -7, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_70_4541_PlayerFrame_161:
    player_frame_header   8, $20, $20, data_70_4850_PlayerTiles + $23a0
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -24,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -6, PLAYER_PIECE_PAL0
    player_piece  -30,   -6, PLAYER_PIECE_PAL1
    player_piece  -29,    2, PLAYER_PIECE_PAL1
    player_piece  -14,   -7, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_70_4566_PlayerFrame_162:
    player_frame_header   9, $20, $20, data_70_4850_PlayerTiles + $24a0
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -24,    0, PLAYER_PIECE_PAL0
    player_piece  -16,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -8, PLAYER_PIECE_PAL0
    player_piece   -8,    0, PLAYER_PIECE_PAL0
    player_piece  -39,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    2, PLAYER_PIECE_PAL1
    player_piece  -18,   -7, PLAYER_PIECE_PAL1
    player_piece  -11,    1, PLAYER_PIECE_PAL1

data_70_458f_PlayerFrame_163:
    player_frame_header   8, $20, $20, data_70_4850_PlayerTiles + $25c0
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -24,    0, PLAYER_PIECE_PAL0
    player_piece   -8,   -7, PLAYER_PIECE_PAL0
    player_piece  -20,    1, PLAYER_PIECE_PAL0
    player_piece  -39,   -4, PLAYER_PIECE_PAL1
    player_piece  -22,   -7, PLAYER_PIECE_PAL1
    player_piece  -27,    4, PLAYER_PIECE_PAL1
    player_piece  -11,    4, PLAYER_PIECE_PAL1

data_70_45b4_PlayerFrame_164:
    player_frame_header   5, $20, $23, data_70_4850_PlayerTiles + $26c0
    player_piece  -24,  -11, PLAYER_PIECE_PAL0
    player_piece  -26,   -3, PLAYER_PIECE_PAL0
    player_piece  -26,    5, PLAYER_PIECE_PAL0
    player_piece  -39,   -4, PLAYER_PIECE_PAL1
    player_piece  -40,    4, PLAYER_PIECE_PAL1

data_70_45cd_PlayerFrame_165:
    player_frame_header   6, $20, $24, data_70_4850_PlayerTiles + $2760
    player_piece  -19,  -14, PLAYER_PIECE_PAL0
    player_piece  -32,   -6, PLAYER_PIECE_PAL0
    player_piece  -32,    2, PLAYER_PIECE_PAL0
    player_piece  -19,    6, PLAYER_PIECE_PAL0
    player_piece  -39,   -6, PLAYER_PIECE_PAL1
    player_piece  -39,    2, PLAYER_PIECE_PAL1

data_70_45ea_PlayerFrame_166:
    player_frame_header   5, $20, $26, data_70_4850_PlayerTiles + $2820
    player_piece  -25,  -15, PLAYER_PIECE_PAL0
    player_piece  -38,   -7, PLAYER_PIECE_PAL0
    player_piece  -38,    1, PLAYER_PIECE_PAL0
    player_piece  -40,    8, PLAYER_PIECE_PAL0
    player_piece  -43,   -3, PLAYER_PIECE_PAL1

data_70_4603_PlayerFrame_167:
    player_frame_header   3, $1e, $20, data_70_4850_PlayerTiles + $28c0
    player_piece  -40,  -14, PLAYER_PIECE_PAL0
    player_piece  -37,   -6, PLAYER_PIECE_PAL0
    player_piece  -37,    2, PLAYER_PIECE_PAL0

data_70_4614_PlayerFrame_168:
    player_frame_header   2, $1e, $1b, data_70_4850_PlayerTiles + $2920
    player_piece  -37,   -6, PLAYER_PIECE_PAL0
    player_piece  -40,   -3, PLAYER_PIECE_PAL0

data_70_4621_PlayerFrame_169:
    player_frame_header   9, $1b, $19, data_70_4850_PlayerTiles + $2960
    player_piece  -28,  -15, PLAYER_PIECE_PAL0
    player_piece  -20,   -7, PLAYER_PIECE_PAL0
    player_piece   -4,   -7, PLAYER_PIECE_PAL0
    player_piece  -22,    1, PLAYER_PIECE_PAL0
    player_piece  -13,  -15, PLAYER_PIECE_PAL1
    player_piece  -25,   -7, PLAYER_PIECE_PAL1
    player_piece   -9,   -7, PLAYER_PIECE_PAL1
    player_piece  -35,    1, PLAYER_PIECE_PAL1
    player_piece   -8,    1, PLAYER_PIECE_PAL1

data_70_464a_PlayerFrame_170:
    player_frame_header   8, $1e, $20, data_70_4850_PlayerTiles + $2a80
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -24,    0, PLAYER_PIECE_PAL0
    player_piece  -21,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -28,   -7, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -12,   -6, PLAYER_PIECE_PAL1
    player_piece  -12,    2, PLAYER_PIECE_PAL1

data_70_466f_PlayerFrame_171:
    player_frame_header   8, $1d, $20, data_70_4850_PlayerTiles + $2b80
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -24,    0, PLAYER_PIECE_PAL0
    player_piece  -21,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -27,   -7, PLAYER_PIECE_PAL1
    player_piece  -27,    1, PLAYER_PIECE_PAL1
    player_piece  -11,   -6, PLAYER_PIECE_PAL1
    player_piece  -11,    2, PLAYER_PIECE_PAL1

data_70_4694_PlayerFrame_172:
    player_frame_header   6, $1c, $1f, data_70_4850_PlayerTiles + $2c80
    player_piece  -26,   -7, PLAYER_PIECE_PAL0
    player_piece  -26,    1, PLAYER_PIECE_PAL0
    player_piece  -10,   -3, PLAYER_PIECE_PAL0
    player_piece  -25,   -6, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1
    player_piece   -9,   -6, PLAYER_PIECE_PAL1

data_70_46b1_PlayerFrame_173:
    player_frame_header   4, $1b, $1d, data_70_4850_PlayerTiles + $2d40
    player_piece  -25,   -4, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,    3, PLAYER_PIECE_PAL1

data_70_46c6_PlayerFrame_174:
    player_frame_header   4, $19, $1d, data_70_4850_PlayerTiles + $2dc0
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece   -7,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1

data_70_46db_PlayerFrame_175:
    player_frame_header   3, $15, $1d, data_70_4850_PlayerTiles + $2e40
    player_piece  -21,   -2, PLAYER_PIECE_PAL0
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece   -5,   -1, PLAYER_PIECE_PAL1

data_70_46ec_PlayerFrame_176:
    player_frame_header   3, $10, $1d, data_70_4850_PlayerTiles + $2ea0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece   -4,   -5, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1

data_70_46fd_PlayerFrame_177:
    player_frame_header   3, $0c, $1c, data_70_4850_PlayerTiles + $2f00
    player_piece  -18,   -2, PLAYER_PIECE_PAL0
    player_piece   -2,   -4, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1

data_70_470e_PlayerFrame_178:
    player_frame_header   7, $10, $2e, data_70_4850_PlayerTiles + $2f60
    player_piece  -16,  -10, PLAYER_PIECE_PAL0
    player_piece  -16,   -2, PLAYER_PIECE_PAL0
    player_piece   -1,    6, PLAYER_PIECE_PAL0
    player_piece  -16,  -17, PLAYER_PIECE_PAL1
    player_piece  -17,   -8, PLAYER_PIECE_PAL1
    player_piece  -16,    0, PLAYER_PIECE_PAL1
    player_piece  -16,    7, PLAYER_PIECE_PAL1

data_70_472f_PlayerFrame_179:
    player_frame_header   4, $27, $16, data_70_4850_PlayerTiles + $3040
    player_piece  -37,   -5, PLAYER_PIECE_PAL0
    player_piece  -34,    3, PLAYER_PIECE_PAL0
    player_piece  -21,   -5, PLAYER_PIECE_PAL0
    player_piece  -18,   -2, PLAYER_PIECE_PAL0

data_70_4744_PlayerFrame_180:
    player_frame_header   4, $27, $16, data_70_4850_PlayerTiles + $30c0
    player_piece  -37,   -4, PLAYER_PIECE_PAL0
    player_piece  -21,   -5, PLAYER_PIECE_PAL0
    player_piece  -33,    4, PLAYER_PIECE_PAL0
    player_piece   -6,   -3, PLAYER_PIECE_PAL0

data_70_4759_PlayerFrame_181:
    player_frame_header   4, $28, $16, data_70_4850_PlayerTiles + $3140
    player_piece  -38,   -4, PLAYER_PIECE_PAL0
    player_piece  -22,   -5, PLAYER_PIECE_PAL0
    player_piece  -34,    3, PLAYER_PIECE_PAL0
    player_piece  -18,   -2, PLAYER_PIECE_PAL0

data_70_476e_PlayerFrame_182:
    player_frame_header   5, $28, $16, data_70_4850_PlayerTiles + $31c0
    player_piece  -38,   -4, PLAYER_PIECE_PAL0
    player_piece  -37,    3, PLAYER_PIECE_PAL0
    player_piece  -22,   -5, PLAYER_PIECE_PAL0
    player_piece  -20,    3, PLAYER_PIECE_PAL0
    player_piece   -6,   -3, PLAYER_PIECE_PAL0

data_70_4787_PlayerFrame_183:
    player_frame_header   4, $28, $16, data_70_4850_PlayerTiles + $3260
    player_piece  -38,   -3, PLAYER_PIECE_PAL0
    player_piece  -38,    3, PLAYER_PIECE_PAL0
    player_piece  -22,   -5, PLAYER_PIECE_PAL0
    player_piece  -19,   -2, PLAYER_PIECE_PAL0

data_70_479c_PlayerFrame_184:
    player_frame_header   5, $28, $16, data_70_4850_PlayerTiles + $32e0
    player_piece  -38,   -3, PLAYER_PIECE_PAL0
    player_piece  -34,    3, PLAYER_PIECE_PAL0
    player_piece  -22,   -5, PLAYER_PIECE_PAL0
    player_piece  -18,    3, PLAYER_PIECE_PAL0
    player_piece   -6,   -3, PLAYER_PIECE_PAL0

data_70_47b5_PlayerFrame_185:
    player_frame_header   5, $27, $16, data_70_4850_PlayerTiles + $3380
    player_piece  -37,   -4, PLAYER_PIECE_PAL0
    player_piece  -34,    3, PLAYER_PIECE_PAL0
    player_piece  -21,   -5, PLAYER_PIECE_PAL0
    player_piece  -11,    3, PLAYER_PIECE_PAL0
    player_piece   -5,   -3, PLAYER_PIECE_PAL0

data_70_47ce_PlayerFrame_186:
    player_frame_header   5, $22, $1c, data_70_4850_PlayerTiles + $3420
    player_piece  -28,   -5, PLAYER_PIECE_PAL0
    player_piece  -33,    3, PLAYER_PIECE_PAL0
    player_piece  -32,    9, PLAYER_PIECE_PAL0
    player_piece  -12,   -4, PLAYER_PIECE_PAL0
    player_piece   -5,    4, PLAYER_PIECE_PAL0

data_70_47e7_PlayerFrame_187:
    player_frame_header   5, $20, $1f, data_70_4850_PlayerTiles + $34c0
    player_piece  -25,  -11, PLAYER_PIECE_PAL0
    player_piece  -28,   -3, PLAYER_PIECE_PAL0
    player_piece  -12,   -3, PLAYER_PIECE_PAL0
    player_piece  -31,    5, PLAYER_PIECE_PAL0
    player_piece  -30,   12, PLAYER_PIECE_PAL0

data_70_4800_PlayerFrame_188:
    player_frame_header   5, $20, $21, data_70_4850_PlayerTiles + $3560
    player_piece  -30,  -11, PLAYER_PIECE_PAL0
    player_piece  -31,   -3, PLAYER_PIECE_PAL0
    player_piece  -33,    5, PLAYER_PIECE_PAL0
    player_piece  -29,   13, PLAYER_PIECE_PAL0
    player_piece  -13,   13, PLAYER_PIECE_PAL0

data_70_4819_PlayerFrame_189:
    player_frame_header   5, $20, $20, data_70_4850_PlayerTiles + $3600
    player_piece  -33,  -11, PLAYER_PIECE_PAL0
    player_piece  -35,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -13,    5, PLAYER_PIECE_PAL0
    player_piece  -26,   13, PLAYER_PIECE_PAL0

data_70_4832_PlayerFrame_190:
    player_frame_header   5, $20, $1d, data_70_4850_PlayerTiles + $36a0
    player_piece  -35,  -11, PLAYER_PIECE_PAL0
    player_piece  -34,   -3, PLAYER_PIECE_PAL0
    player_piece  -25,    5, PLAYER_PIECE_PAL0
    player_piece   -9,    5, PLAYER_PIECE_PAL0
    player_piece  -18,   10, PLAYER_PIECE_PAL0

    ds   $4850 - @, 0                    ; the bank pads to a 16-byte boundary here
data_70_4850_PlayerTiles:
; INCBINd by main.asm - see the header above
