; ==================================================================
; Bank $6e. Gex's animation frames 1 to 53 of PLAYER_GFX_SET_SUPERHERO_SHOW.
;
; Generated by tools/extract_player_sprites.py. The bank splits in two: these
; records from $4000 to $47f8, then 888 tiles of graphics from $4800 to $7f7f, which main.asm
; INCBINs straight after this file. Both halves are in sprite-id order.
;
; The sheet is padded with blank tiles to reach a square-ish shape. They sit at
; the end, so main.asm's INCBIN takes a length and leaves them out of the ROM.
;
; A frame is reached from data/player_sprite_data/bank7f_player_sprite_data.asm, which documents the
; lookup and the format; code/bank00_player_sprites.asm is what walks it.
; ==================================================================

data_6e_4000_PlayerFrame_001:
    player_frame_header  10, $1f, $22, data_6e_4800_PlayerTiles + $0000
    player_piece   -8,  -13, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL0
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    4, PLAYER_PIECE_PAL0
    player_piece  -36,   12, PLAYER_PIECE_PAL0
    player_piece  -23,   -5, PLAYER_PIECE_PAL1
    player_piece   -5,  -10, PLAYER_PIECE_PAL1
    player_piece  -36,   -2, PLAYER_PIECE_PAL1
    player_piece  -29,    6, PLAYER_PIECE_PAL1
    player_piece  -19,    3, PLAYER_PIECE_PAL1

data_6e_402d_PlayerFrame_002:
    player_frame_header   9, $1e, $22, data_6e_4800_PlayerTiles + $0140
    player_piece  -21,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,    6, PLAYER_PIECE_PAL0
    player_piece  -36,    8, PLAYER_PIECE_PAL0
    player_piece   -7,  -11, PLAYER_PIECE_PAL0
    player_piece   -7,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    4, PLAYER_PIECE_PAL1
    player_piece   -4,   -8, PLAYER_PIECE_PAL1
    player_piece  -17,    3, PLAYER_PIECE_PAL1

data_6e_4056_PlayerFrame_003:
    player_frame_header   9, $1e, $22, data_6e_4800_PlayerTiles + $0260
    player_piece   -8,   -9, PLAYER_PIECE_PAL0
    player_piece  -20,   -1, PLAYER_PIECE_PAL0
    player_piece  -32,    7, PLAYER_PIECE_PAL0
    player_piece   -4,   -1, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL1
    player_piece  -28,    5, PLAYER_PIECE_PAL1
    player_piece  -17,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    2, PLAYER_PIECE_PAL1
    player_piece   -4,    8, PLAYER_PIECE_PAL1

data_6e_407f_PlayerFrame_004:
    player_frame_header   8, $1d, $23, data_6e_4800_PlayerTiles + $0380
    player_piece  -10,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece  -30,    6, PLAYER_PIECE_PAL0
    player_piece  -34,    9, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    4, PLAYER_PIECE_PAL1
    player_piece   -4,   -4, PLAYER_PIECE_PAL1
    player_piece  -16,    4, PLAYER_PIECE_PAL1

data_6e_40a4_PlayerFrame_005:
    player_frame_header   9, $1c, $23, data_6e_4800_PlayerTiles + $0480
    player_piece  -11,  -11, PLAYER_PIECE_PAL0
    player_piece  -17,   -3, PLAYER_PIECE_PAL0
    player_piece  -29,    5, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece  -26,    4, PLAYER_PIECE_PAL1
    player_piece  -36,    9, PLAYER_PIECE_PAL1
    player_piece   -3,   -3, PLAYER_PIECE_PAL1
    player_piece  -10,    5, PLAYER_PIECE_PAL1

data_6e_40cd_PlayerFrame_006:
    player_frame_header   9, $1d, $23, data_6e_4800_PlayerTiles + $05a0
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -22,    4, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    4, PLAYER_PIECE_PAL1
    player_piece  -38,    9, PLAYER_PIECE_PAL1
    player_piece   -4,   -5, PLAYER_PIECE_PAL1
    player_piece   -8,    4, PLAYER_PIECE_PAL1

data_6e_40f6_PlayerFrame_007:
    player_frame_header   8, $1e, $23, data_6e_4800_PlayerTiles + $06c0
    player_piece   -9,  -13, PLAYER_PIECE_PAL0
    player_piece  -18,   -5, PLAYER_PIECE_PAL0
    player_piece  -23,    3, PLAYER_PIECE_PAL0
    player_piece  -34,    9, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    5, PLAYER_PIECE_PAL1
    player_piece   -4,   -7, PLAYER_PIECE_PAL1
    player_piece   -7,    2, PLAYER_PIECE_PAL1

data_6e_411b_PlayerFrame_008:
    player_frame_header   8, $1f, $23, data_6e_4800_PlayerTiles + $07c0
    player_piece   -9,  -13, PLAYER_PIECE_PAL0
    player_piece  -22,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    3, PLAYER_PIECE_PAL0
    player_piece  -35,    9, PLAYER_PIECE_PAL0
    player_piece  -21,   -3, PLAYER_PIECE_PAL1
    player_piece  -29,    5, PLAYER_PIECE_PAL1
    player_piece   -8,  -10, PLAYER_PIECE_PAL1
    player_piece  -19,    5, PLAYER_PIECE_PAL1

data_6e_4140_PlayerFrame_009:
    player_frame_header   8, $20, $22, data_6e_4800_PlayerTiles + $08c0
    player_piece  -21,   -5, PLAYER_PIECE_PAL0
    player_piece  -24,    3, PLAYER_PIECE_PAL0
    player_piece  -36,    8, PLAYER_PIECE_PAL0
    player_piece   -8,  -13, PLAYER_PIECE_PAL0
    player_piece  -23,   -4, PLAYER_PIECE_PAL1
    player_piece  -30,    5, PLAYER_PIECE_PAL1
    player_piece   -8,  -11, PLAYER_PIECE_PAL1
    player_piece  -20,    4, PLAYER_PIECE_PAL1

data_6e_4165_PlayerFrame_010:
    player_frame_header  10, $1f, $22, data_6e_4800_PlayerTiles + $09c0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,    4, PLAYER_PIECE_PAL0
    player_piece  -35,    8, PLAYER_PIECE_PAL0
    player_piece   -8,  -11, PLAYER_PIECE_PAL0
    player_piece   -5,   -3, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL1
    player_piece  -29,    5, PLAYER_PIECE_PAL1
    player_piece   -8,   -9, PLAYER_PIECE_PAL1
    player_piece  -18,    3, PLAYER_PIECE_PAL1
    player_piece  -20,    8, PLAYER_PIECE_PAL1

data_6e_4192_PlayerFrame_011:
    player_frame_header  10, $1e, $23, data_6e_4800_PlayerTiles + $0b00
    player_piece   -8,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece  -32,    7, PLAYER_PIECE_PAL0
    player_piece  -35,    9, PLAYER_PIECE_PAL0
    player_piece   -5,   -1, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL1
    player_piece  -28,    5, PLAYER_PIECE_PAL1
    player_piece  -17,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    2, PLAYER_PIECE_PAL1
    player_piece   -4,    9, PLAYER_PIECE_PAL1

data_6e_41bf_PlayerFrame_012:
    player_frame_header  10, $1c, $23, data_6e_4800_PlayerTiles + $0c40
    player_piece   -9,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece  -21,    6, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece   -5,    3, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece  -26,    4, PLAYER_PIECE_PAL1
    player_piece  -37,    9, PLAYER_PIECE_PAL1
    player_piece   -3,   -3, PLAYER_PIECE_PAL1
    player_piece  -16,    5, PLAYER_PIECE_PAL1

data_6e_41ec_PlayerFrame_013:
    player_frame_header   7, $1c, $23, data_6e_4800_PlayerTiles + $0d80
    player_piece  -11,  -10, PLAYER_PIECE_PAL0
    player_piece  -22,   -2, PLAYER_PIECE_PAL0
    player_piece  -30,    6, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -20,   -4, PLAYER_PIECE_PAL1
    player_piece  -26,    4, PLAYER_PIECE_PAL1
    player_piece  -16,   -2, PLAYER_PIECE_PAL1

data_6e_420d_PlayerFrame_014:
    player_frame_header   8, $1d, $23, data_6e_4800_PlayerTiles + $0e60
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -23,    4, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    4, PLAYER_PIECE_PAL1
    player_piece   -3,   -5, PLAYER_PIECE_PAL1
    player_piece   -8,    3, PLAYER_PIECE_PAL1

data_6e_4232_PlayerFrame_015:
    player_frame_header   8, $1d, $23, data_6e_4800_PlayerTiles + $0f60
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -23,    4, PLAYER_PIECE_PAL0
    player_piece  -33,    9, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    4, PLAYER_PIECE_PAL1
    player_piece   -4,   -6, PLAYER_PIECE_PAL1
    player_piece  -17,    3, PLAYER_PIECE_PAL1

data_6e_4257_PlayerFrame_016:
    player_frame_header  10, $1e, $22, data_6e_4800_PlayerTiles + $1060
    player_piece   -9,  -12, PLAYER_PIECE_PAL0
    player_piece  -19,   -4, PLAYER_PIECE_PAL0
    player_piece  -23,    4, PLAYER_PIECE_PAL0
    player_piece  -35,    8, PLAYER_PIECE_PAL0
    player_piece  -28,   -5, PLAYER_PIECE_PAL1
    player_piece  -28,    3, PLAYER_PIECE_PAL1
    player_piece  -30,    8, PLAYER_PIECE_PAL1
    player_piece   -6,  -10, PLAYER_PIECE_PAL1
    player_piece   -9,    4, PLAYER_PIECE_PAL1
    player_piece   -8,    8, PLAYER_PIECE_PAL1

data_6e_4284_PlayerFrame_017:
    player_frame_header   9, $1f, $20, data_6e_4800_PlayerTiles + $11a0
    player_piece   -9,  -14, PLAYER_PIECE_PAL0
    player_piece  -21,   -6, PLAYER_PIECE_PAL0
    player_piece  -23,    2, PLAYER_PIECE_PAL0
    player_piece   -7,    2, PLAYER_PIECE_PAL0
    player_piece  -35,   10, PLAYER_PIECE_PAL0
    player_piece  -16,  -11, PLAYER_PIECE_PAL1
    player_piece  -28,   -3, PLAYER_PIECE_PAL1
    player_piece  -29,    5, PLAYER_PIECE_PAL1
    player_piece   -8,    3, PLAYER_PIECE_PAL1

data_6e_42ad_PlayerFrame_018:
    player_frame_header   9, $1f, $21, data_6e_4800_PlayerTiles + $12c0
    player_piece  -11,  -14, PLAYER_PIECE_PAL0
    player_piece  -22,   -5, PLAYER_PIECE_PAL0
    player_piece  -28,    3, PLAYER_PIECE_PAL0
    player_piece  -35,   11, PLAYER_PIECE_PAL0
    player_piece  -11,  -12, PLAYER_PIECE_PAL1
    player_piece  -17,   -4, PLAYER_PIECE_PAL1
    player_piece  -29,    4, PLAYER_PIECE_PAL1
    player_piece  -23,    4, PLAYER_PIECE_PAL1
    player_piece  -39,   12, PLAYER_PIECE_PAL1

data_6e_42d6_PlayerFrame_019:
    player_frame_header   9, $1f, $20, data_6e_4800_PlayerTiles + $13e0
    player_piece  -12,  -15, PLAYER_PIECE_PAL0
    player_piece  -25,   -5, PLAYER_PIECE_PAL0
    player_piece   -9,   -6, PLAYER_PIECE_PAL0
    player_piece  -29,    3, PLAYER_PIECE_PAL0
    player_piece  -35,   11, PLAYER_PIECE_PAL0
    player_piece  -17,  -11, PLAYER_PIECE_PAL1
    player_piece  -24,   -3, PLAYER_PIECE_PAL1
    player_piece  -32,    5, PLAYER_PIECE_PAL1
    player_piece  -13,    5, PLAYER_PIECE_PAL1

data_6e_42ff_PlayerFrame_020:
    player_frame_header  10, $1f, $20, data_6e_4800_PlayerTiles + $1500
    player_piece  -10,  -12, PLAYER_PIECE_PAL0
    player_piece  -26,   -3, PLAYER_PIECE_PAL0
    player_piece  -10,   -4, PLAYER_PIECE_PAL0
    player_piece  -24,    5, PLAYER_PIECE_PAL0
    player_piece  -10,    4, PLAYER_PIECE_PAL0
    player_piece  -36,   13, PLAYER_PIECE_PAL0
    player_piece  -24,   -9, PLAYER_PIECE_PAL1
    player_piece  -29,   -1, PLAYER_PIECE_PAL1
    player_piece  -29,    7, PLAYER_PIECE_PAL1
    player_piece  -19,    5, PLAYER_PIECE_PAL1

data_6e_432c_PlayerFrame_021:
    player_frame_header   8, $20, $20, data_6e_4800_PlayerTiles + $1640
    player_piece  -10,  -12, PLAYER_PIECE_PAL0
    player_piece  -25,   -3, PLAYER_PIECE_PAL0
    player_piece  -24,    5, PLAYER_PIECE_PAL0
    player_piece   -9,    0, PLAYER_PIECE_PAL0
    player_piece  -37,   12, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL1
    player_piece  -30,    5, PLAYER_PIECE_PAL1
    player_piece  -18,    6, PLAYER_PIECE_PAL1

data_6e_4351_PlayerFrame_022:
    player_frame_header  11, $21, $20, data_6e_4800_PlayerTiles + $1740
    player_piece  -22,  -19, PLAYER_PIECE_PAL0
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece   -7,  -11, PLAYER_PIECE_PAL0
    player_piece  -24,   -3, PLAYER_PIECE_PAL0
    player_piece   -8,   -3, PLAYER_PIECE_PAL0
    player_piece  -37,    5, PLAYER_PIECE_PAL0
    player_piece  -19,  -11, PLAYER_PIECE_PAL1
    player_piece  -31,   -3, PLAYER_PIECE_PAL1
    player_piece  -15,   -3, PLAYER_PIECE_PAL1
    player_piece  -40,    5, PLAYER_PIECE_PAL1
    player_piece   -6,    5, PLAYER_PIECE_PAL1

data_6e_4382_PlayerFrame_023:
    player_frame_header   9, $1e, $20, data_6e_4800_PlayerTiles + $18a0
    player_piece  -11,  -15, PLAYER_PIECE_PAL0
    player_piece  -22,   -7, PLAYER_PIECE_PAL0
    player_piece  -22,    1, PLAYER_PIECE_PAL0
    player_piece  -35,    5, PLAYER_PIECE_PAL0
    player_piece   -6,    3, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL1
    player_piece  -28,    1, PLAYER_PIECE_PAL1
    player_piece  -17,   -3, PLAYER_PIECE_PAL1
    player_piece  -16,    5, PLAYER_PIECE_PAL1

data_6e_43ab_PlayerFrame_024:
    player_frame_header   9, $1c, $20, data_6e_4800_PlayerTiles + $19c0
    player_piece  -10,  -21, PLAYER_PIECE_PAL0
    player_piece  -14,  -13, PLAYER_PIECE_PAL0
    player_piece  -21,   -5, PLAYER_PIECE_PAL0
    player_piece  -32,    3, PLAYER_PIECE_PAL0
    player_piece  -29,  -13, PLAYER_PIECE_PAL1
    player_piece  -26,   -5, PLAYER_PIECE_PAL1
    player_piece  -10,   -5, PLAYER_PIECE_PAL1
    player_piece  -26,    3, PLAYER_PIECE_PAL1
    player_piece  -10,    3, PLAYER_PIECE_PAL1

data_6e_43d4_PlayerFrame_025:
    player_frame_header   9, $1f, $1d, data_6e_4800_PlayerTiles + $1ae0
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -23,    0, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece   -7,    3, PLAYER_PIECE_PAL0
    player_piece  -29,  -11, PLAYER_PIECE_PAL1
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -39,    3, PLAYER_PIECE_PAL1
    player_piece  -13,   -7, PLAYER_PIECE_PAL1
    player_piece  -13,    3, PLAYER_PIECE_PAL1

data_6e_43fd_PlayerFrame_026:
    player_frame_header   9, $20, $1d, data_6e_4800_PlayerTiles + $1c00
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -23,    0, PLAYER_PIECE_PAL0
    player_piece   -7,   -5, PLAYER_PIECE_PAL0
    player_piece   -7,    3, PLAYER_PIECE_PAL0
    player_piece  -30,  -11, PLAYER_PIECE_PAL1
    player_piece  -29,   -3, PLAYER_PIECE_PAL1
    player_piece  -39,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -7, PLAYER_PIECE_PAL1
    player_piece  -13,    3, PLAYER_PIECE_PAL1

data_6e_4426_PlayerFrame_027:
    player_frame_header   9, $20, $1d, data_6e_4800_PlayerTiles + $1d20
    player_piece  -27,   -9, PLAYER_PIECE_PAL0
    player_piece  -24,   -1, PLAYER_PIECE_PAL0
    player_piece   -8,   -5, PLAYER_PIECE_PAL0
    player_piece   -8,    3, PLAYER_PIECE_PAL0
    player_piece  -29,  -12, PLAYER_PIECE_PAL1
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -7, PLAYER_PIECE_PAL1
    player_piece  -11,    3, PLAYER_PIECE_PAL1

data_6e_444f_PlayerFrame_028:
    player_frame_header   8, $1d, $1d, data_6e_4800_PlayerTiles + $1e40
    player_piece  -22,   -8, PLAYER_PIECE_PAL0
    player_piece  -21,    0, PLAYER_PIECE_PAL0
    player_piece   -5,   -6, PLAYER_PIECE_PAL0
    player_piece   -5,    2, PLAYER_PIECE_PAL0
    player_piece  -27,  -11, PLAYER_PIECE_PAL1
    player_piece  -28,   -3, PLAYER_PIECE_PAL1
    player_piece  -20,    3, PLAYER_PIECE_PAL1
    player_piece   -9,   -7, PLAYER_PIECE_PAL1

data_6e_4474_PlayerFrame_029:
    player_frame_header   7, $18, $1d, data_6e_4800_PlayerTiles + $1f40
    player_piece  -16,   -8, PLAYER_PIECE_PAL0
    player_piece  -17,    0, PLAYER_PIECE_PAL0
    player_piece   -1,    0, PLAYER_PIECE_PAL0
    player_piece  -22,  -11, PLAYER_PIECE_PAL1
    player_piece  -22,   -3, PLAYER_PIECE_PAL1
    player_piece  -19,    3, PLAYER_PIECE_PAL1
    player_piece   -6,   -7, PLAYER_PIECE_PAL1

data_6e_4495_PlayerFrame_030:
    player_frame_header   9, $20, $1d, data_6e_4800_PlayerTiles + $2020
    player_piece  -24,   -8, PLAYER_PIECE_PAL0
    player_piece  -25,    0, PLAYER_PIECE_PAL0
    player_piece   -9,   -5, PLAYER_PIECE_PAL0
    player_piece   -9,    3, PLAYER_PIECE_PAL0
    player_piece  -30,   -8, PLAYER_PIECE_PAL1
    player_piece  -29,    0, PLAYER_PIECE_PAL1
    player_piece  -14,   -9, PLAYER_PIECE_PAL1
    player_piece  -22,   -1, PLAYER_PIECE_PAL1
    player_piece  -23,    3, PLAYER_PIECE_PAL1

data_6e_44be_PlayerFrame_031:
    player_frame_header   9, $20, $1d, data_6e_4800_PlayerTiles + $2140
    player_piece  -26,   -9, PLAYER_PIECE_PAL0
    player_piece  -24,   -1, PLAYER_PIECE_PAL0
    player_piece  -13,    3, PLAYER_PIECE_PAL0
    player_piece   -8,   -5, PLAYER_PIECE_PAL0
    player_piece  -30,  -12, PLAYER_PIECE_PAL1
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -27,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -7, PLAYER_PIECE_PAL1
    player_piece  -11,    3, PLAYER_PIECE_PAL1

data_6e_44e7_PlayerFrame_032:
    player_frame_header   9, $20, $20, data_6e_4800_PlayerTiles + $2260
    player_piece  -24,   -6, PLAYER_PIECE_PAL0
    player_piece  -25,    2, PLAYER_PIECE_PAL0
    player_piece   -8,   -7, PLAYER_PIECE_PAL0
    player_piece   -9,    1, PLAYER_PIECE_PAL0
    player_piece  -30,   -7, PLAYER_PIECE_PAL1
    player_piece  -30,    1, PLAYER_PIECE_PAL1
    player_piece  -14,  -12, PLAYER_PIECE_PAL1
    player_piece  -14,   -4, PLAYER_PIECE_PAL1
    player_piece  -16,    4, PLAYER_PIECE_PAL1

data_6e_4510_PlayerFrame_033:
    player_frame_header   9, $20, $21, data_6e_4800_PlayerTiles + $2380
    player_piece  -23,   -9, PLAYER_PIECE_PAL0
    player_piece  -25,   -1, PLAYER_PIECE_PAL0
    player_piece   -9,   -7, PLAYER_PIECE_PAL0
    player_piece   -9,    1, PLAYER_PIECE_PAL0
    player_piece  -25,  -12, PLAYER_PIECE_PAL1
    player_piece  -30,   -4, PLAYER_PIECE_PAL1
    player_piece  -29,    4, PLAYER_PIECE_PAL1
    player_piece  -14,   -5, PLAYER_PIECE_PAL1
    player_piece   -5,    3, PLAYER_PIECE_PAL1

data_6e_4539_PlayerFrame_034:
    player_frame_header   9, $1e, $1f, data_6e_4800_PlayerTiles + $24a0
    player_piece  -20,   -8, PLAYER_PIECE_PAL0
    player_piece  -22,    0, PLAYER_PIECE_PAL0
    player_piece   -6,   -6, PLAYER_PIECE_PAL0
    player_piece   -6,    2, PLAYER_PIECE_PAL0
    player_piece  -27,  -11, PLAYER_PIECE_PAL1
    player_piece  -33,   -3, PLAYER_PIECE_PAL1
    player_piece  -25,    3, PLAYER_PIECE_PAL1
    player_piece  -11,   -7, PLAYER_PIECE_PAL1
    player_piece  -16,    1, PLAYER_PIECE_PAL1

data_6e_4562_PlayerFrame_035:
    player_frame_header   8, $1a, $1d, data_6e_4800_PlayerTiles + $25c0
    player_piece  -16,  -12, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece  -31,    1, PLAYER_PIECE_PAL0
    player_piece  -23,  -12, PLAYER_PIECE_PAL1
    player_piece  -24,   -4, PLAYER_PIECE_PAL1
    player_piece   -8,   -4, PLAYER_PIECE_PAL1
    player_piece  -33,    1, PLAYER_PIECE_PAL1
    player_piece   -3,    1, PLAYER_PIECE_PAL1

data_6e_4587_PlayerFrame_036:
    player_frame_header   6, $19, $1c, data_6e_4800_PlayerTiles + $26c0
    player_piece  -20,  -10, PLAYER_PIECE_PAL0
    player_piece  -21,   -2, PLAYER_PIECE_PAL0
    player_piece  -23,   -8, PLAYER_PIECE_PAL1
    player_piece  -23,    0, PLAYER_PIECE_PAL1
    player_piece   -7,   -8, PLAYER_PIECE_PAL1
    player_piece   -6,    0, PLAYER_PIECE_PAL1

data_6e_45a4_PlayerFrame_037:
    player_frame_header   6, $18, $1b, data_6e_4800_PlayerTiles + $2780
    player_piece  -21,  -10, PLAYER_PIECE_PAL0
    player_piece  -23,   -2, PLAYER_PIECE_PAL0
    player_piece  -22,   -9, PLAYER_PIECE_PAL1
    player_piece  -22,   -1, PLAYER_PIECE_PAL1
    player_piece   -6,   -9, PLAYER_PIECE_PAL1
    player_piece   -6,   -1, PLAYER_PIECE_PAL1

data_6e_45c1_PlayerFrame_038:
    player_frame_header   6, $16, $1b, data_6e_4800_PlayerTiles + $2840
    player_piece  -20,  -10, PLAYER_PIECE_PAL0
    player_piece  -20,   -2, PLAYER_PIECE_PAL0
    player_piece  -20,   -9, PLAYER_PIECE_PAL1
    player_piece  -20,   -1, PLAYER_PIECE_PAL1
    player_piece   -4,   -9, PLAYER_PIECE_PAL1
    player_piece   -4,   -1, PLAYER_PIECE_PAL1

data_6e_45de_PlayerFrame_039:
    player_frame_header   4, $15, $1b, data_6e_4800_PlayerTiles + $2900
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -9, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1

data_6e_45f3_PlayerFrame_040:
    player_frame_header   4, $15, $1b, data_6e_4800_PlayerTiles + $2980
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -9, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1

data_6e_4608_PlayerFrame_041:
    player_frame_header   4, $15, $1b, data_6e_4800_PlayerTiles + $2a00
    player_piece  -19,   -9, PLAYER_PIECE_PAL0
    player_piece  -21,   -1, PLAYER_PIECE_PAL0
    player_piece  -16,   -9, PLAYER_PIECE_PAL1
    player_piece  -16,   -1, PLAYER_PIECE_PAL1

data_6e_461d_PlayerFrame_042:
    player_frame_header   7, $1e, $23, data_6e_4800_PlayerTiles + $2a80
    player_piece  -23,  -14, PLAYER_PIECE_PAL0
    player_piece  -21,   -6, PLAYER_PIECE_PAL0
    player_piece   -7,    2, PLAYER_PIECE_PAL0
    player_piece  -28,  -16, PLAYER_PIECE_PAL1
    player_piece  -28,   -8, PLAYER_PIECE_PAL1
    player_piece  -12,  -15, PLAYER_PIECE_PAL1
    player_piece  -16,   -3, PLAYER_PIECE_PAL1

data_6e_463e_PlayerFrame_043:
    player_frame_header   8, $1e, $22, data_6e_4800_PlayerTiles + $2b60
    player_piece  -23,  -11, PLAYER_PIECE_PAL0
    player_piece  -21,   -4, PLAYER_PIECE_PAL0
    player_piece   -9,   -2, PLAYER_PIECE_PAL0
    player_piece  -27,  -14, PLAYER_PIECE_PAL1
    player_piece  -28,   -6, PLAYER_PIECE_PAL1
    player_piece  -11,  -13, PLAYER_PIECE_PAL1
    player_piece  -16,   -5, PLAYER_PIECE_PAL1
    player_piece   -5,    3, PLAYER_PIECE_PAL1

data_6e_4663_PlayerFrame_044:
    player_frame_header   7, $1f, $25, data_6e_4800_PlayerTiles + $2c60
    player_piece  -23,   -3, PLAYER_PIECE_PAL0
    player_piece  -23,    2, PLAYER_PIECE_PAL0
    player_piece   -7,    2, PLAYER_PIECE_PAL0
    player_piece  -29,   -7, PLAYER_PIECE_PAL1
    player_piece  -29,    1, PLAYER_PIECE_PAL1
    player_piece  -13,   -8, PLAYER_PIECE_PAL1
    player_piece  -13,    0, PLAYER_PIECE_PAL1

data_6e_4684_PlayerFrame_045:
    player_frame_header   9, $1f, $26, data_6e_4800_PlayerTiles + $2d40
    player_piece  -23,  -10, PLAYER_PIECE_PAL0
    player_piece  -24,   -2, PLAYER_PIECE_PAL0
    player_piece  -31,    3, PLAYER_PIECE_PAL0
    player_piece   -8,   -2, PLAYER_PIECE_PAL0
    player_piece   -5,    3, PLAYER_PIECE_PAL0
    player_piece  -29,   -6, PLAYER_PIECE_PAL1
    player_piece  -29,    2, PLAYER_PIECE_PAL1
    player_piece  -13,   -7, PLAYER_PIECE_PAL1
    player_piece  -13,    1, PLAYER_PIECE_PAL1

data_6e_46ad_PlayerFrame_046:
    player_frame_header   8, $1e, $30, data_6e_4800_PlayerTiles + $2e60
    player_piece  -10,   -5, PLAYER_PIECE_PAL0
    player_piece  -21,    3, PLAYER_PIECE_PAL0
    player_piece  -25,   11, PLAYER_PIECE_PAL0
    player_piece  -36,   13, PLAYER_PIECE_PAL0
    player_piece  -17,    0, PLAYER_PIECE_PAL1
    player_piece  -28,    9, PLAYER_PIECE_PAL1
    player_piece   -1,    0, PLAYER_PIECE_PAL1
    player_piece  -18,    8, PLAYER_PIECE_PAL1

data_6e_46d2_PlayerFrame_047:
    player_frame_header  10, $22, $2b, data_6e_4800_PlayerTiles + $2f60
    player_piece  -25,   -7, PLAYER_PIECE_PAL0
    player_piece  -28,    1, PLAYER_PIECE_PAL0
    player_piece  -10,  -14, PLAYER_PIECE_PAL0
    player_piece  -12,   -6, PLAYER_PIECE_PAL0
    player_piece  -12,    2, PLAYER_PIECE_PAL0
    player_piece  -32,   -6, PLAYER_PIECE_PAL1
    player_piece  -31,    2, PLAYER_PIECE_PAL1
    player_piece  -26,   -8, PLAYER_PIECE_PAL1
    player_piece  -16,    0, PLAYER_PIECE_PAL1
    player_piece  -21,    4, PLAYER_PIECE_PAL1

data_6e_46ff_PlayerFrame_048:
    player_frame_header   8, $20, $2a, data_6e_4800_PlayerTiles + $30a0
    player_piece  -25,   -7, PLAYER_PIECE_PAL0
    player_piece  -25,    1, PLAYER_PIECE_PAL0
    player_piece   -9,  -11, PLAYER_PIECE_PAL0
    player_piece   -9,   -3, PLAYER_PIECE_PAL0
    player_piece  -30,   -8, PLAYER_PIECE_PAL1
    player_piece  -20,    3, PLAYER_PIECE_PAL1
    player_piece  -14,   -8, PLAYER_PIECE_PAL1
    player_piece  -19,    1, PLAYER_PIECE_PAL1

data_6e_4724_PlayerFrame_049:
    player_frame_header  10, $20, $2b, data_6e_4800_PlayerTiles + $31a0
    player_piece  -23,  -10, PLAYER_PIECE_PAL0
    player_piece  -23,   -2, PLAYER_PIECE_PAL0
    player_piece  -14,    4, PLAYER_PIECE_PAL0
    player_piece   -7,  -10, PLAYER_PIECE_PAL0
    player_piece   -7,   -2, PLAYER_PIECE_PAL0
    player_piece  -38,   -8, PLAYER_PIECE_PAL1
    player_piece  -26,    0, PLAYER_PIECE_PAL1
    player_piece  -23,  -11, PLAYER_PIECE_PAL1
    player_piece  -10,   -2, PLAYER_PIECE_PAL1
    player_piece  -24,    4, PLAYER_PIECE_PAL1

data_6e_4751_PlayerFrame_050:
    player_frame_header  10, $1f, $30, data_6e_4800_PlayerTiles + $32e0
    player_piece  -23,   -8, PLAYER_PIECE_PAL0
    player_piece  -23,    0, PLAYER_PIECE_PAL0
    player_piece  -14,    8, PLAYER_PIECE_PAL0
    player_piece   -7,   -6, PLAYER_PIECE_PAL0
    player_piece  -29,  -10, PLAYER_PIECE_PAL1
    player_piece  -30,   -2, PLAYER_PIECE_PAL1
    player_piece  -27,    6, PLAYER_PIECE_PAL1
    player_piece  -27,    9, PLAYER_PIECE_PAL1
    player_piece  -13,  -11, PLAYER_PIECE_PAL1
    player_piece  -20,   -3, PLAYER_PIECE_PAL1

data_6e_477e_PlayerFrame_051:
    player_frame_header   9, $1f, $30, data_6e_4800_PlayerTiles + $3420
    player_piece  -22,   -9, PLAYER_PIECE_PAL0
    player_piece  -22,   -1, PLAYER_PIECE_PAL0
    player_piece  -28,    7, PLAYER_PIECE_PAL0
    player_piece   -6,   -6, PLAYER_PIECE_PAL0
    player_piece  -29,   -8, PLAYER_PIECE_PAL1
    player_piece  -24,    0, PLAYER_PIECE_PAL1
    player_piece  -28,    8, PLAYER_PIECE_PAL1
    player_piece  -13,  -11, PLAYER_PIECE_PAL1
    player_piece  -21,   -3, PLAYER_PIECE_PAL1

data_6e_47a7_PlayerFrame_052:
    player_frame_header   9, $1f, $2e, data_6e_4800_PlayerTiles + $3540
    player_piece  -22,   -8, PLAYER_PIECE_PAL0
    player_piece  -22,    0, PLAYER_PIECE_PAL0
    player_piece   -6,   -2, PLAYER_PIECE_PAL0
    player_piece  -29,   -9, PLAYER_PIECE_PAL1
    player_piece  -31,   -1, PLAYER_PIECE_PAL1
    player_piece  -26,    7, PLAYER_PIECE_PAL1
    player_piece  -13,  -13, PLAYER_PIECE_PAL1
    player_piece  -12,   -5, PLAYER_PIECE_PAL1
    player_piece   -7,    3, PLAYER_PIECE_PAL1

data_6e_47d0_PlayerFrame_053:
    player_frame_header   9, $1e, $2e, data_6e_4800_PlayerTiles + $3660
    player_piece  -35,  -15, PLAYER_PIECE_PAL0
    player_piece  -21,   -7, PLAYER_PIECE_PAL0
    player_piece  -21,    1, PLAYER_PIECE_PAL0
    player_piece   -5,    1, PLAYER_PIECE_PAL0
    player_piece  -13,  -15, PLAYER_PIECE_PAL1
    player_piece  -28,   -7, PLAYER_PIECE_PAL1
    player_piece  -12,   -7, PLAYER_PIECE_PAL1
    player_piece  -26,    1, PLAYER_PIECE_PAL1
    player_piece  -26,    7, PLAYER_PIECE_PAL1

    ds   $4800 - @, 0                    ; the bank pads to a 16-byte boundary here
data_6e_4800_PlayerTiles:
; INCBINd by main.asm - see the header above
